scripts/enmasse-deploy.sh
=> Add guide mode (-g) which prints the manual steps required

documentation/getting-started/e2e-example.md, documentation/getting-started/local-development.md
=> Add manual steps of deployment based on deployment guide mode

documentation/getting-started/e2e-example.md, documentation/getting-started/local-development.md, documentation/grafana/broker-dashboard.json, generated/enmasse-template-with-kafka.yaml, generated/enmasse-template.yaml, generated/queue-inmemory-template.yaml, generated/queue-persisted-template.yaml, generated/tls-enmasse-template-with-kafka.yaml, generated/tls-enmasse-template.yaml, generated/tls-queue-inmemory-template.yaml, generated/tls-queue-persisted-template.yaml, generated/tls-topic-inmemory-template.yaml, generated/tls-topic-persisted-template.yaml, generated/topic-inmemory-template.yaml, generated/topic-persisted-template.yaml, include/broker.jsonnet, include/enmasse-instance-infra.jsonnet, include/hawkular-broker-config.jsonnet, include/storage-template.jsonnet
* Message count and consumer count for all queues
=> Enable hawkular metrics for brokers

.travis.yml, generated/enmasse-kubernetes.yaml, generated/enmasse-template-with-kafka.yaml, generated/enmasse-template.yaml, generated/flavor.yaml, generated/queue-inmemory-template.yaml, generated/queue-persisted-template.yaml, generated/sasldb-enmasse-template.yaml, generated/sasldb-tls-enmasse-template.yaml, generated/tls-enmasse-template-with-kafka.yaml, generated/tls-enmasse-template.yaml, generated/tls-queue-inmemory-template.yaml, generated/tls-queue-persisted-template.yaml, generated/tls-topic-inmemory-template.yaml, generated/tls-topic-persisted-template.yaml, generated/topic-inmemory-template.yaml, generated/topic-persisted-template.yaml, include/enmasse-instance-infra.jsonnet, include/hawkular-router-config.jsonnet, include/qdrouterd.jsonnet, include/router.jsonnet, include/storage-template.jsonnet
This adds a colocated container to routers that collects router metrics
=> Add support for router metrics

include/admin.jsonnet, include/console.jsonnet, include/enmasse-instance-infra.jsonnet, install/kubernetes/enmasse.yaml, install/openshift/enmasse-with-kafka.yaml, install/openshift/enmasse-with-sasldb.yaml, install/openshift/enmasse.yaml
=> Add multitenancy support to console

admin/address-controller/lib/src/main/java/enmasse/controller/common/KubernetesHelper.java
=> Skip creating secret for instance if it already exists

HACKING.md, systemtests/src/main/java/enmasse/systemtest/mqtt/ClientHandlerBase.java, systemtests/src/main/java/enmasse/systemtest/mqtt/MqttClient.java, systemtests/src/main/java/enmasse/systemtest/mqtt/Publisher.java, systemtests/src/main/java/enmasse/systemtest/mqtt/Subscriber.java, systemtests/src/test/java/enmasse/systemtest/mqtt/MqttTestBase.java
Update MQTT system tests to support SSL (including some SSLSocketFactory hackery)
=> Update MQTT system tests to support SSL

ragent/build.gradle, ragent/ragent.js, ragent/test/ragent.js
The gradle build triggers running the tests with mocha (don't yet know enough gradle to make that conditional on mocha being on the path).
=> initial router agent changes and some tests

admin/queue-scheduler/src/main/java/enmasse/queue/scheduler/SchedulerState.java
Fix potential NPE in QueueSchuler
=> Closes #90

router/Dockerfile, systemtests/scripts/common.sh
better logging for failed auth service connections; fixed a bug causing segfaults
=> rebase to latest router

HACKING.md
Added description how to execute single system test
=> UPD HACKING.md

console/lib/auth_service.js, console/package.json
=> pass through the correct sasl-init hostname

router/Dockerfile
=> Use router image with TLS stability patch

admin/address-controller/lib/src/main/java/io/enmasse/controller/api/v1/http/HttpAddressSpaceService.java, admin/address-controller/lib/src/test/java/io/enmasse/controller/api/v1/http/HttpAddressSpaceServiceTest.java, admin/address-controller/server/src/main/java/io/enmasse/controller/HTTPServer.java, admin/common-lib/config/src/main/java/io/enmasse/address/model/AddressSpaceList.java, admin/k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapAddressSpaceApi.java
=> Implement REST API for listing, creating and deleting address spaces

build.gradle, mqtt/mqtt-gateway/build.gradle, mqtt/mqtt-lwt/build.gradle
Some changes that was wrongly committed by me, sorry!
=> Reenable mqtt unit tests

admin/configserv/src/main/java/io/enmasse/config/service/Main.java
This makes it possible to run configserv outside openshift
=> Allow setting namespace and token for configserv

address-controller/lib/src/main/java/io/enmasse/controller/standard/AddressController.java, address-controller/lib/src/main/java/io/enmasse/controller/standard/StandardHelper.java, k8s-api/src/main/java/io/enmasse/k8s/api/ResourceController.java, systemtests/src/main/java/enmasse/systemtest/ConnectTimeoutException.java, systemtests/src/main/java/enmasse/systemtest/GlobalLogCollector.java, systemtests/src/main/java/enmasse/systemtest/OpenShift.java, systemtests/src/main/java/enmasse/systemtest/TestUtils.java, systemtests/src/main/java/enmasse/systemtest/amqp/AmqpClient.java, systemtests/src/main/java/enmasse/systemtest/amqp/AmqpClientFactory.java, systemtests/src/main/java/enmasse/systemtest/mqtt/MqttClient.java, systemtests/src/main/java/enmasse/systemtest/mqtt/MqttClientFactory.java, systemtests/src/test/java/enmasse/systemtest/TestBase.java, systemtests/src/test/java/enmasse/systemtest/auth/AuthenticationTest.java
This adds tests for the authentication services as specified in https://github.com/EnMasseProject/enmasse/blob/master/documentation/design_docs/design/authentication.adoc#enmasse-authentication-service
I've tried to move the test scenarios into fewer tests, as they take quite long to run (but added comments as to what is being tested).
The tests are written with MQTT client support, but I have disabled that for now until mqtt stuff is more stable, otherwise the builds would probably break more often.
=> Authentication service tests

documentation/design_docs/design/brokered-addressspace.adoc, documentation/design_docs/design/design-template.adoc
=> Brokered address space design doc

documentation/common/revision-info.adoc, documentation/internal/contributor-guide.adoc, documentation/internal/formatting-guide.adoc, documentation/internal/git-setup-guide.adoc, documentation/internal/git-tips.adoc, documentation/internal/introduction.adoc, documentation/internal/master.adoc, documentation/internal/screenshots.adoc, documentation/internal/styleguide.adoc, documentation/internal/templates.adoc, documentation/internal/templates/template-concept.adoc, documentation/internal/templates/template-procedure-brief.adoc, documentation/internal/templates/template-procedure.adoc, documentation/internal/templates/template-reference.adoc
This is the start of a documentation contribution guide for EnMasse.
=> Add documentation contribution guide

.travis/setup-openshift.sh, address-controller/lib/src/main/java/io/enmasse/controller/api/v1/http/HttpSchemaService.java, address-controller/server/src/test/java/io/enmasse/controller/HTTPServerTest.java, address-model-lib/src/main/java/io/enmasse/address/model/Schema.java, address-model-lib/src/main/java/io/enmasse/address/model/SecretCertProvider.java, address-model-lib/src/main/java/io/enmasse/address/model/types/brokered/BrokeredAddressSpaceType.java, address-model-lib/src/main/java/io/enmasse/address/model/types/brokered/BrokeredType.java, address-model-lib/src/main/java/io/enmasse/address/model/types/brokered/StaticPlanConfig.java, address-model-lib/src/main/java/io/enmasse/address/model/types/common/Plan.java, address-model-lib/src/main/java/io/enmasse/address/model/types/common/TemplateConfig.java, address-model-lib/src/main/java/io/enmasse/address/model/types/standard/StandardAddressSpaceType.java, address-model-lib/src/main/java/io/enmasse/address/model/types/standard/StaticPlanConfig.java, address-model-lib/src/main/java/io/enmasse/address/model/v1/CodecV1.java, address-model-lib/src/test/java/io/enmasse/address/model/v1/address/AddressTest.java, address-model-lib/src/test/java/io/enmasse/address/model/v1/address/PlanTest.java, address-model-lib/src/test/java/io/enmasse/address/model/v1/address/SchemaTest.java, address-model-lib/src/test/java/io/enmasse/address/model/v1/address/SerializationTest.java, build.gradle
=> Add types for brokered address space

address-controller/src/main/java/io/enmasse/controller/HTTPServer.java, address-controller/src/main/java/io/enmasse/controller/api/AuthInterceptor.java, address-controller/src/main/java/io/enmasse/controller/auth/AuthHandler.java, address-controller/src/main/java/io/enmasse/controller/auth/BasicAuthHandler.java, address-controller/src/main/java/io/enmasse/controller/auth/SingleUserAuthenticator.java
This is required for implementing the token based auth, which isn't ready to be merged yet, but these two commits need to get in ASAP, because I keep having to rebase them manually because of all the other changes going on in the master.
=> Httpserver auth refactor

templates/include/persistent-volume.json
Invoke as such: oc process -f persistent-volume.json HOST_DIR=/tmp/volume NAME=pv01 | oc create -f -
=> Make persistent volume into a template

address-controller/src/main/java/io/enmasse/controller/api/v1/AddressApiHelper.java, address-controller/src/main/java/io/enmasse/controller/api/v1/http/HttpAddressService.java, address-controller/src/main/java/io/enmasse/controller/common/TemplateAddressClusterGenerator.java, address-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, address-controller/src/test/java/io/enmasse/controller/HTTPServerTest.java, address-model-lib/src/main/java/io/enmasse/address/model/Address.java, address-model-lib/src/main/java/io/enmasse/address/model/AddressResolver.java, address-model-lib/src/main/java/io/enmasse/address/model/AddressType.java, address-model-lib/src/main/java/io/enmasse/address/model/Plan.java, address-model-lib/src/main/java/io/enmasse/address/model/v1/AddressV1Deserializer.java, address-model-lib/src/main/java/io/enmasse/address/model/v1/CodecV1.java, address-model-lib/src/test/java/io/enmasse/address/model/v1/address/AddressTest.java, address-model-lib/src/test/java/io/enmasse/address/model/v1/address/SerializationTest.java, k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapAddressApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapAddressSpaceApi.java, queue-scheduler/src/main/java/io/enmasse/queue/scheduler/ConfigServiceClient.java
* This makes it possible to use different plan names for addresses in different address spaces
This fixes #314
=> Resolve address default plan and types when needed

keycloak/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/AmqpServer.java
=> Get groups from Keycloak SASL plugin

address-controller/src/main/java/io/enmasse/controller/ControllerHelper.java, address-controller/src/main/java/io/enmasse/controller/common/Kubernetes.java, address-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java
This makes local development in multitenant mode easier.
Fixes #306
=> Add system:image-puller role to new namespace

address-controller/src/main/java/io/enmasse/controller/HTTPServer.java, address-controller/src/main/java/io/enmasse/controller/api/v1/http/HttpHealthService.java, systemtests/scripts/wait_until_up.sh, systemtests/src/main/java/io/enmasse/systemtest/AddressApiClient.java, templates/include/address-controller.jsonnet, templates/include/common.jsonnet, templates/install/kubernetes/enmasse.yaml, templates/install/openshift/enmasse.yaml
=> Address controller readiness improvements

address-controller/src/main/java/io/enmasse/controller/HTTPServer.java, address-controller/src/main/java/io/enmasse/controller/api/v1/http/HttpAddressRootService.java, address-controller/src/main/java/io/enmasse/controller/api/v1/http/HttpAddressSpaceService.java, address-controller/src/main/java/io/enmasse/controller/api/v1/http/HttpRootService.java, address-controller/src/main/java/io/enmasse/controller/api/v1/http/HttpV1RootService.java, address-controller/src/test/java/io/enmasse/controller/HTTPServerTest.java
=> Add discoverable URIs from /v1 root

ragent/test/ragent.js
I think this should fix issue #368
=> retain parent env along with specific env options passed in to child

router/qdrouterd.conf.template
=> Require TLS enabled for listener on port 5671

systemtests/src/main/java/io/enmasse/systemtest/TestUtils.java
=> UPD TestUtils - sleep replaced by waitingForDestinationReady

pom.xml, systemtests/pom.xml, systemtests/src/test/java/io/enmasse/systemtest/MultiTenantTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/jms/TopicTest.java
- new test for durable subscription
- new test for durable subscription with transactions
- new test for non durable subscription
=> NEW Topic Test for jms client

templates/include/address-controller.jsonnet, templates/install/kubernetes/enmasse.yaml, templates/install/openshift/enmasse.yaml
=> Bump memory requirements for address controller

agent/lib/console_server.js, agent/package.json, agent/test/address_ctrl.js
=> remove dependency on express and basic_auth

templates/include/address-controller.jsonnet, templates/install/kubernetes/enmasse.yaml, templates/install/openshift/enmasse.yaml
=> Disable JIR for the address controller until figuring out the root cause

.travis/setup-openshift.sh, systemtests/scripts/run_test_component.sh, systemtests/src/test/java/io/enmasse/systemtest/MultiTenantTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/SmokeTest.java, templates/include/persistent-volume.json
because no brokered system tests are executed in travis
=> UPD ElemtaryAddressSpaceTest - renamed to SmokeTest

systemtests/src/test/java/io/enmasse/systemtest/brokered/jms/JMSTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/jms/TopicTest.java
New TopicTests for shared subscription
=> 436 topic test

templates/include/brokered-space-infra.jsonnet, templates/include/standard-space-infra.jsonnet, templates/include/storage-template.jsonnet, templates/install/kubernetes/enmasse.yaml, templates/install/openshift/enmasse.yaml
=> Add missing required template parameter for storage template

address-controller/src/main/java/io/enmasse/controller/ControllerHelper.java, address-controller/src/main/java/io/enmasse/controller/api/v1/AddressApiHelper.java, address-controller/src/main/java/io/enmasse/controller/api/v1/http/HttpAddressService.java, address-controller/src/main/java/io/enmasse/controller/common/Kubernetes.java, address-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java, address-controller/src/test/java/io/enmasse/controller/api/v1/AddressApiHelperTest.java, address-controller/src/test/java/io/enmasse/controller/api/v1/http/HttpAddressServiceTest.java, address-controller/src/test/java/io/enmasse/controller/api/v1/http/HttpAddressSpaceServiceTest.java, agent/lib/address_ctrl.js, agent/test/address_ctrl.js
=> Add support for RBAC auth and authz for /v1/addresses

artemis/config_templates/bootstrap.xml, artemis/config_templates/brokered/broker.xml
=> Update static broker configuration after update to Artemis 2.4.0

templates/include/auth-service.jsonnet, templates/install/kubernetes/addons/none-authservice.yaml, templates/install/kubernetes/addons/standard-authservice.yaml, templates/install/openshift/addons/none-authservice.yaml, templates/install/openshift/addons/standard-authservice.yaml
=> Add persistent volumes to keycloak deployment by default

agent/lib/artemis.js, agent/lib/broker_controller.js, agent/test/broker_controller.js, agent/testlib/mock_broker.js
* get principal for session
* fix association between receivers/senders and addresses
=> fixes for brokered space console

agent/lib/address_ctrl.js, agent/lib/artemis.js, agent/lib/broker_controller.js, agent/lib/console_server.js, templates/include/brokered-space-infra.jsonnet, templates/install/kubernetes/enmasse.yaml, templates/install/openshift/enmasse.yaml
* connect to address-controller in brokered space (setup ca secret and env var, use correct port)
* handle failure to delete/create addresses on broker better
* handle deletion of topics with existing subscriptions
* don't delete temporary queues
=> Fixes for agent:

agent/lib/router_stats.js
=> update filtering of internal connections

agent/lib/broker_controller.js, agent/lib/internal_address_source.js, agent/lib/kubernetes.js, agent/www/components/addresses/address_wizard.html, agent/www/components/addresses/addresses_ctrl.js, ragent/router.js
* handle reconnect to broker properly
* handle deletion of queue where queue has been deleted but address has not
* add shard stats
* some ui tweaks to address creation wizard
* fix for issue #332
* only update configmap when status changes
=> Further fixes for agent

systemtests/src/test/java/io/enmasse/systemtest/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/auth/AuthenticationTest.java, systemtests/src/test/java/io/enmasse/systemtest/marathon/AuthenticationTest.java
=> Issue 524 longtime keycloak restart

artemis/config_templates/brokered/broker.xml, artemis/config_templates/brokered/login.config, artemis/sasl-delegation/src/main/java/io/enmasse/artemis/sasl_delegation/SaslDelegatingLogin.java, artemis/sasl-delegation/src/main/java/io/enmasse/artemis/sasl_delegation/SaslGroupBasedSecuritySettingsPlugin.java
=> Add plugin to allow authz checks based on keycloak group membership

HACKING.md, Makefile, systemtests/src/main/java/io/enmasse/systemtest/executor/client/AbstractClient.java, systemtests/src/main/java/io/enmasse/systemtest/executor/client/ClientType.java, systemtests/src/main/java/io/enmasse/systemtest/executor/client/proton/python/PythonClientReceiver.java, systemtests/src/main/java/io/enmasse/systemtest/executor/client/proton/python/PythonClientSender.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/clients/proton/python/MsgPatternsTest.java
=> Dk add cli proton python

address-controller/src/main/java/io/enmasse/controller/Controller.java, address-controller/src/main/java/io/enmasse/controller/ControllerHelper.java, address-controller/src/main/java/io/enmasse/controller/Main.java, address-controller/src/main/java/io/enmasse/controller/auth/AuthController.java, address-controller/src/main/java/io/enmasse/controller/common/ControllerReason.java, address-controller/src/main/java/io/enmasse/controller/common/Kubernetes.java, address-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java, address-controller/src/main/java/io/enmasse/controller/event/ControllerKind.java, address-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, address-controller/src/main/java/io/enmasse/controller/standard/StandardController.java, address-controller/src/test/java/io/enmasse/controller/ControllerHelperTest.java, address-controller/src/test/java/io/enmasse/controller/ControllerTest.java, address-controller/src/test/java/io/enmasse/controller/standard/AddressControllerTest.java, address-controller/src/test/java/io/enmasse/controller/standard/StandardControllerTest.java, k8s-api/pom.xml, k8s-api/src/main/java/io/enmasse/k8s/api/AddressSpaceApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapAddressSpaceApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/EventLogger.java, k8s-api/src/main/java/io/enmasse/k8s/api/KubeEventLogger.java, k8s-api/src/test/java/io/enmasse/k8s/api/KubeEventLoggerTest.java, templates/include/enmasse-template.jsonnet, templates/install/openshift/cluster-roles.yaml
* Add use of events in ConfigMapAddressSpaceApi as an example
Issue #465
=> Add java interface for reporting events and a k8s implementation

agent/lib/address_ctrl.js
=> url encode address name for delete url

address-controller/src/main/java/io/enmasse/controller/ControllerHelper.java, address-controller/src/main/java/io/enmasse/controller/common/Kubernetes.java, address-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java, address-controller/src/test/java/io/enmasse/controller/ControllerHelperTest.java, address-model-lib/src/main/java/io/enmasse/address/model/AddressSpace.java, address-model-lib/src/main/java/io/enmasse/address/model/v1/Fields.java, k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapAddressSpaceApi.java
@rgodfrey The second commit is just picked from master to get a jenkins build.
=> Issue 554 ownerreferences namespaces

agent/lib/address_ctrl.js
The underlying error for issue #603 is fixed by #605 but this improves the error handling in the agent.
=> handling error when communicating with address-controller

agent/www/components/addresses/addresses_ctrl.js
=> fix type filter

router-metrics/Dockerfile
=> Update metrics base image to proton 0.18

address-controller/src/main/java/io/enmasse/controller/ControllerHelper.java, address-model-lib/src/main/java/io/enmasse/address/model/AddressSpace.java, address-model-lib/src/main/java/io/enmasse/address/model/v1/AddressSpaceV1Deserializer.java, address-model-lib/src/main/java/io/enmasse/address/model/v1/AddressSpaceV1Serializer.java, address-model-lib/src/test/java/io/enmasse/address/model/v1/address/SerializationTest.java
* Null means that the 'default' list of endpoint should be used
* Empty means that no endpoints should be created
This fixes #648
=> Differensiate between empty and null endpoint list

systemtests/src/main/java/io/enmasse/systemtest/web/SeleniumProvider.java
- quit does: closing every associated window that was open
=> FIX SeleniumProvider - use only quit on driver

ragent/router.js, ragent/test/ragent.js
when not preceded by any address related actions.
=> Ensure proper handling of completion of link route related actions, even

address-controller/src/main/java/io/enmasse/controller/auth/OpenSSLCertManager.java, address-model-lib/src/main/java/io/enmasse/config/AnnotationKeys.java, artemis/Makefile, artemis/config_templates/artemis.profile, artemis/config_templates/bootstrap.xml, artemis/config_templates/jolokia-access.xml, artemis/config_templates/standard/broker_header.xml, artemis/config_templates/standard/login.config, artemis/sasl-delegation/src/main/java/io/enmasse/artemis/sasl_delegation/SaslGroupBasedSecuritySettingsPlugin.java, artemis/utils/bin/launch.sh, none-authservice/none-authservice.js, templates/include/broker.jsonnet, templates/include/qdrouterd.jsonnet, templates/include/storage-template.jsonnet, templates/install/kubernetes/enmasse.yaml, templates/install/openshift/enmasse.yaml
This enables the hawtio console with auth and authz using the sasl delegation plugin.
=> Enable broker console

templates/include/admin.jsonnet, templates/install/kubernetes/enmasse.yaml, templates/install/openshift/enmasse.yaml
=> Remove configserv from template

keycloak/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/AmqpServer.java, keycloak/sasl-plugin/src/test/java/io/enmasse/keycloak/spi/AmqpServerTest.java
=> Keycloak Plugin should pass address permissions as a map in the open.properties

keycloak-controller/src/main/java/io/enmasse/keycloak/controller/KeycloakParams.java, keycloak-controller/src/test/java/io/enmasse/keycloak/controller/KeycloakParamsTest.java, templates/enmasse-template.jsonnet, templates/include/auth-service.jsonnet, templates/install/kubernetes/addons/keycloak-controller.yaml, templates/install/kubernetes/addons/standard-authservice.yaml, templates/install/openshift/addons/standard-authservice.yaml
* Make hostname and port configurable via configmap
* Create deployment yaml for standalone keycloak-controller
This fixes #682
=> Add deployment for self-managed keycloak controller

agent/lib/router_stats.js, agent/test/router_stats.js
=> Only include normal connections links in sender and receiver counts 

agent/Dockerfile, agent/Makefile
=> modify package target for agent to include the runtime dependencies

address-controller/src/main/java/io/enmasse/controller/auth/OpenSSLCertManager.java, standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, standard-controller/src/main/java/io/enmasse/controller/standard/ControllerReason.java, standard-controller/src/main/java/io/enmasse/controller/standard/KubernetesHelper.java, templates/include/storage-template.jsonnet, templates/install/kubernetes/enmasse.yaml, templates/install/openshift/enmasse.yaml
* Handle cert components part of statefulsets
* Use statefulset in broker template
* Fix exception handling on create in address controller
* Create headless service as required by statefulset
This fixes #749
=> Use stateful sets for brokers

router/Dockerfile
An alternative fix to #789 that avoids setting global policy.
=> update to newer router

systemtests/scripts/system-stats.sh
added command for printing top cpu consuming processes
=> UPD system-stats.sh - more logging about system resources

systemtests/src/main/java/io/enmasse/systemtest/executor/client/AbstractClient.java, systemtests/src/test/java/io/enmasse/systemtest/standard/clients/proton/java/MsgPatternsTest.java
fixes https://github.com/EnMasseProject/enmasse/issues/840
=> UPD enable standard client jsm tests

documentation/design_docs/design/resource-scheduler.adoc
@grs @rgodfrey 
This is a proposal with a pseudo-algorithm that can be implemented in standard-controller to:
* check quota
* scale/create deployments
* schedule pooled addresses
=> Proposal of plan-based quota check, scaling and scheduling

amqp-utils/src/main/java/io/enmasse/amqp/Artemis.java, queue-scheduler/src/main/java/io/enmasse/queue/scheduler/ArtemisAdapter.java
=> Only list queues that also have connector services

systemtests/scripts/docker-logs.sh, systemtests/scripts/run_test_component.sh
=> Rsync docker logs while running tests

HACKING.md
=> update readme to reflect npm requirement

agent/lib/internal_address_source.js, agent/lib/utils.js, agent/test/utils.js
* leading- or trailing- '-' is not allowed
* no upper case chars are allowed
Also fix error handling for creation of address.
Fixes #894
=> Fix sanitizing of kubernetes names

address-model-lib/src/main/java/io/enmasse/address/model/AddressResolver.java, systemtests/src/main/java/io/enmasse/systemtest/Destination.java, systemtests/src/test/java/io/enmasse/systemtest/standard/SmokeTest.java, templates/include/standard-plans.yaml, templates/install/kubernetes/addons/standard-plans.yaml, templates/install/openshift/addons/standard-plans.yaml
=> Add support for colocated topics

templates/install/ansible/roles/systemtests_dependencies/tasks/clients.yml, templates/install/ansible/roles/systemtests_dependencies/tasks/dependencies.yml
@lulf could you please test it on fedora 27? I have no fedora for test it.
=> Update dependencies.yml due to issue 906

artemis/sasl-delegation/src/main/java/io/enmasse/artemis/sasl_delegation/SaslDelegatingLogin.java, artemis/sasl-delegation/src/main/java/io/enmasse/artemis/sasl_delegation/SaslGroupBasedSecuritySettingsPlugin.java, artemis/sasl-delegation/src/test/java/io/enmasse/artemis/sasl_delegation/SaslDelegatingLoginTest.java, keycloak-plugin/sasl-plugin/pom.xml, keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/AmqpServer.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBaseWithShared.java
=> Update keycloak/Artemis plugins to respect ADDRESS_AUTHZ

address-model-lib/src/main/java/io/enmasse/address/model/Status.java, address-model-lib/src/test/java/io/enmasse/address/model/v1/address/AddressTest.java
=> Copy phase in Status copy constructor

address-controller/src/main/java/io/enmasse/controller/api/v1/AddressApiHelper.java, address-controller/src/test/java/io/enmasse/controller/api/v1/AddressApiHelperTest.java
* Ensure no duplicate addresses within new addresses
* Ensure no duplicate addresses in new addresses and existing addresses
This fixes #931
=> Enhance address validation in REST API

systemtests/src/main/java/io/enmasse/systemtest/AddressApiClient.java, systemtests/src/main/java/io/enmasse/systemtest/Destination.java, systemtests/src/main/java/io/enmasse/systemtest/TestUtils.java
=> Set 'name' field in destination based on address

systemtests/src/main/java/io/enmasse/systemtest/AddressApiClient.java, systemtests/src/main/java/io/enmasse/systemtest/AddressSpace.java, systemtests/src/main/java/io/enmasse/systemtest/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/WithoutMqttTest.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, templates/include/enmasse-openshift.jsonnet, templates/include/standard-plans.yaml, templates/include/standard-space-infra.jsonnet, templates/include/template-config.jsonnet, templates/install/kubernetes/addons/standard-plans.yaml, templates/install/kubernetes/enmasse.yaml, templates/install/openshift/addons/standard-plans.yaml, templates/install/openshift/enmasse.yaml
=> Issue 768 allow no mqtt

standard-controller/src/main/java/io/enmasse/controller/standard/AddressProvisioner.java, standard-controller/src/test/java/io/enmasse/controller/standard/AddressProvisionerTest.java, standard-controller/src/test/java/io/enmasse/controller/standard/StandardControllerSchema.java
=> Ensure quota and scaling works when addresses are created in batches

address-controller/src/main/java/io/enmasse/controller/api/v1/http/HttpAddressService.java, address-controller/src/test/java/io/enmasse/controller/HTTPServerTest.java, address-controller/src/test/java/io/enmasse/controller/api/v1/http/HttpAddressServiceTest.java, k8s-api-testutil/src/main/java/io/enmasse/k8s/api/TestAddressApi.java
=> Add support for getting an address by address instead of name

address-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java
* This prevents having to manually delete the configmap on permission
issues
=> Invert order when creating configmap and project

templates/install/deploy-kubernetes.sh
=> Deploy only plans relevant to singletenant deployment

systemtests/src/main/java/io/enmasse/systemtest/AddressApiClient.java
=> UPD AddressApiClient - check response in all methods on 200

agent/lib/internal_address_source.js, agent/test/internal_address_source.js, agent/testlib/mock_resource_server.js
Should fix the broken error handling issue from issue #955
=> handle invalid address syntax

systemtests/pom.xml, systemtests/src/main/java/io/enmasse/systemtest/selenium/SeleniumProvider.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebConsoleTest.java, templates/install/ansible/roles/systemtests_dependencies/defaults/main.yml, templates/install/ansible/roles/systemtests_dependencies/tasks/clients.yml, templates/install/ansible/roles/systemtests_dependencies/tasks/dependencies.yml, templates/install/ansible/roles/systemtests_dependencies/tasks/firefox.yml, templates/install/ansible/roles/systemtests_dependencies/tasks/main.yml
Branch with all fixes for webconsole test failures caused by upgrade to new version of geckodriver and firefox.
=> Webconsole fixes

agent/www/components/addresses/addresses_ctrl.js, agent/www/components/connections/connections_ctrl.js, systemtests/src/main/java/io/enmasse/systemtest/selenium/ConsoleWebPage.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/SeleniumProvider.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/web/FirefoxWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/FirefoxWebConsoleTest.java
fix for #949 (updated to check that filterconfig is initialised)
=> ensure results count is updated when addresses change

templates/include/auth-service.jsonnet, templates/include/brokered-space-infra.jsonnet, templates/include/enmasse-openshift.jsonnet, templates/include/standard-space-infra.jsonnet, templates/include/storage-template.jsonnet, templates/install/deploy-openshift.sh
Comes from CE-9
Signed-off-by: Vanessa Busch <vbusch@redhat.com>
=> [ENTMQMAAS-419] Removed the keyword docker from the templates

agent/lib/kubernetes.js, agent/test/internal_address_source.js, agent/testlib/mock_resource_server.js
Fixes possible cause of issue #1052
=> handle failure on kubernetes request

templates/include/auth-service.jsonnet, templates/install/kubernetes/addons/standard-authservice.yaml, templates/install/openshift/addons/standard-authservice.yaml
=> Reduce initial delay for keycloak deployment

keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/SaslAuthenticator.java, keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/XOAUTH2SaslServerMechanism.java, keycloak-plugin/sasl-plugin/src/test/java/io/enmasse/keycloak/spi/XOAUTH2SaslServerMechanismTest.java
=> Add XOAUTH2 support to keycloak plugin

standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java
=> Only check status of router pods that are ready

keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/XOAUTH2SaslServerMechanism.java
@rgodfrey, though a little ugly this seems to me the simplest solution to getting the url set correctly
=> derive base uri from service host if set

keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/SaslAuthenticator.java, keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/XOAUTH2SaslServerMechanism.java
=> Fixes and tweaks to Keycloak XOAUTH2 support

agent/bin/ragent.js, agent/lib/ragent.js, agent/lib/router.js, agent/test/ragent.js, agent/testlib/mock_router.js
(and that are no longer desired of course)
=> have agent only delete entities that it created 

systemtests/src/main/java/io/enmasse/systemtest/TestTag.java, systemtests/src/test/java/io/enmasse/systemtest/WithoutMqttTest.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBaseWithShared.java, systemtests/src/test/java/io/enmasse/systemtest/bases/auth/AuthenticationTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebConsolePlansTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/api/AddressControllerApiTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/plans/PlansTest.java, systemtests/src/test/java/io/enmasse/systemtest/marathon/MarathonTestBase.java
This functionality could help to avoid typos in @ Tags
=> NEW TestTag class with predefined test tags

systemtests/src/main/java/io/enmasse/systemtest/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/common/plans/PlansTest.java
- wait for existing pods instead of Running pods
=> FIX testAutoScaleAfterManualScale - waiting fixed

systemtests/src/main/java/io/enmasse/systemtest/KeycloakClient.java, systemtests/src/main/java/io/enmasse/systemtest/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBaseWithShared.java, systemtests/src/test/java/io/enmasse/systemtest/standard/QueueTest.java
- added method for deploy without wait and for wait without deploy
- logging when user is removed
=> NEW standard/QueueTest for async creating addresses, users, send/receive

agent/lib/auth_service.js, agent/lib/auth_utils.js, agent/lib/ragent.js
=> strip off session_state from query string on authentication

agent/lib/internal_address_source.js, agent/test/internal_address_source.js
=> handle 0 when sorting by displayOrder

templates/install/ansible/roles/none_authservice/tasks/main.yml, templates/install/ansible/roles/standard_authservice/tasks/main.yml
https://github.com/EnMasseProject/enmasse/issues/1213
=> kubectl hard coded in ansible roles

agent/bin/agent.js, agent/lib/broker_controller.js, agent/lib/ragent.js, agent/lib/router_config.js, agent/test/ragent.js, systemtests/src/test/java/io/enmasse/systemtest/common/plans/PlansTest.java
This does not scale well with the number of queues on a broker. Alternative approaches seem overly complex in comparison to the derived benefit.
=> Remove configuration of address settings

templates/install/common.sh
=> Fix missing character escapes

agent/www/help.html, api-common/src/main/java/io/enmasse/api/auth/KubeAuthApi.java, api-common/src/main/java/io/enmasse/api/auth/RbacSecurityContext.java, api-common/src/test/java/io/enmasse/api/auth/AuthInterceptorTest.java, service-broker/src/main/java/io/enmasse/osb/HTTPServer.java, service-broker/src/main/java/io/enmasse/osb/api/OSBServiceBase.java, service-broker/src/main/java/io/enmasse/osb/api/console/HttpConsoleService.java, service-broker/src/main/java/io/enmasse/osb/api/provision/OSBProvisioningService.java, templates/include/address-space-controller.jsonnet, templates/include/api-server.jsonnet, templates/include/cluster-roles/service-broker.yaml, templates/include/service-broker.jsonnet, templates/install/resources/address-space-controller/deployment.yaml, templates/install/resources/api-server/deployment.yaml, templates/install/resources/cluster-roles/service-broker.yaml, templates/install/resources/service-broker/deployment.yaml
=> Set namespace value correctly for new address spaces

service-broker/src/main/java/io/enmasse/osb/api/bind/OSBBindingService.java
=> Use correct realm name when creating bindings

api-server/src/main/resources/swagger.json, documentation/common/configuring-using-restapi.adoc, documentation/getting_started/configuring-addresses.adoc
It woluld be good to generate swagger.json file automatically and have SwaggerUI option for this.
I will try to take care about this in the future.
=> Fix API version and docs misrpints

service-broker/src/main/java/io/enmasse/osb/api/OSBServiceBase.java, systemtests/src/main/java/io/enmasse/systemtest/apiclients/OSBApiClient.java
=> Remove enmasse- prefix from address spaces created through service

address-model-lib/src/main/java/io/enmasse/address/model/Address.java, address-model-lib/src/test/java/io/enmasse/address/model/v1/address/AddressTest.java, standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, standard-controller/src/main/java/io/enmasse/controller/standard/AddressProvisioner.java
=> When creating sharded brokers, use the address without the prefix

address-model-lib/src/main/java/io/enmasse/address/model/AddressSpace.java, address-model-lib/src/test/java/io/enmasse/address/model/AddressSpaceTest.java, address-space-controller/src/main/java/io/enmasse/controller/ControllerChain.java
=> the definition of equals (and hashCode) on AddressSpace should include namespace

templates/include/cluster-roles/api-server.yaml, templates/include/cluster-roles/service-broker.yaml, templates/install/resources/cluster-roles/api-server.yaml, templates/install/resources/cluster-roles/service-broker.yaml
=> Modify api-server role so it uses correct apiGroups

agent/lib/internal_address_source.js, agent/lib/utils.js, agent/test/internal_address_source.js
=> Ensure console creates addresses with names beginning <addressspace>.

templates/include/address.yaml, templates/include/api-server.jsonnet, templates/include/benchmark-template.json, templates/include/brokered-plans.yaml, templates/include/cluster-roles/address-space-controller.yaml, templates/include/cluster-roles/api-server.yaml, templates/include/cluster-roles/service-broker.yaml, templates/include/common.jsonnet, templates/include/grafana.jsonnet, templates/include/prometheus.jsonnet, templates/include/resource-definitions.yaml, templates/include/standard-plans.yaml, templates/install/common.sh, templates/install/deploy.sh, templates/install/resources/cluster-roles/address-space-controller.yaml, templates/install/resources/cluster-roles/api-server.yaml, templates/install/resources/cluster-roles/service-broker.yaml, templates/install/resources/plans/brokered-plans.yaml, templates/install/resources/plans/standard-plans.yaml, templates/install/resources/resource-definitions/resource-definitions.yaml, templates/install/resources/templates/address.yaml
The activities with labels help to delete with selector like
oc delete all,pvc,configmap,rolebindings,secrets,sa -l 'app=enmasse'
I will update ansible configs and add remove action inside deploy.sh in the future if necessary
=> Add label app=enmasse to all entities

templates/include/prometheus.jsonnet, templates/install/resources/prometheus/prometheus.yaml
sorry, fix my typos
@lulf , please merge
=> Fix my missprint during template changes

router/Dockerfile, systemtests/src/main/java/io/enmasse/systemtest/amqp/Receiver.java
Router image includes patch for PROTON-1845
=> Router 1.1.0 rc3

systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/api/ApiServerTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/plans/PlansTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/ChromeWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/FirefoxWebConsoleTest.java
This branch contains fixes for common tests which failed in CI.
=> Fixes for common tests

templates/include/cluster-roles/developer.yaml, templates/include/cluster-roles/tenant.yaml, templates/install/resources/cluster-roles/developer.yaml, templates/install/resources/cluster-roles/tenant.yaml, templates/install/resources/grafana/grafana.yaml, templates/install/resources/prometheus/prometheus.yaml, templates/install/resources/templates/api-service.yaml
@rgodfrey How about something like this that can be assigned to the tenant and developer users. I'm not sure if developer is the best name though...
=> Tenant developer roles

agent/www/shared/address_service.js, systemtests/src/test/java/io/enmasse/systemtest/brokered/web/ChromeWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/web/FirefoxWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/ChromeWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/FirefoxWebConsoleTest.java
=> fix update of results after deletion of addresses

systemtests/src/main/java/io/enmasse/systemtest/TestUtils.java
@tkratky @kornys I think this is what broke systemtests :)
=> Get endpoint object from correct json object

templates/install/deploy.sh
For the Openshift deployment in deploy.sh, the keycloak route host will be used for the keycloak-config httpUrl by default. Only if this resolves to something like "keycloak-enmasse.127.0.0.1.nip.io", the clusterIP of the standard-authservice will be used.
This fixes the keycloak OAuth redirect for the EnMasse console not working in case the standard-authservice clusterIP is used.
=> Fix keycloak-config httpUrl

systemtests/src/main/java/io/enmasse/systemtest/selenium/SeleniumProvider.java
- unfortunately not supported for firefox
=> NEW functionality for saving browser logs

k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapSchemaApi.java, router/Dockerfile, router/qdrouterd.conf.template, systemtests/src/main/java/io/enmasse/systemtest/AddressSpace.java, systemtests/src/main/java/io/enmasse/systemtest/amqp/AmqpClientFactory.java, systemtests/src/main/java/io/enmasse/systemtest/clients/ClientArgument.java, systemtests/src/main/java/io/enmasse/systemtest/clients/rhea/RheaClientConnector.java, systemtests/src/main/java/io/enmasse/systemtest/clients/rhea/RheaClientReceiver.java, systemtests/src/main/java/io/enmasse/systemtest/clients/rhea/RheaClientSender.java, systemtests/src/main/java/io/enmasse/systemtest/mqtt/MqttClientFactory.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/RheaWebPage.java, systemtests/src/main/resources/rhea.html, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/bases/clients/ClientTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebSocketBrowserTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/clients/rhea/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/ChromeWebSocketBrowserTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/FirefoxWebSocketBrowserTest.java, templates/include/address-space-definitions.yaml, templates/install/ansible/roles/standard_authservice/tasks/main.yml, templates/install/deploy.sh, templates/install/resources/address-space-controller/address-space-definitions.yaml
=> Issue 403 websocket support

standard-controller/src/test/java/io/enmasse/controller/standard/AddressProvisionerTest.java, standard-controller/src/test/java/io/enmasse/controller/standard/StandardControllerSchema.java
@grs @vbusch Here are some basic unit tests for the durable subscriptions.
The pooled test passes, but the sharded test fails with a NPE in the current code.
As we agreed, I made this PR against the 'development work' branch.
=> Provisioner unit tests

documentation/messaging_app_developer/connecting.adoc
Sorry I missed the documentation on my previous PR. This one has a client example for using websockets.
Potentially there are more documentation needed for clients, but I don't know the best place to put that.
Issue #403
=> Add example rhea client using websockets

templates/include/address-space-definitions.yaml, templates/install/resources/address-space-controller/address-space-definitions.yaml
=> Add label app=enmasse to broker-prometheus-config ConfigMap

address-space-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java
Part of the fix for #1271.
This makes `addAddressSpaceAdminRoleBinding()` and `addAddressSpaceRoleBindings()` in `KubernetesHelper` work in case of a Kubernetes cluster.
=> Create AddressSpace RoleBindings for Kubernetes (#1271)

address-model-lib/src/main/java/io/enmasse/address/model/AddressSpace.java, address-model-lib/src/main/java/io/enmasse/address/model/v1/AddressSpaceV1Deserializer.java, address-model-lib/src/test/java/io/enmasse/address/model/AddressSpaceTest.java, address-model-lib/src/test/java/io/enmasse/address/model/v1/address/SerializationTest.java, address-space-controller/src/main/java/io/enmasse/controller/ControllerOptions.java, address-space-controller/src/main/java/io/enmasse/controller/CreateController.java, address-space-controller/src/main/java/io/enmasse/controller/EndpointController.java, address-space-controller/src/main/java/io/enmasse/controller/Main.java, address-space-controller/src/main/java/io/enmasse/controller/TemplateInfraResourceFactory.java, address-space-controller/src/main/java/io/enmasse/controller/auth/AuthController.java, address-space-controller/src/main/java/io/enmasse/controller/auth/CertManager.java, address-space-controller/src/main/java/io/enmasse/controller/auth/CertProvider.java, address-space-controller/src/main/java/io/enmasse/controller/auth/EndpointInfo.java, address-space-controller/src/main/java/io/enmasse/controller/auth/OpenSSLCertManager.java, address-space-controller/src/main/java/io/enmasse/controller/auth/SelfsignedCertProvider.java, address-space-controller/src/main/java/io/enmasse/controller/auth/WildcardCertProvider.java, address-space-controller/src/main/java/io/enmasse/controller/common/Kubernetes.java, address-space-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java, address-space-controller/src/test/java/io/enmasse/controller/EndpointControllerTest.java, keycloak-controller/src/main/java/io/enmasse/keycloak/controller/KeycloakManager.java, keycloak-controller/src/test/java/io/enmasse/keycloak/controller/KeycloakManagerTest.java, service-broker/src/main/java/io/enmasse/osb/api/OSBServiceBase.java, templates/include/address-space-controller.jsonnet, templates/install/resources/address-space-controller/deployment.yaml
* Always create endpoints for services by default
* Add configuration option to address space controller config to remove exposure
* Add service host to cert CN
Next step is to allow individual endpoints to be expose.
Fixes #1398
=> Control endpoint exposure via address space controller config

systemtests/src/test/java/io/enmasse/systemtest/brokered/QueueTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/QueueTest.java
Just small change due to standard test naming convention.
=> Refactor brokered Queue test names

systemtests/src/main/java/io/enmasse/systemtest/TestUtils.java, systemtests/src/main/java/io/enmasse/systemtest/apiclients/AddressApiClient.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/common/api/ApiServerTest.java
* New systemtest for deleting all addresses with one command
* Refactor existing test to use new 'deleteAllAddressSpaces' method
=> New API test (#1429)

address-model-lib/src/main/java/io/enmasse/address/model/AddressResolver.java
@grs This should make it clearer.
=> Improve error message when not finding plan of a type

systemtests/src/main/java/io/enmasse/systemtest/selenium/page/OpenshiftLoginWebPage.java, systemtests/src/test/java/io/enmasse/systemtest/common/catalog/ServiceCatalogApiTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/catalog/ServiceCatalogWebTest.java
Hi David + Tomas, 
all tests are passing when I check them now, code is formatted correctly, and sorry about the problems with Jenkins. Lesson learned from my side. 
Thanks for review
=> Refactor of selenium webtests based on failing jenkins jobs

systemtests/src/test/java/io/enmasse/systemtest/bases/clients/ClientTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/clients/artemis/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/clients/openwire/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/clients/proton/java/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/clients/proton/python/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/clients/rhea/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/clients/proton/java/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/clients/proton/python/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/clients/rhea/MsgPatternsTest.java
Fix for selectorTopicTest in MsgPatternsTest.
=> Fix selectorTopic test

agent/lib/router_config.js, agent/test/ragent.js, artemis/config_templates/standard/colocated/broker.xml, artemis/config_templates/standard/sharded-queue/broker.xml, router/qdrouterd.conf.template
… over different connections (related to issue-1431)
=> separate in and out traffic between router and broker 

documentation/design_docs/operations/resources.adoc
Added the following address types:
- sharded queue
- sharded topic
- anycast
- multicast
Added resources created when producers and consumers connect
=> Added remaining address types to docs

templates/include/address-space-definitions.yaml
=> Use -1 for global max size to tune memory limits based on heap

keycloak-controller/src/main/java/io/enmasse/keycloak/controller/Keycloak.java, keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/PlainSaslServerMechanism.java, keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/SaslAuthenticator.java, keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/SaslServerMechanism.java, keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/ScramSaslAuthenticator.java, keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/ScramSaslServerMechanism.java, keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/XOAUTH2SaslServerMechanism.java, keycloak-plugin/sasl-plugin/src/test/java/io/enmasse/keycloak/spi/PlainSaslServerMechanismTest.java, keycloak-plugin/sasl-plugin/src/test/java/io/enmasse/keycloak/spi/XOAUTH2SaslServerMechanismTest.java
=> Only offer SASL mechanisms which can be supported

systemtests/src/main/java/io/enmasse/systemtest/AddressType.java, systemtests/src/main/java/io/enmasse/systemtest/Destination.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/ChromeWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/FirefoxWebConsoleTest.java
issue #1474
* New test for creating/deleting durable subs in web console
* New public enum addressType : SUBSCRIPTION
* Update to systemtest/Destination.java
=>  New systemtest for durable subscriptions in webui

systemtests/scripts/setup-openshift.sh, systemtests/scripts/test_func.sh, systemtests/scripts/wait_until_up.sh
- wait until cluster is up moved into function
=> use logging from logger.sh instead of echo

systemtests/scripts/setup-openshift.sh, systemtests/scripts/test_func.sh
because we want use default docker logging into /var/log/containers/*.logs
=> NEW test_func: remove docker-logs driver from daemon.json config

agent/lib/router_stats.js
=> lookup by prefix not name

agent/www/components/addresses/address_wizard.html
=> restrict length of name allowed

api-server/src/main/java/io/enmasse/api/v1/AddressApiHelper.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpAddressSpaceService.java, api-server/src/test/java/io/enmasse/api/v1/AddressApiHelperTest.java, api-server/src/test/java/io/enmasse/api/v1/http/HttpAddressSpaceServiceTest.java, api-server/src/test/java/io/enmasse/api/v1/http/HttpNestedAddressServiceTest.java, k8s-api-testutil/src/main/java/io/enmasse/k8s/api/TestAddressApi.java, k8s-api-testutil/src/main/java/io/enmasse/k8s/api/TestAddressSpaceApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/AddressApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/AddressSpaceApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapAddressApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapAddressSpaceApi.java
=> PUT on non-existing address(space) now returns 404 (#1384)

systemtests/src/main/java/io/enmasse/systemtest/Destination.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/FirefoxWebConsoleTest.java
* testAddressNameWithHyphens
* testVerylongAddressName
* testCreateAddressWithSpecialChars
=> New tests for console address creation with long/strange names

README.md
* Remove reference to module no longer part of EnMasse
Fixes #1593
=> Fix link to contributing

api-server/src/main/java/io/enmasse/api/v1/AddressApiHelper.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpAddressServiceBase.java, api-server/src/test/java/io/enmasse/api/v1/AddressApiHelperTest.java, api-server/src/test/java/io/enmasse/api/v1/http/HttpNestedAddressServiceTest.java, k8s-api-testutil/src/main/java/io/enmasse/k8s/api/TestAddressApi.java, k8s-api-testutil/src/main/java/io/enmasse/k8s/api/TestAddressSpaceApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/AddressApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/AddressSpaceApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapAddressApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapAddressSpaceApi.java
=> Return 404 when trying to delete non-existing address (#1387)

agent/lib/auth_service.js
=> Logged error when console can't connect to authentication server

keycloak-plugin/src/main/configuration/standalone.xml, keycloak-plugin/src/main/sh/init-keycloak.sh
=> Import system certs into trust store

systemtests/src/main/java/io/enmasse/systemtest/User.java, systemtests/src/main/java/io/enmasse/systemtest/apiclients/UserApiClient.java, systemtests/src/test/java/io/enmasse/systemtest/common/api/UserApiTest.java
* testCreateUserUnderscoreUsername
* new method to pass in custom username into api metadata
=> NEW systemtest for userapi testCreateUserUnderscoreUsername

Makefile.common
=> Remove unused npm targets

api-server/src/main/java/io/enmasse/api/v1/http/HttpAddressService.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpAddressSpaceService.java
=> Fix DELETE requests on non-existing resources returning a 500 response

systemtests/src/test/java/io/enmasse/systemtest/common/api/UserApiTest.java
- Hyphens are allowed in the username created by UserApi
- User name must start with Char, if not reply of 400 BAD_REQUEST
=>  NEW(UserApiTest) new tests for UserApi common tests

agent/package.json
To avoid reported vulnerability
=> further change to debug dependency version

agent/lib/router_stats.js
=> include durable subscription receivers in count of topic receivers 

Makefile, scripts/docker_push.sh
(Assumes coreutils installed from brew or MacPorts)
=> Make Makefile and scripts/docker_push.sh run on Mac OS X.

agent/lib/router_stats.js
=> set message_in/message_out for link routed addresses i.e. topics

address-space-controller/src/main/java/io/enmasse/controller/EndpointController.java, address-space-controller/src/main/java/io/enmasse/controller/auth/SelfsignedCertProvider.java
=> Add more logging around route secret creation

address-model-lib/src/main/java/io/enmasse/address/model/AuthenticationServiceType.java, address-model-lib/src/main/java/io/enmasse/address/model/KubeUtil.java, address-space-controller/src/main/java/io/enmasse/controller/CreateController.java, address-space-controller/src/main/java/io/enmasse/controller/TemplateInfraResourceFactory.java
If auth service CA is not specified, the system CAs will be used in its place.
I'm wondering if this is a solution that will solve your use case @calohmn, as I believe the CA you are using is trusted by the root CA. Question is what to do with cert renewal, but I think that is an issue we need to deal with in other places as well.
=> Issue 1580 make cacert optional

templates/prometheus/010-ConfigMap-prometheus-config.yaml
Removed an extra line causing Prometheus to fail to start
Removed target labels where unnecessary
=> Fixed typo in promethues scrape config

api-server/src/main/java/io/enmasse/api/server/ApiServer.java, api-server/src/main/java/io/enmasse/api/server/ApiServerOptions.java, keycloak-controller/src/main/java/io/enmasse/keycloak/controller/KeycloakManager.java, keycloak-controller/src/test/java/io/enmasse/keycloak/controller/KeycloakManagerTest.java, keycloak-user-api/src/main/java/io/enmasse/user/keycloak/KeycloakUserApi.java, user-api/src/main/java/io/enmasse/user/api/UserApi.java
=> Wait for realm to exist in API server

systemtests/src/main/java/io/enmasse/systemtest/selenium/page/OpenshiftWebPage.java
Fail with better message (rather than an AIOOBExceptions).
=> System tests: Fail clearly when the service broker is not deployed

agent/www/components/addresses/address_wizard.html, agent/www/components/addresses/addresses_ctrl.js
=> prevent address being created through console with certain chars

HACKING.md, documentation/getting_started/kubernetes.adoc, documentation/getting_started/openshift.adoc, documentation/modules/proc-deploying-address-space-controller.adoc, documentation/modules/proc-deploying-api-server.adoc, documentation/modules/proc-deploying-auth-services.adoc, documentation/modules/proc-deploying-service-broker.adoc, documentation/modules/proc-installing-using-template.adoc, systemtests/scripts/run_test_kubernetes.sh, templates/Makefile
* Rename `examples` to `install` and `examples/install` to `install/components`
* Replace myproject in documentation examples
=> Rename paths in tarball

systemtests/src/main/java/io/enmasse/systemtest/amqp/AmqpClient.java, systemtests/src/main/java/io/enmasse/systemtest/amqp/ClientHandlerBase.java, systemtests/src/main/java/io/enmasse/systemtest/amqp/Receiver.java, systemtests/src/main/java/io/enmasse/systemtest/amqp/Sender.java
* Be more verbose in container id
* Be more verbose in exception messages
=> Put more info into client container id

agent/www/components/addresses/addresses.html, agent/www/components/addresses/addresses_ctrl.js
Added message for incorrect filter, from issue #1591.
=> Provide error message, for invalid filter in the console.

agent/lib/router_stats.js, agent/www/components/connections/connections.html, agent/www/components/connections/connections_ctrl.js
=> fix indexing for connection stats

systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/web/ChromeWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/web/FirefoxWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/ChromeWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/FirefoxWebConsoleTest.java
*  test is now negative, as specialChars are now restricted in address names,
* disabled testCreateAddressWithSymbolsAt61stCharIndex until I can update them with the same changes here
=> Complete rewrite to existing specialChars test

agent/www/components/addresses/addresses_ctrl.js, agent/www/components/connections/connections_ctrl.js
=> Re-apply sort on the arrival of connection and address updates.

systemtests/src/main/java/io/enmasse/systemtest/AddressSpace.java, systemtests/src/main/java/io/enmasse/systemtest/amqp/AmqpClient.java, systemtests/src/main/java/io/enmasse/systemtest/amqp/ClientHandlerBase.java, systemtests/src/main/java/io/enmasse/systemtest/amqp/Sender.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/bases/authz/AuthorizationTestBase.java
* Disable test for sending to multicast address
=> Fix authorization tests

systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebConsoleTest.java
This will fix the last fail with chrome test
=> Fix reduce logout/login operation between create/delete action

service-broker/src/main/java/io/enmasse/osb/api/bind/OSBBindingService.java
This should fix unstable catalog tests where service broker receives
another request if the previous response did not get through.
=> Handle multiple bind requests from catalog

agent/www/components/addresses/addresses.html, agent/www/components/addresses/addresses_ctrl.js
=> Fix dismissing of filter error message, allows it to redisplay on next error.

agent/www/components/addresses/addresses_ctrl.js, agent/www/components/connections/connections.html, agent/www/components/connections/connections_ctrl.js
Also refactored algorithm so that it does not rely on the invalid filter being on the end of the array for correct behaviour.
=> Add error message for incorrect filters on connections tab too.

systemtests/src/main/java/io/enmasse/systemtest/timemeasuring/TimeMeasuringSystem.java
Data output:
```json
{
"TEST_EXECUTION": 193168,
"CREATE_ADDRESS_SPACE": 75696,
"CREATE_USER": 2279,
"CREATE_ADDRESS": 48471,
"DELETE_ADDRESS_SPACE": 1716,
"DELETE_USER": 0,
"UPDATE_USER": 0,
"DELETE_ADDRESS": 18137,
"APPEND_ADDRESS": 0,
"CREATE_SELENIUM_CONTAINER": 0,
"DELETE_SELENIUM_CONTAINER": 0
}
```
=> Report sum of test operations

agent/www/components/addresses/addresses.html, agent/www/shared/address_service.js, systemtests/src/main/java/io/enmasse/systemtest/selenium/resources/AddressWebItem.java
Also change the description and add tooltip giving more info.
=> fix and improve messages in/out for addresses

address-space-controller/src/main/java/io/enmasse/controller/auth/OpenSSLCertManager.java
=> Improve error handling of OpenSSL command-line invocations.

keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/SaslAuthenticator.java
=> Always offer PLAIN and XOAUTH2 SASL Mechanisms

documentation/assemblies/assembly-monitoring-kube.adoc, documentation/assemblies/assembly-monitoring-oc.adoc, documentation/modules/proc-get-logs-broker.adoc, documentation/modules/proc-get-logs-router.adoc, documentation/modules/proc-restart-component.adoc
Docs added:
- restarting components
- viewing component logs
=> Added sys-admin docs

api-server/src/main/java/io/enmasse/api/server/ApiServer.java
This works around OpenShift 3.9 cert issues when using oc cluster up
=> Test client certificate before trusting

documentation/modules/proc-create-address-space-cli.adoc
@lulf, I think this should fix this issue. Thanks!
=> Issue 1782: fix docs coding issue

agent/www/components/addresses/addresses_ctrl.js, agent/www/components/connections/connections_ctrl.js, agent/www/shared/address_service.js, systemtests/src/test/java/io/enmasse/systemtest/brokered/web/FirefoxWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/FirefoxWebConsoleTest.java
=> index addresses and coalesce updates

agent/www/components/addresses/addresses_ctrl.js
Potential fix for issue #1728.
=> Avoid error situation recorded in console log for CI failure.

address-space-controller/pom.xml, address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceController.java, address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceControllerOptions.java, address-space-controller/src/main/java/io/enmasse/controller/StatusController.java, address-space-controller/src/test/java/io/enmasse/controller/StatusControllerTest.java, api-server/src/test/java/io/enmasse/api/v1/http/TestUserApi.java, keycloak-controller/src/test/java/io/enmasse/keycloak/controller/KeycloakManagerTest.java, keycloak-user-api/src/main/java/io/enmasse/user/keycloak/KeycloakUserApi.java, templates/address-space-controller/050-Deployment-address-space-controller.yaml, user-api/src/main/java/io/enmasse/user/api/UserApi.java
@k-wall @kornys This adds another status check for address spaces to verify that their keycloak realm have been created when using the standard auth service.
=> Issue 1745 address space ready realm

agent/lib/qdr.js
Potential fix to issues #1566 and #1810
=> throttle requests to router

pom.xml
=> Add missing metadata to top-level pom, including license. 

systemtests/scripts/wait_until_up.sh
Waiting before get count of pods.
=> Hotfix for upgrade phase

agent/lib/router_stats.js, agent/www/components/addresses/addresses_ctrl.js
Partly addresses #1605.
Screenshot attached.
=> Display the Container ID of the client's connection in Console.

agent/lib/broker_controller.js
=> Fix defect that prevented outgoing links being populated on the address tab

agent/npm-shrinkwrap.json, agent/pom.xml
=> include shrinkwrap definition for runtime deps

systemtests/ansible/roles/systemtests_dependencies/defaults/main.yml, systemtests/ansible/roles/systemtests_dependencies/tasks/clients.yml
=> Use stable version of cli-java

systemtests/src/main/java/io/enmasse/systemtest/TestUtils.java, systemtests/src/main/java/io/enmasse/systemtest/apiclients/MsgCliApiClient.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/ClientType.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/mqtt/PahoMQTTClientReceiver.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/mqtt/PahoMQTTClientSender.java, systemtests/src/test/java/io/enmasse/systemtest/bases/clients/ClusterClientTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/clients/mqtt/MsgPatternsInternalTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/clients/mqtt/MsgPatternsInternalTest.java
Tests for base testing internal mqtt messaging.
=> Mqtt internal tests

agent/www/components/addresses/addresses.html, agent/www/components/addresses/addresses_ctrl.js, agent/www/components/connections/connections_ctrl.js
=> Standardise terminolgy "Container ID", "Senders" and "Receiver" labels.

systemtests/src/main/java/io/enmasse/systemtest/Destination.java, systemtests/src/main/java/io/enmasse/systemtest/DestinationPlan.java, systemtests/src/main/java/io/enmasse/systemtest/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/ability/ITestBaseBrokered.java, systemtests/src/main/java/io/enmasse/systemtest/ability/ITestBaseStandard.java, systemtests/src/main/java/io/enmasse/systemtest/ability/ITestBaseWithoutMqtt.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBaseWithShared.java, systemtests/src/test/java/io/enmasse/systemtest/bases/clients/ClusterClientTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/common/CommonTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/api/ApiServerTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/api/CustomResourceDefinitionAddressesTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/api/UserApiTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/catalog/ServiceCatalogApiTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/catalog/ServiceCatalogWebTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/upgrade/UpgradeTest.java, systemtests/src/test/java/io/enmasse/systemtest/marathon/PlansMarathonTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/AnycastTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/QueueTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/SmokeTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/TopicTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/mqtt/ConnectionTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/mqtt/InteroperabilityTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/mqtt/PublishTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/mqtt/SessionTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/ChromeWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/FirefoxWebConsoleTest.java
@lulf PR contains one test just for check if logs are accessible to cover one requirement and I made changes which reduce writing plans for destinations as string.
=> Test for check if logs are accesssible

address-space-controller/pom.xml, address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceController.java, address-space-controller/src/main/java/io/enmasse/controller/ControllerChain.java, address-space-controller/src/main/java/io/enmasse/controller/HTTPServer.java, address-space-controller/src/test/java/io/enmasse/controller/ControllerChainTest.java, api-server/pom.xml, api-server/src/main/java/io/enmasse/api/server/ApiServer.java, api-server/src/main/java/io/enmasse/api/server/ApiServerOptions.java, api-server/src/main/java/io/enmasse/api/server/HTTPServer.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpHealthService.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpMetricsService.java, api-server/src/test/java/io/enmasse/api/server/HTTPServerTest.java, metrics-api/pom.xml, metrics-api/src/main/java/io/enmasse/metrics/api/Metric.java, metrics-api/src/main/java/io/enmasse/metrics/api/MetricLabel.java, metrics-api/src/main/java/io/enmasse/metrics/api/MetricType.java, metrics-api/src/main/java/io/enmasse/metrics/api/MetricValue.java, metrics-api/src/main/java/io/enmasse/metrics/api/Metrics.java, metrics-api/src/main/java/io/enmasse/metrics/api/MetricsFormatter.java, metrics-api/src/main/java/io/enmasse/metrics/api/PrometheusMetricsFormatter.java, metrics-api/src/test/java/io/enmasse/metrics/api/MetricsTest.java, metrics-api/src/test/java/io/enmasse/metrics/api/PrometheusMetricsFormatterTest.java, pom.xml, templates/address-space-controller/040-Service-address-space-controller.yaml, templates/address-space-controller/050-Deployment-address-space-controller.yaml, templates/prometheus/010-ConfigMap-prometheus-config.yaml
* Add Java API for reporting metrics in controller loop
* Report address space status and number of address spaces
* Format metrics as prometheus metrics
Issue #1832
=> Add address space status metrics to address-space-controller

service-broker/src/main/java/io/enmasse/osb/api/bind/OSBBindingService.java, systemtests/src/test/java/io/enmasse/systemtest/common/catalog/ServiceCatalogApiTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/catalog/ServiceCatalogWebTest.java
=> Implement deletion of bindings

systemtests/pom.xml, systemtests/scripts/run_test_component.sh, systemtests/src/main/java/io/enmasse/systemtest/TestTag.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/auth/AuthenticationTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/api/ApiServerTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/api/CustomResourceDefinitionAddressSpacesTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/api/CustomResourceDefinitionAddressesTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/auth/AuthenticationTest.java
@lulf updated profiles for running tests without tests with none auth service
=> New profile for release testing

agent/lib/console_server.js, documentation/modules/proc-deleting-users-cli.adoc, documentation/modules/proc-deploying-address-space-controller.adoc, documentation/modules/proc-deploying-api-server.adoc, documentation/modules/proc-deploying-auth-services.adoc, documentation/modules/proc-deploying-service-broker.adoc, documentation/modules/proc-get-logs-broker.adoc, documentation/modules/proc-get-logs-router.adoc, documentation/modules/proc-installing-using-ansible.adoc, documentation/modules/proc-installing-using-bundle.adoc, documentation/modules/proc-logging-in-console.adoc, documentation/modules/proc-restart-component.adoc, documentation/modules/proc-upgrading-enmasse-using-ansible.adoc, documentation/modules/ref-cpp-example.adoc, documentation/modules/ref-dotnet-example.adoc, documentation/modules/ref-javascript-example.adoc, documentation/modules/ref-jms-example.adoc, documentation/modules/ref-python-example.adoc
@lulf, If you would review just to doublecheck that I didn't alter the meaning of anything in the minor copyedits or clean up of any stray carets in code blocks.
=> Docs: miscellaneous minor edits and styling cleanup

ansible/roles/monitoring/tasks/main.yml, templates/Makefile, templates/kube-state-metrics/010-ServiceAccount-kube-state-metrics.yaml, templates/kube-state-metrics/020-Role-kube-state-metrics.yaml, templates/kube-state-metrics/030-Deployment-kube-state-metrics.yaml, templates/kube-state-metrics/030-Rolebinding-kube-state-metrics.yaml, templates/prometheus/010-ConfigMap-prometheus-config.yaml
Checks added:
* Pods stuck in terminating state
* Pods repeatedly restarting
=> Added health checks for failing kubernetes pods

documentation/assemblies/assembly-managing-address-spaces.adoc, documentation/common/address-space-output-example1.yaml, documentation/modules/con-retrieving-address-space-information.adoc, documentation/modules/proc-create-address-console.adoc, documentation/modules/proc-create-address-space-cli.adoc, documentation/modules/proc-logging-in-console.adoc, documentation/modules/proc-send-receive.adoc
* Add missing links between console docs
=> Move address space commands into own section

scripts/check_docs.sh
=> don't flag words ending in ie or eg

systemtests/scripts/deploy_enmasse.sh, systemtests/scripts/run_test_component.sh, systemtests/scripts/test_func.sh
@lulf I made a mistake which caused that upgrade deployment waiting for wrong count of pods.
=> Fix calling upgrade deployment

systemtests/src/main/java/io/enmasse/systemtest/GlobalLogCollector.java, systemtests/src/main/java/io/enmasse/systemtest/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/standard/QueueTest.java
Some of the useful stuff from #1916
=> Collect router state

address-model-lib/src/main/java/io/enmasse/address/model/KubeUtil.java, keycloak-controller/src/main/java/io/enmasse/keycloak/controller/KeycloakManager.java, user-api/src/main/java/io/enmasse/user/model/v1/UserMetadata.java, user-api/src/main/java/io/enmasse/user/model/v1/UserSpec.java, user-api/src/test/java/io/enmasse/user/model/v1/UserModelTest.java
=> Allow more characters in MessagingUser resource

systemtests/src/test/java/io/enmasse/systemtest/marathon/BrokeredMarathonTest.java, systemtests/src/test/java/io/enmasse/systemtest/marathon/MarathonTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/marathon/PlansMarathonTest.java, systemtests/src/test/java/io/enmasse/systemtest/marathon/StandardMarathonTest.java
https://github.com/EnMasseProject/enmasse/issues/1963
=> Fixes for marathon tests

api-server/src/main/java/io/enmasse/api/v1/http/HttpAddressServiceBase.java
=> Ensure address API produces expected 404 status response text NotFound

systemtests/src/main/java/io/enmasse/systemtest/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/marathon/BrokeredMarathonTest.java, systemtests/src/test/java/io/enmasse/systemtest/marathon/MarathonTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/marathon/StandardMarathonTest.java
=> Wait for all resources to be deleted

systemtests/src/main/java/io/enmasse/systemtest/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/bases/clients/ClusterClientTestBase.java
https://github.com/EnMasseProject/enmasse/issues/1984
=> Fix for mqtt internals tests

standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java
=> Use EnumSet.of(..) rather than Arrays.asList(..) when forming sets

agent/lib/router_stats.js, amqp-utils/src/main/java/io/enmasse/amqp/ProtonRequestClient.java, amqp-utils/src/test/java/io/enmasse/amqp/ProtonRequestClientTest.java, artemis/shutdown-hook/src/main/java/enmasse/broker/prestop/ArtemisBrokerFactory.java, standard-controller/src/main/java/io/enmasse/controller/standard/RouterStatusCollector.java
=> Set containerId for status check and filter in console

standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, standard-controller/src/main/java/io/enmasse/controller/standard/HTTPServer.java, standard-controller/src/main/java/io/enmasse/controller/standard/StandardController.java, templates/address-space-controller/020-ConfigMap-address-space-definitions.yaml
Takes the shutdown bits from #1997 and removes some unnecessary vertx use.
=> Add graceful shutdown of standard controller

address-model-lib/src/main/java/io/enmasse/k8s/model/v1beta1/PartialObjectMetadata.java, address-model-lib/src/main/java/io/enmasse/k8s/model/v1beta1/Table.java, address-model-lib/src/main/java/io/enmasse/k8s/model/v1beta1/TableColumnDefinition.java, address-model-lib/src/main/java/io/enmasse/k8s/model/v1beta1/TableRow.java, api-server/src/main/java/io/enmasse/api/server/ApiServer.java, api-server/src/main/java/io/enmasse/api/server/HTTPServer.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpAddressService.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpAddressServiceBase.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpAddressSpaceService.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpNestedAddressService.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpUserService.java, api-server/src/test/java/io/enmasse/api/server/HTTPServerTest.java, api-server/src/test/java/io/enmasse/api/v1/http/HttpAddressSpaceServiceTest.java, api-server/src/test/java/io/enmasse/api/v1/http/HttpNestedAddressServiceTest.java, api-server/src/test/java/io/enmasse/api/v1/http/HttpUserServiceTest.java, k8s-api/src/main/java/io/enmasse/k8s/util/TimeUtil.java, k8s-api/src/test/java/io/enmasse/k8s/util/TimeUtilTest.java, keycloak-user-api/pom.xml, keycloak-user-api/src/main/java/io/enmasse/user/keycloak/KeycloakUserApi.java
=> Add support for table output for address spaces

address-space-controller/src/main/java/io/enmasse/controller/ControllerChain.java, address-space-controller/src/test/java/io/enmasse/controller/ControllerChainTest.java, templates/grafana/010-ConfigMap-grafana-dashboards.yaml, templates/prometheus/010-ConfigMap-prometheus-config.yaml
Removed Prometheus anti-pattern of changing labels from address space metrics
Added address space metrics to Grafana dashboard
=> Fixed addres space metrics

systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebConsoleTest.java
Should fix issues with random error in web console connection tests.
=> Dynamic wait for connection items

agent/lib/metrics.js
=> Handle case where status is undefined

jenkins-functions.groovy
@lulf I have added catch phase for archiveArtifact, without catch phase build is marked as failed when archiveArtifact raised exception.
=> Do not fail build if archiveArtifact failed

Jenkinsfile-upgrade
@lulf I apologize, I added environment block to the wrong steps block instead of stage block :(
=> Set tag to right version when downgrading enmasse

api-server/src/main/java/io/enmasse/api/server/HTTPServer.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpAddressSpaceService.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpClusterAddressSpaceService.java, api-server/src/test/java/io/enmasse/api/v1/http/HttpClusterAddressSpaceServiceTest.java, k8s-api-testutil/src/main/java/io/enmasse/k8s/api/TestAddressSpaceApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/AddressSpaceApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapAddressSpaceApi.java
=> Add support for listing all address spaces if allowed

artemis/Dockerfile, templates/address-space-controller/020-ConfigMap-address-space-definitions.yaml, templates/address-space-controller/020-ConfigMap-standard-broker-definitions.yaml
=> Set the broker instance dir back to /run/artemis/split-1/serverData

templates/address-space-controller/020-ConfigMap-address-space-definitions.yaml, templates/address-space-controller/020-ConfigMap-standard-broker-definitions.yaml
Fixes after a bad review on my part of #2122
=> Add missing /var prefix to data dir

api-server/src/main/java/io/enmasse/api/v1/http/HttpUserService.java, api-server/src/test/java/io/enmasse/api/v1/http/TestUserApi.java, keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/AmqpServer.java, keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/AmqpServerProviderImpl.java, keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/K8sServiceAccountCredentialProvider.java, keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/PlainSaslServerMechanism.java, keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/SaslAuthenticator.java, keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/SaslServerMechanism.java, keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/ScramSaslServerMechanism.java, keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/XOAUTH2SaslServerMechanism.java, keycloak-plugin/sasl-plugin/src/test/java/io/enmasse/keycloak/spi/AmqpServerTest.java, keycloak-plugin/sasl-plugin/src/test/java/io/enmasse/keycloak/spi/PlainSaslServerMechanismTest.java, keycloak-plugin/sasl-plugin/src/test/java/io/enmasse/keycloak/spi/XOAUTH2SaslServerMechanismTest.java, keycloak-user-api/src/main/java/io/enmasse/user/keycloak/KeycloakUserApi.java, service-broker/src/main/java/io/enmasse/osb/api/bind/OSBBindingService.java
=> Allow PLAIN serviceaccount auth without username

systemtests/src/main/java/io/enmasse/systemtest/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/TestUtils.java, systemtests/src/main/java/io/enmasse/systemtest/User.java, systemtests/src/main/java/io/enmasse/systemtest/amqp/AmqpConnectOptions.java, systemtests/src/main/java/io/enmasse/systemtest/cmdclients/KubeCMDClient.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/common/api/UserApiTest.java
new tests for https://github.com/EnMasseProject/enmasse/pull/2145 and federated users
=> New tests for federated/serviceaccount messagingusers

agent/www/app.module.js, agent/www/components/addresses/addresses_ctrl.js, agent/www/components/connections/connections_ctrl.js, agent/www/index.html
Fixes #1786 On the address page, link the container id, to the connections page.  Adding filter for the container id.
=> In the console, create the links between Address and Connection

api-common/pom.xml, keycloak-controller/pom.xml, mqtt-lwt/pom.xml, standard-controller/pom.xml
=> Remove Hamcrest/Junit Jupiter/Junit Launcher JARs from production artifacts

api-model/pom.xml, api-model/src/main/java/io/enmasse/address/model/KubeUtil.java, api-model/src/test/java/io/enmasse/address/model/v1/address/KubeUtilTest.java, pom.xml
This includes:
* Using compiled patterns
* Added unit tests
* Private constructor for utility class
* Make constant actually constant
=> Fix up a few things in KubeUtil

documentation/modules/ref-view-message-conn-stats-table.adoc
Inaccurate number of Senders are displayed
=> Docs: issue 2199: add note about Console connections page 

.travis/build.sh, .travis/common.sh, Makefile.common, systemtests/scripts/test_func.sh, systemtests/scripts/wait_until_up.sh
* Push extra tags explicitly in travis script
=> Fix Jenkins PR build

Makefile, Makefile.common
Some other locations of the makefile already did that. Here are a few missing spots.
=> Make should always be called with $(MAKE)

systemtests/src/main/java/io/enmasse/systemtest/GlobalLogCollector.java
* Print out full path were files are being created
* Drop back and forth conversion with File and directly use Path
* pull all "create log file with parent" logic into a single method
=> Fix up a few things in the global log collector

systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java
=> Fix replace wait

address-space-controller/src/main/java/io/enmasse/controller/EndpointController.java, api-model/src/main/java/io/enmasse/address/model/AddressSpaceStatus.java
This exports the CA cert of the address space in the status section.
I based this PR on PR #2202, as it already builds on top of the refactored model API.
=> Export CA cert in AddressSpaceStatus

agent/lib/artemis.js, agent/lib/kubernetes.js, agent/test/ragent.js
=> fix shutting down of broker controller tests

systemtests/src/main/java/io/enmasse/systemtest/GlobalLogCollector.java, systemtests/src/main/java/io/enmasse/systemtest/cmdclients/KubeCMDClient.java
use KubeCMDClient for collecting events in order to be compatible with oc and kubectl
=> use KubeCMDClient for collecting events

address-space-controller/src/main/java/io/enmasse/controller/TemplateInfraResourceFactory.java, standard-controller/src/main/java/io/enmasse/controller/standard/TemplateBrokerSetGenerator.java, standard-controller/src/test/java/io/enmasse/controller/standard/StandardControllerSchema.java, standard-controller/src/test/java/io/enmasse/controller/standard/TemplateBrokerSetGeneratorTest.java
=> Issue 2328 standard pvc set

documentation/design/proposals/auth-service-controller.adoc, documentation/design/proposals/auth-service-resource.adoc
Design docs for installing standard auth service, see #2289
=> Add auth service controller design doc

agent/lib/internal_address_source.js
=> Fix reference to address space plan in agent

api-model/src/main/java/io/enmasse/admin/model/v1/AbstractHasMetadataWithAdditionalProperties.java, api-model/src/main/java/io/enmasse/admin/model/v1/BrokeredInfraConfig.java, api-model/src/main/java/io/enmasse/admin/model/v1/StandardInfraConfig.java
This makes it possible to reuse this base class in new types.
=> Generalize type with additional properties

agent/lib/auth_utils.js, agent/npm-shrinkwrap.json, agent/package.json, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/OpenshiftLoginWebPage.java
Bump keycloak-connect nodejs library
=> Update keycloak login page field names in system tests

standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, standard-controller/src/test/java/io/enmasse/controller/standard/AddressControllerTest.java, standard-controller/src/test/java/io/enmasse/controller/standard/AddressProvisionerTest.java
=> Ensure that address is replaced if plan has changed

api-model/src/main/java/io/enmasse/address/model/AddressPlanDescription.java, api-model/src/main/java/io/enmasse/address/model/AddressSpacePlanDescription.java, api-model/src/main/java/io/enmasse/address/model/AddressSpaceSchema.java, api-model/src/main/java/io/enmasse/address/model/AddressSpaceSchemaList.java, api-model/src/main/java/io/enmasse/address/model/AddressSpaceSchemaSpec.java, api-model/src/main/java/io/enmasse/address/model/AddressTypeInformation.java, api-model/src/test/java/io/enmasse/address/model/v1/address/SerializationTest.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpSchemaService.java, systemtests/src/main/java/io/enmasse/systemtest/utils/AddressSpaceUtils.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/common/api/ApiServerTest.java
* Add resource limits and resource usage by plans to output
* Add available authentication services to output
* Remove undocumented schema endpoint
* Rewrite systemtest to check official schema endpoint
Fixes #2461
=> Add serialization test of address space schema

systemtests/src/main/java/io/enmasse/systemtest/GlobalLogCollector.java, systemtests/src/main/java/io/enmasse/systemtest/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/cmdclients/KubeCMDClient.java, systemtests/src/test/java/io/enmasse/systemtest/standard/infra/InfraTest.java
@lulf I see stat standard job fail on timeout because collecting router state stuck without error message. So I will try to investigate that
=> Debug collecting router state

standard-controller/src/main/java/io/enmasse/controller/standard/RouterStatus.java, standard-controller/src/main/java/io/enmasse/controller/standard/RouterStatusCollector.java
=> Make less assumptions in router check code

pkg/controller/iotproject/managed.go
=> change command to control in user permissions

address-space-controller/src/main/java/io/enmasse/controller/ControllerChain.java, address-space-controller/src/test/java/io/enmasse/controller/ControllerChainTest.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpMetricsService.java, standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, templates/grafana/010-ConfigMap-grafana-dashboards.yaml, templates/prometheus-rules/010-PrometheusRules-prometheus.yaml
* Changed misleading metric names
* Added Prometheus rules for aggregated metrics
* Improved alerts for critical components
* Refactored Grafana dashboard to reflect changes
=> Refactored metrics and alerts

.jenkins/Jenkinsfile
https://github.com/rh-messaging/amq-ci/commit/12a87ebc7e85a765904876085f43a8e3831bbfbd
=> Allow pass upgrade_from via master pipeline

pkg/controller/authenticationservice/standard.go
Neither data source or persistence of standard authservice will be
changed even if custom resource is changed, in case applied by mistake. Changing these settings are not supported and should be prevented by a validation admission webhook in the future.
=> Dont change persistence settings of standard authservice

keycloak-plugin/src/main/configuration/standalone-postgresql.xml, pkg/controller/authenticationservice/standard.go
With these changes I'm able to use the postgresql datasource @kornys
=> Postgresql fix

pkg/controller/iotproject/iotproject_controller.go, pkg/controller/iotproject/managed.go
Currently the logic sets a new password on every iteration until IoT project becomes ready
=> Improve IoT adapter password changing logic

router/Dockerfile
(based on https://github.com/EnMasseProject/router-docker-base/pull/56)
=> Patched router 

address-space-controller/src/main/java/io/enmasse/controller/CreateController.java, address-space-controller/src/main/java/io/enmasse/controller/StatusController.java, agent/npm-shrinkwrap.json, api-model/src/main/java/io/enmasse/address/model/AddressSpaceSpec.java, api-model/src/main/java/io/enmasse/address/model/AddressSpaceStatus.java, api-model/src/main/java/io/enmasse/address/model/AddressSpec.java, api-model/src/main/java/io/enmasse/address/model/AuthenticationService.java, api-model/src/main/java/io/enmasse/address/model/CertSpec.java, api-model/src/main/java/io/enmasse/address/model/EndpointStatus.java, api-model/src/main/java/io/enmasse/address/model/ExposeSpec.java, api-model/src/main/java/io/enmasse/admin/model/v1/NetworkPolicy.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpAddressSpaceService.java
* Allows downgrade to previous version
* Allow unknown fields to all model objects in order to allow future
extensions without breaking forward compatiblity.
=> Make phase forward compatible

console/console-init/pom.xml, console/console-init/ui/package.json, pom.xml
=> Use npm instead of yarn

documentation/modules/ref-brokered-infra-config-fields.adoc, documentation/modules/ref-standard-infra-config-fields.adoc
@lulf, please review the new field descriptions for technical accuracy.
=> Docs: edits to infra config field tables

.travis.yml
=> Disable IoT tests in travis CI

systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/plans/PlansTest.java
fixes plans tests and webconsoletests
=> Fixes for console tests

console/console-init/ui/src/components/MessagingInstances/MessagingInstance/InstanceLoader.js
=> Fix loading of instances on kubernetes.

console/console-init/ui/src/context/notification-manager.js
=> Hide the notifications after 8s

Makefile, Makefile.java.mk, agent/lib/console_server.js, agent/npm-shrinkwrap.json, agent/www/index.css, agent/www/index.html
=> Reskin the agent/console masthead to match PF4

console/console-init/ui/src/components/About/About.js, console/console-init/ui/src/components/Layout/Layout.js
=> Update the about box

systemtests/src/test/java/io/enmasse/systemtest/iot/registry/DeviceRegistryTest.java
fixes the fail we are currently having in jenkins iot job
=> fix DeviceRegistryTest#testDeviceCredentials

address-space-controller/src/main/java/io/enmasse/controller/EndpointController.java, documentation/modules/proc-iot-api.adoc, documentation/modules/ref-retrieving-address-space-information.adoc
Update recommendation to use status.caCert
=> Set endpoint cert on Kubernetes

console/console-init/ui/src/components/MessagingInstances/MessagingInstance.js, console/console-init/ui/src/components/MessagingInstances/MessagingInstance/Enmasse/EnmasseAddressSpaces.js, console/console-init/ui/src/components/MessagingInstances/MessagingInstances.js, systemtests/src/test/java/io/enmasse/systemtest/bases/web/GlobalConsoleTest.java
This is missing the use of colors for the different phases.
=> Use phase instead of isReady

console/console-init/ui/src/components/MessagingInstances/MessagingInstance/Enmasse/CreateAddressSpace/Steps/Configuration/AuthenticationServiceInput.js, console/console-init/ui/src/components/MessagingInstances/MessagingInstance/Enmasse/CreateAddressSpace/Steps/Configuration/ConfigurationForm.js, console/console-init/ui/src/components/MessagingInstances/MessagingInstance/Enmasse/EnmasseAddressSpaces.js, console/console-init/ui/src/components/MessagingInstances/MessagingInstance/InstanceLoader.js
=> Fix select box handling for authentication service

agent/www/index.css, agent/www/index.html, pom.properties, pom.xml
Commit missing pom properties for the back link to the main console
=> Add the user name to the masthead.

console/console-init/oauth-proxy/bin/init.sh
Defect effects the case where the user does not wish to use SSO.
=> Ensure that console will generate a secret, if one is not provided

pom.xml
=> json-patch: Exclude superfluous runtime dependency (jsr305).

systemtests/README.md
Running the tests as system:admin may break the tests, i lost a fair bit of time with this :)
=> recommend standard openshift user for the tests

api-common/src/main/java/io/enmasse/api/auth/AllowAllAuthInterceptor.java, api-common/src/main/java/io/enmasse/api/auth/ApiHeaderConfig.java, api-common/src/main/java/io/enmasse/api/auth/AuthApi.java, api-common/src/main/java/io/enmasse/api/auth/AuthInterceptor.java, api-common/src/main/java/io/enmasse/api/auth/KubeAuthApi.java, api-common/src/main/java/io/enmasse/api/auth/RbacSecurityContext.java, api-common/src/main/java/io/enmasse/api/auth/TokenReview.java, api-common/src/test/java/io/enmasse/api/auth/AuthInterceptorTest.java, api-server/src/main/java/io/enmasse/api/server/ApiServer.java, api-server/src/main/java/io/enmasse/api/server/HTTPServer.java, api-server/src/test/java/io/enmasse/api/server/HTTPServerTest.java, service-broker/src/main/java/io/enmasse/osb/HTTPServer.java, service-broker/src/test/java/io/enmasse/osb/HTTPServerTest.java
Read X-Remote-Group and X-Remote-Extra- headers and propagate to subject access review
Fixes #2688
=> Propagate all headers expected by the kubernetes api

keycloak-plugin/Dockerfile
=> Use same user as Keycloak in init image

systemtests/src/main/java/io/enmasse/systemtest/utils/IoTUtils.java, systemtests/src/test/java/io/enmasse/systemtest/bases/IoTTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/iot/mqtt/MqttAdapterTest.java
this tryies to solve instability in MqttAdapterTest
=> connect to mqtt adapter retrying

console/console-init/ui/src/components/MessagingInstances/MessagingInstance/Enmasse/CreateAddressSpace/CreateAddressSpace.js, console/console-init/ui/src/components/MessagingInstances/MessagingInstance/Enmasse/CreateAddressSpace/Steps/Configuration/ConfigurationForm.js, console/console-init/ui/src/components/MessagingInstances/MessagingInstance/Enmasse/CreateAddressSpace/Steps/Configuration/NamespaceInput.js, console/console-init/ui/src/components/MessagingInstances/MessagingInstance/Enmasse/EnmasseAddressSpaces.js, console/console-init/ui/src/components/MessagingInstances/MessagingInstance/Enmasse/EnmasseAddressSpaces.test.js
- load the plans & auth services after the namespace input (text or select), is populated.
=> Fixed loading of Authentication Services and plans

systemtests/src/main/java/io/enmasse/systemtest/AdminResourcesManager.java
I don't yet understand this test failure (AuthServiceTest#testStandardAuthServiceWithDB).  The enmasse-operator pod log is missing for the time when the test failed so I can't confirm that the operator actioned the auth service.  This extra logging should help if we see the issue again.
=> AuthServiceTest - extra test-only logging to help diagnose test failure

agent/npm-shrinkwrap.json, agent/package.json, agent/pom.xml, console/console-init/ui/package-lock.json
=> Fix npm shrinkwraps

systemtests/src/main/java/io/enmasse/systemtest/apiclients/MsgCliApiClient.java
this merges #2757 with already merged changes from #2765 and changes the timeout for a more reasonable one as suggested here https://github.com/EnMasseProject/enmasse/pull/2765#issuecomment-488811506
if we merge this PR #2757 should be closed
=> workaround for vertx problem Connection was closed

console/console-init/oauth-proxy/bin/init.sh, console/console-init/pom.xml, console/console-init/ui/src/containers/Console/Console.js, console/console-init/ui/webpack.common.js, pkg/controller/consoleservice/consoleservice_controller.go
Getting the refresh rate from container environment variable.
TODO: set the variable on the consoleservice CR.  Currently the controller is setting it as a container environment variable
=> Allow the refresh rate to be set in the container

console/console-init/ui/src/components/MessagingInstances/MessagingInstance/Enmasse/CreateAddressSpace/Steps/Configuration/PlansInput.js, console/console-init/ui/src/components/MessagingInstances/MessagingInstance/Enmasse/CreateAddressSpace/Steps/Review.js
=> Fix label (Address space plan)

console/console-init/ui/src/components/MessagingInstances/MessagingInstance/Enmasse/CreateAddressSpace/CreateAddressSpace.js
=> Fixed 'finish' button label, that changed due to PF4 upgrade

systemtests/src/main/java/io/enmasse/systemtest/GlobalLogCollector.java
In iot tests, when adapter tests failed we collect some info from qpid router in adapter's pods, there was a bug because the arguments to connect to the router lead to an ssl error. This is fixed now
=> fix collect logs of qdr-proxy

iot/examples/README.md, templates/iot/examples/infinispan-service.yml, templates/iot/examples/iot-config-infinispan.yaml
While we'll still working on the device registry and writing the docs , here is a quick guide to use the infinispan DR easily.
Inspiration is from https://github.com/infinispan-demos/infinispan-kubernetes
=> suggest infinispan DR in IoT Readme

iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/InfinispanRegistryConfig.java
Signed-off-by: Jean-Baptiste Trystram <jbtrystram@redhat.com>
=> prevent HTTP and AMQP tenant endpoints in Infinispan DR

api-common/src/main/java/io/enmasse/api/auth/AuthInterceptor.java, api-common/src/test/java/io/enmasse/api/auth/AuthInterceptorTest.java
The api-server does not properly parse the X-Remote-Group header when it contains multiple comma-separated values. This prevents the api-server to work OOTB with OLM on certain
installations such as minikube, possibly also OCP4.
=> Correct parsing of group header

agent/lib/artemis.js
Corrects a defect introduced by #2366.   The management response queue creation was inadvertently tied to the `sendable` Rhea event rather than the `sender_open` event.   The upshot of this meant that the management response queue would be recreated every time the management sender became sendable again.  If this event coincided with outstanding management responses, the response to the new queue's creation got processed as it were a response to another management request.  This is what lead to:
`2019-05-16T04:03:36.846Z agent ERROR [broker.ywnlnc9zxy-9d8d7fdbc-7ctxs] failed to retrieve addresses: SyntaxError: Unexpected token Q in JSON at position 0
`
This would lead to addresses 'sticking' in an unready state.  This defect affected by brokered and standard address space.
=> Fix #2823: Prevent unintended recreation of the management response queue by agent

documentation/common/attributes.adoc, documentation/modules/proc-installing-using-olm.adoc
https://github.com/EnMasseProject/enmasse/issues/2821
=> [2821] Fixed docs YAML using incorrect source name for operator install

pkg/controller/authenticationservice/upgrader/standard.go
Fixes bug introduced as part of #2857 that prevents the correct extraction of the existing database-name from the Postgres secret.
=> Fix retrieval of existing database-name from postgresql secret

api-model/src/main/java/io/enmasse/address/model/KubeUtil.java, standard-controller/src/test/java/io/enmasse/controller/standard/TemplateBrokerSetGeneratorTest.java
(Immediate use-case for this is ability to turn vars such as PN_TRACE_FRM, for diagnostic purposes).
=> Allow broker/router container environment to be overridden from the infra podspec

systemtests/src/main/java/io/enmasse/systemtest/cmdclients/KubeCMDClient.java, systemtests/src/test/java/io/enmasse/systemtest/common/CommonTest.java
Attempt to prevent random failures, by giving qstat more time to complete.
=> Increase timeout for qdstat in test

templates/grafana-dashboards/010-GrafanaDashboard-brokers.yaml, templates/prometheus-rules/010-PrometheusRules-enmasse.yaml, templates/prometheus-rules/010-PrometheusRules-kube-metrics.yaml, templates/service-monitors/010-ServiceMonitor-enmasse.yaml
* Changed broker count in Grafana dashboard to current value
* Namespaced kube-metrics based alerts
* Changed namepsace selector in service monitor to use labels
=> Fixed bugs in monitoring resources

.jenkins/Jenkinsfile-upgrade
Continue with for loop for next version in case when for previous it failed.
=> Do all rounds of upgrade tests

api-model/src/main/java/io/enmasse/admin/model/v1/BrokeredInfraConfig.java, api-model/src/main/java/io/enmasse/admin/model/v1/StandardInfraConfig.java, api-model/src/test/java/io/enmasse/admin/model/v1/BrokeredInfraConfigTest.java, api-model/src/test/java/io/enmasse/admin/model/v1/StandardInfraConfigTest.java, api-model/src/test/resources/io/enmasse/admin/model/v1/resources/brokered-infra-empty.json, api-model/src/test/resources/io/enmasse/admin/model/v1/resources/standard-infra-empty.json
I think we should also backport this.
=> Fix a possible NPE, having an empty spec section

agent/www/app.module.js, agent/www/index.css
Updated vertical nav to have PF4 styling for console.
=> PF4 Vertical nav updates for console

.jenkins/Jenkinsfile-tests, .jenkins/jenkins-functions.groovy, systemtests/ansible/inventory/systemtests.ocp4.inventory, systemtests/scripts/test_func.sh, systemtests/src/test/java/io/enmasse/systemtest/common/Credentials.java
this PR adds some modifications to jenkins pipeline and script to be able to run systemtests in openshift 4
=> jenkins job using openshift 4

agent/bin/subserv.js
I noticed that `subserv` fails to respond to SIGTERM so its pod hangs around for 30s afters Kubernetes/OpenShift shuts it down (presumably a timeout before killing it).  This change ensures that the Node process handles SIGTERM and closes down the process.  This should also have a positive affect on the length of the test run.
=> Ensure subserv exits in timely fashion

systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java
New version of Vertx introduces a new exception `MechanismMismatchException`.  Handle that too.
=> Fix failing AuthenticationTest caused by vertx upgrade

systemtests/src/main/java/io/enmasse/systemtest/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/ability/TestWatcher.java, systemtests/src/main/java/io/enmasse/systemtest/cmdclients/KubeCMDClient.java
In order to help understand failings tests in CI environment.
=> Gather node state on test fail too.

systemtests/src/test/java/io/enmasse/systemtest/common/plans/PlansTest.java
Extra diagnostics to understand a sporadic failure.
=> Add extra diagnostics to PlansTest#testMessagePersistenceAfterAutoScale

systemtests/src/main/java/io/enmasse/systemtest/utils/IoTUtils.java, systemtests/src/test/java/io/enmasse/systemtest/iot/IoTProjectManagedTest.java
Changes the AddressSpacePlan used in the iotprojects created by the tests
=> systemtests iot decrease resource usage

documentation/common/snip-prerequisites-openshift.adoc
@k-wall Would you mind reviewing this?
=> Docs issue 2985: add link about how to install CLI

documentation/assemblies/assembly-installing.adoc, documentation/assemblies/assembly-service-admin-guide.adoc, documentation/assemblies/assembly-uninstalling.adoc, documentation/modules/proc-installing-using-ansible.adoc, documentation/modules/proc-installing-using-bundle.adoc, documentation/modules/proc-uninstalling-using-ansible.adoc, documentation/modules/proc-uninstalling.adoc
and related install and uninstall doc fixes
=> Docs: issue-3002: Uninstall using Ansible 

systemtests/src/test/java/io/enmasse/systemtest/bases/web/GlobalConsoleTest.java
While investigating openshift 4 test failures I needed to fix this test
=> fix failing testSwitchAddressSpacePlan

systemtests/src/main/java/io/enmasse/systemtest/utils/AddressSpaceUtils.java
java.lang.NullPointerException: null
at io.enmasse.systemtest.utils.AddressSpaceUtils.waitForAddressSpaceReady(AddressSpaceUtils.java:71)
=> Prevent npe in test

documentation/assemblies/assembly-uninstalling.adoc, documentation/modules/proc-uninstalling.adoc
Also clarifies the title for the Uninstalling using YAML bundle procedure
=> Docs: issue-3037: remove uninstalling using Ansible procedure from Kubernetes guide

systemtests/scripts/test_func.sh, systemtests/src/main/java/io/enmasse/systemtest/GlobalLogCollector.java, systemtests/src/test/java/io/enmasse/systemtest/common/monitoring/MonitoringTest.java
Also made `all_events log` capture a UTC timestamp too.
=> Collect events from monitoring namespace if MonitoringTest fails

systemtests/src/test/java/io/enmasse/systemtest/bases/common/PersistentMessagesTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/common/BrokeredPersistentMessagesTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/CommonTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/StandardPersistentMessagesTest.java
splits CommonTest.testMessagePersistent into multiple tests, one per address tested
=> split CommonTest.testMessagePersistent into multiple tests

agent/www/app.module.js
=> Fix selection of vertical nav item in dashboard

systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java
Augment the existing firefox profile provided by the server rather than replacing it completely.
=> Augment the server side provided firefox profile with devtools.console.stdout.content=true

pkg/controller/iotproject/iotproject_controller.go, pkg/controller/iotproject/managed.go
Also, clean up a few things, reduce log output.
=> Handle error when creating addresses fails

systemtests/scripts/run_tests.sh, systemtests/src/main/java/io/enmasse/systemtest/cmdclients/KubeCMDClient.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/common/CommonTest.java
=> Await API service registration before ending CommonTest#testMessagingDuringRestartComponents

api-model/src/main/java/io/enmasse/iot/model/v1/IoTProjectStatus.java, pkg/apis/iot/v1alpha1/funcs.go, pkg/apis/iot/v1alpha1/types.go, pkg/controller/iotproject/iotproject_controller.go, pkg/util/tenant.go, templates/iot/api/010-CustomResourceDefinition-iot-project.yaml
Put the IoT tenant name in an explicit field in the status section.
=> Put the IoT tenant name in the status section

agent/bin/agent.js, agent/lib/internal_address_source.js, agent/lib/ragent.js, agent/test/internal_address_source.js, agent/test/ragent.js
=> Ensure that addresses are not synced until addresses have been defined

address-space-controller/src/main/java/io/enmasse/controller/TemplateInfraResourceFactory.java, api-model/src/main/java/io/enmasse/address/model/AuthenticationServiceOverrides.java, api-model/src/main/java/io/enmasse/admin/model/v1/AuthenticationServiceSpecExternal.java, systemtests/src/main/java/io/enmasse/systemtest/AdminResourcesManager.java, systemtests/src/main/java/io/enmasse/systemtest/utils/AuthServiceUtils.java, systemtests/src/test/java/io/enmasse/systemtest/common/api/AuthServiceTest.java
* added override function of caCertSecret and clientCertSecret in
external auth services when creating address spaces
* added systemtest for external auth service
=> Allow override of certs for external auth

systemtests/src/test/java/io/enmasse/systemtest/common/CommonTest.java
=> systemtest restart admin component with messages enqueued

Makefile, Makefile.env.mk, documentation/Makefile, documentation/contributing/make-tooling.adoc, documentation/contributing/master.adoc
* Add build, check, clean and publish targets
Fixes #3082
=> Add makefile to documentation module

documentation/design/proposals/bridging_external.adoc
Link for readability: https://github.com/EnMasseProject/enmasse/blob/16857d258e4776205c1705bfd9b6e1660286d72f/documentation/design/proposals/bridging_external.adoc
=> Proposal on bridging to external endpoints

address-space-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java, standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, standard-controller/src/main/java/io/enmasse/controller/standard/BrokerCluster.java, standard-controller/src/main/java/io/enmasse/controller/standard/Kubernetes.java, standard-controller/src/main/java/io/enmasse/controller/standard/KubernetesHelper.java, standard-controller/src/test/java/io/enmasse/controller/standard/BrokerClusterTest.java
=> Replace statefulset if volumeclaimtemplate has changed

documentation/design/proposals/iot-tenant-data-cleaner.adoc
link to the document for readability :  https://github.com/EnMasseProject/enmasse/blob/785616ff0bb5ba0573a218ab25c7d318b2522594/documentation/design/proposals/iot-tenant-data-cleaner.adoc
=> Design proposal for iot tenant cleanup 

address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceController.java, address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceControllerOptions.java, address-space-controller/src/main/java/io/enmasse/controller/RouterStatusController.java, amqp-utils/src/main/java/io/enmasse/amqp/RouterEntity.java, amqp-utils/src/main/java/io/enmasse/amqp/RouterManagement.java, standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, standard-controller/src/main/java/io/enmasse/controller/standard/RouterStatusCollector.java
(@k-wall currently based on #3166 but will rebase this once that is merged)
* Refactor and move router status collection into amqp-utils
* Add controller in address-space-controller for checking the router status by querying all routers for an address space looking for the connector and verifying its state.
=> Add router status check for connectors

CONTRIBUTING.md, DEVELOPMENT.md
This is an attempt to capture a set of development guidelines that should be followed when developing EnMasse. The idea is that PRs should be reviewed against these guidelines and ensure that we end up with a code base consistent with these guidelines.
This first edition is just an extraction of the current state from what is there in the project and also coloured by my subjective opinion. I'd like to get an agreement on the basics, and any additions or suggestions to changes are welcome.
Some sections are a bit short, so I'd love suggestions on what we could put in them.
=> Add first edition of development guidelines

documentation/design/proposals/bridging_external.adoc
Please review and share your opinion in any missing testcase
=> add list of bridging test cases

.jenkins/Jenkinsfile-pr, address-space-controller/src/main/java/io/enmasse/controller/router/config/RouterConfig.java
=> Handle upgrade from a version without router in json

standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java
This defect didn't produce a functional defect.
=> Avoid upgrade processing deleted broker clusters

documentation/modules/proc-restart-component.adoc, documentation/modules/proc-upgrading-router-pods.adoc, templates/Makefile, templates/scripts/restart-authservices.sh, templates/scripts/restart-brokers.sh, templates/scripts/restart-operators.sh, templates/scripts/restart-routers.sh
Initial version of utility scripts for restarting. I made each script self-contained, i.e. no need to rely on other scripts, only `kubectl`. I did consider merging them into a single script, but I think thats an appropriate task for an 'enmassectl' tool instead, at which point these scripts should be removed again.
=> Restart scripts

agent/lib/subctrl.js
- Bugfix
This PR fixes the SessionTest#previousPersistentSessionDiscarded test which failed due to connector format being changed.
=> Fix mqtt sessions test

api-server/src/main/resources/swagger.json
- Bugfix
Cleans up the swagger API definition and run through a JSON formatter.
=> Fix syntax errors in swagger

documentation/master-kubernetes.adoc, documentation/master-openshift.adoc, documentation/modules/proc-installing-using-olm.adoc
Update the instructions for installing using OLM now that enmasse can be installed in its own namespace.
=> Update operator install docs

systemtests/src/main/java/io/enmasse/systemtest/time/TimeoutBudget.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java
This PR doesn't require to run systemtests
=> implement time spent in TimeoutBudget

documentation/modules/con-console.adoc, documentation/modules/ref-address-space-example-external-auth-service-override.adoc, documentation/modules/ref-example-roles.adoc
Need to change these book links since the titles have changed for new release
=> Docs: change links to reflect book titles change

systemtests/src/test/java/io/enmasse/systemtest/isolated/api/ApiServerTest.java
=> fix ApiServerTest.testCreateAddressSpaceRoleTenantEdit in openshift 4

pom.xml
- Bugfix
This manages the version of the JSR310 jackson time module, which is being used by Hono, but currently not version aligned in the POM.
=> Manage dependency version for jackson jsr310 (time) module

HACKING.md, systemtests/README.md
New info about upgrade and test prfiles
=> Add new info about systemtests into readme

pkg/util/password.go
- Bugfix
Use less special characters when creating passwords, trying to fix issues with passwords in env-vars.
=> Remove some of the special characters

templates/iot/examples/iot-config-dev.yaml, templates/iot/examples/iot-config-k8s.yaml, templates/iot/examples/iot-config.yaml
=> Adapt IoT example config to the change Infnispan service name

documentation/modules/con-standard-queue.adoc, documentation/modules/ref-view-message-conn-stats-table.adoc
=> Docs: stored DLQ content

templates/iot/examples/infinispan/common/010-Config.yaml, templates/iot/examples/infinispan/manual/050-StatefulSet.yaml
Add a volumeClaimTemplate in infinispan deployment so when scaled each new replicas will have a volume attached to persist the data.
=> Add file persistence for infinispan

documentation/modules/con-standard-queue.adoc, documentation/modules/ref-view-message-conn-stats-table.adoc
Documentation
Fix wording in DLQ docs
=> Docs: fix wording per QE review

documentation/modules/proc-installing-using-bundle.adoc
Re-add service catalog install step
=> Add step to install service catalog integration

.jenkins/Jenkinsfile-pr, pom.xml, systemtests/src/main/java/io/enmasse/systemtest/Environment.java, systemtests/src/main/java/io/enmasse/systemtest/cmdclients/CmdClient.java, systemtests/src/main/java/io/enmasse/systemtest/cmdclients/KubeCMDClient.java, systemtests/src/main/java/io/enmasse/systemtest/info/TestInfo.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitExecutionListener.java, systemtests/src/main/java/io/enmasse/systemtest/manager/IsolatedIoTManager.java, systemtests/src/main/java/io/enmasse/systemtest/manager/ResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/manager/SharedIoTManager.java, systemtests/src/main/java/io/enmasse/systemtest/manager/SharedResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/ExternalClientsExtension.java, systemtests/src/main/java/io/enmasse/systemtest/operator/OperatorManager.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener
Systemtests operator manager should take care about deploying enmasse and iot operators on demand.
=> Systemtests operator manager

CHANGELOG.md, Makefile.env.mk, pom.xml
Update to ActiveMQ Artemis 2.10.1
=> Update broker 2.10.1

amqp-utils/src/main/java/io/enmasse/amqp/RouterManagement.java, standard-controller/src/main/java/io/enmasse/controller/standard/RouterStatusCache.java
Parallelise router queries. Will rebase on master once #3300 is merged.
=> Parallel router query

amqp-utils/pom.xml, amqp-utils/src/main/java/io/enmasse/amqp/Artemis.java, broker-plugin/Makefile, broker-plugin/broker-cli/pom.xml, broker-plugin/broker-cli/src/main/java/io/enmasse/broker/cli/Cli.java, broker-plugin/broker-cli/src/main/java/io/enmasse/broker/cli/ClientFactory.java, broker-plugin/broker-cli/src/main/resources/logback.xml, broker-plugin/plugin/pom.xml, broker-plugin/plugin/src/assembly/unix-dist.xml, broker-plugin/plugin/src/main/sh/init-broker.sh, broker-plugin/pom.xml, pom.xml
Added broker tool to allow running commands on Artemis
=> Created broker tool

systemtests/src/main/java/io/enmasse/systemtest/Environment.java, systemtests/src/main/java/io/enmasse/systemtest/TestTag.java, systemtests/src/main/java/io/enmasse/systemtest/bases/ITestBase.java, systemtests/src/main/java/io/enmasse/systemtest/bases/iot/ITestIoTBase.java, systemtests/src/main/java/io/enmasse/systemtest/bases/iot/ITestIoTIsolated.java, systemtests/src/main/java/io/enmasse/systemtest/bases/iot/ITestIoTShared.java, systemtests/src/main/java/io/enmasse/systemtest/bases/shared/ITestSharedBrokered.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java, systemtests/src/main/java/io/enmasse/systemtest/manager/IsolatedIoTManager.java, systemtests/src/main/java/io/enmasse/systemtest/manager/IsolatedResourcesManager.java, systemtests/src/main/java/io/enmasse/systemtest/manager/ResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/manager/SharedIoTManager.java, systemtests/src/main/java/io/enmasse/systemtest/manager/SharedResourceManager.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/bases/marathon/MarathonTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/GlobalConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/catalog/ServiceCatalogWebTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/infra/brokered/InfraTestBrokered.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/infra/standard/InfraTestStandard.java, systemtests/src/test/java/io/enmasse/systemtest/olm/OperatorLifecycleManagerTest.java
This PR does some modifications over the recent refactoring that included the usage of Resource Managers, and this PR tries to simplify the API of the resource managers and use best practices
- Refactoring
=> systemtests refactor cleanups

api-common/src/main/java/io/enmasse/api/common/DefaultExceptionMapper.java, api-common/src/test/java/io/enmasse/api/common/DefaultExceptionMapperTest.java
- Bugfix
Avoid a NPE when handling a SocketTimeoutException condition when interacting with the Kubernetes API server.
=> Fix #3316: Improve the handling of java.net.SocketTimeoutException

documentation/assemblies/assembly-ops-procedures.adoc, documentation/modules/proc-get-logs-broker.adoc, documentation/modules/proc-get-logs-router.adoc, documentation/modules/proc-restart-component.adoc
Documentation
Need to add some intro text for these procedures
=> Docs: copyedits for Operations procedures

agent/lib/artemis.js, agent/lib/console_server.js, agent/lib/pod_watcher.js, agent/lib/podgroup.js, agent/lib/queue.js, agent/lib/utils.js, agent/www/components/addresses/addresses.html, agent/www/components/addresses/addresses_ctrl.js, agent/www/shared/address_service.js
-Removed the inactive suspend menu item.
- Hooked up the purge menu item.
- Bugfix
- Refactoring
=> Implemented purge functionality

iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/autowire/AutowiredTenantManagementAdapter.java, iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/config/MetricsConfiguration.java, iot/iot-tenant-service/src/main/java/io/enmasse/iot/tenant/config/MetricsConfiguration.java, iot/pom.xml, pkg/controller/iotconfig/utils.go
- Bugfix
Update to Hono 1.0.0. Drop workaround for eclipse/hono#1471.
=> Update to Hono 1.0.0

broker-plugin/plugin/src/main/sh/probe.sh, pkg/controller/consoleservice/consoleservice_controller.go
- Bugfix
Use local ip to prevent DNS lookup
=> Use local ip to prevent DNS lookup

documentation/assemblies/assembly-configuring-olm.adoc, documentation/assemblies/assembly-installing-configuring-olm.adoc, documentation/assemblies/assembly-installing.adoc, documentation/master-openshift.adoc, documentation/modules/proc-create-address-plan-custom-resource-olm-ui.adoc, documentation/modules/proc-create-address-space-plan-custom-resource-olm-ui.adoc, documentation/modules/proc-create-auth-service-custom-resource-olm-ui.adoc, documentation/modules/proc-create-infraconfig-custom-resource-olm-ui.adoc, documentation/modules/proc-installing-using-custom-operator-source.adoc, documentation/modules/proc-olm-installing-from-operatorhub-using-console.adoc
Documentation
Adding documentation for how to install EnMasse using OLM 
=> Docs: adding doc for installing EnMasse using OLM method

api-server/src/main/java/io/enmasse/api/server/HTTPServer.java, api-server/src/main/java/io/enmasse/api/server/RequestLogger.java
=> Log per-request latency and status

systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java
- Bugfix
I have seen tests fail in the teardown section but the logs not reporting nothing at all, then digging into [junit docs](https://junit.org/junit5/docs/5.5.0-RC2/user-guide/index.html#extensions-execution-order-overview) I found the handleXXXXMethodExecutionException are fired with their corresponding annotation based methods like `@aftereach` ... so then our callbacks firing an exception are not caught by our exeception handlers.
This PR fix this in a simple way :)
=> Save kubernetes state when error is produced in junit callback

systemtests/src/main/java/io/enmasse/systemtest/clients/ClientUtils.java, systemtests/src/main/java/io/enmasse/systemtest/utils/AddressSpaceUtils.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/bases/clients/ClientTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/bases/marathon/MarathonTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/PersistentMessagesTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/plans/brokered/PlansTestBrokered.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/plans/standard/PlansTestStandard.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/QueueTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/TopicTest.java
- Refactoring
This PR includes some cleanups in related to ClientUtils
=> ClientUtils cleanups

systemtests/src/main/java/io/enmasse/systemtest/bases/ThrowableRunner.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java, systemtests/src/test/java/io/enmasse/systemtest/bases/marathon/MarathonTestBase.java
Just proposal for handle lifecycle callbacks
=> Handle exception in callbacks

documentation/assemblies/assembly-using-console.adoc, documentation/modules/proc-purging-queues.adoc
Documentation
Docs for purging a queue/subscription using the Console
=> Docs issue 3324: Purging a queue using the console procedure

documentation/modules/ref-address-example-forwarders.adoc, documentation/modules/ref-address-space-example-connectors.adoc
Fix asciidoc formatting issue and clarify address connector and address forwarder conceptual information
=> Docs: clarify address space connector and address forwarder conceptual information

systemtests/src/main/java/io/enmasse/systemtest/info/TestInfo.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java, systemtests/src/main/java/io/enmasse/systemtest/operator/OperatorManager.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java
- Bugfix
This PR fixes a bug introduced in this PR #3327 
=> Fix unexpected uninstall of iot operator

HACKING.md
- Developer Documentation
Update HACKING.md to note `SKIP_UNINSTALL`.
=> Add note about SKIP_UNINSTALL

systemtests/src/test/java/io/enmasse/systemtest/olm/OperatorLifecycleManagerTest.java
- Bugfix
This PR fixes a current bug in OLM tests
=> fix missing resourcesManager in olm test

systemtests/src/test/java/io/enmasse/systemtest/isolated/upgrade/UpgradeTest.java
- Refactoring
This PR tries to improve our UpgradeTest adding more waits after resources creation and reducing the resources created
=> improve upgrade test for slow and resource constrained environments

documentation/assemblies/assembly-configuration-sizing-guide.adoc, documentation/modules/proc-run-calculation-script.adoc, documentation/modules/ref-broker-component-sizing.adoc, documentation/modules/ref-plan-sizing.adoc, documentation/modules/ref-router-component-sizing.adoc
Documentation
Fix miscellaneous formatting issues and one link issue
=> Docs issue-3404: fix sizing guide formatting and link issues

systemtests/src/main/java/io/enmasse/systemtest/clients/ClientUtils.java, systemtests/src/main/java/io/enmasse/systemtest/manager/IsolatedResourcesManager.java, systemtests/src/main/java/io/enmasse/systemtest/manager/ResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/AbstractClient.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/ExternalClientsExtension.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/rhea/RheaClientReceiver.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/rhea/RheaClientSender.java, systemtests/src/main/java/io/enmasse/systemtest/operator/OperatorManager.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/policy/NetworkPolicyTestBrokered.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/policy/NetworkPolicyTestStandard.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/TopicTest.java
Network policy tests, should cover both address space types standard and brokered and both types of selectors pod and namespace.
=> Network policy tests

systemtests/src/main/java/io/enmasse/systemtest/utils/AddressUtils.java
=> Fix web console tests

systemtests/src/main/java/io/enmasse/systemtest/manager/IsolatedResourcesManager.java, systemtests/src/main/java/io/enmasse/systemtest/manager/ResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/utils/AddressSpaceUtils.java, systemtests/src/main/java/io/enmasse/systemtest/utils/AddressUtils.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java
=> Fix isolated

README.md
=> Update chat link to use Gitter chat

pkg/controller/iotproject/managed.go, pkg/controller/iotproject/utils.go, pkg/util/install/utils.go
- Refactoring
Move functionality to more global place. Prepare for larger PR of the IoT tenant cleanup.
=> Move functionality to install package

systemtests/src/main/java/io/enmasse/systemtest/Environment.java, systemtests/src/main/java/io/enmasse/systemtest/platform/KubeCMDClient.java, systemtests/src/main/resources/operator-subscription.json, systemtests/src/test/java/io/enmasse/systemtest/olm/OperatorLifecycleManagerTest.java
- Refactoring
This PR refactors the OLM tests and uses the CLI to install the operator instead of using the web UI, this should guarrantee better stability in the long term
=> OLM tests using CLI

pkg/controller/authenticationservice/authenticationservice_controller.go, pkg/controller/authenticationservice/authenticationservice_controller_test.go, pkg/controller/authenticationservice/none.go, pkg/controller/authenticationservice/standard.go, pkg/controller/authenticationservice/upgrader/standard.go, pkg/util/install/utils.go, pkg/util/install/utils_test.go
- Bugfix
Find and fix a few more location where errors had been ignored.
=> Find and fix a few more ignored errors

amqp-utils/pom.xml, api-model/pom.xml, iot/iot-device-registry-infinispan/pom.xml, k8s-api/pom.xml, pom.xml, standard-controller/pom.xml, systemtests/pom.xml, topic-forwarder/pom.xml
- Refactoring
Upgrade 7years old hamcrest matcher library
=> Upgrade hamcrest dependency

address-space-controller/src/main/java/io/enmasse/controller/ControllerChain.java, address-space-controller/src/main/java/io/enmasse/controller/TemplateInfraResourceFactory.java, k8s-api/src/main/java/io/enmasse/k8s/api/KubeAddressSpaceApi.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/IoTProjectManagedTest.java
=> Some cleanups

CONTRIBUTING.md, HACKING.md
- Bugfix
Cleaning up some typos, inconsistencies in the introduction files
=> Cleaning up some typos, inconsistencies in the introduction files

standard-controller/src/main/java/io/enmasse/controller/standard/KubernetesHelper.java
- Bugfix
Retry delete operation on failure.
=> Retry delete 10 times on failure

.jenkins/Jenkinsfile-pr
Allow to switch PR run to use CRC (ocp4) by `ocp4` arg in pr comment
=> Allow PR jenkins to set agent

systemtests/src/main/java/io/enmasse/systemtest/Environment.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitExecutionListener.java, systemtests/src/main/java/io/enmasse/systemtest/logs/GlobalLogCollector.java, systemtests/src/main/java/io/enmasse/systemtest/logs/LogCollector.java, systemtests/src/main/java/io/enmasse/systemtest/manager/ResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/manager/SharedResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/SeleniumManagement.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/SeleniumProvider.java, systemtests/src/main/java/io/enmasse/systemtest/time/TimeMeasuringSystem.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/bases/clients/ClientTestBase.java
- Refactoring
Make the "qdrouter" information available in the "failed tests" folder. Use `Path` instead of converting between `File` and `Path` all the time.
=> Write out qdrouter information to "failed_tests" folder. Use Paths.

systemtests/scripts/run_tests.sh
=> Keep logging of dowload in make systemtests

.jenkins/Jenkinsfile-pr
- Bugfix
- Refactoring
Jenkins pipeline for PRs using testonly parameter is broken
=> fix testonly case in PR jenkins pipeline

standard-controller/src/main/java/io/enmasse/controller/standard/KubernetesHelper.java
- Bugfix
Attempt different workaround the statefulset deletion error.
=> Try different statefulset workaround

pom.xml, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/QueueTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/TopicTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/clients/artemis/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/clients/openwire/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/clients/proton/java/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/clients/proton/python/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/clients/rhea/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/clients/stomp/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/QueueTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/TopicTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/clients/proton/java/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/clients/proton/python/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/clients/rhea/MsgPatternsTest.java
Use latest surefire plugin for junit, it allows us to use displayName for tests and clean test reports in xunit file.
=> Updated surefire to latest version

.jenkins/Jenkinsfile-pr, systemtests/pom.xml, systemtests/src/main/java/io/enmasse/systemtest/Environment.java, systemtests/src/main/java/io/enmasse/systemtest/IndicativeSentences.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/upgrade/UpgradeTest.java
use parametrized junit tests for upgrade tests
=> Upgrade test parametrized

pom.xml, systemtests/pom.xml, systemtests/src/main/java/io/enmasse/systemtest/info/TestInfo.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/mqtt/ConnectionTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/mqtt/InteroperabilityTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/mqtt/PublishTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/mqtt/SessionTest.java
Add jupiter ability to rerun flaky tests
=> Rerun flaky mqtt tests

systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java
- Refactoring
This PR includes several code cleanups of non used methods and some small refactoring
=> systemtests code cleanups

systemtests/src/test/java/io/enmasse/systemtest/isolated/api/ApiServerTest.java
=> fix flaky test ApiServerTest.testCreateAddressSpaceRoleTenantEdit

systemtests/src/main/java/io/enmasse/systemtest/Environment.java, systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java, templates/iot/examples/infinispan/manual/050-StatefulSet.yaml
- Refactoring
Allow specifying the project for the infinispan deployment.
=> Allow overriding infinispan project

api-model/src/main/java/io/enmasse/iot/model/v1/IoTConfigStatus.java, api-model/src/main/java/io/enmasse/iot/model/v1/IoTProjectStatus.java, api-model/src/test/java/io/enmasse/iot/model/v1/IoTConfigTest.java, api-model/src/test/resources/io/enmasse/iot/model/v1/resources/iot-config.json, cmd/iot-proxy-configurator/configurator.go, pkg/apis/iot/v1alpha1/types_config.go, pkg/apis/iot/v1alpha1/types_project.go, pkg/controller/iotconfig/iotconfig_controller.go, pkg/controller/iotproject/external.go, pkg/controller/iotproject/iotproject_controller.go, pkg/controller/iotproject/managed.go, systemtests/src/main/java/io/enmasse/systemtest/utils/IoTUtils.java
=> Align to use the "phase" field

cmd/iot-proxy-configurator/configurator.go, cmd/iot-proxy-configurator/main.go, cmd/iot-proxy-configurator/sync.go
- Refactoring
Pulling out minor cleanups from #3556
=> Minor cleanups

systemtests/src/main/java/io/enmasse/systemtest/manager/ResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/utils/AddressSpaceUtils.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/soak/PlansSoakTest.java
- New test
Added a test that creates 2500 queue adresses and 7500 anycast adresses.
=> Add test for creating 10000 adresses.

systemtests/src/main/java/io/enmasse/systemtest/listener/JunitExecutionListener.java
- Refactoring
Don't delete the infinispan project if it is equal to the infrastructure project.
=> Don't delete project if it is the infrastructure project

systemtests/src/main/java/io/enmasse/systemtest/utils/IoTUtils.java
- Refactoring
Use constant instead of plain string.
=> Use existing constant

iot/iot-service-base/src/main/java/io/enmasse/iot/service/base/AbstractProjectBasedService.java
- Bugfix
The watcher missed handling the "modified" event.
=> Also process the "modified" event

cmd/iot-proxy-configurator/configurator.go, pkg/apis/iot/v1alpha1/types_config.go, pkg/apis/iot/v1alpha1/types_project.go, pkg/controller/iotconfig/iotconfig_controller.go, pkg/controller/iotproject/external.go, pkg/controller/iotproject/iotproject_controller.go, pkg/controller/iotproject/managed.go, systemtests/src/main/java/io/enmasse/systemtest/utils/IoTUtils.java
- Refactoring
Change the phase value from "Ready" to "Active".
=> Rename "Ready" to "Active"

cmd/iot-proxy-configurator/configurator.go, cmd/iot-proxy-configurator/main.go
- Bugfix
- Refactoring
Try fixing the systemtests by lowering the number of changes hitting the qdr proxy work queue.
=> Only queue when something important has changed

api-model/pom.xml, api-model/src/main/java/io/enmasse/common/model/CustomResources.java, api-model/src/main/java/io/enmasse/iot/model/v1/IoTProject.java, iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/InfinispanRegistry.java, iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/config/AmqpEndpointConfiguration.java, iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/config/ApplicationConfiguration.java, iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/config/DeviceServiceProperties.java, iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/config/HealthConfiguration.java, iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/config/InfinispanProperties.java, iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/config/RestEndpointConfiguration.java, iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/config/VertxConfiguration.java, iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/debug/DebugEndpoint.java, iot/iot-service-base/src/main/java/io/enmasse/iot/service/base/AbstractKubernetesBasedService.java, iot/iot-service-base/src/main/java/io/enmasse/iot/service/base/AbstractProjectBasedService.java, iot/iot-service-base/src/main/java/io/enmasse/iot/service/base/ServiceBase.java
- Bugfix
- Refactoring
Use informer instead of plain watchers.
=> Use informer instead of plain watcher

systemtests/src/main/java/io/enmasse/systemtest/EnmasseInstallType.java, systemtests/src/main/java/io/enmasse/systemtest/operator/OperatorManager.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/upgrade/UpgradeTest.java
- Refactoring
Call right uninstall type in upgrade tests
=> Refactor upgrade tests

systemtests/src/main/java/io/enmasse/systemtest/operator/OperatorManager.java, templates/example-olm/operator-group.yaml
- Bugfix
Clean the created operatorgroup by OLM suite
=> Systemtests OLM tests - delete operatorgroup

systemtests/src/main/java/io/enmasse/systemtest/TestTag.java, systemtests/src/main/java/io/enmasse/systemtest/condition/SupportedInstallTypeCondition.java, systemtests/src/main/java/io/enmasse/systemtest/info/MethodBasedExtensionContext.java, systemtests/src/main/java/io/enmasse/systemtest/info/TestInfo.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/test/java/io/enmasse/systemtest/bases/olm/OLMTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/olm/OLMDefaultTest.java, systemtests/src/test/java/io/enmasse/systemtest/olm/OLMSpecificTest.java
- Bugfix
Fix olm test disabling in isolated profile
=> Add olm testtag again, and fix issues with olm test disabling

keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/PlainSaslServerMechanism.java, keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/SaslAuthenticator.java, keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/SaslServerMechanism.java, keycloak-plugin/sasl-plugin/src/test/java/io/enmasse/keycloak/spi/PlainSaslServerMechanismTest.java, keycloak-plugin/sasl-plugin/src/test/java/io/enmasse/keycloak/spi/XOAUTH2SaslServerMechanismTest.java, pkg/controller/messaginguser/messaginguser_controller.go, pkg/keycloak/client.go, pkg/util/finalizer/finalizer.go
Fixes #3579 . Adds some additional logging that was useful to understand the cause.
=> Handle transaction conflicts when authenticating users

pkg/controller/messaginguser/messaginguser_controller.go, pkg/keycloak/client.go, pkg/logs/helpers.go, templates/enmasse-operator/050-Deployment-enmasse-operator.yaml
- Refactoring
* Use permitted log levels.
* Allow changing level using env var.
Future work would involve to add a mechanism for modifying the logLevel
variable dynamically (for instance via http).
=> Update log levels

olm-manifest/src/main/resources/latest/enmasse.clusterserviceversion.yaml, pkg/controller/iotconfig/adapter.go, pkg/controller/iotconfig/file_device_registry.go, pkg/controller/iotconfig/http_adapter.go, pkg/controller/iotconfig/lorawan_adapter.go, pkg/controller/iotconfig/mqtt_adapter.go, pkg/controller/iotconfig/sigfox_adapter.go, pkg/controller/iotconfig/tenant_service.go, templates/iot/common/010-ServiceAccount.yaml, templates/iot/common/020-ClusterRole-qdr-configurator.yaml, templates/iot/operator/010-ServiceAccount-iot-tenant-service.yaml, templates/iot/operator/020-ClusterRole-iot-tenant-service.yaml, templates/iot/operator/030-ClusterRoleBinding-iot-tenant-service.yaml
- Bugfix
Fix RBAC issues when deploying with OLM.
=> Set a service account for the protocol adapters

iot/iot-tenant-service/src/main/java/io/enmasse/iot/tenant/Application.java, pkg/controller/iotconfig/auth_service.go, pkg/controller/iotconfig/file_device_registry.go, pkg/controller/iotconfig/http_adapter.go, pkg/controller/iotconfig/infinispan_device_registry.go, pkg/controller/iotconfig/lorawan_adapter.go, pkg/controller/iotconfig/mqtt_adapter.go, pkg/controller/iotconfig/sigfox_adapter.go, pkg/controller/iotconfig/tenant_service.go, pkg/controller/iotconfig/utils.go, pkg/util/install/utils.go, templates/service-monitors/010-ServiceMonitor-enmasse.yaml
Enable metrics endpoints for Hono components.
=> Enable metrics endpoints for Hono components

.github/scripts/build.sh, .github/scripts/collectLogs.sh, .github/scripts/install_dep.sh, .github/scripts/test.sh, .github/workflows/release.yml, .github/workflows/smoke.yml, .github/workflows/unit.yml
- Smoke tests
- Unit tests
Proposal for github actions. Possible replacement for Travis.
=> Create github actions workflows

.github/scripts/install_dep.sh, .github/scripts/setup_docker.sh, .github/workflows/release.yml, .github/workflows/smoke.yml, .github/workflows/unit.yml
=> Actions fix

address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceController.java, address-space-controller/src/main/java/io/enmasse/controller/AppliedConfig.java, address-space-controller/src/main/java/io/enmasse/controller/CreateController.java, address-space-controller/src/main/java/io/enmasse/controller/InfraResourceFactory.java, address-space-controller/src/main/java/io/enmasse/controller/RouterConfigController.java, address-space-controller/src/main/java/io/enmasse/controller/RouterSet.java, address-space-controller/src/main/java/io/enmasse/controller/RouterStatusController.java, address-space-controller/src/main/java/io/enmasse/controller/StatusController.java, address-space-controller/src/main/java/io/enmasse/controller/TemplateInfraResourceFactory.java, address-space-controller/src/main/java/io/enmasse/controller/common/Kubernetes.java, address-space-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java, address-space-controller/src/test/java/io/enmasse/controller/CreateControllerTest.java, address-space-controller/src/test/java/io/enmasse/controller/StatusControllerTest.java, address-space-controller/src/test/java/io/enmasse/controller/TemplateInfraResourceFactoryTest.java, api-model/src/main/java/io/enmasse/address/model/AddressSpaceResolver.java, api-model/src/main/java/io/enmasse/config/AnnotationKeys.java, systemtests/src/main/java/io/enmasse/systemtest/manager/IsolatedResourcesManager.java, systemtests/src/main/java/io/enmasse/systemtest/manager/ResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/utils/AddressSpaceUtils.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/GlobalConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/api/ApiServerTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/api/AuthServiceTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/api/CustomResourceDefinitionAddressSpacesTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/plans/standard/PlansTestStandard.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/upgrade/UpgradeTest.java
=> Allow addressspace spec changes (#3541)

.github/workflows/smoke.yml
=> PR job fix

.github/workflows/release.yml
=> Change tag format

.github/scripts/olm_test.sh, .github/scripts/smoke_test.sh, .github/workflows/release.yml, .github/workflows/smoke.yml
=> GitHub actions split tests

templates/iot/common/020-ClusterRole-qdr-configurator.yaml
- Bugfix
This is just a typo, but it looks odd.
=> Fix ClusterRoleBinding name

cmd/iot-proxy-configurator/configurator.go, cmd/iot-proxy-configurator/main.go, cmd/iot-proxy-configurator/sync.go, iot/TODO.md
=> Store certificates in directory hierarchy

systemtests/src/main/java/io/enmasse/systemtest/EnmasseInstallType.java, systemtests/src/main/java/io/enmasse/systemtest/OLMInstallationType.java, systemtests/src/main/java/io/enmasse/systemtest/SysytemTestsErrorCollector.java, systemtests/src/main/java/io/enmasse/systemtest/clients/ClientUtils.java, systemtests/src/main/java/io/enmasse/systemtest/condition/SupportedInstallTypeCondition.java, systemtests/src/main/java/io/enmasse/systemtest/manager/IsolatedIoTManager.java, systemtests/src/main/java/io/enmasse/systemtest/manager/ResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/manager/SharedIoTManager.java, systemtests/src/main/java/io/enmasse/systemtest/manager/SharedResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/ExternalClientsExtension.java, systemtests/src/main/java/io/enmasse/systemtest/operator/OperatorManager.java, systemtests/src/main/java/io/enmasse/systemtest/utils/AddressSpaceUtils.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/policy/NetworkPolicyTestBrokered.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/policy/NetworkPolicyTestStandard.java
- Refactoring
Clean and refactor systemtest suite
=> Systemtests clean

systemtests/src/main/java/io/enmasse/systemtest/manager/IsolatedIoTManager.java, systemtests/src/main/java/io/enmasse/systemtest/manager/SharedIoTManager.java
=> Systemtests- collect infinispan logs

.github/workflows/release.yml
=> Change trigger of release job

.github/workflows/release.yml
=> Change asset path

systemtests/src/main/java/io/enmasse/systemtest/logs/GlobalLogCollector.java, systemtests/src/main/java/io/enmasse/systemtest/manager/IsolatedIoTManager.java, systemtests/src/main/java/io/enmasse/systemtest/manager/SharedIoTManager.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/MultipleProjectsTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/project/ManagedTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/shared/http/HttpAdapterTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/shared/mqtt/MqttAdapterTest.java
- Refactoring
- [X ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
=> Clean up in iot logs and only collect infinispan logs if test failed

systemtests/src/main/java/io/enmasse/systemtest/condition/SupportedInstallType.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java, systemtests/src/main/java/io/enmasse/systemtest/operator/OperatorManager.java, systemtests/src/test/java/io/enmasse/systemtest/olm/OLMDefaultTest.java, systemtests/src/test/java/io/enmasse/systemtest/olm/OLMSpecificTest.java
- Bugfix
This PR fixes some olm deployment issues found in our CI
=> Fix olm deployment issues

keycloak-plugin/src/main/sh/init-keycloak.sh, keycloak-user-api/src/main/java/io/enmasse/user/keycloak/KubeKeycloakFactory.java
- Bugfix
Make use of new annotation to generate certificates. Ensure that we don't trust certificate directly, but add service-ca.crt to the trust chain.
Fixes #3457
=> Use service ca

address-space-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java, pom.xml, standard-controller/src/main/java/io/enmasse/controller/standard/KubernetesHelper.java
- Bugfix
Taking newer version of kubernetes-client (4.6.4) which will allow some workarounds to be removed from the code-base.
=> Update to kubernetes-client 4.6.4

systemtests/src/main/java/io/enmasse/systemtest/apiclients/ApiClient.java, systemtests/src/main/java/io/enmasse/systemtest/apiclients/OpenshiftCertValidatorApiClient.java, systemtests/src/main/java/io/enmasse/systemtest/apiclients/PrometheusApiClient.java, systemtests/src/main/java/io/enmasse/systemtest/iot/CredentialsRegistryClient.java, systemtests/src/main/java/io/enmasse/systemtest/iot/DeviceRegistryClient.java, systemtests/src/main/java/io/enmasse/systemtest/iot/HonoApiClient.java, systemtests/src/main/java/io/enmasse/systemtest/iot/HttpAdapterClient.java, systemtests/src/main/java/io/enmasse/systemtest/utils/IoTUtils.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/MultipleProjectsTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/project/ManagedTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/DeviceRegistryTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/shared/control/CommandAndControlTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/shared/http/HttpAdapterTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/shared/mqtt/MqttAdapterTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/certs/CertProviderTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/monitoring/MonitoringTest.java
=> Clean systemtests api clients

iot/pom.xml
- Refactoring
Upgrade to Hono 1.0.2
=> Switch to Hono 1.0.2

systemtests/src/main/java/io/enmasse/systemtest/apiclients/ApiClient.java, systemtests/src/main/java/io/enmasse/systemtest/apiclients/PrometheusApiClient.java, systemtests/src/main/java/io/enmasse/systemtest/iot/HonoApiClient.java, systemtests/src/main/java/io/enmasse/systemtest/iot/HttpAdapterClient.java
=> Fix iot api clients auth

documentation/design/proposals/shared-infrastructure.adoc
Initial proposal on shared infrastructure based on discussion in #3420.
=> Initial shared infra proposal

address-space-controller/Dockerfile, agent/Dockerfile, console/console-httpd/Dockerfile, console/console-init/Dockerfile, controller-manager/Dockerfile, iot/iot-auth-service/Dockerfile, iot/iot-device-registry-file/Dockerfile, iot/iot-device-registry-infinispan/Dockerfile, iot/iot-http-adapter/Dockerfile, iot/iot-lorawan-adapter/Dockerfile, iot/iot-mqtt-adapter/Dockerfile, iot/iot-proxy-configurator/Dockerfile.template, iot/iot-sigfox-adapter/Dockerfile, iot/iot-tenant-cleaner/Dockerfile, iot/iot-tenant-service/Dockerfile, keycloak-plugin/Dockerfile, mqtt-gateway/Dockerfile, mqtt-lwt/Dockerfile, none-authservice/Dockerfile, olm-manifest/Dockerfile, service-broker/Dockerfile, standard-controller/Dockerfile, topic-forwarder/Dockerfile
=> Use build arguments instead of env-vars, for using podman

pom.xml
=> Align to the most recent 6.0.x version we have

documentation/assemblies/assembly-iot-guide.adoc, documentation/assemblies/assembly-iot-project-owner-guide.adoc, documentation/assemblies/assembly-iot-tenant-guide.adoc, documentation/common/iot-project-external-example.yaml, documentation/common/iot-project-managed-example.yaml, documentation/modules/ref-iot-project-external-example.adoc, documentation/modules/ref-iot-project-managed-example.adoc
Add some documentation around the iotproject.
=> Iot docs : add iot projects examples

console/console-init/ui/src/Components/AddressDetail/AddressDetailHeader.tsx, console/console-init/ui/src/Components/AddressSpace/Address/EmptyAddress.tsx, console/console-init/ui/src/Components/AddressSpace/AddressSpaceHeader.tsx, console/console-init/ui/src/Components/AddressSpace/AddressSpaceNavigation.tsx, console/console-init/ui/src/Components/AddressSpace/Connection/EmptyConnection.tsx, console/console-init/ui/src/Components/AddressSpaceList/AddressSpaceList.tsx, console/console-init/ui/src/Components/AddressSpaceList/AddressSpaceListFilter.tsx, console/console-init/ui/src/Components/AddressSpaceList/EmptyAddressSpace.tsx, console/console-init/ui/src/Components/Common/DeletePrompt.tsx, console/console-init/ui/src/Components/Common/EmptyLinks.tsx, console/console-init/ui/src/Components/Common/FilterDropdown.tsx, console/console-init/ui/src/Components/Common/SortForMobileView.tsx, console/console-init/ui/src/Components/Common/TypePlan.tsx, console/console-init/ui/src/Components/ConnectionDetail/ConnectionDetailHeader.tsx, console/console-init/ui/src/Components/ConnectionDetail/MessagesDetail.tsx, console/console-init/ui/src/Components/NavToolBar/NavToolBar.tsx, console/console-init/ui/src/Pages/AddressDetail/AddressDetailPage.tsx, console/console-init/ui/src/Pages/AddressDetail/AddressLinksFilter.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListFilter.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListPage.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/ConnectionList/ConnectionListFilter.tsx, console/console-init/ui/src/Pages/ConnectionDetail/ConnectionDetailPage.tsx, console/console-init/ui/src/Pages/ConnectionDetail/ConnectionLinksFilter.tsx, console/console-init/ui/src/Pages/CreateAddress/CreateAddressDefinition.tsx, console/console-init/ui/src/Pages/CreateAddress/PreviewAddress.tsx, console/console-init/ui/src/Pages/CreateAddressSpace/CreateAddressSpaceConfiguration.tsx, console/console-init/ui/src/Pages/CreateAddressSpace/ReviewAddressSpace.tsx
This PR includes ids in filters, buttons, drop-downs and input fields in all the source files to enable testing.
=> Add ids to all elements for testing

documentation/assemblies/assembly-troubleshooting-guide.adoc, documentation/master-kubernetes.adoc, documentation/master-openshift.adoc, documentation/modules/proc-troubleshooting.adoc
Initial guide with troubleshooting steps.
=> Initial troubleshooting guide

documentation/assemblies/assembly-iot-service-admin-guide.adoc, documentation/modules/con-iot-monitoring.adoc, documentation/modules/ref-iot-metrics.adoc
=> Add IoT metrics documentation

documentation/assemblies/assembly-iot-service-admin-guide.adoc, documentation/modules/proc-iot-troubleshoot-stuck-iotproject.adoc
=> Add a troubleshooting section for IoT

cmd/console-server/main.go, pkg/consolegraphql/resolvers/resolver_address.go, pkg/consolegraphql/resolvers/resolver_addressspace.go, pkg/consolegraphql/server/request_context.go
Created mutations for Addresses & Address Spaces.  Implement Create, Patch, and Delete
- Bugfix
- Refactoring
=> Created mutations for add, delete, and patch

.github/workflows/release.yml
=> Fix uploading release assets

address-space-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java
=> Set propagation policy Background to PVC deletion

console/console-init/ui/src/Components/AddressSpace/Address/EmptyAddress.tsx, console/console-init/ui/src/Components/AddressSpaceList/EmptyAddressSpace.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListFilterPage.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListPage.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressesListWithFilterAndPaginationPage.tsx, console/console-init/ui/src/Pages/AddressSpaceList/AddressSpaceListFilterPage.tsx, console/console-init/ui/src/Pages/AddressSpaceList/AddressSpaceListPage.tsx, console/console-init/ui/src/Pages/AddressSpaceList/AddressSpaceListWithFilterAndPaginationPage.tsx, console/console-init/ui/src/Pages/ConnectionDetail/ConnectionDetailPage.tsx, console/console-init/ui/src/stories/AddressList.stories.tsx, console/console-init/ui/src/stories/LinkList.stories.tsx
Fix - New fresh global console shows in middle of page button Create Address Space and create Address in Empty List page does not work.
=> fix-create address and address space button and create address button of empty list not working

console/console-init/ui/src/Pages/AddressDetail/AddressLinksListPage.tsx
=> Fix fetching of metric for delivery rate

.github/workflows/release.yml
=> Fix asset path

console/console-init/ui/src/Tests/AddressList.test.tsx, console/console-init/ui/src/Tests/ConnectionDetailHeader.test.tsx, console/console-init/ui/src/Tests/ConnectionList.test.tsx, console/console-init/ui/src/Tests/EmptyAddress.test.tsx
- Bugfix
Changes test data based on the changed schema, to prevent react test fails in CI mode.
=> Change test data to prevent test fails in CI mode

CHANGELOG.md, iot/pom.xml
=> bump infinispan to latest productised version

CHANGELOG.md, Makefile.env.mk
Upgrade to newly release ActiveMQ Artemis 2.11.0
=> Update to ActiveMQ Artemis 2.11.0

systemtests/src/main/java/io/enmasse/systemtest/operator/OperatorManager.java
=> Fix remove unsupported command arg

Makefile, Makefile.common, Makefile.java.mk
=> Use maven batch mode

CHANGELOG.md, olm-manifest/src/main/resources/latest/enmasse.clusterserviceversion.yaml
This is also used for disconnected installs.
=> Add support for configuring related images via downward API

console/console-init/ui/src/Components/AddressSpace/Address/AddressList.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListPage.tsx
- Bugfix
Checks if planStatus is null and accordingly assigns partitions a value.
=> Add null checks for planStatus

.gitignore, Makefile, hack/generate-groups.sh, hack/verify-codegen.sh
=> Re-add verify codegen script to the CI

address-space-controller/src/main/java/io/enmasse/controller/PodDistruptionBudgetController.java, api-model/src/main/java/io/enmasse/admin/model/v1/StandardInfraConfigSpecBroker.java, api-model/src/main/java/io/enmasse/admin/model/v1/StandardInfraConfigSpecRouter.java, templates/crds/standardinfraconfigs.crd.yaml
Bugfix of PodDistructionBudget functionalities
=> PodDistruptionBudget use correct config values

CHANGELOG.md, templates/example-plans/020-AddressPlan-standard-large-partitioned-queue.yaml, templates/example-plans/020-AddressPlan-standard-medium-partitioned-queue.yaml, templates/example-plans/020-AddressPlan-standard-small-partitioned-queue.yaml, templates/example-plans/020-AddressSpacePlan-standard-medium.yaml, templates/example-plans/020-AddressSpacePlan-standard-unlimited-with-mqtt.yaml, templates/example-plans/020-AddressSpacePlan-standard-unlimited.yaml
Adding new example plans for partitioned/sharded queues. These are for the small, medium and large queues with updated description and partitions of 3.
=> Add partitioned queues

systemtests/src/main/java/io/enmasse/systemtest/operator/OperatorManager.java
- Bugfix
Fix issue in OLM tests I noticed in our CI, it'm not 100% sure the issue is because of this but anyway unifiying our delete steps in systemtests is good
=> Use correct delete crd steps when OLM

console/console-init/ui/src/Components/AddressDetail/AddressDetailHeader.tsx, console/console-init/ui/src/Pages/AddressDetail/AddressDetailPage.tsx, console/console-init/ui/src/stories/AddressDetailHeader.stories.tsx
- Bugfix
Add metrics for stored messages in address detail header
=> Add stored messages in address detail header

console/console-init/ui/src/Pages/CreateAddress/CreateAddressDefinition.tsx, console/console-init/ui/src/Pages/CreateAddressSpace/CreateAddressSpaceConfiguration.tsx, console/console-init/ui/src/Tests/AddressList.test.tsx
There was some inconsistency in behaviour of dropdowns, in terms of selection which was not working for html elements as children of button.
The inconsistency has been reproduced here : 
https://codesandbox.io/s/recursing-swartz-vziq7
=> Fix: onSelect method of dropdowns in creation wizards

console/console-init/ui/src/Components/AddressSpace/Address/AddressList.tsx, console/console-init/ui/src/Components/AddressSpaceList/AddressSpaceList.tsx, console/console-init/ui/src/Components/AddressSpaceList/AddressSpaceListFilter.tsx, console/console-init/ui/src/Pages/AddressDetail/AddressDetailPage.tsx, console/console-init/ui/src/Pages/AddressDetail/AddressLinksListPage.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListFilter.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListFilterPage.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListPage.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressesListWithFilterAndPaginationPage.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressSpaceDetailPage.tsx, console/console-init/ui/src/Pages/AddressSpaceList/AddressSpaceListFilterPage.tsx, console/console-init/ui/src/Pages/AddressSpaceList/AddressSpaceListPage.tsx, console/console-init/ui/src/Pages/AddressSpaceList/AddressSpaceListWithFilterAndPaginationPage.tsx, console/console-init/ui/src/Pages/ConnectionDetail/ConnectionDetailPage.tsx, console/console-init/ui/src/Pages/ConnectionDetail/ConnectionsLinksListPage.tsx, console/console-init/ui/src/Pages/CreateAddress/CreateAddressPage.tsx, console/console-init/ui/src/Queries/Queries.tsx, console/console-init/ui/src/Tests/AddressDetialHeader.test.tsx, console/console-init/ui/src/Tests/AddressList.test.tsx, console/console-init/ui/src/Tests/AddressSpaceList.test.tsx, console/console-init/ui/src/stories/AddressList.stories.tsx, console/console-init/ui/src/stories/AddressSpaceList.stories.tsx
- Fix - Multiple selection of address and adddressSpace
- Delete All(selected address spaces) working
- Delete/Purge All (selected addresses) working
- Handled null check for connection.Spec.Properties in connection Detail page
- Added mutation query for purge Address
=> Fix - Delete/Purge all addresses and Delete All address space don't work

console/console-init/ui/src/App.tsx, console/console-init/ui/src/Components/AddressSpace/Address/AddressList.tsx, console/console-init/ui/src/Components/AddressSpaceList/AddressSpaceList.tsx, console/console-init/ui/src/Components/Common/AddressSpaceListFormatter.tsx, console/console-init/ui/src/Pages/AddressDetail/AddressDetailPage.tsx, console/console-init/ui/src/Pages/AddressDetail/AddressLinksListPage.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListFilter.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListFilterPage.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListPage.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressesListWithFilterAndPaginationPage.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressSpaceDetailPage.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/ConnectionList/ConnectionsListPage.tsx, console/console-init/ui/src/Pages/AddressSpaceList/AddressSpaceListPage.tsx, console/console-init/ui/src/Pages/ConnectionDetail/ConnectionDetailPage.tsx, console/console-init/ui/src/Pages/ConnectionDetail/ConnectionsLinksListPage.tsx, console/console-init/ui/src/Pages/CreateAddressSpace/CreateAddressSpacePage.tsx, console/console-init/ui/src/Queries/Queries.tsx, console/console-init/ui/src/Tests/AddressSpaceList.test.tsx, console/console-init/ui/src/Types/ResponseTypes.tsx, console/console-init/ui/src/stories/AddressSpaceList.stories.tsx
- Include all type of status in Address space list page
- Add sort function for time created in AddressSpace list
- Refetch data of addressSpace List after creation of addressSpace
- Fixed Lock Icon in connection Detail Header
- rename name column with address in filter and list of address list
- Polling of data in every 5 seconds
=> fixes related to address space list and addresses

console/console-init/ui/src/Components/AddressSpace/Address/AddressList.tsx, console/console-init/ui/src/Components/AddressSpaceList/AddressSpaceList.tsx, console/console-init/ui/src/Components/Common/AddressFormatter.tsx, console/console-init/ui/src/Components/Common/AddressSpaceListFormatter.tsx, console/console-init/ui/src/Components/Common/Error.tsx, console/console-init/ui/src/Pages/AddressSpaceList/AddressSpaceListPage.tsx, console/console-init/ui/src/Queries/Queries.tsx, console/console-init/ui/src/Tests/AddressSpaceList.test.tsx, console/console-init/ui/src/Types/ResponseTypes.tsx, console/console-init/ui/src/stories/AddressSpaceList.stories.tsx
- show Status with message in address space list
- show Status column in address list
=> Add status column in address

address-space-controller/src/main/java/io/enmasse/controller/PodDistruptionBudgetController.java, address-space-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java
Mark distruption budgets with infra labels and delete in finalizer
=> Delete PodDisruptionBudgets when address space is deleted

address-space-controller/src/main/java/io/enmasse/controller/PodDistruptionBudgetController.java
- Bugfix
Delete pod disruption budget if not configured
=> Ensure that pod disruption budget gets deleted if not configured

.github/scripts/collectLogs.sh, .github/scripts/smoke_test.sh, .github/workflows/release.yml, .github/workflows/smoke.yml
=> Change format of uploaded artifacts - Github Actions

systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java
Cleanup unused methods in TestUtils
=> Cleanup TestUtils unused methods

console/console-init/ui/src/Components/Common/AddressSpaceListFormatter.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListPage.tsx, console/console-init/ui/src/Pages/AddressSpaceList/AddressSpaceListPage.tsx
handle null response for status and plan in address space and addresses
=> fix- handle null response for status and plan in address space and addresses

console/console-init/ui/src/Pages/CreateAddress/CreateAddressDefinition.tsx, console/console-init/ui/src/Pages/CreateAddress/CreateAddressPage.tsx, console/console-init/ui/src/Queries/Queries.tsx
The addressSpaceType query now takes into account the address space type.
=> Fix : fetch address types based on address space type

console/console-init/ui/src/Components/AddressSpaceList/AddressSpaceListFilter.tsx, console/console-init/ui/src/Pages/AddressDetail/AddressLinksFilter.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListFilter.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/ConnectionList/ConnectionListFilter.tsx, console/console-init/ui/src/Pages/ConnectionDetail/ConnectionLinksFilter.tsx
Add disabled select option for typeahead search input box. "Enter more characters" option if input length is less than 5 characters and "No results found" if server return empty response.
=> Default select option for empty typeahead search box

templates/crds/addresses.crd.yaml, templates/crds/addressplans.crd.yaml, templates/crds/addressspaceplans.crd.yaml, templates/crds/addressspaces.crd.yaml, templates/crds/addressspaceschemas.crd.yaml, templates/crds/authenticationservices.crd.yaml, templates/crds/brokeredinfraconfigs.crd.yaml, templates/crds/consoleservices.crd.yaml, templates/crds/iotconfigs.crd.yaml, templates/crds/iotprojects.crd.yaml, templates/crds/messagingusers.crd.yaml, templates/crds/standardinfraconfigs.crd.yaml
Add OpenAPI description for all CRDs. The output will appear in the `kubectl explain <resourcename in plural>` output.
=> Add descriptions to all CRDs

console/console-init/ui/src/Components/AddressSpaceList/AddressSpaceList.tsx, console/console-init/ui/src/Pages/AddressSpaceList/AddressSpaceListPage.tsx, console/console-init/ui/src/Pages/EditAddressSpace.tsx, console/console-init/ui/src/Queries/Queries.tsx, console/console-init/ui/src/Tests/AddressSpaceList.test.tsx, console/console-init/ui/src/stories/AddressSpaceList.stories.tsx
Editing plans of AddressSpaces was not working as the plan value data wasn't being fetched for AddressSpaceList.
=> Fix: edit address space plans

pkg/controller/iotconfig/infinispan_device_registry.go
=> Drop the creation of a PVC when using Infinispan

pkg/controller/iotproject/finalizers.go, pkg/util/install/delete.go
=> Wait for deletion of address space

console/console-init/ui/src/Pages/CreateAddress/CreateAddressDefinition.tsx, console/console-init/ui/src/Pages/CreateAddress/CreateAddressPage.tsx, console/console-init/ui/src/Pages/CreateAddressSpace/CreateAddressSpaceConfiguration.tsx, console/console-init/ui/src/Pages/CreateAddressSpace/CreateAddressSpacePage.tsx
- Bugfix
Enable validations for create address and address space wizards
=> Remove capital letters from name validation

console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListPage.tsx, console/console-init/ui/src/Pages/AddressSpaceList/AddressSpaceListPage.tsx
fix - console is broken after create new addressspace. As message in status object is null
=> fix address space list error when message in status is null

console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListFilterPage.tsx, console/console-init/ui/src/Queries/Queries.tsx
Fix- sort is not working due to addition of a new column i.e "status" in address list
=> fix sorting in address list

console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressesListWithFilterAndPaginationPage.tsx, console/console-init/ui/src/Pages/AddressSpaceList/AddressSpaceListWithFilterAndPaginationPage.tsx
Fix - "Multiselect of items does not work, when I select items and want to select another, first item is unselected.
=> fix-multi select not working

console/console-init/ui/src/Components/AddressDetail/AddressDetailHeader.tsx, console/console-init/ui/src/Components/AddressSpace/AddressSpaceHeader.tsx, console/console-init/ui/src/Components/AddressSpaceList/AddressSpaceListFilter.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListFilter.tsx
IDs have been given to kebab menus and menu items for AddressSpaceHeader and AddressDetailHeader components.
=> Chore: give IDs to kebab menus and menu items

address-space-controller/src/main/java/io/enmasse/controller/TemplateInfraResourceFactory.java, api-model/src/main/java/io/enmasse/config/AnnotationKeys.java, api-model/src/main/java/io/enmasse/config/Apps.java, api-model/src/main/java/io/enmasse/config/LabelKeys.java, cmd/controller-manager/main.go, k8s-api/src/main/java/io/enmasse/k8s/api/KubeAddressSpaceApi.java, pkg/controller/iotconfig/adapter.go, pkg/controller/iotconfig/file_device_registry.go, pkg/controller/iotconfig/infinispan_device_registry.go, pkg/controller/iotconfig/tenant_service.go, pkg/util/install/utils.go, pkg/util/openshift.go, standard-controller/src/main/java/io/enmasse/controller/standard/TemplateBrokerSetGenerator.java
=> Set annotations/labels for apps

.github/workflows/master.yml, .github/workflows/release.yml
=> Change master build trigger

pkg/consolegraphql/resolvers/generated.go, pkg/consolegraphql/resolvers/resolver_addressspace.go, pkg/consolegraphql/resolvers/resolver_addressspace_test.go
- Used for downloading the cert from the console
- Bugfix
- Refactoring
=> Implemented the MessagingCertificateChain Query

pkg/controller/iotconfig/iotconfig_controller.go, pkg/controller/iotproject/iotproject_controller.go
Update status only if there are changes
=> Improve IoT project reconciliation; 

console/console-init/ui/src/Components/AddressSpace/Address/AddressList.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListFilterPage.tsx
- add sort functionality to sender and receivers column in address list
=> add sort functionality to sender and receivers column in address list

iot/iot-device-registry-base/src/main/java/io/enmasse/iot/registry/tenant/KubernetesTenantInformationService.java, iot/iot-device-registry-base/src/main/java/io/enmasse/iot/registry/tenant/TenantInformation.java, iot/iot-device-registry-base/src/main/java/io/enmasse/iot/registry/util/DeviceRegistryTokenAuthProvider.java, iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/config/DeviceServiceConfiguration.java, systemtests/src/main/java/io/enmasse/systemtest/iot/DeviceRegistryClient.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/DeviceRegistryTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/InfinispanDeviceRegistryTest.java
First step in the process of moving the tenant validation from service implementation to the auth layer
=> [iot] Add tenant validation to the registry auth layer

api-model/src/main/java/io/enmasse/address/model/KubeUtil.java, api-model/src/test/java/io/enmasse/address/model/v1/address/KubeUtilTest.java, pkg/controller/iotproject/iotproject_controller.go, pkg/controller/iotproject/managed.go, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/IoTProjectManagedTest.java
=> Test re-creation of an address space

cmd/console-server/main.go, console/console-init/ui/src/Pages/CreateAddressSpace/CreateAddressSpacePage.tsx, console/console-init/ui/src/Pages/CreateAddressSpace/ReviewAddressSpace.tsx, console/console-server/src/main/resources/gqlgen.yml, console/console-server/src/main/resources/schema.graphql, pkg/consolegraphql/resolvers/generated.go, pkg/consolegraphql/resolvers/resolver_address.go, pkg/consolegraphql/resolvers/resolver_address_test.go, pkg/consolegraphql/resolvers/resolver_addressspace.go, pkg/consolegraphql/resolvers/resolver_addressspace_test.go, pkg/consolegraphql/server/request_context.go
- returned the yaml required for running the commands on command-line
- Added authentication service type to the create addressspace
- Bugfix
- Refactoring
=> Implemented the command queries

console/console-init/ui/mock-console-server/mock-console-server.js, console/console-init/ui/mock-console-server/schema.js
AddressSpace.Spec.AuthenticationService is part of the console server.  Adding it to the mock-server as well.
=> In the mock server, added AuthenticationService to the AddressSpace.Spec
