EnMasseProject/enmasse

enmasse-template.jsonnet, generated/enmasse-kubernetes.yaml, generated/enmasse-template-with-kafka.yaml, generated/enmasse-template.yaml, generated/tls-enmasse-template-with-kafka.yaml, generated/tls-enmasse-template.yaml, include/address-controller.jsonnet, include/common.jsonnet, include/enmasse-instance-infra.jsonnet, include/enmasse-kubernetes.jsonnet, include/enmasse-template.jsonnet, include/template-config.jsonnet
* All templates are part of a enmasse-template-config configMap, and is
mounted inside the address controller for it to process them when
requested.
This is a first step in making the configs useful on kubernetes as in #17
=> Embed all templates in a config

generated/enmasse-kubernetes.yaml, generated/enmasse-template-with-kafka.yaml, generated/enmasse-template.yaml, generated/sasldb-enmasse-template.yaml, generated/sasldb-tls-enmasse-template.yaml, generated/tls-enmasse-template-with-kafka.yaml, generated/tls-enmasse-template.yaml, include/messaging-service.jsonnet
Needed if you want to exten the router network beyond the local openshift cluster.
=> added inter-router port to the messaging service

documentation/address-model/resource-definitions.md
(to identify the format of the body)
=> Define a subject for AMQP messages sent out by configserv 

console/Dockerfile, ragent/Dockerfile, subserv/Dockerfile
This saves some time and space for building docker images that all
install the same RPMs.
@grs Wdyt? Some travis builds hang on RPM install, and I was hoping this would fix that as well.
=> Use common base image with node runtime

build.gradle
Default dockerUser and dockerPassword changed from "unset" to null due to authentication fails. Now dockerUser and dockerPassword should be set only via System properties.
=> FIX build.gradle - docker authentication

templates/include/amqp-kafka-bridge.jsonnet, templates/include/common.jsonnet, templates/install/openshift/enmasse-with-kafka.yaml
Modified clientContainer function to allow HTTP readiness probe creation
Updated AMQP - Kafka bridge definition with HTTP readiness probe
=> Added a way to add readiness probe to a "client" mode container

Jenkinsfile, ragent/build.gradle, systemtests/scripts/collect_logs.sh, systemtests/scripts/common.sh
Docker registry and OpenShift instance settings are provided using
jenkins credentials that must be setup on the jenkins master.
This fixes #92
=> Add jenkinsfile to support building on jenkins

router/colocated-topic.snippet, router/qdrouterd.conf.template, router/ssl.snippet, router/subscriptions.snippet
This avoids https://issues.apache.org/jira/browse/DISPATCH-804 (though that is now resolved).
=> Updated to use host in favour of the deprecated addr.

.travis.yml
The build logs confirm that mocha is being run with this change.
=> Install javascript test dependencies

templates/install/common.sh, templates/install/deploy-kubernetes.sh, templates/install/deploy-openshift.sh
OS X uses openssl 0.9.8 rather than something more modern (which uses PKCS#1 rather than PKCS#8 format for keys by default)
Also, for tr to work from /dev/urandom we must set LC_CTYPE=C (this would also likely cause problems with linux users with non-default LC_CTYPE also)
Finally the command line options for base64 are different
=> Modify deployment scripts to work on OS X

console/bin/console_server.js
This makes it possible to run the console server outside of openshift (while still connecting to the other components), which is very useful for dev.
=> allow path for auth-service ca to be overridden

templates/install/deploy-kubernetes.sh
When deploying on Kubernetes, the external load balancers and keycloak credentials are deployed without namespace. As a result they end up in the default namespace and that causes problems.
=> Deploy external loadbalancers and keycloak credentials into the correct namespace

admin/address-controller/lib/src/main/java/io/enmasse/controller/api/v1/AddressApiHelper.java, admin/address-controller/lib/src/test/java/io/enmasse/controller/api/v1/AddressApiHelperTest.java, admin/common-lib/config/src/main/java/io/enmasse/address/model/Address.java
Address objects are compared including their uuid, however where a request is made without specifying a uuid then a random value is generated.
Instead a stable uuid value should be generated based on the address string if no uuid is supplied.
=> Stop address controller incorrectly deleting existing queues

templates/include/amqp-kafka-bridge.jsonnet, templates/include/common.jsonnet, templates/install/openshift/enmasse-with-kafka.yaml
In master the AMQP-Kafka bridge doesn't work because the bridge doesn't use TLS and the right port when connecting to the router. 
This PR adds the annotation to the bridge deployment to generate the secret with TLS certificates and maps this secret as a volume. A second PR  EnMasseProject/amqp-kafka-bridge#75 adds TLS support for the bridge it self.
=> Add TLS support for AMQP-Kafka bridge

documentation/getting-started/kubernetes.adoc
The Kubernetes deployment doesn't currently support RBAC enabled cluster. This PR adds a note to the Getting started guide for Kubernetes about RBAC and how to get EnMasse up and running.
=> Add note about RBAC support to the Getting started guide for Kubernetes - fixes #201

gradle/wrapper/gradle-wrapper.properties
Gradle 4.x can cause issues with older (2016) versions of IntelliJ
=> Downgrade gradle wrapper version

admin/common-lib/config/src/main/java/io/enmasse/address/model/v1/AddressListV1Serializer.java, admin/common-lib/config/src/main/java/io/enmasse/address/model/v1/AddressSpaceListV1Serializer.java, admin/common-lib/config/src/main/java/io/enmasse/address/model/v1/AddressSpaceV1Serializer.java, admin/common-lib/config/src/test/java/io/enmasse/address/model/v1/address/SerializationTest.java
When serializing address lists always provide a (possibly empty) list of items.
This closes #216
=> Always provide list of items in JSON serialisation of an AddressList

.travis/build.sh, admin/address-controller/lib/src/main/java/io/enmasse/controller/common/KubernetesHelper.java, documentation/getting-started/kubernetes.adoc, templates/install/kubernetes/addons/console-ingress.yaml
This feature is only half-working due to limited capability in
ingress resources. Instead, add instructions on how to add
ingress manually to console.
=> Disable automatic ingress for endpoints

admin/address-controller/lib/src/main/java/io/enmasse/controller/auth/AuthController.java, admin/address-controller/lib/src/main/java/io/enmasse/controller/standard/AddressController.java, admin/address-controller/lib/src/main/java/io/enmasse/controller/standard/StandardController.java, admin/address-controller/lib/src/test/java/io/enmasse/controller/standard/AddressControllerTest.java, admin/address-controller/server/src/main/java/io/enmasse/controller/Controller.java, admin/address-controller/server/src/main/java/io/enmasse/controller/HTTPServer.java, admin/common-lib/amqp/src/main/java/io/enmasse/amqp/SyncRequestClient.java, admin/k8s-api/src/main/java/io/enmasse/k8s/api/KubeUtil.java, router/qdrouterd.conf.template, router/run_qdr.sh, templates/include/enmasse-instance-infra.jsonnet, templates/include/qdrouterd.jsonnet, templates/include/router.jsonnet, templates/include/storage-template.jsonnet, templates/install/kubernetes/enmasse.yaml, templates/install/openshift/enmasse.yaml
This is a workaround for allowing the address controller to perform the health check against the router. Ideally this should be part of a component running inside the standard address space (standard-controller or whatever), but this 'hack' is needed for the health check to work with keycloak deployments.
I've added comments in some places that explains the 'hack' and reason for it. 
This fixes issue #242  though I'd like to do a manual run to verify that the issue has been fixed before merging.
=> Use TLS when connecting to router for address health check

systemtests/src/main/java/enmasse/systemtest/KeycloakClient.java, systemtests/src/main/java/enmasse/systemtest/amqp/AmqpClientFactory.java, systemtests/src/main/java/enmasse/systemtest/mqtt/MqttClientFactory.java, systemtests/src/test/java/enmasse/systemtest/AnycastTest.java, systemtests/src/test/java/enmasse/systemtest/BroadcastTest.java, systemtests/src/test/java/enmasse/systemtest/QueueTest.java, systemtests/src/test/java/enmasse/systemtest/TestBase.java, systemtests/src/test/java/enmasse/systemtest/TopicTest.java, systemtests/src/test/java/enmasse/systemtest/mqtt/PublishTest.java
For authentication tests, it  would be useful to be able to create clients for multiple protocols in the same test. Rather than inheriting the capability from the test case parent, expose client support as 2 alternative client factories that can be called by tests.
=> Refactor framework to support creating both AMQP and MQTT clients in the same test

address-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, address-controller/src/test/java/io/enmasse/controller/standard/AddressControllerTest.java, address-model-lib/src/main/java/io/enmasse/address/model/Address.java, address-model-lib/src/main/java/io/enmasse/address/model/AddressResolver.java, k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapAddressApi.java
This fixes an issue in the address controller where a previously deleted
address may re-appear if the controller loop is running during the
delete.
This fixes #433
=> Ensure deleted addresses are not recreated

Jenkinsfile, systemtests/src/test/java/io/enmasse/systemtest/auth/AuthenticationTest.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/jms/TopicTest.java
- Jenkins timeout increased due to failing on 'timeout reached'
=> Durable Subscribers in jms.TopicTest renamed to be unique for each test

address-controller/src/main/java/io/enmasse/controller/ControllerHelper.java, address-controller/src/main/java/io/enmasse/controller/ControllerOptions.java, address-controller/src/main/java/io/enmasse/controller/Main.java, address-controller/src/main/java/io/enmasse/controller/common/Kubernetes.java, address-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java, address-controller/src/test/java/io/enmasse/controller/ControllerHelperTest.java, address-model-lib/src/main/java/io/enmasse/config/LabelKeys.java, templates/include/address-controller.jsonnet, templates/include/enmasse-kubernetes.jsonnet, templates/include/enmasse-template.jsonnet, templates/install/deploy-openshift.sh, templates/install/kubernetes/enmasse.yaml, templates/install/openshift/enmasse.yaml
An address controller may optionally be configured with an 'ENVIRONMENT'
environment variable (available through OpenShift templates). Each
namespace created by a controller is labeled with the same environment,
ensuring that a controller will only touch namespaces with for its own
environment.
This fixes #474
=> Add environment parameter to controller to support multiple controllers in a cluster

.travis/upload-artifacts.sh, address-controller/src/main/java/io/enmasse/controller/api/v1/http/HttpAddressRootService.java, address-controller/src/main/java/io/enmasse/controller/api/v1/http/HttpAddressService.java, address-controller/src/main/java/io/enmasse/controller/api/v1/http/HttpAddressSpaceService.java, address-controller/src/main/java/io/enmasse/controller/api/v1/http/HttpHealthService.java, address-controller/src/main/java/io/enmasse/controller/api/v1/http/HttpRootService.java, address-controller/src/main/java/io/enmasse/controller/api/v1/http/HttpSchemaService.java, address-controller/src/main/java/io/enmasse/controller/api/v1/http/HttpV1RootService.java, address-controller/src/main/resources/swagger.json, address-controller/src/test/java/io/enmasse/controller/HTTPServerTest.java, address-controller/src/test/java/io/enmasse/controller/auth/AuthInterceptorTest.java, agent/lib/address_ctrl.js, agent/test/address_ctrl.js, agent/www/help.html, documentation/common/configuring-using-restapi.adoc, documentation/service_admin/installing-kubernetes.adoc, documentation/service_admin/installing-openshift.adoc, systemtests/src/main/java/io/enmasse/systemtest/AddressApiClient.java, templates/include/address-controller.jsonnet, templates/include/api-service.json, templates/include/restapi-route.jsonnet, templates/install/kubernetes/addons/external-lb.yaml, templates/install/kubernetes/enmasse.yaml, templates/install/openshift/enmasse.yaml
This aligns the API with the format of other custom k8s apis and will make it easier to enable the API aggregator in 3.7
=> Move API paths from /v1 to /apis/enmasse.io/v1

agent/www/assets/css/enmasse.css
- Removes the mdash to the left of the short description help text on the Create Address wizard. 
- Removes the headings on the Create Address wizard review page.
=> Tweaks to the add address wizard styles

address-controller/src/main/java/io/enmasse/controller/Controller.java, address-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java, address-model-lib/src/main/java/io/enmasse/address/model/Endpoint.java, address-model-lib/src/main/java/io/enmasse/address/model/v1/AddressSpaceV1Deserializer.java, address-model-lib/src/main/java/io/enmasse/address/model/v1/AddressSpaceV1Serializer.java, address-model-lib/src/main/java/io/enmasse/address/model/v1/Fields.java, address-model-lib/src/main/java/io/enmasse/config/AnnotationKeys.java, agent/www/help.html, documentation/common/prerequisites-kubernetes.adoc, documentation/getting_started/kubernetes.adoc, documentation/service_admin/installing-kubernetes.adoc, templates/include/address-controller.jsonnet, templates/include/enmasse-kubernetes.jsonnet, templates/include/enmasse-template.jsonnet, templates/install/kubernetes/addons/external-lb.yaml, templates/install/kubernetes/enmasse.yaml, templates/install/openshift/cluster-roles.yaml
This attempts to fix the broken Ingress support, which has become more broken after moving to HTTPS for
our endpoints (Ingress doesnt support TLS passthrough).
Instead, on kubernetes, expose services using LoadBalancer, which works nicely with minikube as it will expose these using NodePort. For
production deployments, type=LoadBalancer is what you'd typically want so I think this makes the kubernetes use case much better.
=> Replace use of Ingress with LoadBalancer for kubernetes

agent/lib/auth_service.js, agent/lib/authz.js, agent/lib/console_server.js, agent/lib/registry.js, agent/lib/utils.js, agent/test/console_server.js, agent/testlib/mock_authservice.js, agent/www/components/addresses/addresses.html, agent/www/components/addresses/addresses_ctrl.js, agent/www/shared/address_service.js
Based on keycloak groups returned by auth service. Enabled through KEYCLOAK_GROUP_PERMISSIONS env var. Being a member of address-space-admin group provides full access. Being a member of address-space-monitor provides read only access to all data. Being a member of view_<address-name> provides read only access to the address in question (no wildcards yet). User not in either address-space-admin or address-space-monitor can only see their own connections.
=> simple authorization for console 

keycloak/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/SaslAuthenticator.java, keycloak/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/ScramSaslAuthenticator.java, keycloak/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/ScramSha1SaslServerMechanism.java, keycloak/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/ScramSha256SaslServerMechanism.java, keycloak/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/ScramSha512PasswordHashProviderFactory.java, keycloak/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/ScramSha512SaslServerMechanism.java, keycloak/sasl-plugin/src/main/resources/META-INF/services/org.keycloak.credential.hash.PasswordHashProviderFactory
Despite the large diff, all I'm really doing here is factoring the `ScramSaslAuthenticator` out of the SHA1 mechanism, and reusing it with the new mechanisms.
=> Add support for SCRAM-SHA-256 and SCRAM-SHA-512

keycloak/src/main/sh/init-keycloak.sh, keycloak/src/main/xsl/addKeyStore.xsl, keycloak/src/main/xsl/addSaslPlugin.xsl, keycloak/src/main/xsl/removeFileLogging.xsl
saxon is only available from the optional repository, which isn't available for productized images.
xsltproc is already available in the rhel image for modifying standalone.xml.  Using it, instead of having a productized build of saxon made available.
=> replaced saxon with xsltproc

keycloak/runlocal.sh, keycloak/src/main/sh/start-keycloak.sh, keycloak/src/main/xsl/addSaslPlugin.xsl, templates/include/auth-service.jsonnet, templates/install/kubernetes/addons/standard-authservice.yaml, templates/install/openshift/addons/standard-authservice.yaml
To keep mount points for the upstream and downstream templates consistent, created a certificate directory in /opt/enmasse.  Note: /opt/[product], is the recommended directory for ce images.
=> Common cert deploy directory.

systemtests/src/main/java/io/enmasse/systemtest/GlobalLogCollector.java, systemtests/src/main/java/io/enmasse/systemtest/Kubernetes.java, systemtests/src/test/java/io/enmasse/systemtest/TestBase.java
when name space is deleted then previous log from restarted pods is stored into log with following structure: ${NAMESPACE}.${POD-NAME}.terminated.log within ${NAMESCAPE} folder
=> NEW functionality for storing logs of restarted pods

amqp-utils/src/main/java/io/enmasse/amqp/Artemis.java, artemis/shutdown-hook/src/main/java/enmasse/broker/prestop/TopicMigrator.java, queue-scheduler/src/main/java/io/enmasse/queue/scheduler/ArtemisAdapter.java
This bug caused colocated queues to get created as multicast addresses,
which in turn causes unexpected creation of temporary queues for
clients.
This fixes #720
=> Use correct routing type when creating queues

address-controller/src/main/java/io/enmasse/controller/ControllerHelper.java, k8s-api-testutil/src/main/java/io/enmasse/k8s/api/TestSchemaApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapSchemaApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/SchemaApi.java
@grs It currently still copies all the resource definitions, but I think that is ok.
=> Only copy address space plan and referred plans

systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/bases/clients/MsgPatternsTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/web/ChromeWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/web/FirefoxWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/marathon/ChromeWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/marathon/FirefoxWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/marathon/WebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/clients/proton/java/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/clients/proton/python/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/clients/rhea/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/ChromeWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/FirefoxWebConsoleTest.java
- 'get web browser drivers' moved into TestBase
- standard clients test(testMessageSelectorTopic, testTopicSubscribe) enabled for rhea, proton(java, python)
=> NEW TestBase - method for check count of subscribers via console

artemis/config_templates/artemis.profile, artemis/config_templates/brokered/broker.xml, artemis/utils/bin/launch.sh, k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapSchemaApi.java, templates/include/brokered-space-infra.jsonnet, templates/install/kubernetes/enmasse.yaml, templates/install/openshift/enmasse.yaml
* Put non-AMQP protocols over the same port as other protocols
* Expose broker console in brokered address space
=> Brokered space improvements

artemis/sasl-delegation/src/main/java/io/enmasse/artemis/sasl_delegation/SaslGroupBasedSecuritySettingsPlugin.java
This allows OpenWire clients to work out of the box
=> Permit senders to open non-durable queues

agent/bin/agent.js, agent/lib/broker_controller.js, agent/lib/internal_address_source.js, agent/lib/ragent.js, agent/lib/router.js, agent/lib/utils.js, agent/test/broker_controller.js, agent/test/internal_address_source.js, agent/test/ragent.js, agent/test/utils.js, agent/testlib/mock_broker.js, agent/testlib/mock_resource_server.js, artemis/config_templates/standard/broker_queue_colocated.xml, standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, templates/include/admin.jsonnet, templates/install/kubernetes/enmasse.yaml, templates/install/openshift/enmasse.yaml
Ignore addresses in the Pending and Terminating phases.
Have 'pool' brokers connect to agent rather than queue-scheduler.
=> Configure connected brokers where indicated by broker-id annotation.

templates/include/address-controller.jsonnet, templates/include/admin.jsonnet, templates/include/brokered-space-infra.jsonnet, templates/install/kubernetes/enmasse.yaml, templates/install/openshift/enmasse.yaml
This ensures that only 1 instance of these components may exist, to avoid any conflicts of 2 components running at the same time during upgrades.
=> Set Recreate strategy for controller components

templates/install/common.sh
The 'old' approach was from before kubectl supported creating tls secrets via the command line. Later versions of kubectl (1.6 here) appears to support this.
=> Remove need for base64 when creating secret

templates/Makefile, templates/include/auth-service.jsonnet, templates/include/subserv.jsonnet
When generating the templates:
- allow to specify the node command to use
- allow to specify the keycloak home dir
- allow to specify if you are adding extra script to keycloak-plugin
=> Variable substition for generating the templates for keycloak-plugin and subserv

documentation/service_admin/installing-kubernetes.adoc, documentation/service_admin/monitoring-kubernetes.adoc, documentation/service_admin/monitoring-openshift.adoc
This PR fixes the links from the index for "installing on Kubernetes" and "monitoring" sections. Currently they always reference the OpenShift ones (even for Kubernetes).
=> Fix wrong references from the index

systemtests/src/test/java/io/enmasse/systemtest/standard/authz/AuthorizationTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/StandardWebConsoleTest.java
This prevents CI from creating many brokers that the test strictly doesn't need
=> Use pooled brokers by default in webconsole tests

agent/test/internal_address_source.js
On 0.17.2 release branch, address order in internal events is creation order (on master it is now ordered by address). This change fixes the order for the release branch which does not have the ordering change from master.
=> Fix for mocha tests on release branch (not relevant for master)

keycloak-controller/src/main/java/io/enmasse/keycloak/controller/KeycloakManager.java, keycloak-controller/src/main/java/io/enmasse/keycloak/controller/Main.java
This fixes an issue where the controller would receive all address
space creation events before keycloak was fully running and accepting
connections. The update to keycloak would then get lost. Instead, introduce a more frequent interval in which keycloak is checked against the latest known set of address spaces.
@grs @kornys I believe this will the 'unable to find realm within timeout' failures we've seen in the systemtests.
=> Check keycloak realm existence every 30 seconds by default

systemtests/src/test/java/io/enmasse/systemtest/bases/TestBaseWithShared.java, systemtests/src/test/java/io/enmasse/systemtest/common/api/AddressControllerApiTest.java
- because we use dummy address for faster deploy of new destinations and
this test remove all addresses (include dummy-address)
- delete all addresse moved into common.api tests
=> restapi tests modified to not delete all address in addr-space

address-controller/src/main/java/io/enmasse/controller/common/StandardAuthenticationServiceResolver.java
@rgodfrey  This makes it easier to connect to the standard authservice through
alternative hosts and ports if needed
=> Allow standard authservice host port to be overridden

agent/bin/agent.js, agent/lib/artemis.js, agent/lib/broker_address_settings.js, agent/lib/broker_controller.js, agent/lib/ragent.js, agent/lib/router.js, agent/lib/utils.js, agent/test/ragent.js, agent/testlib/mock_broker.js, agent/testlib/mock_resource_server.js, standard-controller/src/main/java/io/enmasse/controller/standard/RouterStatus.java
(This requires using a connector per address, created on the broker after the queue is created,
in order to ensure the autolinks do not fire before address settings and queue have been created
explicitly, as triggering the links will cause implicit creation of queue)
=> Set per-address address settings to limit max size

Jenkinsfile, systemtests/scripts/wait_until_agent_ready.sh
Jobs in Jenkins are triggered before all commands from "Manage file" are finished, so we need to check that all required dependencies are installed. At the bottom of "Manage file" is now "touch /tmp/agent_ready" command and Jenkinsfile is extended about wait until this file exists.
=> NEW script for wait until machine is completely prepared

documentation/service_admin/installing-kubernetes.adoc, documentation/service_admin/installing-openshift.adoc, templates/install/ansible/roles/address_controller/tasks/main.yml
Ensure that `address-space-definitions.yaml` is applied before deploying the address controller.
This prevents errors in address controller about the ConfigMap `address-space-definitions` not being found.
=> Fix address controller deployment order

agent/lib/router.js, agent/test/ragent.js, router/amqp-kafka-bridge.snippet, router/colocated-topic.snippet, router/qdrouterd.conf.template, router/subscriptions.snippet
closes #1096 (and is decoupled from a newer router image, just focusing on earlier deprecations).
=> change from dir to direction

k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapAddressSpaceApi.java, templates/include/address-space.yaml, templates/install/common.sh, templates/install/resources/templates/address-space.yaml
This introduces a separator char between namespace and AddressSpace name in the name of the AddressSpace ConfigMap in order to prevent potential naming clashes.
The dot has been chosen as separator char since it isn't allowed in a K8s namespace name.
Usage of the AddressSpace ConfigMap naming scheme has been adopted to places where such a ConfigMap gets created.
=> Change naming of AddressSpace ConfigMap

address-space-controller/src/main/java/io/enmasse/controller/Main.java, templates/install/deploy.sh
With this, OAuth can be disabled for the agent console login. This is used for the deploy.sh Kubernetes deployment where the external Keycloak URL cannot be determined in all cases.
(Corresponding changes to the manual installation guide will go in a separate PR.)
=> Add optional oauthDisabled entry in keycloak-config (#1197)

keycloak-controller/src/main/java/io/enmasse/keycloak/controller/Main.java, templates/include/auth-service.jsonnet, templates/install/ansible/roles/standard_authservice/tasks/main.yml, templates/install/deploy.sh, templates/install/resources/standard-authservice/controller-deployment.yaml
This allows oc cluster up to work out of the box with Keycloak + OpenShift Identity Provider without specifying public-hostname.
=> Fallback to kubernetes service URL if the well-known URI is localhost

templates/install/deploy.sh
This change shows an explicit list of options on cases where options are available and also always falls back to showing the usage help when an argument is unknown.
=> Improve usage output of deployment script

templates/install/common.sh
The change to lower-case [here](https://github.com/EnMasseProject/enmasse/commit/51dfa8ef5bc69f8136d699a3e84b0512a6fd82d2#diff-e108f3c1f5c3a556bda94d26ad0a313e) wasn't in the PR that got merged later.
=> Fix missing to-lowercase change in create_address_space

documentation/getting_started/kubernetes.adoc, documentation/getting_started/openshift.adoc, documentation/service_admin/installing-manual.adoc
Kubernetes documentation: Add info on how to set the enmasse namespace as the default namespace after having created the namespace. This is needed as the following kubectl commands don't have the `--namespace` param.
=> Docs: Add info about setting default k8s ns; fix typos/formatting

k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapAddressSpaceApi.java
This fixes an empty AddressSpaceList being returned by the API-Server (#1275)
=> Fix missing namespace label on AddressSpace ConfigMap (#1275)

systemtests/src/test/java/io/enmasse/systemtest/bases/clients/ClientTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/clients/artemis/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/clients/openwire/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/clients/proton/java/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/clients/proton/python/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/clients/rhea/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/clients/proton/java/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/clients/proton/python/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/clients/rhea/MsgPatternsTest.java
This will fix issue when receivers are not attached to queue when sender tries to send messages in testRoudRobinReceiver.
=> Wait for subscribers in roundRobin test

api-server/src/main/java/io/enmasse/api/server/HTTPServer.java, api-server/src/main/java/io/enmasse/api/v1/AddressApiHelper.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpAddressService.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpAddressServiceBase.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpAddressSpaceService.java, api-server/src/test/java/io/enmasse/api/v1/http/HttpAddressSpaceServiceTest.java, api-server/src/test/java/io/enmasse/api/v1/http/HttpNestedAddressServiceTest.java, k8s-api-testutil/src/main/java/io/enmasse/k8s/api/TestAddressApi.java, k8s-api-testutil/src/main/java/io/enmasse/k8s/api/TestAddressSpaceApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/AddressApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/AddressSpaceApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapAddressApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapAddressSpaceApi.java
These handlers are called when a namespace is deleted and the kubernetes namespace controller attempts to delete all resources in the namespace
=> Issue 1334 delete handler

api-common/src/main/java/io/enmasse/api/common/UnprocessableEntityException.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpAddressService.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpAddressServiceBase.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpAddressSpaceService.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpNestedAddressService.java, api-server/src/test/java/io/enmasse/api/v1/http/HttpAddressSpaceServiceTest.java, api-server/src/test/java/io/enmasse/api/v1/http/HttpNestedAddressServiceTest.java, k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapAddressApi.java
Validates given object name (of address/addressSpace) and corresponding URL part for POST/PUT requests on the "addresses" and "addressspaces" endpoints.
Changed resources:
`/apis/enmasse.io/v1alpha1/namespaces/{namespace}/addresses`
POST: added check that address.getName is set - prevents NPE
PUT /{addressName}: added check that address.getName is set - prevents NPE
PUT /{addressName}: added check that address.getName matches {addressName}
`/apis/enmasse.io/v1alpha1/namespaces/{namespace}/addressspaces`
PUT {addressSpace}: added checks for existence of addressSpace.getName, matching of addressSpace.getName with {addressSpace}.
`/apis/enmasse.io/v1alpha1/namespaces/{namespace}/addressspaces/{addressSpace}/addresses`
PUT {addressName}: added checks for existence of address.getName, matching …
=> Add extra validation for POST/PUT api-server requests

mqtt-gateway/src/main/java/enmasse/mqtt/MqttGateway.java, mqtt-gateway/src/test/java/enmasse/mqtt/MockMqttGatewayTestBase.java, mqtt-gateway/src/test/java/enmasse/mqtt/PublishTest.java, templates/include/address-space-definitions.yaml, templates/install/resources/address-space-controller/address-space-definitions.yaml
=> Allow max message size to be configured for MQTT and set it to 128K by default

agent/test/ragent.js
Increasing the timeouts below fixes errors we got when running the ragent tests.
=> Increase timeout for ragent tests

systemtests/src/test/java/io/enmasse/systemtest/common/api/CustomResourceDefinitionAddressesTest.java
fix for NPE in io.enmasse.systemtest.common.api.CustomResourceDefinitionAddressesTest.io.enmasse.systemtest.common.api.CustomResourceDefinitionAddressesTest
=> use BeforeEach instead of BeforeAll for set up address-space

artemis/config_templates/brokered/broker.xml, templates/include/address-space-definitions.yaml, templates/install/resources/address-space-controller/address-space-definitions.yaml
This adopts the usage of the broker related BROKER_MEMORY_LIMIT and GLOBAL_MAX_SIZE settings to the brokered address space.
=> Make broker memory settings configurable in brokered address space

systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/standard/AnycastTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/clients/rhea/MsgPatternsTest.java
@lulf this issue was fixed in cli-rhea and published in 2.1.4, so I have enabled test and it passed.
=> Enable fixed cli-rhea test and testRouterScale

templates/include/cluster-roles/tenant-edit.yaml, templates/include/cluster-roles/tenant-view.yaml
This should allow users having the 'edit' and 'admin' roles inside a project to be able to create address spaces when this role is granted to a group like system:authenticated.
=> Add label to roles to auto-add them to edit and view roles

systemtests/scripts/ocenv.sh
minor fix for ocenv.sh variable setting
=>     Fix to default variable setting in ocenv.sh (missing colons)

Makefile, Makefile.java.mk, agent/pom.xml, agent/src/assembly/unix-dist.xml, agent/www/index.html
- Can set the name that appears in the console using -Dapplication.display.name for maven or by setting the env_variable PROJECT_DISPLAY_NAME for make.
- Defaults to EnMasse
Signed-off-by: Vanessa <vbusch@localhost.localdomain>
=> Allow the name that is displayed in the console, to be set/overridden during the build

standard-controller/src/main/java/io/enmasse/controller/standard/AddressProvisioner.java, standard-controller/src/test/java/io/enmasse/controller/standard/AddressProvisionerTest.java
This change allows to use manually specify the cluster ID for sharded
queues so that it is possible to work around issue #1149.
=> Allow to manually specify the cluster ID (#1449)

api-server/src/main/java/io/enmasse/api/server/HTTPServer.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpOpenApiService.java
This prevents an error in the log for the API server when registered
with the kubernetes master on version 1.10 an newer.
=> Add /openapi/v2 handler for api server

api-server/Dockerfile, api-server/src/main/resources/log4j.properties, service-broker/Dockerfile
Allow enabling of debug logging for API server by adding corresponding log4j.properties and remove superfluous LOG_LEVEL setting from Dockerfiles.
=> Add log4j.properties for api server

router-metrics/Dockerfile, router-metrics/router-metrics.py
This ensures that even if router connection is broken, it will reconnect on next attempt. It is assumed that the cost of creating a new connection for each query is not significant since the collection does not happen frequently.
Fixes #1488
=> Ensure that client connects on each metric collection

api-common/src/main/java/io/enmasse/api/common/DefaultExceptionMapper.java, api-common/src/test/java/io/enmasse/api/common/DefaultExceptionMapperTest.java
This fixes #1396.
Looking at K8s source, status 422 seems to be the only status used in K8s API but not defined in `javax.ws.rs.core.Response.Status` - therefore adding a special case for it here.
=> Fix handling of 422 status responses from K8s api server (#1396)

templates/install/deploy.sh
This change will let the deploy script fail in case of any command returning a non-zero result.
For example I did run into an issue with `openssl` not properly creating a key/cert. However the script continued to run, spitting out occasional errors about missing files. The initial error of openssl failing was hard to spot.
With `set -e` the script would abort when the `openssl` call failed, leaving this the last message on the console and not create further resources.
=> Fail on any error in the script

user-api/src/main/java/io/enmasse/user/model/v1/UserSpec.java, user-api/src/test/java/io/enmasse/user/model/v1/UserModelTest.java
@kornys Should probably add a systemtest that sets different values for .metadata.name and .spec.username and uses underscores in .spec.username.
=> Allow underscores in .spec.username field

agent/lib/auth_service.js
For some reason, the agent unit tests started failing locally on master for no apparent reason. This PR fixes the build, but it might not be the correct fix.  I'm wondering what the underlying cause could be.
=> Handle case where error can be undefined

address-model-lib/src/main/java/io/enmasse/address/model/KubeUtil.java, address-space-controller/src/main/java/io/enmasse/controller/CreateController.java, address-space-controller/src/main/java/io/enmasse/controller/EndpointController.java, address-space-controller/src/main/java/io/enmasse/controller/TemplateInfraResourceFactory.java, address-space-controller/src/test/java/io/enmasse/controller/EndpointControllerTest.java, systemtests/src/main/java/io/enmasse/systemtest/AddressSpace.java
This should fix the systemtest failures. The certificates are taking longer than necessary to create due to 'stale' address space objects going through the controller loop. This ensures that the address space 'object' is always updated to the 'desired' state.
=> Always update endpoints at start of controller loop

address-model-lib/src/main/java/io/enmasse/address/model/CertSpec.java, address-model-lib/src/main/java/io/enmasse/address/model/v1/AddressSpaceV1Deserializer.java, address-model-lib/src/test/java/io/enmasse/address/model/v1/address/SerializationTest.java, address-space-controller/src/main/java/io/enmasse/controller/ControllerChain.java, address-space-controller/src/main/java/io/enmasse/controller/CreateController.java, address-space-controller/src/main/java/io/enmasse/controller/EndpointController.java, address-space-controller/src/main/java/io/enmasse/controller/StatusController.java, k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapSchemaApi.java
Ensure that cert spec is always copied and not reused between address space
This fixes a bug when 2 address spaces are created within the same controller loop cycle, which caused the cert secret names to be wrong. This broke the brokered SmokeTest in Jenkins.
=> Issue 1692 enforce cert secret name copy

systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/web/ChromeWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/web/FirefoxWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/ChromeWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/FirefoxWebConsoleTest.java
* tests if filtering addresses in console is valid with regex
* if non valid regex is used the console shows an alert (positive)
test passes
=> New webconsole systemtest  doTestFilterAddressWithRegexSymbols

systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/web/ChromeWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/web/FirefoxWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/ChromeWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/FirefoxWebConsoleTest.java
* tests that the alert that appears when using invalid regex to filter addresses, behaves consistently once it had been cleared, and more invalid regex attempts are used.
=> new systemtest for web console, doTestRegexAlertBehavesConsistently

systemtests/src/main/java/io/enmasse/systemtest/selenium/resources/AddressWebItem.java
Fixes test regression `io.enmasse.systemtest.*.web.FirefoxWebConsoleTest#testMessagesMetrics` caused by changes made in c4f33b5bf0 related to screen labels on address tab.
=> Fix test regression caused by c4f33b5bf0 (screen labels on address tab)

api-common/src/main/java/io/enmasse/api/common/DefaultExceptionMapper.java
This aligns the response with that given by Kubernetes API server for 409 responses. I'm not sure if there is a case where we should set it to 'Conflict', but I think this will be correct for most foreseeable cases.
=> Return AlreadyExists instead of Conflict for 409 response codes

pom.xml
Avoid dependency classed as Alpha.
=> Bump jboss-logging-processor from 2.0.0.Alpha2 to 2.0.1.Final 

service-broker/pom.xml
originating from service-broker module (keycloak-user-api dependency duplicate).  No functional change.
=> Fix duplicate declaration of version error from Maven

pom.xml
Avoids dependency on 3.2.1, which is associated with CVE-2017-15708.
=> Dependency manage commons-collections to 3.2.2

Jenkinsfile-upgrade
@kornys I think this is the best workaround for now. We can remove this once we are done with 0.24.x
=> Run pre-upgrade systemtests with plans compatible with 0.23.1

address-model-lib/src/main/java/io/enmasse/address/model/AddressResolver.java, address-model-lib/src/main/java/io/enmasse/address/model/AddressSpaceResolver.java, address-model-lib/src/main/java/io/enmasse/address/model/AddressType.java, address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceController.java, address-space-controller/src/main/java/io/enmasse/controller/MigrationController.java, standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java
In order for users to upgrade from 0.23.0 to 0.24.0 out of the box, the following PR is needed. It will change the address space plan and address plan names to the appropriate new name if they don't exist.
=> Migrate default plans

agent/pom.xml, pom.xml, systemtests/pom.xml
All shaded JARs now include:
```
/licenses.xml    - summary that lists the licenses of all dependencies used by the artefact
/licenses/*      - license body (txt/html)
/THIRD-PARTY.txt - identifies the license associated with each third party dependency
```
=> Include license bodies, license summary (xml) and third-party info

jenkins-functions.groovy
Should avoid situation where we have no artifact when deployment fails and no junit results are available.
=> Fix allow archive empty dirs

systemtests/src/test/java/io/enmasse/systemtest/bases/clients/ClusterClientTestBase.java
should fix brokered mqtt internal test.
=> Decrease timeout between send and receive mqtt

agent/create-license-metadata.sh, agent/pom.xml, agent/src/assembly/unix-dist.xml
Uses license-reporter to generate a license.xml for both agent and the console.  These artefacts
are then merge into a single file that is included in the distribution.  license-reporter is also
used to create files containing the text of the license themselves. These too are include in the
distribution artefact.
Note that unlike the Maven license-plugin, license-reporter does not actually download the license.  Instead it takes it from the npm module itself.
=> Create license metadata for agent too

templates/grafana/030-Deployment-grafana.yaml
Fixes this kind of error when deploying Grafana in Kubernetes:
> error validating "030-Deployment-grafana.yaml": error validating data: ValidationError(Deployment.spec.template.spec.containers[0]): unknown field "readOnly" in io.k8s.api.core.v1.Container; if you choose to ignore these errors, turn validation off with --validate=false
=> Fix error in grafana deployment spec

HACKING.md, agent/create-license-metadata.sh, agent/licenses.xsl, agent/pom.xml, licenses.xsl, pom.properties, pom.xml, systemtests/pom.xml, templates/Makefile
Move licenses.xml to within the licenses/ directory.
Generate a per-module `licenses.html` providing a human readable summary and link to the remote/local license.
Allow license artifact production to be surpressed (for reasons of speed during a developer's build/test cycle).
=> More license metadata automation

templates/address-space-controller/020-ConfigMap-address-space-definitions.yaml, templates/address-space-controller/050-Deployment-address-space-controller.yaml, templates/api-server/050-Deployment-api-server.yaml, templates/kube-state-metrics/030-Deployment-kube-state-metrics.yaml, templates/prometheus/030-Deployment-prometheus.yaml, templates/service-broker/050-Deployment-service-broker.yaml, templates/standard-authservice/050-Deployment-keycloak-controller.yaml
`serviceAccount` is deprecated in K8s 1.7 already.
=> Replace deprecated serviceAccount field with serviceAccountName

templates/api-server/030-RoleBinding-apiserver-authentication-reader.yaml
This is to allow applying the EnMasse installation instructions multiple times (in multiple namespaces).
=> Add namespace suffix to name of role binding

Makefile.common, templates/Makefile
(Assumes coreutils installed from brew or MacPorts)
=> Make templates/Makefile run on Mac OS X

pom.xml
Avoid configuration management problems (release 3.0.3 is not tagged).
=> Downgrade kubernetes-model from 3.0.3 to 3.0.2

address-model-lib/src/main/java/io/enmasse/address/model/AddressSpace.java, address-model-lib/src/main/java/io/enmasse/address/model/CertSpec.java, address-model-lib/src/main/java/io/enmasse/address/model/EndpointSpec.java, address-space-controller/src/main/java/io/enmasse/controller/auth/CertBundleCertProvider.java, address-space-controller/src/test/java/io/enmasse/controller/auth/CertBundleCertProviderTest.java, agent/npm-shrinkwrap.json, api-server/src/main/java/io/enmasse/api/v1/http/HttpAddressSpaceService.java, api-server/src/test/java/io/enmasse/api/v1/http/HttpAddressSpaceServiceTest.java
This allows address spaces to have annotations, labels and endpoints replaced. The certBundle endpoints also switch the certificate in the secret, allowing users to perform certificate rotation without downtime.
=> Patch secret if cert bundle has changed

k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapAddressApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/ResourceChecker.java, standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, standard-controller/src/main/java/io/enmasse/controller/standard/AddressProvisioner.java, standard-controller/src/main/java/io/enmasse/controller/standard/RouterStatus.java
@lulf I took an alternative approach to solving this problem to one that was discussed a few weeks ago.  I tried caching state locally but I couldn't get an implementation that wasn't ugly.   This approach guards the standard controller from acting on an address if its representation is stale.  This staleness may occur owing to the relative actions of the refresh/watchers.  This approach is also appealing because should we start to support patching of addresses (say to allow the user to add their own annotations), then this approach will mean that the standard controller cannot overwrite these changes.
I left some commented out code only for discussion purposes.  My intention is to remove it.
Also there are some analogous changes which I think need to be reflected into the address-space …
=> Prevent the StandardController from overwriting address configmaps

k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapAddressApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapAddressSpaceApi.java, k8s-api/src/test/java/io/enmasse/k8s/api/ConfigMapAddressApiTest.java, k8s-api/src/test/java/io/enmasse/k8s/api/ConfigMapAddressSpaceApiTest.java
Also make use of openshift API the same between ConfigMapAddressApi/ConfigMapAddressSpaceApi implementations.
=> Remove redundant calls to inNamespace() when interacting with openshift API.

api-server/src/main/java/io/enmasse/api/v1/AddressApiHelper.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpAddressServiceBase.java, api-server/src/test/java/io/enmasse/api/v1/AddressApiHelperTest.java
Currently, when creating many address at once, the entire list of addresses on the server were fetched for every address created. Furthermore, the addressSpaceApi was recreated for every new address too (which resulted in an additional config map read.
=> Avoid n addr list retrievals when creating n addresses

Jenkinsfile, Jenkinsfile-tests, Jenkinsfile-upgrade
@lulf I enabled mailing notification when master build failed + fix for upgrade pipeline issue with script for download released enmasse.
=> Enable mailing when master build failed

templates/address-space-controller/020-ConfigMap-broker-prometheus-config.yaml
Non-greedy regex pattern matching should be used in the Prometheus JMX exporter patterns. As of now with greedy matching, the `address` label contains more than just the address .
For example in `artemis_consumer_count`:
**JMX exporter output with greedy regex (incorrect)**
`artemis_consumer_count{address="myqueue\", subcomponent=queues, routing-type=\"anycast\", queue=\"myqueue",broker="broker-pooled-c84ir342pj-0",} 1.0`
(the `address` label contains `myqueue", subcomponent=queues, routing-type="anycast", queue="myqueue`)
Full relevant output of the jmx exporter: [jmx-exporter-output.txt](https://github.com/EnMasseProject/enmasse/files/2603351/jmx-exporter-output.txt)
**JMX exporter output with non-greedy regex (correct)**
`artemis_consumer_count{address="myqueue",broker="c84ir342pj-0",} …
=> Non-greedy regex for JMX exporter expressions

pom.xml
I know this is convenience thing for Eclipse users, but still it helps getting an overview if projects are healthy by not having everything "red" in the workspace.
=> Exclude plugins from the m2e lifecycle

agent/bin/agent.js, agent/bin/launch_node.sh, agent/www/app.module.js, agent/www/components/addresses/addresses_ctrl.js, agent/www/index.html, agent/www/shared/address_service.js
This PR adds a modal dialogue that pops up if the connection to the server is lost.   If the connection reestablishes itself the modal will automatically pop-down.  Scenarios where thus might happen are if the admin pod was restarted, or the user's internet connection dropped temporarily. The user currently has no way to dismiss the dialogue and cannot interact with the app whilst it is popped up.
My original intent was to offer a [Logout] button.  However, currently the `/logout` url relies on relies on the server (agent) being available.
I think an improvement would be to allow the infra config to specify a site specific `logoutUrl`.  Currently we just redirect back to keycloak (or openshift) but this probably is not too helpful in terms of workflow. The deployer would configure …
=> Issue 1595 - display warning if connection to the server is lost

address-space-controller/Dockerfile, address-space-controller/src/main/resources/log4j.properties, agent/lib/log.js, api-server/Dockerfile, api-server/src/main/resources/log4j.properties, artemis/Dockerfile, artemis/plugin/src/main/resources/logging.properties, artemis/plugin/src/main/sh/launch.sh, keycloak-controller/Dockerfile, keycloak-controller/src/main/resources/log4j.properties, keycloak-plugin/Dockerfile, keycloak-plugin/src/main/configuration/logging.properties, keycloak-plugin/src/main/configuration/standalone.xml, mqtt-gateway/Dockerfile, mqtt-gateway/src/main/resources/log4j.properties, mqtt-lwt/Dockerfile, mqtt-lwt/src/main/resources/log4j.properties, router/Dockerfile, service-broker/Dockerfile, standard-controller/Dockerfile, standard-controller/src/main/resources/log4j.properties, templates/standard-authservice/050-Deployment-keycloak.yaml, topic-forwarder/Dockerfile, topic-forwarder/src/main/resources/log4j.properties
* Minor difference for agent where component comes before log level due
to debug library needing this.
* Use UTC/GMT for all component logs
Closes #2003
=> Use same logging patterns for all components

jenkins-functions.groovy
@lulf the problem in archiveArtifact is not caused by opened file but it is reported bug for this plugin, so I used try block to eliminate build failure (because artifacts are store despite error appeard).
=> Fix store artifacts

agent/lib/router_stats.js
Could potentially make tests unstable if they show up in the connection tab in the console
=> Dont show router metrics in connection tab

jenkins-functions.groovy
@lulf I removed archoveArtifacts it is deprecated and without updated, I switched back to archive which is updated and it allows empty archive as well
=> Use archive instead archiveArtifacts in pipeline

templates/address-space-controller/020-ConfigMap-address-space-definitions.yaml, templates/address-space-controller/020-ConfigMap-standard-broker-definitions.yaml, templates/address-space-controller/050-Deployment-address-space-controller.yaml, templates/alertmanager/030-Deployment-alertmanager.yaml, templates/api-server/050-Deployment-api-server.yaml, templates/grafana/030-Deployment-grafana.yaml, templates/kube-state-metrics/030-Deployment-kube-state-metrics.yaml, templates/none-authservice/050-Deployment-none-authservice.yaml, templates/prometheus/030-Deployment-prometheus.yaml, templates/service-broker/050-Deployment-service-broker.yaml, templates/standard-authservice/050-Deployment-keycloak-controller.yaml, templates/standard-authservice/050-Deployment-keycloak.yaml
This matches the form used by Openshift node groups and makes it easier to have multiple roles on the same node during openshift install.
=> Rename node affinity labels

templates/address-space-controller/020-ConfigMap-address-space-definitions.yaml, templates/address-space-controller/020-ConfigMap-standard-broker-definitions.yaml
The upgrade test requires the data in persistent volumes
=> Added persistent volume back for the broker data dir

templates/alertmanager/010-Service-alertmanager.yaml, templates/alertmanager/030-Deployment-alertmanager.yaml, templates/grafana/010-ConfigMap-grafana-config.yaml, templates/prometheus/010-Service-prometheus.yaml, templates/prometheus/030-Deployment-prometheus.yaml
Fixed a bug in the services for Prometheus and Alertmanager so Grafana
can access them by the correct ports
=> Fixed services for Prometheus, Alertmanager

systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/SmokeTest.java
- added try catch as setAddresses was throwing an Execution exception rather than an 
AddressAlreadyExists exception (fault with test not addressApi)
=> enabled testCreateAlreadyExistingAddress (#346 fixed)

address-space-controller/src/main/java/io/enmasse/controller/StatusController.java, address-space-controller/src/main/java/io/enmasse/controller/common/Kubernetes.java, address-space-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java, address-space-controller/src/test/java/io/enmasse/controller/StatusControllerTest.java
* Check statefulsets in addition to deployments
* Less strict: require >= 1 ready pod per deployment/statefulset to pass status check.
* Only check components belonging to address space
=> Improve address space status check

address-space-controller/src/main/java/io/enmasse/controller/CreateController.java, address-space-controller/src/test/java/io/enmasse/controller/CreateControllerTest.java
* Filter addresses client side for now, performance will be "impacted" if > 1 address space exists within the same namespace as it will retrieve addresses for all address spaces within the namespace. We should consider adding labels to addresses and migrate to use those after version + 1.
* Add unit test for quota check.
=> Fix quota calculation

artemis/utils/bin/launch.sh
I think this could fix the master build, but upgrade may still not work.
I'm really starting to be in favor of just dropping all scripts from artemis/ and using startup scripts exclusively from broker-plugin.
=> Replace the correct gc parameter

api-common/pom.xml, api-server/pom.xml
The dependency seems to be unused.  Dependency is used in service-broker, this remains, although its usage could easily be eliminated.
=> Remove jackson-module-jsonschema-from-api-server and api-common.

broker-plugin/sasl-delegation/pom.xml, pom.xml
* Vertx (3.5.3 -> 3.6.2)
* Netty (4.1.25.Final -> 4.1.30.Final)
* Qpid Proton-J (0.27.3 -> 0.34.0) versions
Also Qpid JMS test dependency (0.31.0 -> 0.40.0)
=> Bump Vertx/Netty/Qpid Proton-J dependencies

.owasp/project-suppressions.xml, pom.xml
Also update suppressions for misidentified products.
=> Bump CVE detection tool dependency-check-maven-plugin from 3.3.2 to 4.0.2.

.travis.yml
This gives me a "boost" of about two minutes … 
… but I think it makes things more clear in the logs.
=> Speed up travis build by skipping initial "mvn install"

.travis.yml
It looks like Oracle JDK 8 is already gone when using the Xenial image at travis, so I would suggest to use OpenJDK instead. Even for the current build.
=> Switch build to openjdk

systemtests/scripts/run_test_kubernetes.sh
The removed call to `kubectl` is actually failing on all travis jobs:
~~~
…
+export KUBERNETES_NAMESPACE=enmasseci
+KUBERNETES_NAMESPACE=enmasseci
+kubectl exec -ti busybox -- nslookup kubernetes.default
Error from server (NotFound): pods "busybox" not found
+kubectl create namespace enmasseci
namespace "enmasseci" created
++kubectl config current-context
+kubectl config set-context minikube --namespace=enmasseci
…
~~~
=> let the script fail on errors, drop non working command

systemtests/src/main/java/io/enmasse/systemtest/TestUtils.java, systemtests/src/main/java/io/enmasse/systemtest/TimeoutBudget.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBaseWithShared.java
This change waits after the update of the address space that the
resource version changes, only after that does it make sense to wait
to wait for the readiness of the address space.
What happened was that the update came, and immediately it was checked
that the address space is ready, which succeeded, but for the old state.
Then the test progressed, but actually ran into an "unready" address
space.
=> Fix the PlanTest failing due to missing endpoint

systemtests/src/main/java/io/enmasse/systemtest/Minikube.java, systemtests/src/main/java/io/enmasse/systemtest/executor/Executor.java
We have 2 commands for minikube so there is no need to create CmdClient for minikube so I just replaced the usage of Process and ProcessBuilder with our Executor for commands.
=> use generic command executor for minikube commands

pom.xml
Currently the S2I Java build is broken as the Maven compiler plugin 3.1 is being used (current is 3.8). And 3.1 fails building on Java 11, and Java 11 is in the fabric8 s2i image.
=> Fix compiler issue when running Maven with Java 11

pkg/controller/iotproject/managed.go
This change switches a few more locations to selectively update
the created resources, by manipulating the required fields.
That leaves other fields untouched and prevent unnecessary updates.
=> Selectively update generated resources, instead of overwriting them

.travis.yml
Split up the travis build into two jobs, running in parallel.
The first job is the existing configuration, and the second job runs the S2I builder to ensure "buildability" on the sources.
The job split is done in order to reduce the chance to run into the 50 minute job limit of travis.
=> Split the travis build and run a second build, validating S2I

broker-plugin/sasl-delegation/src/main/java/io/enmasse/artemis/sasl_delegation/SaslDelegatingLogin.java, keycloak-user-api/src/main/java/io/enmasse/user/keycloak/KeycloakUserApi.java, keycloak-user-api/src/test/java/io/enmasse/user/keycloak/KeycloakUserApiTest.java
The broker sasl plugin has been updated to handle the same wildcard
syntax as the dispatch router.
=> Remove group wildcards special to brokered address space

pom.xml
Upgrade other librariee in Jackson suite to the same version.
Note: jackson-databind 2.9.6 was vulnerable to the following CVE (all deserialisation vulnerabilities).  It is not actually believed that versions of EnMasse that included jackson-databind 2.9.6 were vulnerable, this is because additional libraries were required to exploit the vulnerability (such as Apache Axis), which are not included.
CVE-2018-14718
CVE-2018-14719
CVE-2018-14720
CVE-2018-14721
CVE-2018-19360
CVE-2018-19361
CVE-2018-19362
=> Upgrade jackson-databind from 2.9.6 to 2.9.8.

keycloak-plugin/sasl-plugin/pom.xml
In order to silence spurious report of CVE-2018-11771 during CVE scan.  No functional change - openshift-restclient-java was a provided dependency and not shipped.
=> Keycloak plugin: Exclude transitive provided openshift-restclient-java

pom.xml
in selenium-firefox-driver.  No production functional change.
@enmasse-ci run tests testcase=*ConsoleTest
=> Bump Selenium from 3.14.0 to 3.141.59 to avoid test dependency vulnerability

systemtests/scripts/wait_until_up.sh
Shows the time until the system tests for for the pods to come up, but in a human readable form
=> Also show human readable timestamp

.travis.yml
It looks like a merge issue, a duplicate installation of asciidoctor.
We also don't need glide on the travis build, as we only rely on the
vendor folder.
=> Fix duplicate install, and drop installation of glide

pkg/controller/authenticationservice/standard.go
This will only happen if JVM settings are not overriden explicitly.
=> Derive keycloak JVM memory settings from container memory

address-space-controller/src/main/java/io/enmasse/controller/TemplateInfraResourceFactory.java, pkg/controller/authenticationservice/authenticationservice_controller.go, pkg/util/install/utils.go, templates/enmasse-operator/020-Role-enmasse-operator.yaml
@ctron Wdyt about not reassigning the label selector if it is already set? If you try to the label selectors, the Kubernetes API will complain about it being immutable, so this prevents an upgrade where labels change to work for instance.
@k-wall Various fixes to handle upgrades, deleting keycloak-controller, better error handling in address space controller
=> Upgrade fixes

pom.xml
Synchs with the vertx version already already used by the IoT modules.
=> Bump vertx 3.6.2 to 3.6.3 

Makefile.common, enmasse-controller-manager/Makefile, iot/iot-gc/Makefile, iot/qdr-proxy-configurator/Makefile
Ensures that when building EnMasse on platforms such as Mac OS X, the executables created run in the containers that target linux/amd64.
=> Use cross compile options when linking Go executables destined for images

api-model/src/main/java/io/enmasse/address/model/AddressPlanStatus.java, api-model/src/main/java/io/enmasse/address/model/AddressResolver.java, api-model/src/main/java/io/enmasse/address/model/AddressSpaceStatus.java, api-model/src/main/java/io/enmasse/address/model/Status.java, standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, standard-controller/src/main/java/io/enmasse/controller/standard/AddressProvisioner.java, standard-controller/src/test/java/io/enmasse/controller/standard/AddressControllerTest.java, standard-controller/src/test/java/io/enmasse/controller/standard/AddressProvisionerTest.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java
Storing plan name and assumed credits in status allows the
standard-controller to detect if the credits of a plan was changed, and
perform the necessary migration.
=> Add actual plan to address status

address-space-controller/src/main/java/io/enmasse/controller/CreateController.java
This is a small improvement to endpoints:
1) Don't require mqtt endpoint to be specified when infra config does not enable mqtt
2) Instead of throwing error on missing services, create the default endpoints for those services
Overall this is more intuitive for developers creating address spaces
Fixes #2430
=> Improve developer experience with default service automatically created

.jenkins/Jenkinsfile, .jenkins/jenkins-functions.groovy, .travis/build-only.sh, .travis/build.sh, HACKING.md, Makefile, Makefile.common, iot/pom.xml, pom.xml
* Require docker_build to be explicitly invoked
* Use podman on travis and parallelize build
This avoids a deadlock where Golang docker images depended on java build
to complete, and java build depended on golang build to complete. Make
docker_build a standalone target also allows for parallelizing
docker_build invocations, which should work well with non-daemon
container tools such as podman
=> Split docker build from default target

iot/pom.xml
It omision was causing versions:set to omit its children
=> Include the iot-application-base in iot/pom.xml list of submodules.

api-server/src/main/resources/swagger.json
I've backported this to release-0.27. This causes kubectl error when creating resources on Kubernetes.
=> Add missing type for array

address-space-controller/src/main/resources/templates/standard-space-infra.yaml
This makes sure the router is not killed if it is not configured within
liveness probe interval. Only readiness check should check that
router is configured. This bug was introduced when switching to http
based probes.
=> Perform liveness check on statically configured listener

.gitignore, .travis/common.sh, .travis/test-iot.sh, systemtests/scripts/run_test_kubernetes.sh, systemtests/src/main/java/io/enmasse/systemtest/cmdclients/CmdClient.java, systemtests/src/main/java/io/enmasse/systemtest/cmdclients/KubeCMDClient.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/iot/SimpleK8sDeployTest.java
So it turns out the system tests should have have worked. However the failure to detect "non-ready" containers in the `TestUtils` reported "OK" for the test, although the test was not ok.
The cause for the test to fail was that the hostnames in the plain k8s inter service certificates where generated with `enmasse-infra` instead of `enmasseci`, which is required for running on travis.
=> Fix IoT system tests

address-space-controller/pom.xml
Fixes build noise...  No functional change.
```
[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.enmasse:address-space-controller:jar:0.27-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.jboss.resteasy:resteasy-jackson2-provider:jar -> duplicate declaration of version (?) @ io.enmasse:address-space-controller:[unknown-version], /Users/keith/go/src/github.com/enmasseproject/enmasse/address-space-controller/pom.xml, line 76, column 17
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
```
=> fix maven build warning (duplicate dependency)

Makefile.java.mk
For instance,
`make -C address-space-controller  SKIP_TESTS=true`
Now builds just:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] EnMasse
[INFO] api-model
[INFO] metrics-api
[INFO] k8s-api
[INFO] keycloak-user-api
[INFO] k8s-api-testutil
[INFO] address-space-controller
```
rather than all the world.
=> Trim the Maven reactor of superfluous modules when performing a single module Make build.

cmd/qdr-proxy-configurator/configurator.go, cmd/qdr-proxy-configurator/main.go
Also, lower the number of threads to 1 … which should be enough for
a sidecar.
=> Properly handle errors on qdr-proxy-configurator startup

doc-utils/parse.py
When python3 is set as default python executable the build fails because this script use some py2 syntax.
This ensure the script is ran with the appropriate python version.
=> enforce python2 to avoid errors when default is python3

api-model/src/main/java/io/enmasse/iot/model/v1/AddressConfig.java, api-model/src/main/java/io/enmasse/iot/model/v1/AddressSpaceConfig.java, api-model/src/main/java/io/enmasse/iot/model/v1/AddressesConfig.java, api-model/src/main/java/io/enmasse/iot/model/v1/IoTConfigList.java, api-model/src/main/java/io/enmasse/iot/model/v1/IoTCrd.java, api-model/src/test/java/io/enmasse/iot/model/v1/IoTProjectTest.java
It looks like the changes to the addressspace and address configuration are missing on the Java side. As is the `IoTConfigList`, which is required when working with the fabric8 client.
=> Align the Java API with the Go API

k8s-api/src/main/java/io/enmasse/k8s/api/KubeSchemaApi.java
This makes it less error prone to define invalid plans. For instance, authentication services will still be loaded if you have invalid plans, and plans that are valid will still be available.
=> Allow using schema if some parts are missing

pkg/qdr/qdmanage.go, pkg/qdr/qdmanage_test.go
Currently when the configurator tries do delete an item, it may happen that the item is not there. In this case it currently fails to resync the configuration, as deleting returns "not found" as an error.
=> Don't fail deleting an item that is already gone

api-server/src/main/java/io/enmasse/api/server/ApiServer.java, api-server/src/main/java/io/enmasse/api/server/HTTPHealthServer.java, api-server/src/main/java/io/enmasse/api/server/HTTPServer.java, api-server/src/test/java/io/enmasse/api/server/HTTPServerTest.java
This fixes an issue where the health check could potentially be blocked by API handler threads
=> Split health and metrics reporting into its own server

service-broker/src/main/java/io/enmasse/osb/HTTPServer.java, service-broker/src/main/java/io/enmasse/osb/ServiceBroker.java, service-broker/src/main/java/io/enmasse/osb/api/OSBServiceBase.java, service-broker/src/main/java/io/enmasse/osb/api/ServiceMapping.java, service-broker/src/main/java/io/enmasse/osb/api/bind/OSBBindingService.java, service-broker/src/main/java/io/enmasse/osb/api/console/HttpConsoleService.java, service-broker/src/main/java/io/enmasse/osb/api/provision/OSBProvisioningService.java, systemtests/src/main/java/io/enmasse/systemtest/ability/ExecutionListener.java, systemtests/src/main/java/io/enmasse/systemtest/apiclients/AddressApiClient.java, systemtests/src/main/java/io/enmasse/systemtest/apiclients/ApiClient.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/GlobalConsolePage.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/OpenshiftWebPage.java, systemtests/src/main/java/io/enmasse/systemtest/utils/AddressSpaceUtils.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebConsolePlansTest.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/api/ApiServerTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/api/CustomResourceDefinitionAddressSpacesTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/api/CustomResourceDefinitionAddressesTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/catalog/ServiceCatalogWebTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/plans/PlansTest.java, systemtests/src/test/java/io/enmasse/systemtest/marathon/MarathonTestBase.java
Add namespace parameter when creating address space using service
catalog, as the user does not have permissions to the address space
stored in the global enmasse namespace
Fixes #2649
=> Add namespace parameter in service catalog

agent/lib/auth_utils.js, agent/lib/cookie_decoder.js
The intent was that if cookie decode fails for any reason, we fall back on the OAuth/OIDC.  The implemented logic was duff.
Also remove redundant refresh cookie handling on SSO path.
=> Correct cookie decoder error handling

pom.xml
EnMasse does not make use of the SocketServer and ServerSocketReceiver feature affected by the CVE, so was probably not impacted.
=> Bump logback from 1.0.13 to 1.2.3 to avoid report of CVE-2017-5929.

address-space-controller/src/main/resources/templates/standard-space-infra.yaml
Moves http health check port to 7770 to allow qdmanage and qdstat to
work on 7777 as intended.
=> Use AMQP only on 7777

agent/www/shared/address_service.js
This change should fix an occasional test fail seen during system test runs.  It affects only the client (browser) side.  I theory is that the test failure is a race condition likely on slow hardware, where the server side manages to close the connection before the client's thread of control has had chance to install the connection listeners.
=> install connection event listeners before opening the connection

bundle/pom.xml
Change affects only the bundle module for now (no functional change).
=> Bump maven-assembly-version to avoid suspected bundling issue with symlinks

systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/common/catalog/ServiceCatalogWebTest.java
Most likely cause for sporadic test failure is that the controller has not yet fully actioned the removal of the user.  Test now awaits the user to be gone before proceeding.
=> Fix sporadically failing ServiceCatalogWebTest

pkg/controller/consoleservice/consoleservice_controller.go
Correct defect that would prevent the creation  of OAuthClient object if the route did not yet have an ingress.
=> Correct console operator error handling

api-model/src/main/java/io/enmasse/user/model/v1/UserAuthorization.java, keycloak-user-api/src/main/java/io/enmasse/user/keycloak/KeycloakUserApi.java, keycloak-user-api/src/test/java/io/enmasse/user/keycloak/KeycloakUserApiTest.java
Authorization rules containing a '_' character will not be read back
correctly when doing a GET for a MessagingUser. This change adds a unit
test to verify the issue and a fix that ensures the entire address is
preserved when decoding the group name from Keycloak.
=> Fix readback of authorization rules

pkg/controller/consoleservice/consoleservice_controller.go, pkg/util/install/utils.go
We saw a case in an OCP4 test environment where the sso-cookie secret didn't get automatically generated.  This changes the reconcile algorithm so that if that situation were to occur, the secret would get generated on the next pass.
Also changed the reconciler so that if it itself updates the consoleservice CR it suppresses the requeue to prevent a needless iteration (that usually resulted in errors in the logs).
=> Further console operator improvements

console/console-init/oauth-proxy/bin/init.sh, console/console-init/ui/src/components/MessagingInstances/MessagingInstance/Enmasse/CreateAddressSpace/Steps/Configuration/ConfigurationForm.test.js, console/console-init/ui/src/components/MessagingInstances/MessagingInstance/InstanceLoader.js, console/console-init/ui/src/index.html, pkg/controller/consoleservice/consoleservice_controller.go
used variable to replaced calls to 'apis/project.openshift.io/v1/' to decide if openshift vs kubernetes.
=> Modified way of detecting if we are kubernetes

documentation/modules/proc-applying-infra-config.adoc
Changes the version field in one example of infraestructure configuration to be consistent with the rest of examples and just because it's the correct way.
=> Version between quotes in infra config example

api-common/src/main/java/io/enmasse/api/auth/AuthInterceptor.java, documentation/modules/proc-minimal-service-configuration.adoc, templates/csv/enmasse.clusterserviceversion.yaml
* Use same names for resources as in the documentation
* Fix an issue with the default service configuration
=> Fix inconsistent use of names in CSV

address-space-controller/pom.xml, address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceController.java, api-common/src/main/java/io/enmasse/api/common/OpenShift.java, api-server/src/main/java/io/enmasse/api/server/ApiServer.java
The Go path already uses this environment variable so it seems reasonable for Java to do the same.
=> Use ENMASSE_OPENSHIFT as a short-circuit to determine the presence of OpenShift

pkg/controller/consoleservice/consoleservice_controller.go, pkg/util/install/utils.go
and define HTTPD pod readiness/liveness probes.
The use of the `Recreate` strategy was unintentional.  I copied/pasted the code from elsewhere and didn't review sufficiently.
=> Fix #2759: Use RollingUpdate for console redeployments

pom.xml
Includes PROTON-2037 which has been seen to impact EnMasse use-cases.
=> Bump Proton-J from 0.31.0 to 0.33.0. 

broker-plugin/plugin/src/main/resources/logging.properties
The audit logging is quite noisy for the EnMasse use-case.
=> Turn off Artemis  audit logging (new in 2.7+) in default broker config

console/console-init/ui/src/components/MessagingInstances/MessagingInstances.js
fixes #2763 by hiding the paginator when no elements.
Next step is to add an empty state
=> Hide the pagination when there are no instances in the table

systemtests/src/main/java/io/enmasse/systemtest/GlobalLogCollector.java, systemtests/src/test/java/io/enmasse/systemtest/common/certs/CertProviderTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/QueueTest.java
Currently, during the scale down tests, the logs corresponding to the brokers that are removed as the queue is scaled down are never captured.  This change captures the full set of broker log prior to each scale up/down to close that gap.
=> Improve logging in QueueTest#testScaledown to help understand test failure

systemtests/src/main/java/io/enmasse/systemtest/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/iot/HttpAdapterClient.java, systemtests/src/main/java/io/enmasse/systemtest/iot/IoTProjectTestContext.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/bases/IoTTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/bases/IoTTestBaseWithShared.java, systemtests/src/test/java/io/enmasse/systemtest/iot/MultipleProjectsTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/control/CommandAndControlTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/http/HttpAdapterTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/mqtt/MqttAdapterTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/registry/DeviceRegistryTest.java
Adds a few fixes for iot tests with the new usage of fabric8 clients in systemtests
Also adds new test MultipleProjectsTest which for now runs a simple workload over http-adapter of 2 iot projects concurrently.
The idea with this test and more similar tests to come is to verify the behaviour of the platform in a more real case because the iot infrastructure is shared between tenants
=> Test of multiple iotprojects

iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/CredentialsKey.java, iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/RegistrationKey.java, iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/RegistryCredentialObject.java, iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/RegistryTenantObject.java
using the protostream annotations and unsing Infinispan's ProtoStreamMarashaller does the serialization work, there is no need to extend serializable.
=> remove uneeded serializable in Infinispan Device Registry

.travis.yml, .travis/find-qdrouterd-base-versions.sh, Makefile.env.mk
This adds a small check to travis to check if the qdrouter-base versions are aligned. Because currently aren't. Again.
=> Validate router version alignment

k8s-api/src/main/java/io/enmasse/k8s/api/KubeSchemaApi.java
Version 0.26 has a version number in InfraConfig..  And we should upgrade even if we see it.
=> Upgrade the address space, even if there is the version number is in the config

address-space-controller/src/main/java/io/enmasse/controller/StatusController.java
Handles the upgrade case, where previously, phase would be left unset.
=> Fix #2865: Ensure phase is set, even if it  is not already

standard-controller/src/main/java/io/enmasse/controller/standard/BrokerStatusCollector.java
Issue #2876: the queue's original broker status was already going correctly into Migrating.   The issue was that check for a drained broker assumes that the broker *is drained* if it is not running (io.enmasse.controller.standard.BrokerStatusCollector#getQueueMessageCount) .  This is not safe.  During an upgrade the old broker is upgraded to the new image, so it does restart.
The controller was checking queue depth whilst the broker is down, and then prematurely deleting the broker. This lead to be the message loss.
=> Issue 2876 don't garbage collect offline broker pods

systemtests/src/main/java/io/enmasse/systemtest/amqp/AmqpClient.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/common/CommonTest.java
On Jenkins, we occasional saw this test fail with an SSLHandshakeException.  I think what is happening is the service has not yet realised that the pod has become ready.
(test change only)
=> Prevent sporadic failures from CommonTest#testMessagePersistent

standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, standard-controller/src/main/java/io/enmasse/controller/standard/AddressProvisioner.java, standard-controller/src/main/java/io/enmasse/controller/standard/Kubernetes.java, standard-controller/src/main/java/io/enmasse/controller/standard/KubernetesHelper.java, standard-controller/src/test/java/io/enmasse/controller/standard/AddressProvisionerTest.java
#2880 describes a problem whereby when upgrading a broker statefulset the patch is rejected by the server owing to either a correct JSON patch produced by zjson-patch or a server side bug (not clear which).
This code temporarily works around the issue. It does this by on encountering the PATCH error, applying only the failed statefulset without the environment variables. On the next cycle, the address with still be noticed as not upgraded. The resources will be regenerated and applied.
The desire is that this code is temporary until the root cause established and properly resolution applied.
=> Fix #2880 - workaround issue patching statefulset environment variables

pom.xml, systemtests/src/main/java/io/enmasse/systemtest/ability/TestWatcher.java
@ctron this allow us to hadle exceptions in before and after methods, so we can collect logs immediately when iot project or addressspace creation failed.
=> Handle exceptions in lifecycle methods

ansible/roles/monitoring-operator/tasks/main.yml
I found an error installing monitoring using ansible. The error was concretely when installing kube-state-metrics because it depends on `ServiceMonitors` crd which is installed by monitoring-operator which was installed after kube-state-metrics. So basically what I did to fix it is to move the installation of kube-state-metrics after monitoring-operator and wait until `ServiceMonitors` crd is available.
The command to try this would be like :
`ansible-playbook templates/build/enmasse-latest/ansible/playbooks/openshift/deploy_all.yml -i systemtests/ansible/inventory/systemtests.inventory --extra-vars "{\"namespace\": \"enmasse-infra\", \"monitoring_namespace\": \"enmasse-monitoring\", \"monitoring_operator\": \"true\", \"monitoring\": \"true\" }"`
=> fix ansible monitoring-operator installation

api-model/src/main/java/io/enmasse/address/model/KubeUtil.java, api-model/src/test/java/io/enmasse/address/model/v1/address/KubeUtilTest.java
Also applied resource requirements and env var to initcontainers too. Bolstered unit tests.
=> Fix #2864: Allow liveness/readiness probe timeouts to be configured from the infraconfigs

api-model/src/main/java/io/enmasse/address/model/CoreCrd.java
The deserialiser registration used incorrect KIND names for some of our API extensions.  I haven't seen this cause a defect.
=> Fix  KubernetesDeserializer registration (Java)

pkg/controller/consoleservice/consoleservice_controller.go, systemtests/src/test/java/io/enmasse/systemtest/standard/web/FirefoxWebConsoleTest.java
I needed to switch from watching the routes to watching the configmaps backing the addressspaces.  My preference would have been to watch to address spaces directly, but this is currently not possible as our API server does not yet have that ability.
=> Fix #2855: Respect custom routes when building oauth redirects

templates/csv/enmasse.clusterserviceversion.yaml
Update the olm clusterserviceversion
- Fix missing role (relates to changes made in #2857 but not reflected here)
- remove consoleservice from the example.  the consoleservice operator spontaneously creates the CR, so creating it explicity is supefluous.
- remove addressspaceschema from example. you can't create these, standard and brokered are baked in
=> Upd OLM csv

pkg/controller/iotconfig/file_device_registry.go
This also includes a few formatting changes automatically applied by `go fmt`.
=> Use re-create deployment strategy for file based device registry

systemtests/src/main/java/io/enmasse/systemtest/cmdclients/KubeCMDClient.java
Captures 
```
LAST SEEN              FIRST SEEN             COUNT     NAME                                                        KIND           SUBOBJECT                                   TYPE      REASON                   SOURCE                     MESSAGE
2019-07-05T15:01:04Z   2019-07-05T15:01:04Z   1         api-server.15ae8aeb897f47d4                                 Deployment     <none>                                      Normal    ScalingReplicaSet        deployment-controller      Scaled up replica set api-server-7b5d9df774 to 1
```
Rather than:
```
LAST SEEN   FIRST SEEN   COUNT     NAME                             KIND      SUBOBJECT   TYPE      REASON           SOURCE                MESSAGE
4s          4h           569       standard-controller.1729922031   Broker …
```
=> Capture event LAST SEEN and FIRST SEEN as absolute time-stamps:

systemtests/src/test/java/io/enmasse/systemtest/bases/mqtt/MqttPublishTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/mqtt/PublishTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/mqtt/PublishTest.java
Adds a PublishTest class for the tests of brokered address space and shares the logic with the already existent for the standard address space
=> Mqtt tests in brokered addressspace

systemtests/src/test/java/io/enmasse/systemtest/bases/web/GlobalConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/common/plans/PlansTest.java
Decreases the messages sent in `PlansTest#testMessagePersistenceAfterAutoScale` because of problems with timeouts in openshift 4 tests.
Fixes a bug in `GlobalConsoleTest#doTestSwitchAddressSpacePlan` that made `GlobalConsoleTest#doTestConnectToAddressSpaceConsole` fail
=> suite improvements and fixes

api-model/src/main/java/io/enmasse/admin/model/v1/AuthenticationServiceSpecStandard.java, api-model/src/main/java/io/enmasse/admin/model/v1/AuthenticationServiceSpecStandardStorage.java, api-model/src/main/java/io/enmasse/admin/model/v1/AuthenticationServiceSpecStandardType.java, systemtests/src/test/java/io/enmasse/systemtest/common/upgrade/UpgradeTest.java
The bundle upgrade test was failing when upgrading from 0.28.  This was because the bundle doesn't define a persistent standard authentication service, so the users were lost.   The test is changed to replace the standard authentication service if it is not persistent.
=> Ensure bundle upgrade test uses persistent-claim

systemtests/src/test/java/io/enmasse/systemtest/common/upgrade/UpgradeTest.java
Test failed on CI with:
`Failure executing: POST at: https://10.0.132.97:8443/apis/admin.enmasse.io/v1beta1/namespaces/enmasse-infra/authenticationservices. Message: object is being deleted: authenticationservices.admin.enmasse.io "standard-authservice" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=admin.enmasse.io, kind=authenticationservices, name=standard-authservice, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=object is being deleted: authenticationservices.admin.enmasse.io "standard-authservice" already exists, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={})`
=> Handle 409 - object is being deleted: authenticationservices already exists.

templates/Makefile
Allow the use of `${VERSION}` as a replacement in OLM metadata.  It will carry the two part release number from `pom.properties`.
=> Allow ${VERSION} substitution in OLM metadata

systemtests/src/main/java/io/enmasse/systemtest/messagingclients/AbstractClient.java, systemtests/src/test/java/io/enmasse/systemtest/bases/clients/ClusterClientTestBase.java
Previously the consumer was using a timeout of 200ms, which I think is too low in a stressed environment.  Also improved the logging for diagnostic purposes (Test change only).
=> Increase timeout on receive MsgPatternsInternalTest

systemtests/src/test/java/io/enmasse/systemtest/bases/clients/ClientTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/common/plans/PlansTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/QueueTest.java
Reduces the amount of messages sent in some tests to deal with the slowness in ocp4 testing and fixes an sporadic NPE that happened in recent test runs.
=> reduces the messages sent in some tests and fix a possible NPE

HACKING.md, pom.xml
=> Upgrade org.codehaus.mojo:license-maven-plugin version to 2.0.0

pkg/controller/iotconfig/auth_service.go, pkg/controller/iotconfig/iotconfig_controller.go, pkg/util/cchange/change.go, pkg/util/cchange/change_test.go, pkg/util/install/utils.go
When reconciling fails, it may be that the "config map", holding the inter-service credentials gets updated, without any updates to the authentication service. In this case the authentication service will not pick up the changes, as Hono services do require a restart by design to pick up changes.
This change calculates a hash from the relevant parts of the configuration and sets this hash to an annotation on the pod spec template. So if the config changes, the hash changes and so does the annotation. A changed annotation on the pod spec template will cause a new deployment and thus a pod re-start.
=> Re-deploy auth service in case the permissions change

systemtests/src/test/java/io/enmasse/systemtest/bases/clients/ClientTestBase.java
Increase the timeout to 10sec. from the default 200ms.  
To solve: org.opentest4j.AssertionFailedError: Expected 50 received messages ==> expected: <50> but was: <10> 
=> Increase the timeout to 10sec. from the default 200ms

systemtests/src/main/java/io/enmasse/systemtest/mqtt/MqttUtils.java, systemtests/src/test/java/io/enmasse/systemtest/bases/mqtt/MqttPublishTestBase.java
Increase timeouts to solve:
java.lang.AssertionError: Incorrect count of messages received
Expected: is <3> but: was <2>
=> Increase timeouts to solve MQTT PublishTest sporadic failure.

broker-plugin/plugin/src/main/sh/launch-broker.sh
The downstream broker image (unlike the upstream one), defines AMQ_RESET_CONFIG=false at the Docker level.  Unconditionally apply true unless an ENMASSE specific variable is set overriding it.
=> Unconditionally set AMQ_RESET_CONFIG unless overridden by ENMASSE scoped variable

systemtests/src/test/java/io/enmasse/systemtest/brokered/SmokeTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/QueueTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/SmokeTest.java
Increases some timeouts for the smoke tests because in openshift 4 test runs are slower
=> increase timeouts in smoke tests

systemtests/src/main/java/io/enmasse/systemtest/GlobalLogCollector.java, systemtests/src/main/java/io/enmasse/systemtest/Kubernetes.java, systemtests/src/test/java/io/enmasse/systemtest/common/monitoring/MonitoringTest.java
collects the logs of all pods in `enmasse-monitoring` namespace in case MonitoringTest fails
=> collect logs in monitoring namespace in case MonitoringTest fails

agent/lib/console_server.js
Now defaults to `30s` but can be reconfigured/disabled using environment variable `CONSOLE_AMQP_IDLE_TIMEOUT`.
=> Turn on AMQP heartbeating between console (browser) and console-server

systemtests/src/main/java/io/enmasse/systemtest/selenium/page/GlobalConsolePage.java
adds more screenshot taking in order to have better tracing of global console tests when creating address spaces
=> more screenshots in GlobalConsolePage.createAddressSpace

systemtests/src/test/java/io/enmasse/systemtest/bases/web/GlobalConsoleTest.java
Currently the test waits only 30s, which might be insuffiicent for the resources to spin-up and, due to the polling nature of the console, to detect the state change.
=> Wait longer for addressspace to be ready

systemtests/src/test/java/io/enmasse/systemtest/bases/common/PersistentMessagesTestBase.java
Attempt to fix timing issue where not all pods are started in ocp4
=> Persistent message test: Wait for all pods to be running (or terminated), before starting

systemtests/src/main/java/io/enmasse/systemtest/GlobalLogCollector.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/SeleniumManagement.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/SeleniumProvider.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java
Currently for the Firefox tests, the console logs aren't collected owing to [this issue in the driver](https://github.com/mozilla/geckodriver/issues/284).  This change utilises a [Firefox specific workaround](https://github.com/mozilla/geckodriver/issues/284#issuecomment-458305621) that directs console.log() etc. to the process's stdout. We then collect it from the pod's logs.
=> Capture the logs from the Firefox console during Selenium tests

systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/web/ChromeWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/brokered/web/FirefoxWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/ChromeWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/standard/web/FirefoxWebConsoleTest.java
The issue was a race condition within the test itself.  The test  is changed to explicitly await the no rbac dialogue box.
=> FirefoxWebConsoleTest#testCannotOpenConsolePage fails sporadically

systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/bases/common/PersistentMessagesTestBase.java
The initial pod count in the test is increased by 1, due to having 2 consoles.
Added a wait until there is only 1 console pod, before getting intial pod count.
=> Added wait for console rolling update to complete

systemtests/src/main/java/io/enmasse/systemtest/SystemtestsKubernetesApps.java, systemtests/src/main/java/io/enmasse/systemtest/ability/TestWatcher.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/ExternalClientsExtension.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/SeleniumProvider.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBaseWithShared.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/WebConsoleTest.java
In some test environments, the sender/receivers/connectors terminate whilst the test was still making observations about the state of the UI.  I've changed the timeouts of sender/receivers/connectors to avoid the problem and used try/finally in a couple of places to be assured on clean-up.
=> Fix unreliable WebConsoleTest tests

agent/bin/agent.js, agent/lib/internal_address_source.js
This defect meant that all existing addresses were considered modified even if they weren't.
This lead to unnecessary reconcilations against all routers and brokers.
=> Correct address allocation equality.

agent/lib/router_config.js
When processing thousands of addresses, the logs become very large owing to the "`Constructing config for queue<queue> allocated to: <broker>` that appears for every queue address for every router reconciliation.
=> Turn down noisy per reconcilation per address logging

agent/lib/qdr.js
This issue occurs if you increase the number of routers beyond 10.  I don't think this is a likely production configuration, but it should not fail as it does right now.
=> Turn off EventEmitter#maxListeners check for router management connections

agent/lib/router_config.js, agent/npm-shrinkwrap.json, agent/package.json
This change limits the number of promises that can be created when create/delete entities on the router.  Previous n promises would be created at once, where n was the number of address defined in the standard address space.
=> Restrict the number of active promises when creating/deleting entities on the routers

systemtests/src/main/java/io/enmasse/systemtest/Kubernetes.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/bases/common/PersistentMessagesTestBase.java
- Wait for the broker pods to begin to restart, before checking if they are up.
=> Fix for randomly failing test: io.enmasse.systemtest.common.BrokeredPersistentMessagesTest#testBrokeredQueue

agent/lib/internal_address_source.js
The address status equality check was out of date.  It considered the `message` field rather than then `messages` array.  I saw a case during testing where the addresses stuck at isReady false, and this was the cause.
=> Correct address status equality check

agent/bin/launch_node.sh
Previously, no account was taken on the container's memory.  This meant that the memory size assumed by node processes (agent, subserv) could be larger than the amount of memory allocated to the container.  This change adjusts the max_old_space_size to a percent (80% by default) of the container.
=> Adjust node max_old_space_size to a percentage of available container memory

agent/lib/broker_controller.js
Analogous with #3095, but for the brokers rather than the routers. 
Fix #3090
=> Restrict the number of active promises when creating/deleting entities on the brokers

systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java
Fix for: StandardPersistentMessagesTest.testTopic
=> Corrected test logic in waitForPodsToTerminate

api-server/src/main/java/io/enmasse/api/v1/AddressApiHelper.java, api-server/src/test/java/io/enmasse/api/server/HTTPServerTest.java, api-server/src/test/java/io/enmasse/api/v1/AddressApiHelperTest.java, k8s-api-testutil/src/main/java/io/enmasse/k8s/api/TestSchemaApi.java, standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, standard-controller/src/test/java/io/enmasse/controller/standard/AddressControllerTest.java
This change improves api server address create performance by almost an order of magnitude when 1000 addresses are defined.
The changes moves the validation of spec.address to standard-controller for the standard address space. For the brokered address space, the validation remains in the api-server, as it would require adding write-back capability to the agent. Future refactoring/consolidation of agent/standard-controller should incorporate this validation.
Fixes #3111
=> Improve api server address create performance

api-server/src/main/java/io/enmasse/api/v1/AddressApiHelper.java, api-server/src/test/java/io/enmasse/api/v1/AddressApiHelperTest.java, standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, standard-controller/src/test/java/io/enmasse/controller/standard/AddressControllerTest.java
This change improves api server address create performance by almost an order of magnitude when 1000 addresses are defined.
The changes moves the validation of spec.address to standard-controller for the standard address space. For the brokered address space, the validation remains in the api-server, as it would require adding write-back capability to the agent. Future refactoring/consolidation of agent/standard-controller should incorporate this validation.
Fixes #3111
=> Backport 0.26: Improve api server address create performance

documentation/common/attributes.adoc, documentation/master-kubernetes.adoc, documentation/modules/con-configuring.adoc, documentation/modules/proc-logging-in-console.adoc
The {imagesdir} attribute is added automatically when using the image reference. The current docs are not showing any images referenced this way.
=> Ensure that images render correctly in doc

api-model/src/main/java/io/enmasse/iot/model/v1/AdapterStatus.java, pkg/apis/iot/v1alpha1/types.go, pkg/controller/iotconfig/adapter.go, pkg/controller/iotconfig/auth.go, pkg/controller/iotconfig/auth_service.go, pkg/controller/iotconfig/auth_test.go, pkg/controller/iotconfig/collector.go, pkg/controller/iotconfig/data.go, pkg/controller/iotconfig/file_device_registry.go, pkg/controller/iotconfig/http_adapter.go, pkg/controller/iotconfig/infinispan_device_registry.go, pkg/controller/iotconfig/iotconfig_controller.go, pkg/controller/iotconfig/lorawan_adapter.go, pkg/controller/iotconfig/mqtt_adapter.go, pkg/controller/iotconfig/sigfox_adapter.go, pkg/util/install/utils.go
* All adapter containers are now called "adapter".
* All code required to be executed per-adapter is now controlled by
an array of adapters.
* A label was added to the device registry, indicating which type it
actually is.
* A duplicate replica assignment was dropped.
* The default logback configuration no longer uses profiles which we
didn't use in the first place.
* Pass enabled status to status section
=> Clean up a few odd things in the IoTConfig controller

agent/lib/internal_address_source.js
This bug caused the readiness info to be stale where the agent believed
readiness was good, but it was in fact reset.
Fixes #3137
=> Update readiness when address is changed

api-server/src/main/resources/swagger.json, documentation/common/restapi-reference.adoc, documentation/design/proposals/bridging_external.adoc
@k-wall @rgodfrey I made some changes to how certs and credentials are specified in the connector. Inspired by https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#define-container-environment-variables-using-configmap-data :)
=> Update proposal and add swagger schema

templates/csv/enmasse.clusterserviceversion.yaml, templates/enmasse-operator/050-Deployment-enmasse-operator.yaml
As a temporary "fix" for #3133, use default memory settings to increase
unlikelyness that the issue will be seen.
=> Bump default limits of operator

address-space-controller/src/main/java/io/enmasse/controller/RouterConfigController.java, address-space-controller/src/main/java/io/enmasse/controller/router/config/Address.java, address-space-controller/src/main/java/io/enmasse/controller/router/config/Connector.java, address-space-controller/src/main/java/io/enmasse/controller/router/config/LinkRoute.java, address-space-controller/src/test/java/io/enmasse/controller/RouterConfigControllerTest.java, api-model/src/main/java/io/enmasse/address/model/AddressSpaceSpec.java, api-model/src/main/java/io/enmasse/address/model/AddressSpaceSpecConnector.java, api-model/src/main/java/io/enmasse/address/model/AddressSpaceSpecConnectorAddressRule.java, api-model/src/main/java/io/enmasse/address/model/AddressSpaceSpecConnectorCredentials.java, api-model/src/main/java/io/enmasse/address/model/AddressSpaceSpecConnectorEndpoint.java, api-model/src/main/java/io/enmasse/address/model/AddressSpaceSpecConnectorTls.java, api-model/src/main/java/io/enmasse/address/model/AddressSpaceStatus.java, api-model/src/main/java/io/enmasse/address/model/AddressSpaceStatusConnector.java, api-model/src/main/java/io/enmasse/address/model/StringOrSecretSelector.java, api-model/src/main/java/io/enmasse/config/AnnotationKeys.java, api-server/src/main/java/io/enmasse/api/v1/http/HttpAddressSpaceService.java, api-server/src/main/resources/swagger.json, documentation/common/restapi-reference.adoc, documentation/design/proposals/bridging_external.adoc, templates/address-space-controller/020-Role-address-space-controller.yaml
Create router connectors and addresses based on address space connector specification.
* Reconcile secrets storing the connector certs
* Update router config based on connectors
* Add generation annotation to statefulset pod template to allow triggering a rolling update when the router config changes.
* Unit test for reconciling secrets and router config
@famartinrh With this PR, it should be possible to write tests to connect to remote brokers and send/receive messages via address space to them. Forwarding will come in another PR.
=> Issue 3150 connector support

address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceController.java, address-space-controller/src/main/java/io/enmasse/controller/ControllerChain.java, address-space-controller/src/main/java/io/enmasse/controller/MetricsReporterController.java, address-space-controller/src/main/java/io/enmasse/controller/RouterStatusController.java, address-space-controller/src/test/java/io/enmasse/controller/ControllerChainTest.java, address-space-controller/src/test/java/io/enmasse/controller/MetricsReporterTest.java
This PR (based #3172) adds support for exposing connector metrics to the address space controller prometheus endpoint.
* Track number of connectors ready, notready and total
* Refactor metrics reporting into its own controller
=> Issue 3150 connector metrics

agent/lib/artemis.js, agent/lib/broker_controller.js, agent/lib/subctrl.js, agent/testlib/mock_broker.js, api-model/src/main/java/io/enmasse/address/model/Address.java, api-model/src/main/java/io/enmasse/address/model/AddressSpec.java, api-model/src/main/java/io/enmasse/address/model/AddressSpecForwarder.java, api-model/src/main/java/io/enmasse/address/model/AddressSpecForwarderDirection.java, api-model/src/main/java/io/enmasse/address/model/AddressStatus.java, api-model/src/main/java/io/enmasse/address/model/AddressStatusForwarder.java, api-model/src/test/java/io/enmasse/address/model/v1/address/AddressTest.java, broker-plugin/amqp-connector/src/main/java/org/apache/activemq/artemis/integration/amqp/AMQPConnectorService.java, broker-plugin/amqp-connector/src/main/java/org/apache/activemq/artemis/integration/amqp/AMQPConnectorServiceFactory.java, broker-plugin/amqp-connector/src/main/java/org/apache/activemq/artemis/integration/amqp/Direction.java, broker-plugin/amqp-connector/src/main/java/org/apache/activemq/artemis/integration/amqp/LinkInfo.java, broker-plugin/amqp-connector/src/main/java/org/apache/activemq/artemis/integration/amqp/LinkInitiator.java, documentation/design/proposals/bridging_external.adoc, standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, standard-controller/src/main/java/io/enmasse/controller/standard/AddressProvisioner.java, standard-controller/src/main/java/io/enmasse/controller/standard/RouterStatus.java, standard-controller/src/main/java/io/enmasse/controller/standard/RouterStatusCollector.java, standard-controller/src/test/java/io/enmasse/controller/standard/AddressControllerTest.java, standard-controller/src/test/java/io/enmasse/controller/standard/AddressProvisionerTest.java
* Doc: Update design doc
* Model: Add classes for forwarder spec and status
* Broker AMQP Connector: Add support for creating links in both directions
* Agent: Add support for creating broker -> router connectors + links based on forwarder definitions
* Standard Controller: Collect forwarder status from routers and report metrics on the number of forwarders in ready vs not ready state.
* Other: Rename Status to AddressStatus
Issue #3150
@famartinrh With this it should be possible to test forwarding of queues and subscriptions as well
=> Add support for address forwarding to standard address space

systemtests/src/main/java/io/enmasse/systemtest/cmdclients/KubeCMDClient.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/api/ApiServerTest.java
this PR adds one test that checks the example cluster role tenant-edit allows or disallows to be able to create an address space
=> add authorization test using tenant-edit example role

api-model/src/main/java/io/enmasse/model/validation/AddressSpaceConnectorAddressRulePatternValidator.java, api-model/src/test/java/io/enmasse/address/model/AddressSpaceSpecConnectorAddressRuleTest.java, documentation/design/proposals/bridging_external.adoc, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java, systemtests/src/main/java/io/enmasse/systemtest/utils/AddressSpaceUtils.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/bases/bridging/BridgingBase.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/bridging/ConnectorsTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/bridging/ForwardersTest.java
* invalid connector names (ie: using / in connector name) - it works 
* invalid patterns in address rule in connector (ie: queue*) - it's failing added a unit test too, maybe the pattern needs to be modified ( could you check that @lulf )
* Restart broker to ensure router reattached to broker and you can send/recv messages - it works
* try to forward messages when the remote broker is unavailable , and check how the messages are automatically forwarded when the remote broker comes back up - it works
=> More bridging tests

address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceController.java, agent/bin/agent.js, agent/lib/internal_address_source.js, api-model/src/main/java/io/enmasse/config/AnnotationKeys.java, api-server/src/main/java/io/enmasse/api/server/ApiServer.java, k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapAddressApi.java, k8s-api/src/main/java/io/enmasse/k8s/api/ConfigMapAddressSpaceApi.java, k8s-api/src/test/java/io/enmasse/k8s/api/ConfigMapAddressApiTest.java, k8s-api/src/test/java/io/enmasse/k8s/api/ConfigMapAddressSpaceApiTest.java, service-broker/src/main/java/io/enmasse/osb/ServiceBroker.java, standard-controller/src/main/java/io/enmasse/controller/standard/StandardController.java, templates/address-space-controller/020-Role-address-space-admin.yaml, templates/address-space-controller/020-Role-address-space-controller.yaml, templates/api-server/020-Role-api-server.yaml
Use ownerreferences instead to make sure address configmaps are deleted
when an address space configmap is deleted.
=> Remove infraType label to prevent accidental delete

systemtests/src/main/java/io/enmasse/systemtest/utils/AddressSpaceUtils.java, systemtests/src/main/java/io/enmasse/systemtest/utils/CertificateUtils.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/certs/CertProviderTest.java
* Configure route hosts as well as certificate CN
* Refactor tests to set endpoints and explicitly specify expose
* Limit tests to OpenShift environment as Minikube does not have the capability to do SNI based routing out of the box.
* Reenable tests failing due to http client redirect being followed (#2427)
Fixes #2427
=> Fix cert bundle certificate provider test

templates/csv/enmasse.clusterserviceversion.yaml
- Bugfix
Allow SingleNamespace installmode so that EnMasse can be installed into its own namespace when using Operator Catalog.
=> Allow single mode install mode

broker-plugin/amqp-connector/src/main/java/org/apache/activemq/artemis/integration/amqp/LinkInitiator.java
Set supported outcomes and default outcome for outgoing connector sender links.
@k-wall I wasn't sure what the most appropriate default outcome would be. My thinking was that released would allow us to re-send.
=> Set outcomes and default outcome for outgoing links

agent/lib/broker_stats.js, agent/www/components/addresses/addresses.html
This change adds another field 'Global DLQ' to addresses of type queue in the console, showing the depth of the '!!GLOBAL_DLQ' address.
=> Add global DLQ stats to console page

pkg/apis/enmasse/v1beta1/types.go, pkg/apis/enmasse/v1beta1/zz_generated.deepcopy.go
Unmarshalling an addressspace instance in Go with fowarding defined fails with an exception like this:
`panic: v1beta1.AddressSpaceList.Items: []v1beta1.AddressSpace: v1beta1.AddressSpace.Spec: v1beta1.AddressSpaceSpec.Connectors: []v1beta1.ConnectorSpec: v1beta1.ConnectorSpec.Addresses: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|dresses":[{"name":"m|..., bigger context ...|uest"},"password":{"value":"guest"}},"addresses":[{"name":"myqueueKW","pattern":"*"},{"name":"X","pa|...
`
=> Go types - ConnectorAddressRule should be an array type

documentation/design/proposals/bridging_external.adoc, systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java, systemtests/src/main/resources/broker/broker.xml, systemtests/src/test/java/io/enmasse/systemtest/bases/bridging/BridgingBase.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/bridging/ConnectorsTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/bridging/ForwardersTest.java
new systemtests
This PR includes 2 new tests for the bridging features:
- forwarding to a full queue and consuming the exceeded messages in '!!GLOBAL_DLQ' 
- configure a connector using secrets
In order to write those tests some minor refactor has been needed in the exsisting bridging classes
=> systemtests bridging to full queue

documentation/design/proposals/bridging_external.adoc, documentation/modules/ref-address-space-example-connectors.adoc, documentation/modules/ref-address-space-example-exporting-endpoints.adoc
Simplify the description on how to provide access to secrets and configmaps for EnMasse infrastructure. By not mentioning the specific service account, we will be free to change the service account without breaking any API.
=> Update examples to use service account group rather than a specific service account

agent/lib/router_config.js, broker-plugin/plugin/src/main/resources/standard/sharded-queue/README.md, broker-plugin/plugin/src/main/resources/standard/sharded-queue/broker.xml
- Bugfix
This fixes an issue when upgrading where the router statefulset is not
completely rolled out after the upgrade. Once upgraded, the new agent
image will delete the old probe listener on the old router, causing the
readiness probe to fail. While the readiness probe is failing, the
rollout fails to proceed.
This fix re-adds the old probe which have to be kept around until
upgrading from 0.26.x is no longer supported.
Another upgrade issue fixed in this PR is that a missing sharded-queue/broker.xml causes sharded queues to not be reachable, as the draining broker is missing its broker.xml to be able to connect to the router.
=> Fix upgrade test

address-space-controller/Dockerfile, address-space-controller/src/assembly/unix-dist.xml, address-space-controller/src/main/resources/templates/standard-space-infra.yaml, standard-controller/Dockerfile, standard-controller/src/assembly/unix-dist.xml, templates/Makefile, templates/address-space-controller/050-Deployment-address-space-controller.yaml, templates/csv/enmasse.clusterserviceversion.yaml
- Refactoring
This simplifies build process as there is no need to care about these variables.
=> Remove the need to parameterize TEMPLATE_DIR and RESOURCES_DIR during build

CHANGELOG.md, pkg/controller/consoleservice/consoleservice_controller.go
- Bugfix
Defect fix. Fix path to probe endpoint used when running on Kubernetes.  Caused crash looping pod owing to failing health probe.
=> Fix #3247: Fix path to probe endpoint used when running on Kubernetes

systemtests/src/test/java/io/enmasse/systemtest/isolated/upgrade/UpgradeTest.java
Removes test workaround - relates to #3256
=> Remove now redundant workaround restart of the router pods following upgrade

keycloak-user-api/src/main/java/io/enmasse/user/keycloak/KeycloakUserApi.java, keycloak-user-api/src/test/java/io/enmasse/user/keycloak/KeycloakUserApiTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/api/UserApiTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/api/UserApiTest.java
- Bugfix
Fixes an exception when the value of an annotation on the "user" object to "too long" for keycloak to store.
=> Fix issue of "too long" annotations on the user object due to keycloak

iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/device/impl/DeviceManagementServiceImpl.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/DeviceRegistryTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/FileDeviceRegistryTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/InfinispanDeviceRegistryTest.java
- Bugfix
When a device gets created with the same id a second time, the request has to fail, but that didn't happen. The device was not created, and still "success" was returned.
This PR fixes this issue, and also adds a system test.
=> Fix return code when device was already registered

documentation/assemblies/assembly-configuring.adoc, documentation/assemblies/assembly-using-console.adoc, documentation/modules/proc-configure-openid-connect-for-kubernetes.adoc
Contribute docs around configuring OIDC on Kubernetes to enable use of the EnMasse Console.  Does not apply to OpenShift.
=> Fix #2919: Document configuring OIDC for EnMasse Console on Kubernetes

systemtests/src/test/java/io/enmasse/systemtest/isolated/CommonTest.java
this PR reimplements the test CommonTest#testMessagingDuringRestartComponents in order to consume less resources because we have seen cases in which this test fails because of the recursion used
=> improve testMessagingDuringRestartComponents

systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java, systemtests/src/main/java/io/enmasse/systemtest/manager/SharedIoTManager.java, systemtests/src/main/java/io/enmasse/systemtest/utils/IoTUtils.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/IoTProjectManagedTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/MultipleProjectsTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/project/ManagedTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/DeviceRegistryTest.java
Fix iot config cleanup
- Bugfix
IoT manager cannot delete iotconfig because it tried to remove it from non exists namespace. I changed building of iot config in systemtest to add namespace into metadata.
=> Systemtests fix clean iot

k8s-api/src/main/java/io/enmasse/k8s/api/ResourceChecker.java, k8s-api/src/main/java/io/enmasse/k8s/api/cache/EventCache.java, k8s-api/src/main/java/io/enmasse/k8s/api/cache/Reflector.java, standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, standard-controller/src/main/java/io/enmasse/controller/standard/RouterStatusCache.java, standard-controller/src/main/java/io/enmasse/controller/standard/RouterStatusCollector.java, standard-controller/src/main/java/io/enmasse/controller/standard/StandardControllerOptions.java
- Bugfix
This change spins of router status collection into a separate thread. This prevents the status collection to block the reconciliation loop and should speed up the time between address creation and addresses being ready.
Fixes #3299
=> Run router status collection in a separate thread

agent/lib/router_config.js
- Bugfix
Filter internally defined router entities earlier to avoid spurious reconciliation errors.
=> Fix #3309: Filter router entity earlier to avoid router recon errors

Makefile.env.mk
- Refactoring
Bumped the application monitoring operator to version 0.0.27. This ensures that the v0.33.0 of the Prometheus operator is deployed, including the fix for the following bug:
[https://bugzilla.redhat.com/show_bug.cgi?id=1735691](https://bugzilla.redhat.com/show_bug.cgi?id=1735691)
=> Bump application monitoring operator to 0.0.27

iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/config/DeviceServiceConfiguration.java, iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/config/DeviceServiceProperties.java, iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/device/impl/CredentialsManagementServiceImpl.java, iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/util/Credentials.java, systemtests/src/main/java/io/enmasse/systemtest/iot/CredentialsRegistryClient.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/DeviceRegistryTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/FileDeviceRegistryTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/InfinispanDeviceRegistryTest.java
- Bugfix
Use hono's  `SpringBasedHonoPasswordEncoder` to hash passwords in the device registry.
This should fix https://issues.jboss.org/browse/ENTMQMAAS-1388
=> Hash plain text passwords in device registry

systemtests/src/main/java/io/enmasse/systemtest/amqp/AmqpClient.java, systemtests/src/main/java/io/enmasse/systemtest/amqp/Receiver.java, systemtests/src/main/java/io/enmasse/systemtest/amqp/ReceiverStatus.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/CommonTest.java
- Bugfix
test CommonTest#testMessagingDuringRestartComponents has a possible race condition in the way the sender and receiver are stopped. This PR tries to fix that introducing a wait between the stop of those two. Other solution could be changing the assertion and not focus on exact messages sent and received, we can discuss that.
=> try to fix racey test testMessagingDuringRestartComponents

systemtests/src/main/java/io/enmasse/systemtest/info/FakeExtensionContext.java, systemtests/src/main/java/io/enmasse/systemtest/info/MethodBasedExtensionContext.java, systemtests/src/main/java/io/enmasse/systemtest/info/TestInfo.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java, systemtests/src/main/java/io/enmasse/systemtest/manager/SharedResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java
- Bugfix
This PR fix an issue because of the incorrect tracking of the executed tests that made systemtests share address spaces wrongly between brokered and standard address space tests.
=> systemtests detect disabled tests in TestInfo#tests

address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceController.java, address-space-controller/src/main/java/io/enmasse/controller/NetworkPolicyController.java, address-space-controller/src/test/java/io/enmasse/controller/NetworkPolicyControllerTest.java
- Bugfix
This prevents the user from deliberately opening all ports if desired.
The current list is in any case not sufficient to allow internal
components to talk to eachother.
=> Stop adding service ports to network policy rule by default

address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceController.java, address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceControllerOptions.java, api-server/src/main/java/io/enmasse/api/server/ApiServer.java, api-server/src/main/java/io/enmasse/api/server/ApiServerOptions.java, standard-controller/src/main/java/io/enmasse/controller/standard/StandardController.java, standard-controller/src/main/java/io/enmasse/controller/standard/StandardControllerOptions.java, systemtests/pom.xml, systemtests/src/main/java/io/enmasse/systemtest/Environment.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Minikube.java, systemtests/src/main/java/io/enmasse/systemtest/platform/OpenShift.java
- Refactoring
In slow CI environments we see sporadic failures with kubernetes API interactions. Raising the
timeouts seems to help.  This changes exposse OkHttp3 read/write/connect timeouts for configuration for both production and test use-cases.
=> Expose OkHttp3 read/write/connect timeouts for configuration

documentation/modules/ref-view-message-conn-stats-table.adoc
Documentation
Fixed UI label reference to `Global DLQ` and tried to improve explanation of what Global DLQ means
=> Docs: fix UI label reference to Global DLQ and improve explanation

systemtests/src/main/java/io/enmasse/systemtest/platform/KubeCMDClient.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/CommonTest.java
- Bugfix
This PR adds to testRestartComponents the same wait we added in the past to testMessagingDuringRestartComponents because after restarting the api-server we need to ensure the api services are up again or if not next tests will faill because of this
=> Ensure proper tear down of testRestartComponents

systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java, systemtests/src/main/java/io/enmasse/systemtest/manager/IsolatedResourcesManager.java, systemtests/src/main/java/io/enmasse/systemtest/manager/SharedResourceManager.java
- Bugfix
This PR adds proper tear down of shared tests when test successfully pass and the environment is shared with the next test. We were missing the closing of clients.
=> Close clients in tear down of shared tests

documentation/assemblies/assembly-configuring-olm.adoc, documentation/modules/proc-create-address-plan-custom-resource-olm-ui.adoc, documentation/modules/proc-create-address-space-plan-custom-resource-olm-ui.adoc, documentation/modules/proc-create-auth-service-custom-resource-olm-ui.adoc, documentation/modules/proc-create-infraconfig-custom-resource-olm-ui.adoc, documentation/modules/proc-olm-installing-from-operatorhub-using-console.adoc
Documentation
Document option for OpenShift 4.2 and ability to install into a specific namespace when using the Operator install method
=> Docs: Operator installation method into specific namespace

systemtests/src/test/java/io/enmasse/systemtest/isolated/CommonTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/monitoring/MonitoringTest.java
- Bugfix
This PR adds a workaround for wairForExpectedReadyPods where non-existing pods are passed to waitUntilPodIsReady
=> Workaround for wairForExpectedReadyPods

systemtests/src/main/java/io/enmasse/systemtest/operator/OperatorManager.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java
- Workaround 
Have the system tests, when installing EnMasse on OpenShift await a populated consoleservice
record.
=> Workaround #2969 in systemtests by awaiting a pouplated consoleservice

address-space-controller/src/main/java/io/enmasse/controller/RouterStatusController.java
This adds a check for router mesh connectivity by querying the routers
for its connected nodes in the router network. If the list of nodes does
not contain the number of ready router pods, the address space status is
set to false, and an error message is added to the status and in the
log.
Fixes #3355
=> Check router mesh connectivity

systemtests/src/main/java/io/enmasse/systemtest/info/TestInfo.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java
- Bugfix
With the recent refactor where systemtests takes care of enmasse installation we forgot about OLM tests, this PR fixes that
=> Fix systemtests for OLM test

api-server/src/main/java/io/enmasse/api/server/ApiServer.java, api-server/src/main/java/io/enmasse/api/server/ApiServerOptions.java, api-server/src/main/java/io/enmasse/api/server/HTTPServer.java, api-server/src/main/java/io/enmasse/api/server/ResteasyDeploymentFactory.java, api-server/src/test/java/io/enmasse/api/server/HTTPServerTest.java
- Enhancement 
Create multiple instances of HTTP servers while keeping the service
handlers and request filters singletons.
Set the number of HTTP server instances based on the number of CPUs,
optionally via an environment variable.
Fixes #3392 
Co-authored-by: Keith Wall <kwall@apache.org>
=> Handle multiple API server requests in parallel

systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java
- Bugfix to test code
Works around Kubernetes Client issue where a NPE may occur when awaiting pods.
=> Workaround Fabric8 NPE that may erronously occur whilst awaiting pods

documentation/modules/con-user-model.adoc
The application's AMQP client must be configured to use SASL plain when using this authentication type.
=> Use SASL plain for the Serviceaccount authentication type

agent/lib/router_config.js, agent/test/ragent.js, agent/test/router_stats.js
The agent currently causes the Router to log a deprecation warning during auto link
creation.  This PR resolves that issue.
`The 'addr' attribute of autoLink has been deprecated. Use 'address' instead`
- Refactoring
As above.
=> Resolve router deprecation warning logged during autolink creation

systemtests/pom.xml, systemtests/src/main/java/io/enmasse/systemtest/TestTag.java, systemtests/src/main/java/io/enmasse/systemtest/manager/ResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/utils/AddressUtils.java, systemtests/src/test/java/io/enmasse/systemtest/bases/soak/SoakTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/soak/BrokeredSoakTest.java, systemtests/src/test/java/io/enmasse/systemtest/soak/PlansSoakTest.java, systemtests/src/test/java/io/enmasse/systemtest/soak/RestartTest.java, systemtests/src/test/java/io/enmasse/systemtest/soak/StandardSoakTest.java
- Refactoring
Changed "marathon" suite to "soak", deleted unneeded tests. Added load test that creates several address spaces with several addresses for both (standard, brokered) address space types.
=> Soak suite cleanup, add load test, add create address spaces method

iot/iot-service-base/src/main/java/io/enmasse/iot/service/base/AbstractProjectBasedService.java, systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java
- Bugfix
Since the upgrade to fabric8, all IoT tests fail due to unknown tenants. It looks
like fabric8 changed it behavior, to apply a default namespace ot the client, which
makes the client only watch for tenants in the current namespace of the infrastructure.
This change explicitly enables "any" namespace.
=> Fix 404 when using a tenant outside of the enmasse namespace

pkg/controller/address_space_controller_deployer/deployer.go, systemtests/src/test/java/io/enmasse/systemtest/isolated/upgrade/UpgradeTest.java
- Bugfix
This avoids the cause found by upgrade tests, where the enmasse-operator
was restarted after failing to replace address-space-controller
deployment and not scaling api-server back up.
=> Scale explicitly back up to 1 api-server

systemtests/src/test/java/io/enmasse/systemtest/isolated/console/ChromeGlobalConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/console/FirefoxGlobalConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/plans/web/FirefoxWebConsolePlansTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/web/ChromeWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/web/FirefoxWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/ChromeWebConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/FirefoxWebConsoleTest.java
Temporarily exclude the web console and global tests during the console refactoring work.
=> Temporarily disable web console/global console tests

documentation/assemblies/assembly-iot-getting-started.adoc, documentation/assemblies/assembly-iot-guide.adoc, documentation/assemblies/assembly-iot-service-admin-guide.adoc, documentation/assemblies/assembly-iot-tenant-guide.adoc, documentation/modules/proc-iot-configure-hono-cli.adoc, documentation/modules/snip-iot-customer-api.adoc, documentation/modules/snip-iot-http-api.adoc, documentation/modules/snip-iot-mqtt-api.adoc
This is the first attempt to restructure the existing material according to #3423 proposal
We are limited by the nesting depth we can go with headlines so the deepest titles are not properly showed in the menu. I'm not sure what's the best way to overcome this. Maybe move everything one level up and lose the general "IoT Guide" level in the main menu, but have "IoT Overview", "IoT service admin guide" and "IoT tenant guide" instead?
Take a look and let me know what you think.
=> Restructure IoT documentation

pkg/controller/iotconfig/adapter.go, pkg/controller/iotconfig/auth_service.go, pkg/controller/iotconfig/file_device_registry.go, pkg/controller/iotconfig/http_adapter.go, pkg/controller/iotconfig/infinispan_device_registry.go, pkg/controller/iotconfig/iotconfig_controller.go, pkg/controller/iotconfig/lorawan_adapter.go, pkg/controller/iotconfig/mqtt_adapter.go, pkg/controller/iotconfig/project_operator.go, pkg/controller/iotconfig/sigfox_adapter.go, pkg/controller/iotconfig/tenant_service.go, pkg/controller/iotconfig/utils.go, pkg/util/cchange/change.go
This change sets the proxy routers to not created addresses
when the protocol adapters requests them.
Also it does add config tracking to the protocol adapter deployments in
in order to activate the change.
- Bugfix
=> Fix issues of "temporary unavailable"

pkg/apis/enmasse/v1beta1/types.go
- Bugfix
Add the missing Phase field to Go AddressSpaceStatus
=> Add the missing Phase field to Go AddressSpaceStatus

pkg/controller/iotproject/managed.go
As the map key order is randomized, a change will cause a new order in
the message field, which will cause an update on the object, which will
cause another change, …
- Bugfix
=> Prevent continuous updates when project is creating

address-space-controller/src/main/java/io/enmasse/controller/AddressFinalizerController.java, address-space-controller/src/main/java/io/enmasse/controller/ControllerChain.java, address-space-controller/src/test/java/io/enmasse/controller/AddressFinalizerControllerTest.java, address-space-controller/src/test/java/io/enmasse/controller/ControllerChainTest.java, address-space-controller/src/test/java/io/enmasse/controller/CreateControllerTest.java, address-space-controller/src/test/java/io/enmasse/controller/EndpointControllerTest.java, address-space-controller/src/test/java/io/enmasse/controller/ExportsControllerTest.java, address-space-controller/src/test/java/io/enmasse/controller/NetworkPolicyControllerTest.java, address-space-controller/src/test/java/io/enmasse/controller/RouterConfigControllerTest.java, address-space-controller/src/test/java/io/enmasse/controller/StatusControllerTest.java, k8s-api-testutil/src/main/java/io/enmasse/k8s/api/TestAddressApi.java
- Bugfix
The controller chain called the wrong method (the one processing the "non-deleted" state). In this case the finalizer was never run, and when deleting the object, still all the "active" methods got called.
This change fixes the call, now calling the correct method. And adding a unit test to ensure that the finalizer gets called and properly handles finalizing the address space.
=> Fix finalizer logic in address space controller, add unit test

address-space-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java, standard-controller/src/main/java/io/enmasse/controller/standard/KubernetesHelper.java
Fix ##3480
- Bugfix
Works around an defect in the Fabric8 kubernetes-client.
=> Fabric8 kubernetes-client race when deleting a deployment may leave pods behind

.jenkins/Jenkinsfile-pr
- Bugfix
CRC image localbuild for PR does not work because of different internal registry URL
=> Fix crc image localbuild

olm-manifest/src/main/resources/latest/enmasse.clusterserviceversion.yaml, pkg/controller/address_space_controller/controller.go, pkg/controller/authenticationservice/standard.go, pkg/controller/iotconfig/file_device_registry.go, pkg/util/install/utils.go, templates/enmasse-operator/050-Deployment-enmasse-operator.yaml
- Bugfix
Instead of applying the fsgroup environment to the
address-space-controller, propagate it so that it is applied to brokers
etc.
Remove unneeded GVK setting that was added for some debugging earlier.
=> Propagate fsGroup environment

documentation/modules/ref-address-space-example-cert-providers.adoc
Add a note about not using self-signed certs in production environments
=> Docs: add admonition to not use self-signed certs in prod environments

iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/util/DeviceRegistryTokenAuthHandler.java, iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/util/DeviceRegistryTokenAuthProvider.java
With the log level being "debug", every call to the device registry will cause two log entries on "info" level.
=> Reduce log output for normal cases

systemtests/src/test/java/io/enmasse/systemtest/isolated/api/ApiServerTest.java
- Bugfix
Fix ApiServerTest.testReplaceAddressSpace that started failing in ocp4, the issues is that it does a nonsense address space replacing without modifiying it
=> fix ApiServerTest.testReplaceAddressSpace

systemtests/src/test/java/io/enmasse/systemtest/isolated/api/CustomResourceDefinitionAddressSpacesTest.java
- Bugfix
CustomResourceDefinitionAddressSpacesTest.testCliOutput is failing in our CI , this PR changes a nonsense wait for deleted namespace to a wait for address space delete which will give us better information about the reason why test fails in case it keeps failing
=> fix flaky test CustomResourceDefinitionAddressSpacesTest.testCliOutput

systemtests/src/main/java/io/enmasse/systemtest/Environment.java, systemtests/src/test/java/io/enmasse/systemtest/bases/olm/OLMTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/olm/OLMDefaultTest.java, systemtests/src/test/java/io/enmasse/systemtest/olm/OLMSpecificTest.java
This PR adds some refactor to OLM tests and adds new tests to create address space in different namespace than the one the operator is installed
=> add OLM tests that create address space in different namespace

address-space-controller/src/main/resources/templates/standard-space-infra.yaml
- Bugfix
Currently the image pull policy for agent image is ignored and "Always" is used.
=> Apply proper pull policy on agent image

cmd/controller-manager/main.go, pkg/cache/delegate_cache.go, pkg/cache/delegate_cache_test.go, vendor/sigs.k8s.io/controller-runtime/pkg/cache/informertest/fake_cache.go, vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/doc.go, vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/testing.go, vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/util.go
This allows for using both namespaced and global watches based on object
type.
An implementation of controller-runtime Cache interface that delegates lookups and watches to either a local namespaced cache, or a global cache, depending on the type. The type mapping is registered at manager creation time.
The intention is to use this to allow the enmasse-operator deployment to watch both local and global objects.
=> Add delegate cache to handle caching of global objects

pom.xml, systemtests/pom.xml, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java
- Bugfix
Fix current surefire console logs 
from
```
running null
```
to
```
running io.enmasse.systemtest.TestClass
```
and also contains temp workaround for issue in surefire plugin https://issues.apache.org/jira/browse/SUREFIRE-1688
=> Fix surefire console reporting

address-space-controller/src/main/java/io/enmasse/controller/AppliedConfig.java, address-space-controller/src/main/java/io/enmasse/controller/CreateController.java, address-space-controller/src/main/java/io/enmasse/controller/StatusController.java, address-space-controller/src/main/java/io/enmasse/controller/common/Kubernetes.java, address-space-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java, address-space-controller/src/test/java/io/enmasse/controller/CreateControllerTest.java, api-model/src/main/java/io/enmasse/address/model/AddressSpaceResolver.java, api-model/src/main/java/io/enmasse/config/AnnotationKeys.java
- Refactoring
Retrigger processing of templates whenever address space spec changes, not only when plan changes. This will cover cases such as changing the authentication service, or any other change to spec that requires reprocessing of templates.
=> Allow addressspace spec changes

systemtests/src/main/java/io/enmasse/systemtest/manager/IsolatedResourcesManager.java
NetworkPolicyTestStandard was leaving its standardinfraconfig resource behind.  This change ensures that it gets cleaned up during tear down.
=> Prevents NetworkPolicyTestStandard leaving behind its infraconfig

address-space-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/policy/NetworkPolicyTestStandard.java
- Bugfix
Delete networkpolicies created for an address space. Add checks to systemtests to verify that networkpolicy is gone.
Fixes #3547
=> Delete network policies created for address space

address-space-controller/src/main/resources/templates/brokered-space-infra.yaml, address-space-controller/src/main/resources/templates/standard-space-infra.yaml, agent/lib/kubernetes.js
- Bugfix
This adds periodic resync intervals to agent watches similar to what
exists for other controller processes.
On watch error, abort current request and reconnect.
Issue #3542
=> Add resync period for agent watches

pkg/controller/iotconfig/iotconfig_controller.go, pkg/controller/iotproject/iotproject_controller.go, pkg/controller/iotproject/managed.go, pkg/util/finalizer/finalizer.go, pkg/util/finalizer/finalizer_test.go
Pulling out more changes in preparation to #3557.
Aside from some cleanups, the adds the API reader, so that, later on, the finalizer can use this API reader, to read Jobs on a single namespace only, without creating a system wide informer on the "any" namespace for jobs.
- Refactoring
=> Add API reader, cleanup logs, cleanup.

cmd/iot-proxy-configurator/configurator.go, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitExecutionListener.java, systemtests/src/main/java/io/enmasse/systemtest/manager/ResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/utils/IoTUtils.java, systemtests/src/test/java/io/enmasse/systemtest/iot/shared/http/HttpAdapterTest.java
- Bugfix
The order in which the system tests destroy resources. IoT projects first, then address spaces. Otherwise the IoT operator will automatically re-created the resources.
=> Change order of destroying resources

systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/ExternalClientsExtension.java, systemtests/src/test/java/io/enmasse/systemtest/bases/clients/ClientTestBase.java
- Refactoring
Since we started using parametrized tests, we need to store artifacts in handlers with DisplayName of test to store every parametrized test iteration
=> Use displayname for storing artifacts

address-space-controller/src/main/java/io/enmasse/controller/EndpointController.java
Balance by least number of connections by default
Using this policy as a default is more appropriate for messaging application that typically have long-living connections.
Fixes #3484
=> Default route annotation

pkg/controller/address_space_controller/controller.go, pkg/controller/authenticationservice/none.go, pkg/controller/authenticationservice/standard.go, pkg/controller/consoleservice/consoleservice_controller.go, pkg/controller/iotconfig/adapter.go, pkg/controller/iotconfig/auth_service.go, pkg/controller/iotconfig/file_device_registry.go, pkg/controller/iotconfig/http_adapter.go, pkg/controller/iotconfig/infinispan_device_registry.go, pkg/controller/iotconfig/lorawan_adapter.go, pkg/controller/iotconfig/mqtt_adapter.go, pkg/controller/iotconfig/project_operator.go, pkg/controller/iotconfig/sigfox_adapter.go, pkg/controller/iotconfig/tenant_service.go, pkg/util/install/utils.go, pkg/util/install/utils_test.go
- Refactoring
Pull out changes from #3556. This change pulls "ApplyContainer" and "ApplyInitContainer" into a single function. And then re-uses that function to implement the feature for "Init", "Job" and "Deployment" containers.
=> Refactor "ApplyContainer" to support Init, Deployment and Job

systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java
- Bugfix
New version of chrome in selenium does not communicate on wss when cert is untrusted, so this setting allow to communicate with self signed certs
=> Fix chrome untrusted cert wss

pkg/controller/address_space_controller/controller.go
- Bugfix
On master the address-space-controller was missing its readiness/liveness probes.
=> Re-add Address Space Controller probes

systemtests/src/main/java/io/enmasse/systemtest/info/TestInfo.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java
- Refactoring
This PR moves the preparation for UpgradeTest from the afterAll callback to the beforeAll callback, this is being done to get rid of the method `isNextTestUpgrade` in `TestInfo` class. IMO we should avoid the kind of logic that were in methods like `isNextTestUpgrade`
=> Refactor upgrade tests preparation to simplify code

documentation/modules/proc-uninstalling.adoc, systemtests/src/main/java/io/enmasse/systemtest/operator/OperatorManager.java, templates/crds/addresses.crd.yaml, templates/crds/addressspaces.crd.yaml, templates/crds/messagingusers.crd.yaml
- Bugfix
Order the CRD deletion so that the iot is cleanup before addresses/addressspaces/users, and addresses/addressspaces/users are cleaned up before the infrastructure.
This ensures that finalizers will be run correctly.
=> Order CRD cleanup by iot,tenant-api and the rest

address-space-controller/src/main/resources/templates/brokered-space-infra.yaml, address-space-controller/src/main/resources/templates/standard-space-infra.yaml, documentation/assemblies/assembly-monitoring.adoc, documentation/modules/proc-enable-tenant-metrics.adoc, standard-controller/src/main/resources/templates/queue-persisted.yaml, standard-controller/src/main/resources/templates/topic-persisted.yaml
Added a label to tenant specific metrics, allowing them to be scrape independently of system-admin metrics and provided sample service monitor to scrape only tenant metrics in docs.
=> Enabled tenant metrics

CHANGELOG.md, address-space-controller/src/main/resources/templates/standard-space-infra.yaml
Fixes #3646
Define commonly desired default policy for router anti-affinity.
=> Configure router pod anti-affinity preference default

iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/health/AbstractCacheHealthCheck.java, iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/health/AbstractSyncHealthCheck.java, iot/iot-infinispan-base/src/main/java/io/enmasse/iot/infinispan/cache/DeviceManagementCacheProvider.java, iot/iot-service-base/src/main/java/io/enmasse/iot/service/base/AbstractProjectBasedService.java, iot/iot-tenant-cleaner/src/main/java/io/enmasse/iot/tools/cleanup/InfinispanTenantCleaner.java
- Bugfix
Cache schema check is not consistent when the schema is updated multiple times. The schema is the same, just with the reordered elements. The quick fix is to prevent tenant cleaner job to update the schema (as I think it shouldn't do anyways). But we might want to revisit how we do this check in the future anyways.
=> [IoT] Prevent tenant cleaner to update caches schema

systemtests/src/main/java/io/enmasse/systemtest/bases/ITestSeparator.java, systemtests/src/main/java/io/enmasse/systemtest/info/TestInfo.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java
- Bugfix
This PR fixes the test name that were printed and used as logs folder because it had whitespaces. Also adds a fix for the method TestInfo.isEndOfIotTests because I saw errors produced because an exception there in our CI
=> Fix logs folder name

address-space-controller/Makefile, address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceController.java, olm-manifest/src/main/resources/latest/enmasse.clusterserviceversion.yaml, pkg/controller/address_space_controller/controller.go, templates/enmasse-operator/050-Deployment-enmasse-operator.yaml
- Bugfix
Fixes the upgrade case with many addresses:
* Ensure liveness probes can pass while conversion is running
* Avoid holding on converted objects once conversion is done
* Increase default memory configuration and fix typo in env var
=> Fix upgrade with many addresses

address-space-controller/src/main/java/io/enmasse/controller/RouterConfigController.java, api-model/src/main/java/io/enmasse/admin/model/v1/StandardInfraConfigSpecRouter.java, documentation/src/main/resources/swagger.json, olm-manifest/src/main/resources/latest/enmasse.clusterserviceversion.yaml, templates/address-space-controller/020-ClusterRole-address-space-controller.yaml, templates/address-space-controller/020-Role-address-space-controller.yaml, templates/crds/standardinfraconfigs.crd.yaml
Allow specifying minAvailable for the router pods created for an address space. This will create a pod disruption budget to ensure minAvailable routers are always running.
=> Pod distruption budget

systemtests/src/main/java/io/enmasse/systemtest/IndicativeSentences.java, systemtests/src/main/java/io/enmasse/systemtest/bases/ITestSeparator.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java, systemtests/src/main/java/io/enmasse/systemtest/manager/IsolatedIoTManager.java, systemtests/src/main/java/io/enmasse/systemtest/manager/SharedIoTManager.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/ExternalClientsExtension.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/bases/bridging/BridgingBase.java, systemtests/src/test/java/io/enmasse/systemtest/bases/olm/OLMTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/monitoring/MonitoringTest.java
- Bugfix
This PR fix the default display name generator we have and removes a previous workaround added because I didn't notice we had a default display name generator
=> fix tests default displayname

console/console-init/ui/src/Pages/CreateAddressSpace/CreateAddressSpaceConfiguration.tsx, console/console-init/ui/src/Pages/CreateAddressSpace/ReviewAddressSpace.tsx, console/console-init/ui/src/Queries/Queries.tsx
* The authentication services dropdown is now getting populated through data returned by backend.
* The grid had to be adjusted to display address space preview properly.
* The as_create mutation was failing due to defect in PF dropdown which has been fixed.
=> Feat: implement authentication service dropdown

systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/DeviceRegistryTest.java
- Bugfix
Fix test in DeviceRegistryTest which uses incorrect method to delete an IoTProject, this could be the cause of some issues
=> use correct method to delete iotproject in DeviceRegistryTest

console/console-init/ui/src/Components/AddressSpaceList/AddressSpaceListFilter.tsx, console/console-init/ui/src/Pages/AddressDetail/AddressLinksFilter.tsx, console/console-init/ui/src/Pages/AddressDetail/AddressLinksWithFilterAndPaginationPage.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListFilter.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListFilterPage.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListPage.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressesListWithFilterAndPaginationPage.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/ConnectionList/ConnectionListFilter.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/ConnectionList/ConnectionListWithFilterAndPaginationPage.tsx, console/console-init/ui/src/Pages/AddressSpaceList/AddressSpaceListFilterPage.tsx, console/console-init/ui/src/Pages/ConnectionDetail/ConnectionLinksFilter.tsx, console/console-init/ui/src/Pages/ConnectionDetail/ConnectionsLinksListPage.tsx, console/console-init/ui/src/Queries/Queries.tsx
The filters now use 'LIKE' instead of '='. The filters have been modified in all of the 5 lists.
ToDos : 
* In some cases redundant elements are encountered in the dropdowns.
=> Fix: searchbar auto-populate issue

console/console-init/ui/src/Queries/Queries.tsx
address column ordering on the connection detail page not working
=> fix - ENTMQMAAS-1609, add orderBy clause for name and address

console/console-init/ui/src/Components/AddressSpaceList/AddressSpaceListFilter.tsx, console/console-init/ui/src/Pages/AddressDetail/AddressLinksFilter.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListFilter.tsx, console/console-init/ui/src/Pages/ConnectionDetail/ConnectionLinksFilter.tsx
The filters were showing  an extra unnecessary filter icon for certain drop down items.
=> Fix: remove extra filter icons

iot/iot-infinispan-base/src/main/java/io/enmasse/iot/infinispan/cache/AbstractCacheProvider.java, iot/iot-infinispan-base/src/main/java/io/enmasse/iot/infinispan/cache/DeviceConnectionCacheProvider.java, iot/iot-infinispan-base/src/main/java/io/enmasse/iot/infinispan/cache/DeviceManagementCacheProvider.java, iot/iot-infinispan-base/src/main/java/io/enmasse/iot/infinispan/config/InfinispanProperties.java, iot/iot-tenant-cleaner/src/main/java/io/enmasse/iot/tools/cleanup/InfinispanTenantCleaner.java, systemtests/src/main/java/io/enmasse/systemtest/iot/MessageSendTester.java, systemtests/src/main/java/io/enmasse/systemtest/utils/IoTUtils.java
This change tries to fix the issue when the tenant cleaner tries to
clean up a tenant from an infinispan cluster, which never got
the protobuf schema uploaded by the device registry.
In change 4824dbb7ae73eda147fccf9cb0b19553ed8f6699 the tenant cleaner
was changes to never upload the protobuf schema. But this may cause
the problem, that when an IoTProject is being created and deleted
without the device registry properly uploading the schema, then the
tenant cleaner will fail.
While in production the argument could be, that the device registry
should be brought up online, before starting to clean up IoTProjects,
in testing this might be an issue, especially when the test environment
gets broken by that situation.
So with this change, when the device registry is configured to upload
the …
=> Let the tenant cleaner upload, but not override the protobuf schema

CHANGELOG.md, address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceController.java, address-space-controller/src/main/java/io/enmasse/controller/PodDistruptionBudgetController.java, address-space-controller/src/main/java/io/enmasse/controller/RouterConfigController.java, api-model/src/main/java/io/enmasse/admin/model/v1/StandardInfraConfigSpecBroker.java, standard-controller/src/main/resources/templates/queue-persisted.yaml, templates/crds/standardinfraconfigs.crd.yaml
Allow creating poddisruptionbudgets for brokers, and prefer to schedule brokers on separate hosts. This is mainly useful in combination with partitioned queues in order to get HA during node upgrades.
Fixes #3637
=> Disruption budget broker

agent/lib/internal_address_source.js, agent/test/internal_address_source.js, agent/test/ragent.js
- Bugfix
This prevents the original object from being modified and cause issues
for other address comparisons happening when addresses are updated. This
happened when objects were created from Go-based code where status field
was initialized.
Remove check for unused annotation.
=> Start from empty object when extracting spec

console/console-init/ui/src/Components/AddressSpace/Address/AddressList.tsx
On the address list page, the stored message value has been hidden for rows corresponding to anycast and mulicast addressTypes.
=> Fix: hide stored messages for anycast/multicast address types

console/console-init/ui/src/Pages/ConnectionDetail/ConnectionDetailPage.tsx
Fix - On the connection detail page, use the connection's hostname as a title rather than the uuid.
=> Fix - connection detail page to use connecion's hostname rather than id

console/console-init/ui/src/Components/AddressDetail/AddressDetailHeader.tsx, console/console-init/ui/src/Components/AddressSpace/Address/AddressList.tsx, console/console-init/ui/src/Pages/AddressDetail/AddressDetailPage.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListPage.tsx, console/console-init/ui/src/Tests/AddressDetialHeader.test.tsx, console/console-init/ui/src/Tests/AddressList.test.tsx, console/console-init/ui/src/stories/AddressDetailHeader.stories.tsx, console/console-init/ui/src/stories/AddressList.stories.tsx
Shards has been replaced with Partitions for addresses. The partitions is being shown only for addresses of type queue.
=> Fix: show partitions instead of shards for addresses

console/console-init/ui/src/Components/AddressSpace/Address/AddressList.tsx, console/console-init/ui/src/Pages/AddressDetail/AddressDetailPage.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListFilter.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListPage.tsx, console/console-init/ui/src/Queries/Queries.tsx, console/console-init/ui/src/Tests/AddressList.test.tsx, console/console-init/ui/src/Types/ResponseTypes.tsx, console/console-init/ui/src/stories/AddressList.stories.tsx
Fix - On the address list page, replace the name column with an address column (address.Spec.Address). The name filter should be changed into a filter on address name. In the address creation dialogue collect the address rather than the name.
=> Fix -  Use address on the address list page rather than name

address-space-controller/src/main/java/io/enmasse/controller/MetricsReporterController.java, address-space-controller/src/test/java/io/enmasse/controller/MetricsReporterTest.java, pkg/controller/address_space_controller/controller.go, pkg/util/install/utils.go
Added metrics for address space phases and allowed them to be scraped by
tenant service monitors
=> Added metrics to address space controller

console/console-init/ui/src/Components/AddressSpaceList/AddressSpaceList.tsx
The name/namespace label of AddressSpaceList has been substituted with a line break separation.
=> Fix: Change Name /Namespace label of AddressSpaceList

address-space-controller/src/main/java/io/enmasse/controller/MessagingUserFinalizerController.java
- Bugfix
Fixes uninstall issue that I'm seeing locally.
=> Use cascading delete on messaging users when finalizing address space

console/console-init/ui/src/Pages/CreateAddress/CreateAddressDefinition.tsx, console/console-init/ui/src/Pages/CreateAddress/CreateAddressPage.tsx, console/console-init/ui/src/Pages/CreateAddressSpace/CreateAddressSpaceConfiguration.tsx, console/console-init/ui/src/Pages/CreateAddressSpace/CreateAddressSpacePage.tsx, console/console-init/ui/src/Pages/CreateAddressSpace/ReviewAddressSpace.tsx
The AddressSpaceCreation and AddressCreation wizards now allow going to the next step only after all the required fields are available/provided.
=> Fix: handle validations of creation wizards

cmd/console-server/main.go, go.mod, go.sum, pkg/consolegraphql/accesscontroller/access_controller.go, pkg/consolegraphql/accesscontroller/access_controller_test.go, pkg/consolegraphql/non_kubernetes_types.go, pkg/consolegraphql/resolvers/resolver_address.go, pkg/consolegraphql/resolvers/resolver_address_test.go, pkg/consolegraphql/resolvers/resolver_addressspace.go, pkg/consolegraphql/resolvers/resolver_addressspace_test.go, pkg/consolegraphql/resolvers/resolver_connection.go, pkg/consolegraphql/resolvers/resolver_connection_test.go, pkg/consolegraphql/resolvers/resolver_namespace.go, pkg/consolegraphql/resolvers/resolver_namespace_test.go, pkg/consolegraphql/server/request_context.go, pkg/consolegraphql/server/tracer.go, vendor/github.com/alexedwards/scs/v2/.travis.yml, vendor/github.com/alexedwards/scs/v2/LICENSE, vendor/github.com/alexedwards/scs/v2/README.md, vendor/github.com/alexedwards/scs/v2/codec.go, vendor/github.com/alexedwards/scs/v2/data.go, vendor/github.com/alexedwards/scs/v2/go.mod, vendor/github.com/alexedwards/scs/v2/memstore/README.md, vendor/github.com/alexedwards/scs/v2/memstore/memstore.go, vendor/github.com/alexedwards/scs/v2/session.go, vendor/github.com/alexedwards/scs/v2/store.go, vendor/modules.txt
Limits the namespace, address space, address objects visible to the logged on console user to those that the user has GET permission.   Connections are permissions by considering the permissions of the address space to which they belong.
=> Limit objects that the user may see by filtering using cached SelfSubjectAccessReviews

console/console-init/ui/src/Components/AddressSpace/Address/AddressList.tsx, console/console-init/ui/src/Components/AddressSpace/Connection/ConnectionList.tsx, console/console-init/ui/src/Components/ConnectionDetail/MessagesDetail.tsx, console/console-init/ui/src/Tests/AddressList.test.tsx, console/console-init/ui/src/Tests/ConnectionDetailHeader.test.tsx
The labels have been updated to convey that they are displaying a rate.
It is an update over #3724
=> Fix: show Message In/sec instead  of just Message In

systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/test/java/io/enmasse/systemtest/bases/infra/InfraTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/infra/brokered/InfraTestBrokered.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/infra/standard/InfraTestStandard.java, templates/crds/standardinfraconfigs.crd.yaml
- Bugfix
- Systemtests
This PR adds new systemtests to verify the PodDisruptionBudget functionalities, also fixes the StandardInfraConfig CRD which I broke before :) 
Note atm the tests added are expected to fail because address-space-controller doesn't implement the delete of the pdb when a addressspace is deleted or when the infraconfig is updated.
=> Add systemtests for pdb and fix StandardInfraConfig CRD

console/console-init/ui/src/Pages/CreateAddress/CreateAddressPage.tsx, console/console-init/ui/src/Pages/CreateAddressSpace/CreateAddressSpacePage.tsx
Earlier the CreateAddressSpace and CreateAddress wizards didn't check navigation between steps based upon form validation.
An update to #3738 .
=> Fix: prevent creation wizards froom skipping steps without validation

console/console-init/ui/src/Pages/ConnectionDetail/ConnectionDetailPage.tsx
The connection detail page now shows the right title 'Connection Details' instead of 'Address Space Detail'.
=> Fix: show proper title for ConnectionDetailPage

console/console-init/ui/mock-console-server/README.md, console/console-init/ui/mock-console-server/mock-console-server.js
Improve the behaviour of the mock so that the state of new address space and address objects transitions through having no state before finally reaching a terminal state of Active.
=> console mock- addressspace and address status field now mimics actual behaviour

console/console-init/ui/src/Pages/CreateAddress/CreateAddressDefinition.tsx
Pass address in Spec.topic for creating address of type subscription instead of ObjectMeta.Name
=> Fix-create address of type subscription to pass Spec.address as topic

Makefile, Makefile.java.mk, olm-manifest/Dockerfile, olm-manifest/src/assembly/unix-dist.xml, olm-manifest/src/main/resources/latest/enmasse.clusterserviceversion.yaml, olm-manifest/src/main/resources/sh/replace-images.sh
- Refactoring
Replacing images during image build time instead of during source
build time allows for building the manifest image build in a separate
stage after the main images.
=> Replace images during image build time

console/console-init/ui/src/Components/AddressDetail/AddressDetailHeader.tsx, console/console-init/ui/src/Pages/AddressDetail/AddressDetailPage.tsx
- Fix-  Brokered addresses are broken in console, it does not show status and also when I click to address link it redirects me to blank page. Able to handle null for .Status.PlanStatus for address
=> Fix-Handle null for .Status.PlanStatus in address detail page

console/console-init/ui/src/Pages/CreateAddressSpace/CreateAddressSpaceConfiguration.tsx
Navigating from AddressSpaceReview to AddressSpaceConfiguration didn't reflect the AddressSpace type in the radio buttons.
=> Fix: retain AStype in ASCreateWizard navigations

console/console-init/ui/src/Components/Common/TypePlan.tsx
Show type/plan in a single line in address list for mobile view.
Before :- 
After :-
=> fix type/plan icon to display as a single element for mobile view

hack/run-codegen.sh, hack/update-codegen.sh, hack/verify-codegen.sh
After fixing the code validation on the CI, the update script is still broken and generates stuff into `github.com/…` in the local directory. As the generator is unaware of go modules, there is no proper fix. I saw others firing up containers for doing this, but I think a simple `cp` should do the trick just fine.
I also experimented with `go generate`. The "deep copy" part could be done by `controller-gen`, but they removed the `clientset`, `lister`, … from that.
=> Fix code generation locally

console/console-init/ui/src/Pages/CreateAddress/PreviewAddress.tsx, console/console-init/ui/src/Queries/Queries.tsx
Earlier the address command preview didn't check if topic was available to be previewed and displayed a null string. This bug has been fixed by conditionally adding the key. It also fixes a typo.
Current preview for a non-subscription address type :
=> Fix: hide topic in address comd preview when it is not available

console/console-init/ui/src/Pages/CreateAddress/CreateAddressDefinition.tsx, console/console-init/ui/src/Pages/CreateAddressSpace/CreateAddressSpaceConfiguration.tsx
The app was breaking for cases in which the DropDownItems was an empty array as we were trying to get the value of an undefined element. In this scenario, event.currentTarget.childNodes[0] was undefined, from which we were trying to extract the value.
=> Fix: handle dropdowns witth no items

templates/example-plans/020-StandardInfraConfig-default-with-mqtt.yaml, templates/example-plans/020-StandardInfraConfig-default.yaml
Adding a maxUnavailable: 1 setting to the default standard infra config examples. This will create a pod disruption budget for the brokers and routers in address spaces created with this standard infra config. 
This is building on the work by @lulf in these two PRs:
https://github.com/EnMasseProject/enmasse/pull/3694
https://github.com/EnMasseProject/enmasse/pull/3698
The PDB with a maxUnavailable of 1 will still work with a setup of a single broker and/or single router. Since one pod is allowed to be unavailable, having a single replica offline does not violate the pod disruption budget.
=> Add pdb creation to example infra config

CHANGELOG.md, standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, standard-controller/src/test/java/io/enmasse/controller/standard/AddressControllerTest.java
- Bugfix
When creating an address of type subscription, the topic field of its spec should reference a topic address by its address.  If it does not, the subscription address's status will now report the fact that it is absent.
=> Fix #3764: validate the topic refenced by a subscription actually exists

address-space-controller/Dockerfile, broker-plugin/Dockerfile, console/console-init/Dockerfile, console/console-init/oauth-proxy/bin/init.sh, controller-manager/Dockerfile, iot/iot-auth-service/Dockerfile, iot/iot-device-registry-file/Dockerfile, iot/iot-device-registry-infinispan/Dockerfile, iot/iot-device-registry-jdbc/Dockerfile, iot/iot-http-adapter/Dockerfile, iot/iot-lorawan-adapter/Dockerfile, iot/iot-mqtt-adapter/Dockerfile, iot/iot-sigfox-adapter/Dockerfile, iot/iot-tenant-cleaner/Dockerfile, iot/iot-tenant-service/Dockerfile, keycloak-plugin/Dockerfile, mqtt-gateway/Dockerfile, mqtt-lwt/Dockerfile, none-authservice/Dockerfile, service-broker/Dockerfile, standard-controller/Dockerfile, topic-forwarder/Dockerfile
- Refactoring
Given that fedora-minimal has been available for a while now and seems to be a common upstream for rhel-based images, I propose that we move to this. This should:
a) Hopefully fix CI issues with missing docker images
b) Reduce the image size
It would also change from installing jdk-devel to jdk-headless.
=> Reduce image footprint by using fedora minimal image as base image

Makefile.common
- Bugfix
The `docker build` target was missing in the `buildpush` of the Makefile.common. Which was leading to not building images when called from a module.
=> add docker build to the buildpush target in Makefile.common

CHANGELOG.md, broker-plugin/amqp-connector/src/main/java/org/apache/activemq/artemis/integration/amqp/AMQPConnectorService.java, pom.xml, systemtests/src/test/java/io/enmasse/systemtest/isolated/bridging/ForwardersTest.java
- Refactoring
* Ensure that MODIFIED outcome is used for transient errors
* Ensure that REJECT outcome causes a retry instead of ending up on the
global DLQ
@k-wall Should we make this option (especially the REJECT behavior) configurable in the infra configs?
=> Set default behavior of rejects

address-space-controller/src/main/resources/templates/brokered-space-infra.yaml, address-space-controller/src/main/resources/templates/standard-space-infra.yaml, standard-controller/src/main/resources/templates/queue-persisted.yaml, standard-controller/src/main/resources/templates/topic-persisted.yaml
- Bugfix
The current affinity settings does not get applied as they are placed
directly under deployment.spec and statefulset.spec
Fixes #3646
=> Put default affinity spec under podTemplate spec

pkg/consolegraphql/watchers/resource_watcher_agent.go, pkg/consolegraphql/watchers/resource_watcher_agent_test.go
existing algorithm used two nested loops to process each link, which could have resulted in n^2 iterations (where n is the number of links) which could be costly for a connection with many links.
the intent is the new code is functionally equal to the old.
=> refactor link processing

cmd/controller-manager/main.go, pkg/custom-metrics/custom_metrics.go
Relevant issue - https://issues.redhat.com/browse/INTLY-5106
Verification can be completed with Enmasse deployed in cluster, or running locally.
- Install the operator
- Replace operator image with `quay.io/robrien/controller-manager:add-custom-metrics`. This image was built from this feature branch
- Within the operator pod, run the following command:
`curl http://<pod_ip_address>:8383/metrics`
- Ensure the the output of the preceding step contains a custom metric that displays both the operator version, and product version. The operator version in this instance is `latest`, with the product version being `0.31-SNAPSHOT`.
```
enmasse_version_info{operator_version="latest",version="0.31-SNAPSHOT"} 0
```
**Locally**
- Install and run the operator locally, using …
=> Add operator and product version custom metric

console/console-init/ui/mock-console-server/README.md, console/console-init/ui/mock-console-server/mock-console-server.js, console/console-init/ui/mock-console-server/schema.js, console/console-init/ui/mock-console-server/test/mock.js, console/console-server/src/main/resources/gqlgen.yml, console/console-server/src/main/resources/schema.graphql, pkg/consolegraphql/resolvers/generated.go, pkg/consolegraphql/resolvers/resolver_address.go, pkg/consolegraphql/resolvers/resolver_address_test.go, pkg/consolegraphql/resolvers/test_utils.go
To simplify the UI, the server should default the address resource name from the address if it is not specified.
=> Default address resource name from address

console/console-init/ui/src/Components/AddressSpaceList/AddressSpaceList.tsx, console/console-init/ui/src/Pages/AddressSpaceList/AddressSpaceListPage.tsx, console/console-init/ui/src/Pages/EditAddressSpace.tsx, console/console-init/ui/src/Queries/Queries.tsx, console/console-init/ui/src/Types/ResponseTypes.tsx, console/console-init/ui/src/stories/AddressSpaceList.stories.tsx
- Bugfix
The authentication service of address spaces can now be edited. The auth service is now being fetched with the all_address_spaces query, and populated accordingly in the AddressSpaceEdit component. Saving handles the patch for auth_service.
=> Fix: edit auth service

pkg/consolegraphql/filter/filter_test.go, pkg/consolegraphql/non_kubernetes_types.go
The JSON tags were missing on the fields of the data types used to back the GraphQL API.  This prevented JSON path expressions being written in terms of the json fields names.  With this change expressions in terms of Go field names and JSON field names are supported for both order by and filter clauses.
=> Add missing json tags to connections, link objects etc

CHANGELOG.md, documentation/modules/ref-example-roles.adoc, templates/example-roles/020-ClusterRole-service-admin.yaml
Allow the service admin example role the ability to modify authenticationservices.
=> Updating service admin cluster role to include AuthenticationService

templates/iot/examples/infinispan/manual/050-StatefulSet.yaml
Currently our tests fail to deploy our infinispan example deployment in Openshift 4.4 because of the limits on cpu we have on that deployment.
Just removing the limits work, I also tried to reduce the limits to 0.25 and also work.
=> Example infinispan deployment remove cpu limits

console/console-init/ui/src/pages/AddressDetail/AddressLinksFilter.tsx
If you search text was exactly 5 characters, it was returning 'No results Found'.
Changed it so it would lookup the results if it was 5 characters or more.
- Bugfix
- Refactoring
=> Fix Console server typeahead

cmd/console-server/main.go, console/console-init/ui/mock-console-server/mock-console-server.js, pkg/consolegraphql/resolvers/resolver_user.go, pkg/controller/consoleservice/consoleservice_controller.go, pkg/controller/consoleservice/domain.go, pkg/util/openshift.go
- Bugfix
Switched console-server code to use new HasApi() call and fix the HasApi) implementation
to cope the the user GVK object (special case required).  Also propagated the
`NAMESPACE` environment var from EnMasse controller to console-server.
=> Ensure that logged user name appears next to avatar in the UI

documentation/common/restapi-reference.adoc, documentation/src/main/resources/swagger.json
In the swagger based documentation, the authorisation operation is documented as "receive" whereas in the code the value is "recv".
=> Issue #3582 - fix swagger documentation for auth ops

k8s-api/src/main/java/io/enmasse/k8s/api/cache/EventCache.java, k8s-api/src/main/java/io/enmasse/k8s/api/cache/Reflector.java, k8s-api/src/main/java/io/enmasse/k8s/api/cache/WorkQueue.java, k8s-api/src/test/java/io/enmasse/k8s/api/cache/EventCacheTest.java
- Bugfix
If the resourceVersion of objects may change between list and watch, the
watch may be closed immediately after creation. To avoid waiting for the
next resync, trigger a new resync if the exception has the 410 Gone
status.
=> Add wakeup event to trigger resync on outdated resource version

console/console-init/ui/package.json, console/console-init/ui/src/constants/constants.ts, console/console-init/ui/src/pages/CreateAddress/CreateAddressPage.tsx, console/console-init/ui/src/pages/CreateAddress/PreviewAddress.tsx, console/console-init/ui/src/queries/Address.ts, console/console-init/ui/src/queries/AddressSpace.ts, console/console-init/ui/src/queries/User.ts
The server should default the address resource name from the address if not specified.
Prettified the .ts files with prettier.
Front-end changes for #3838 
- Bugfix
- Refactoring
=> Chore: default the address resource name from adddress

cmd/console-server/main.go, console/console-server/src/assembly/unix-dist.xml, console/console-server/src/main/resources/probe.sh, pkg/controller/consoleservice/consoleservice_controller.go
Adds a readiness/liveness probe to the console-server to ensure that it is minimally functional.
=> Add console-server readiness/liveness probe

console/console-init/ui/src/pages/AddressSpaceDetail/AddressList/AddressListPage.tsx, console/console-init/ui/src/queries/index.ts
- Bugfix
The dialogues in address list page weren't closing after a successful patch or delete operation. The issues were arising due to typos. This commit also adds copyright statement to one of the source file.
=> Fix: close the dialogue after address delete/patch

systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java, systemtests/src/main/java/io/enmasse/systemtest/logs/GlobalLogCollector.java, systemtests/src/main/java/io/enmasse/systemtest/manager/ResourceManager.java
This should fix the EOFException we are getting in shared tests jobs because in the case of creating and deleteing lots of address space systemetsts will leak lots of watches
=> fix leaking watches in systemtests

pom.xml
When using the Eclipse IDE, having M2E (maven integration) configured, it already took a while to process the console project, due to the npm maven integration.
After merging the new console branch, it took for me around 10 minutes on 100% CPU every time it made a change to a resource in the console project, including things likes switching a branch.
This PR disables the npm targets in the Eclipse IDE. I don't think anybody will miss it.
=> Disable the npm maven plugin in Eclipse M2E

agent/lib/broker_controller.js, agent/lib/router_stats.js
- Bugfix
In the brokered address space, the agent generated consumer uuids were colliding, resulting in missing receiver links on the connection and address detail pages.
=> In broker address space, include session id in the formation of the consumer uuid

hack/generate_resource_watchers.go, pkg/consolegraphql/watchers/resource_watcher_address.go, pkg/consolegraphql/watchers/resource_watcher_addressplan.go, pkg/consolegraphql/watchers/resource_watcher_addressspace.go, pkg/consolegraphql/watchers/resource_watcher_addressspaceplan.go, pkg/consolegraphql/watchers/resource_watcher_addressspaceschema.go, pkg/consolegraphql/watchers/resource_watcher_agent.go, pkg/consolegraphql/watchers/resource_watcher_authenticationservice.go, pkg/consolegraphql/watchers/resource_watcher_namespace.go
Ensure that the error that causes the watch to restart is written to the log.
=> Log reason for watch restart / improve handling of watch channel read failure

CHANGELOG.md, console/console-init/ui/src/pages/CreateAddress/CreateAddressDefinition.tsx, console/console-init/ui/src/pages/CreateAddress/CreateAddressPage.tsx, console/console-init/ui/src/pages/CreateAddress/PreviewAddress.tsx, console/console-init/ui/src/pages/CreateAddressSpace/CreateAddressSpaceConfiguration.tsx, console/console-init/ui/src/queries/Address.ts, console/console-init/ui/src/types/Configs.tsx, templates/crds/addresses.crd.yaml
- Bugfix
Address CRD now validates that the address.spec.address field comprises only legal characters (i.e. not # * . : or whitespace).  Same validation now applied by the create address workflow in the UI too.
Fixed the address command preview (needed to pass the addressspace name as an argument) in order to allow the server to default 
Fixed a couple of typos (misspelt names in the code).
=> Address.spec.address name validation 

cmd/console-server/main.go, hack/generate_resource_watchers.go, pkg/consolegraphql/cache/cache.go, pkg/consolegraphql/watchers/resource_watcher.go, pkg/consolegraphql/watchers/resource_watcher_address.go, pkg/consolegraphql/watchers/resource_watcher_address_test.go, pkg/consolegraphql/watchers/resource_watcher_addressplan.go, pkg/consolegraphql/watchers/resource_watcher_addressspace.go, pkg/consolegraphql/watchers/resource_watcher_addressspaceplan.go, pkg/consolegraphql/watchers/resource_watcher_addressspaceschema.go, pkg/consolegraphql/watchers/resource_watcher_agent.go, pkg/consolegraphql/watchers/resource_watcher_authenticationservice.go, pkg/consolegraphql/watchers/resource_watcher_namespace.go, pkg/consolegraphql/watchers/resource_watcher_namespace_test.go
- Bugfix
A defect in the update path meant that *every* update of an address (or address space) resource causes the watcher to restart.  This would cause all resources to be restarted and the watch
re-established.   This would result on unnecessary load on the kubernetes api-server and the console.
=> Bug fix - prevent address space and address watchers spinning on resource update

hack/generate_resource_watchers.go, pkg/consolegraphql/watchers/resource_watcher_address.go, pkg/consolegraphql/watchers/resource_watcher_addressplan.go, pkg/consolegraphql/watchers/resource_watcher_addressspace.go, pkg/consolegraphql/watchers/resource_watcher_addressspaceplan.go, pkg/consolegraphql/watchers/resource_watcher_addressspaceschema.go, pkg/consolegraphql/watchers/resource_watcher_agent.go, pkg/consolegraphql/watchers/resource_watcher_authenticationservice.go, pkg/consolegraphql/watchers/resource_watcher_namespace.go
- Bugfix
the code omitted to call `watcher.Stop()` meaning client/server resources were likely being leaked.
=> bug fix: unconditionally free watcher resources

cmd/console-server/main.go, console/console-init/ui/src/queries/Address.ts, console/console-init/ui/src/queries/AddressSpace.ts, pkg/consolegraphql/cache/console_cache.go, pkg/consolegraphql/filter/lex.go, pkg/consolegraphql/filter/lex.rl, pkg/consolegraphql/filter/parser.go, pkg/consolegraphql/filter/parser.y, pkg/consolegraphql/filter/support.go, pkg/consolegraphql/metric/metric_updater_test.go, pkg/consolegraphql/resolvers/resolver.go, pkg/consolegraphql/resolvers/resolver_address.go, pkg/consolegraphql/resolvers/resolver_addressspace.go, pkg/consolegraphql/resolvers/resolver_connection.go, pkg/consolegraphql/resolvers/resolver_test.go, pkg/consolegraphql/watchers/resource_watcher_agent.go
If the filter query is passed, use it to construct the longest hierarchy key to maximise use of the index.  This is helpful on the addressspace/address/connection 'detail' pages where otherwise the resolver may need to filter all (worst case) addressspace/address/connection to locate the subject of the page.
=> If the filter is passed to query, use it to construct the longest hierarchy key

systemtests/src/test/java/io/enmasse/systemtest/shared/standard/PlansTest.java
Fixes PlansTest disabling it at the class level as well because a class with all tests disabled at method level makes JunitCallbackListener throw errors
=> disable PlansTest

agent/lib/router_stats.js
- Bugfix
Add address-space-controller to the list of internal_identifiers used to exclude the AMQP containers relating to internal components.
=> Add address-space-controller to the list of container ids considered internal

cmd/console-server/main.go, hack/generate_resource_watchers.go, pkg/consolegraphql/watchers/resource_watcher_address.go, pkg/consolegraphql/watchers/resource_watcher_address_test.go, pkg/consolegraphql/watchers/resource_watcher_addressplan.go, pkg/consolegraphql/watchers/resource_watcher_addressspace.go, pkg/consolegraphql/watchers/resource_watcher_addressspaceplan.go, pkg/consolegraphql/watchers/resource_watcher_addressspaceschema.go, pkg/consolegraphql/watchers/resource_watcher_agent.go, pkg/consolegraphql/watchers/resource_watcher_agent_test.go, pkg/consolegraphql/watchers/resource_watcher_authenticationservice.go, pkg/consolegraphql/watchers/resource_watcher_namespace.go, pkg/consolegraphql/watchers/resource_watcher_namespace_test.go
This limits the duration of the watch, regardless of any activity or inactivity.  Previously it seems a default of 1 minute was being imposed from the client causing excessive resynching.
- Bugfix
=> Pass timeoutSeconds param when creating resource watcher 

CHANGELOG.md, console/console-init/ui/src/pages/CreateAddress/CreateAddressDefinition.tsx, console/console-init/ui/src/pages/CreateAddress/CreateAddressPage.tsx, console/console-init/ui/src/pages/CreateAddress/PreviewAddress.tsx, console/console-init/ui/src/pages/CreateAddressSpace/CreateAddressSpaceConfiguration.tsx, console/console-init/ui/src/queries/Address.ts, console/console-init/ui/src/types/Configs.tsx, templates/crds/addresses.crd.yaml
Address CRD now validates that the address.spec.address field comprises only legal characters (i.e. not # * or whitespace). Same validation now applied by the create address workflow in the UI too.  The UI validation is less strict than that applied by the previous console. 
Fixed the address command preview (needed to pass the addressspace name as an argument) in order to allow the server to default
Fixed a couple of typos (misspelt names in the code).
=> Address.spec.address name validation (now allowing : .)

CHANGELOG.md, api-model/src/main/java/io/enmasse/address/model/AddressTypeInformation.java, api-model/src/main/java/io/enmasse/address/model/Schema.java, k8s-api/src/main/java/io/enmasse/k8s/api/KubeSchemaApi.java
- Bugfix
The code was reading from currentAddressSpacePlans etc whilst holding the mutex, but the write
was made without.  Other threads (the other watching threads) were seeing stale values and therefore writing incomplete addressspacechema records.
=> Address unsafe publication to volatiles used to form the schema

address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceController.java, address-space-controller/src/main/java/io/enmasse/controller/DefaultsController.java, address-space-controller/src/main/java/io/enmasse/controller/common/Kubernetes.java, address-space-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java, address-space-controller/src/main/resources/templates/brokered-space-infra.yaml, address-space-controller/src/main/resources/templates/standard-space-infra.yaml, api-model/src/main/java/io/enmasse/config/AnnotationKeys.java
- Bugfix
This adds an extra annotation with the namespace of the address space to the 'messaging' Service resource that is created for every address space. In the event that an address space is replaced and the annotations are lost, they can be recovered from the service resource in the reconciliation loop.
This fix is a lot simpler than my original which were to introduce status subresource for address and address space, as that would have required upgrading kubernetes-client again. I think we should keep AddressSpace and Address as they are for now.
=> Ensure infra uuid is not lost on replace

console/console-init/ui/src/components/common/NoDataFound.tsx, console/console-init/ui/src/pages/AddressDetail/AddressDetailPage.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/AddressSpaceDetailPage.tsx, console/console-init/ui/src/pages/ConnectionDetail/ConnectionDetailPage.tsx
- Bugfix
- If a connection closed whilst the user is view the links of the connection, the browser goes blank. I would expect a message to display informing the user that the connection is gone and allowing them to navigate back to the address or connection list. The issue is the same for both standard and brokered address spaces.
=> display empty state page if server returns empty array for any query

console/console-init/ui/src/pages/CreateAddressSpace/CreateAddressSpaceConfiguration.tsx, console/console-init/ui/src/types/Configs.tsx, pkg/consolegraphql/resolvers/resolver_address.go, pkg/consolegraphql/resolvers/resolver_address_test.go
- Bugfix
When the user supplies an address space name through the UI, the UI should ensure it meets the specification [1].  Also when the backend generates an address resource name from an address it must ensure that the resulting name conforms to the same.
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names
=> Ensure address-space and generated address resource names meet RFC 1123

api-model/src/main/java/io/enmasse/address/model/Schema.java, k8s-api/src/main/java/io/enmasse/k8s/api/KubeSchemaApi.java, k8s-api/src/test/java/io/enmasse/k8s/api/KubeSchemaApiTest.java, olm-manifest/src/main/resources/latest/enmasse.clusterserviceversion.yaml, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java, templates/address-space-controller/020-Role-address-space-admin.yaml, templates/address-space-controller/020-Role-address-space-controller.yaml
- Refactoring
Removes consoleservice from KubeSchemaApi and its associated watcher. This was required only to propagate console information to the addressspace agents. With the removal of the address space specific consoles, this code is redundant.
Removed the address-space-controller roles that supported the read of this resource too.
=> Remove consoleservice from KubeSchemaApi (dead code)

hack/generate_resource_watchers.go, pkg/consolegraphql/watchers/resource_watcher_address.go, pkg/consolegraphql/watchers/resource_watcher_address_test.go, pkg/consolegraphql/watchers/resource_watcher_addressplan.go, pkg/consolegraphql/watchers/resource_watcher_addressspace.go, pkg/consolegraphql/watchers/resource_watcher_addressspaceplan.go, pkg/consolegraphql/watchers/resource_watcher_addressspaceschema.go, pkg/consolegraphql/watchers/resource_watcher_authenticationservice.go, pkg/consolegraphql/watchers/resource_watcher_namespace.go, pkg/consolegraphql/watchers/resource_watcher_namespace_test.go
- Bugfix
The console's Accesscontrol mechanism requires that GVK is available on all objects in the cache.   While the go-client lists populate the GVK, unfortunately watches do not.  We now set the GVK if it is absent before placing the object in the cache.
=> Ensure that GVK is set all objects in the cache.

ansible/playbooks/openshift/uninstall.yml, documentation/modules/proc-uninstalling-using-olm-console.adoc, documentation/modules/proc-uninstalling-using-olm.adoc, documentation/modules/proc-uninstalling.adoc, pkg/controller/consoleservice/consoleservice_controller.go, systemtests/src/main/java/io/enmasse/systemtest/operator/OperatorManager.java
- Bugfix
The documentation needs to call out a manual step to remove the consolelink.  This is OpenShift 4 only step.
=> Document remove console link step

templates/crds/addresses.crd.yaml
- Bugfix
To avoid a behavioural change, weaken the address validation imposed by the server to permit the router # and * wildcards.   I left the UI validation unchanged.
=> Weaken address validation to permit router wildcards

pkg/consolegraphql/resolvers/resolver_addressspace_test.go, pkg/consolegraphql/resolvers/utils.go
- Bugfix
Remove spurious `creationTimestamp: null` (and the metadata container, which will be empty) from address space command preview.
=> Remove spurious creationTimestamp from address space command preview

controller-manager/src/main/resources/templates/PrometheusRules-enmasse.yaml, pkg/controller/authenticationservice/authenticationservice_controller.go, pkg/custom-metrics/custom_metrics.go
Updated the authentication service status to reflect whether the necessary deployments are created or not and added an alert which leverages this status to notify about unavailable authentication services.
=> Authservice status metric

console/console-init/ui/src/pages/CreateAddressSpace/CreateAddressSpaceConfiguration.tsx
- Bugfix
remove css used for adjusting the namespace label in dropdown in create address space wizard
=> remove css used for adjusting casing in the namespace

CHANGELOG.md, address-space-controller/src/main/java/io/enmasse/controller/common/Kubernetes.java, address-space-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java, address-space-controller/src/test/java/io/enmasse/controller/ComponentFinalizerControllerTest.java
- Bugfix
Wait for deployment pods to be deleted
This prevents the standard-controller from re-creating resources that  gets deleted after the deployments are deleted.
=> Wait for pods to be removed

documentation/assemblies/assembly-metrics-rules.adoc, documentation/assemblies/assembly-monitoring.adoc
Docs fix to add parent context to two assemblies
=> Docs: add parent context to assemblies to fix build errors

pom.xml
- Bugfix
hibernate-validator  6.0.17.Final  contains vulnerability CVE-2019-10219.  Whilst it is believed this vulnerability is not exploitable from EnMasse (it does not use the HTML validation feature), it makes sense to upgrade to fixed version on the 6.0 line.
We tried this before #3629, but at that point a vulnerability fix on the 6.0 release line was not available.
=> Bump hibernate-validator from 6.0.17.Final -> 6.0.18.Final (CVE-2019-10219)

pkg/apis/user/v1beta1/types.go
This caused a lot of logging in enmasse-operator during upgrade tests which created users with operation 'manage' without any addresses
=> Allow addresses field to be optional

console/console-init/ui/package.json, console/console-init/ui/yarn.lock
- Bugfix
Bumps the micro revision on the following transitive dependencies.
Bump kind-of from 6.0.2 to 6.0.3
Bump request from 2.88.0 to 2.88.2
Bump elliptic from 6.5.1 to 6.5.2.
Bump react-popper from 1.3.4 to 1.3.5
Bump (dev) dependency handlebars 4.4.3 => 4.5.3
=> Bump yarn dependencies (on a few transitive dependencies).

console/console-init/ui/src/components/AddressSpaceList/AddressSpaceList.tsx
- Bugfix
- FIX - list page row kebab menu not fully visible
=> add padding in bottom of table to avoid scrolling for kebab

console/console-init/ui/src/pages/CreateAddress/PreviewAddress.tsx, console/console-init/ui/src/pages/CreateAddressSpace/ReviewAddressSpace.tsx
- Enhancement
The preview of AddressSpace and Address creation wizards now show visual feedback upon successful copy to clipboard.
The feedback is looking something like this :
=> Chore: show visual feedback upon sccessful copy to clipboard

address-space-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java, ansible/playbooks/openshift/uninstall.yml, documentation/modules/proc-uninstalling-using-olm.adoc, documentation/modules/proc-uninstalling.adoc, systemtests/src/main/java/io/enmasse/systemtest/operator/OperatorManager.java, systemtests/src/main/java/io/enmasse/systemtest/platform/KubeCMDClient.java
- Bugfix
The finalizer now waits until pods are
terminated before marking an address space finalized, therefore
finalization is taking longer.
Setting the timeout flag prevents the delete command to timeout when waiting for address spaces to be finalized.
=> Add timeout flag when deleting CRDs

documentation/assemblies/assembly-metrics-rules.adoc
Add missing closing single quote on module ID
=> Docs: fix missing single quote on module ID

agent/lib/broker_stats.js
- Bugfix
There's a missing catch block on the broker stats path.   I would expect that control would flow down this path when a broker pod is going away during stats retrieval.   As the broker stats ae triggered by a timer, I don't think the absence of this block would give rise to a functional defect.
Could explain the `UnhandledPromiseRejectionWarning` (#3739) warnings we occasionally see in the agent's log.
=> Add missing promise catch in broker stats retrieval

documentation/assemblies/assembly-iot-device-developer-guide.adoc, documentation/assemblies/assembly-iot-device-manager-guide.adoc, documentation/assemblies/assembly-iot-getting-started.adoc, documentation/assemblies/assembly-iot-guide.adoc, documentation/assemblies/assembly-iot-project-owner-guide.adoc, documentation/assemblies/assembly-iot-service-admin-guide.adoc, documentation/assemblies/assembly-iot-solution-developers-guide.adoc, documentation/assemblies/assembly-iot-tenant-guide.adoc, documentation/assemblies/assembly-rules.adoc, documentation/assemblies/assembly-service-admin-guide.adoc
Missing closing single quote on assembly IDs
=> Docs: fix missing closing single quote on assembly IDs

pkg/controller/address_space_controller/controller.go
- Bugfix
Fixed a bug which was causing the service for the address-space-controller to not be created.
=> Create address-space-controller service

cmd/controller-manager/main.go, controller-manager/src/main/resources/templates/PrometheusRules-enmasse.yaml, pkg/controller/address_space_controller/controller.go, pkg/controller/consoleservice/consoleservice_controller.go, pkg/util/install/utils.go
- Refactoring
Modified the console Prometheus rule to only be created when the console is created
=> Create console alert only when console is created

console/console-init/ui/src/components/AddressSpaceList/AddressSpaceListFilter.tsx
- Bugfix
- Fix - unable to delete address space filter chip for type
=> Unable to delete address space filter chip by type

console/console-init/ui/src/pages/AddressSpaceDetail/AddressSpaceDetailPage.tsx
- Bugfix
- FIx - delete address space space dialogue doesn't pop down
=> fix-issue delete space modal doesn't pop down

systemtests/src/test/java/io/enmasse/systemtest/isolated/catalog/ServiceCatalogWebTest.java
- Bugfix
Fix ExternalMessagingClient cmd line for ServiceCatalogWebTest#testSendReceiveInsideCluster
=> fix ExternalMessagingClient cmd line for ServiceCatalogWebTest#testSendReceiveInsideCluster

console/console-init/ui/src/components/common/NoDataFound.tsx, systemtests/src/test/java/io/enmasse/systemtest/isolated/catalog/ServiceCatalogWebTest.java
- Bugfix
Test was still looked for the behaviour from the old console.  I needed to add an id to the NoDataFound tsx to be able to detect the content from the test.
=> Fix ServiceCatalogWebTest#testConsoleErrorOnDeleteAddressSpace

console/console-init/ui/src/components/AddressSpaceList/EmptyAddressSpace.tsx, console/console-init/ui/src/components/common/EmptyLinks.tsx, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java
- Bugfix
Test needs to check for the EmptyState component rather thann an empty table.
=> Fix FirefoxConsoleTest#testFilterAddressSpace

address-space-controller/src/main/java/io/enmasse/controller/RouterStatusCache.java, address-space-controller/src/test/java/io/enmasse/controller/RouterStatusCacheTest.java
- Bugfix
- Refactoring
Fix a potential race where the status cache would get updated
with an entry after an address space has been deleted. This fix ensures
that the current list of address spaces known and the router status
cache is in sync.
Add unit test for router status cache to ensure correct behavior.
=> Ensure that router status cache is consistent

console/console-init/ui/mock-console-server/mock-console-server.js, console/console-init/ui/mock-console-server/schema.js, console/console-server/src/main/resources/schema.graphql, pkg/consolegraphql/non_kubernetes_types.go, pkg/consolegraphql/resolvers/generated.go, pkg/consolegraphql/resolvers/resolver_connection.go, pkg/consolegraphql/watchers/resource_watcher_agent.go
Connection principal had been omitted from the GraphQL layer in error.   This is now populated with data from the agent.
=> console backend - expose connection prinicpal at graphql layer

pkg/controller/iotconfig/data.go
- Bugfix
Ignore vert.x warning until https://github.com/eclipse-vertx/vert.x/pull/3316 is fixed.
=> Ignore vert.x ssl check warnings for now

pkg/consolegraphql/watchers/resource_watcher_agent.go
- Bugfix
The watcher responsible for agents was incorrectly applying its resyncinterval to the underlying kubernetes watch call, so the services were never being resync.
=> Fix improperly applied resyncinterval

documentation/modules/proc-uninstalling-using-olm.adoc
Docs: Change `OperatorNamespace` variable to `OperatorName`
=> Docs issue-4022: fix OperatorNamespace variable

cmd/console-server/main.go
- Bugfix
Change the console-server to log using UTC time-stamps using millisecond precision to facilitate easy correlation with the logs of other components which already use the same format.
=> console server - log using UTC time-stamps to millisecond precision

console/console-init/ui/src/components/AddressSpaceList/AddressSpaceListFilter.tsx, console/console-init/ui/src/pages/AddressDetail/AddressLinksFilter.tsx, console/console-init/ui/src/pages/AddressDetail/AddressLinksListPage.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/AddressList/AddressListFilter.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/AddressList/AddressListFilterPage.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/AddressSpaceDetailPage.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/ConnectionList/ConnectionListFilter.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/ConnectionList/ConnectionsListPage.tsx, console/console-init/ui/src/pages/AddressSpaceList/AddressSpaceListFilterPage.tsx, console/console-init/ui/src/pages/AddressSpaceList/AddressSpaceListPage.tsx, console/console-init/ui/src/pages/ConnectionDetail/ConnectionDetailPage.tsx, console/console-init/ui/src/pages/ConnectionDetail/ConnectionLinksFilter.tsx, console/console-init/ui/src/pages/ConnectionDetail/ConnectionsLinksListPage.tsx
- Bugfix
- add fetchPoilcy as network-only for all graphql query to avoid caching
=> add netork-only as fetch policy for all queries

pkg/controller/consoleservice/consoleservice_controller.go, pkg/util/openshift.go
- Bugfix
For 0.31, we changed the way openshift was detected to use make an API refactoring the `detectOpenshift` function in the process to use `Route`.  Unfortunately, this brought with it an implict requirement that the service account running the code had access to that API.  For the console-server process, this wasn't the case.
* Switched `detectOpenshift` to use `user.openshift.io`.
* also propagared ENMASSE_OPENSHIFT from the enmasse-operator to the console-server to allow the check to the short circuited in environments where OpenShift is a certainty.
=> Use user.openshift.io to make the determination about openshift rather than route.openshift.io

console/console-init/oauth-proxy/cfg/oauth-proxy-kubernetes.cfg
@k-wall This fixes an issue for me attempting to run the console on Kubernetes where I see the oauth proxy getting 404, whereas adding this same line that exists in the oauth-proxy-openshift.cfg, I get a 401 instead (which I think might is a separate issue). Thought I'd raise this PR in case this should be added.
=> Add console-server to upstream urls for Kubernetes

console/console-init/ui/mock-console-server/README.md, console/console-init/ui/mock-console-server/test/graphql.js, console/console-init/ui/src/pages/CreateAddress/CreateAddressPage.tsx, console/console-init/ui/src/queries/Address.ts
- Bugfix
* The filter was assuming the addresses have spec.addressSpace populated. this is not the case.
* Changed address creation not to set the spec.addressSpace field when creating new addresses
=> Correct filter used to support type ahead address search

cmd/console-server/main.go, pkg/consolegraphql/server/handler.go, pkg/consolegraphql/server/handler_test.go
To support the kubernetes case (when pusher's oauth-proxy is in use), take the bearer token from the `Authorization` header if `X-Forwarded-Access-Token` is not set.
=> Console Server - fallback to authorization header if X-Forwarded-Access-Token is not populated

console/console-init/ui/src/pages/AddressDetail/AddressDetailPage.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/AddressList/AddressListPage.tsx, console/console-init/ui/src/pages/CreateAddress/CreateAddressDefinition.tsx, console/console-init/ui/src/pages/EditAddressPage.tsx
- Bugfix
- Refactoring
- fix issue - console does not show custom address plan properly.
- show metadata.name as label for plan if spec.displayName is not present in response of addressPlan
=> Fix - console does not show custom address plan properly

console/console-init/ui/src/pages/CreateAddressSpace/CreateAddressSpaceConfiguration.tsx, console/console-init/ui/src/queries/Address.ts
- Bugfix
- Enhancement
- fix - Mismatch in contents of dropdown for plan in address and address space
- add label and short description for address space plan dropdown similar to address plan dropdown.
=> add label and description in plan for address space

CHANGELOG.md, agent/lib/qdr.js, agent/lib/router.js
- Bugfix
Avoid memory leak if connected router is disconnected.
=> Fix #4076: avoid memory leak if connected router is disconnected

agent/bin/agent.js, agent/lib/qdr.js, agent/lib/ragent.js
- Bugfix
#4040 added an idle timeout to the Agent's container when connecting to the Brokers and Routers. Testing showed the the the idle timeout was too short, and this resulted in spurious connection aborts (which triggered #4077)
Increased the idle timeout.
Corrects the use of Rhea API to pass the idle_time_out as an option.
=> Increase the AMQP idle timeout

documentation/Makefile, documentation/modules/con-standard-subscription.adoc, scripts/check_docs.sh
- Bugfix
The check_docs.sh script never checked anything the way it got called. Also did it check all excluded files again via the "html" folder. There was an actual issue discovered when it finally ran.
I also changed the default target of the makefile from "fetch swagger" to "build", which makes more sense to me.
=> Fix calling the check_doc, define default target, fix doc issues

address-space-controller/src/main/java/io/enmasse/controller/AbstractFinalizerController.java, address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceController.java, address-space-controller/src/main/java/io/enmasse/controller/Controller.java, address-space-controller/src/main/java/io/enmasse/controller/ControllerChain.java, address-space-controller/src/main/java/io/enmasse/controller/RouterConfigController.java, address-space-controller/src/main/java/io/enmasse/controller/StatusController.java, address-space-controller/src/main/java/io/enmasse/controller/StatusInitializer.java, address-space-controller/src/test/java/io/enmasse/controller/AddressFinalizerControllerTest.java, address-space-controller/src/test/java/io/enmasse/controller/ControllerChainTest.java, address-space-controller/src/test/java/io/enmasse/controller/CreateControllerTest.java, address-space-controller/src/test/java/io/enmasse/controller/EndpointControllerTest.java, address-space-controller/src/test/java/io/enmasse/controller/RouterConfigControllerTest.java, address-space-controller/src/test/java/io/enmasse/controller/StatusControllerTest.java
- Bugfix
This change ensures that finalizers are persisted immediately and that
we don't orphan resources created if address space was deleted before
finalizers are persisted.
=> Ensure finalizers are persisted immediately

console/console-init/ui/src/pages/CreateAddress/CreateAddressDefinition.tsx, console/console-init/ui/src/pages/CreateAddressSpace/CreateAddressSpaceConfiguration.tsx
- Bugfix
- add orientation for plan dropdown in create address space
- temporary fix using custom styles to avoid - data get hidden in right side if is too large(working with PF guys to fix this in PF4 Dropdown component)
- fix for this PR - https://github.com/EnMasseProject/enmasse/pull/4074
=> Fix- orientation issue in dropdown for plan in create address space

systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java
- Test fix
Fix for: ChromeConsoleTest.testFilterAddressSpace
When deleting 2 or more address spaces, the time allowed isn't always enough.
=> Test fix: Allow more time for deletion of multiple address spaces

agent/lib/artemis.js
Fixes #4081 
- Bugfix
Added the error handler to 'connection'. Used for both brokered and standard controller.
A 'connection_close' event will follow.  Therefore only logging the error.  See: https://github.com/amqp/rhea#error
=> Enhanced BrokerController's error handling for unhandled socket errors

CHANGELOG.md, api-server/src/main/java/io/enmasse/api/server/RequestLogger.java
- Bugfix
Use JAX-RS `@PreMatching` annotation of the api-server RequestLogger to ensure that 404 are processed without NPE
=> Fix handling of requests for resources that do not exist in api-server RequestLogger.

documentation/modules/proc-logging-in-console.adoc, documentation/modules/ref-view-message-conn-stats-table.adoc
Fix console access cmd formatting and add the two address/connection screenshots
=> Fix console access cmd formatting and add the two address/connection screenshots

systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java
- Bugfix
Examning a test failure for a CI run of ForwardersTest show us more time should be allowed for the external broker to start-up.
=> Allow more time for the external broker to start in ForwardersTest

systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java
- Bugfix
Purging a queue is an asynchronous operation.  Control may return to the UI before the operation completes.  Test needs to await the metric reaching zero before making the observation using the client.
=> Fix firefox console test test purge address

agent/lib/kubernetes.js, agent/test/kubernetes.js
- Bugfix
Ensure the watch is restarted on all paths (including initial connection refused etc).
=> Fix #4131: Ensure the watch is restarted on all paths

agent/lib/kubernetes.js
- Bugfix
Fixes #4134
Copies requestTimeout into timeoutSeconds on the query params
=> Add timeout to agent watches

systemtests/src/main/java/io/enmasse/systemtest/bases/ITestSeparator.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/H2DeviceRegistryTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/api/CustomResourceDefinitionAddressSpacesTest.java, systemtests/src/test/java/io/enmasse/systemtest/scale/ScaleTest.java
- Bugfix
The scale tests results file wasn't using the correct filename and some tests were using a logger that shouldn't be used
=> fix scale results filename and fix logger used in some tests

documentation/modules/con-standard-subscription.adoc
Docs: Minor edits to the subscription address type concept file to make it more clear
=> Docs issue 4143: minor edits to the subscription address type description

systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java, systemtests/src/main/java/io/enmasse/systemtest/scale/ScaleTestClientConfiguration.java, systemtests/src/main/java/io/enmasse/systemtest/scale/ScaleTestEnvironment.java, systemtests/src/main/java/io/enmasse/systemtest/scale/ScaleTestManager.java, systemtests/src/test/java/io/enmasse/systemtest/scale/ScaleTest.java
- Enhancement 
Comes from suggestion, to be prepared for representing iot usecase this PR adds ability to set the number of senders and receivers to create by the tenant client
=> Scale tests - set number of senders and receivers in tenant client

pkg/controller/iotconfig/auth_service.go, pkg/controller/iotconfig/http_adapter.go, pkg/controller/iotconfig/lorawan_adapter.go, pkg/controller/iotconfig/mqtt_adapter.go, pkg/controller/iotconfig/sigfox_adapter.go
- Bugfix
Vertx native support was only enabled for EnMasse IoT components, but not for vanilla Hono components. TLS native support was already enabled for all components.
=> Enable vertx native also for vanilla hono components

systemtests/src/main/java/io/enmasse/systemtest/platform/KubeCMDClient.java, systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/CommonTest.java
System test verifying behaviour when connection to the Kubernetes API server is lost
=> Test verifying Agent's behaviour when connection to the Kubernetes API server is lost

systemtests/src/main/java/io/enmasse/systemtest/manager/ResourceManager.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/plans/brokered/PlansTestBrokered.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/plans/standard/PlansTestStandard.java
- Bugfix
- Refactoring
Adds tests verifying the api server validates the plan of address spaces/addresses
=> Adds tests verifying the api server validates the plan of address spaces/addresses

standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java
- Bugfix
#4147 didn't completely eliminate the problem.  If the address space plan changes leaving an existing address with an illegal plan ref, the standard controller's processing loop aborts, leaving new addresses unprocessed.
This chnage prevent address with invalid plan from blocking standard controller reconcile loop
=> Prevent address with invalid plan from blocking standard controller reconcile loop

systemtests/src/test/java/io/enmasse/systemtest/isolated/plans/standard/PlansTestStandard.java
Test that an unknown address plan is reported properly through the address's status  It also
ensures that the presence of an address with an unknown plan does not impeded another valid address becoming ready.
=> Unknown address plan test

systemtests/src/main/java/io/enmasse/systemtest/platform/Minikube.java
- Bugfix
Adds `--url=true` to the minikube service cmd line to ensure compatibility with Minikube v1.8.
=> Add --url=true to the minikube service cmd line to ensure compatibility

iot/iot-device-registry-base/src/main/java/io/enmasse/iot/registry/debug/DebugEndpoint.java
Add another system property for the debug endpoint, allowing to have it enabled without turning on the whole springboot debug.
=> add another system property for the device registry debug endpoint

olm-manifest/src/main/resources/latest/enmasse.clusterserviceversion.yaml
These are no longer needed to pass operator scorecard test.
=> Remove examples for CRs that are created by default

systemtests/src/main/java/io/enmasse/systemtest/logs/GlobalLogCollector.java, systemtests/src/main/java/io/enmasse/systemtest/platform/KubeCMDClient.java
This makes it easier to debug issues where events in other namespaces
than the infra namespace could be relevant.
=> Collect all events in cluster on error

systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java
A change needs to be made to api-proxy to resolve a downstream problem (SCC related - see #4218), this changes lets me update the image without breaking the tests.
This change makes no functional change.
=> Reference api-proxy image by tag

iot/iot-jdbc-base/pom.xml, iot/iot-jdbc-base/src/main/java/io/enmasse/iot/jdbc/store/StatementConfiguration.java, iot/iot-jdbc-base/src/test/java/io/enmasse/iot/jdbc/store/StatementTest.java
=> Restrict YAML parser to not create Java objects

pkg/controller/authenticationservice/authenticationservice_controller.go, pkg/controller/authenticationservice/none.go, pkg/controller/authenticationservice/standard.go
- Bugfix
Ensure that all defaults are applied before performing any potentially
failing operations. This prevents an issue where other reconcile loops
were making assumptions defaults were set, whereas they were not set
due to a failing operation.
Fixes #4184
=> Apply defaults before performing impure operations

pkg/controller/consoleservice/consoleservice_controller.go
- Bugfix
Hard-coded namespace in Prometheus rules was causing alert to fire when EnMasse is installed to non-default namespace. Changed to use the infra namespace environment variable
=> Removed hardcoded namespace from console rule

address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceController.java, address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceControllerOptions.java, address-space-controller/src/main/java/io/enmasse/controller/auth/AuthController.java, pkg/controller/address_space_controller/controller.go
This allows for manging certificates for messaging endpoints using an
external infrastructure. The external infrastructure would use this
feature by reading the address space resource to find the name of the
secret that should be populated with the certificate.
=> Add support for disabling cert provosioning for external endpoints

systemtests/src/test/java/io/enmasse/systemtest/isolated/CommonTest.java
- Bugfix
The test was using the wrong labels - so the agent pod was not updated to use the proxy.
=> Fix brokered - testAddressSpaceKubernetesApiServerRestart

templates/iot/common/020-ClusterRole-qdr-configurator.yaml
- Bugfix
Without this permission, protocol adapters are failing to watch iot projects.
=> Add watch permission to iot projects to protocol adapter roles

pkg/controller/iotconfig/iotconfig_controller.go, pkg/controller/iotproject/iotproject_controller.go, pkg/controller/iotproject/managed.go, pkg/controller/messaginguser/messaginguser_controller.go, pkg/controller/messaginguser/messaginguser_controller_test.go, pkg/util/errors.go, pkg/util/errors_test.go, pkg/util/finalizer/finalizer.go, pkg/util/loghandler/handler.go, pkg/util/recon/reconcile.go, pkg/util/recon/reconcile_test.go
- Bugfix
- Refactoring
Reduced the number of changes generated by:
* Only updating when changes have been made
* No requesting re-queue when updates have been made
* Using requeueAfter in cases of a temporary error
* Detecting "non-recoverable" errors, and not re-trying in that case
=> Try reducing the number of changes when reconciling

systemtests/src/test/java/io/enmasse/systemtest/iot/IoTTestSessionTest.java
This test fails if the machine building the code is not running Kubernetes, which I think framework tests should require.
@ctron I'm just disabling it for now.
=> Disable framework test that requires Kubernetes to run

CHANGELOG.md, pkg/controller/upgrader/upgrader.go
- Bugfix
If these resources don't exist, the upgrade can still proceed as they
are not needed for upgrade process to run.
Fixes #4241
=> Allow deletion of api-server deployment and service to fail

CHANGELOG.md, pkg/controller/authenticationservice/standard.go
Change standard auth service to use AMQP port probe rather than probing the Keycloak `auth` endpoint.
=> Change standard auth service to use AMQP port probe

api-model/pom.xml
Sources got generated into:
* target/generated-sources/
* target/generated-sources/annotations
Which creates an overlap in the project source hierarchy.
The default of "jsonschema2pojo" already declared a sane default,
which got overridden by the enmasse build. This commit falls back
to the default.
=> Fix overlapping source directories

systemtests/src/main/java/io/enmasse/systemtest/executor/Exec.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/AbstractClient.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/ExternalMessagingClient.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/artemis/ArtemisJMSClientReceiver.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/artemis/ArtemisJMSClientSender.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/openwire/OpenwireJMSClientReceiver.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/openwire/OpenwireJMSClientSender.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/proton/java/ProtonJMSClientReceiver.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/proton/java/ProtonJMSClientSender.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/proton/python/PythonClientReceiver.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/rhea/RheaClientReceiver.java, systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java, systemtests/src/test/java/io/enmasse/systemtest/bases/clients/ClientTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/clients/artemis/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/clients/openwire/MsgPatternsTest.java
- Bugfix
This PR tries to make messaging client tests more stable, currently there are tests where receivers are started before senders and this is a source of failures in some environments...
To address that systemtests now detects when the receivers are attached reading the trace log from the clients, note some clients we use do not support any kind of trace log that we can use for this purpose.
a sleep in some tests where receivers are started before senders,
=> systemtests - cli clients tests - wait for receivers to attach

templates/iot/examples/iot-config.yaml
Fix a small issue introduced by Jens refactoring. 
The default deployment of the postgresql is in another namespace.
=> fix JDBC service url

CHANGELOG.md, pom.xml
Bump Netty dependency from netty-4.1.45.Final to netty-4.1.48.Final
=> Bump Netty to netty-4.1.48.Final

CHANGELOG.md, templates/crds/brokeredinfraconfigs.crd.yaml, templates/crds/standardinfraconfigs.crd.yaml
- Improvement
Field broker.globalMaxSize is missing from the standardinfraconfig and brokeredinfraconfig CRDs.
Applies regex that has same effect of that of ARTEMIS-873.
=> Add broker.globalMaxSize to the infraconfig CRDs

console/console-init/ui/src/pages/AddressSpaceDetail/AddressList/AddressListFilterPage.tsx, console/console-init/ui/src/pages/CreateAddress/CreateAddressDefinition.tsx, console/console-init/ui/src/pages/CreateAddress/CreateAddressPage.tsx, console/console-init/ui/src/queries/Address.ts
- Bugfix
- Handled null check for fetching queries to get address types and plans in create Address configuration view.
- Fix - #4279
=> Fix - Creating an address fails with message "address space plan '' not found"

console/console-init/ui/src/pages/AddressDetail/AddressDetailPage.tsx, console/console-init/ui/src/pages/AddressDetail/AddressLinksListPage.tsx
- Bugfix
- fix - 'Cannot read property 'links' of undefined' reported in browser console log after address deletion
=> add null check for links in address links page

systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java
ConnectorsTest have been failing several times failing to connect to the remote broker. Hoping a new broker will improve that, and maybe we should also consider to use an on-cluster client and turn of TLS.
=> Update broker image used in tests

.tekton/test/enmasse-repo.yaml, .tekton/test/systemtest-pipeline.yaml, .tekton/test/systemtest-task.yaml, Makefile, systemtests/Makefile
Ability to run enmasse systemtests as tekton pipeline on ocp4, this is only draft, it contains only fer params and it can test only master right now. But I will work more on that.
=> Run systemtests as tekton pipeline

.jenkins/Jenkinsfile-pr, systemtests/.gitignore, systemtests/Makefile, systemtests/custom-operator-registry/.gitignore, systemtests/custom-operator-registry/Dockerfile, systemtests/custom-operator-registry/Makefile, systemtests/custom-operator-registry/build_push_registry.sh, systemtests/custom-operator-registry/catalog-source.yaml, systemtests/custom-operator-registry/example_manifests_replacer.sh, systemtests/custom-operator-registry/operator-group.yaml, systemtests/custom-operator-registry/subscription.yaml, systemtests/pom.xml, systemtests/src/main/java/io/enmasse/systemtest/Environment.java, systemtests/src/main/java/io/enmasse/systemtest/bases/ITestBase.java, systemtests/src/main/java/io/enmasse/systemtest/logs/GlobalLogCollector.java, systemtests/src/main/java/io/enmasse/systemtest/manager/ResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/operator/OperatorManager.java, systemtests/src/main/java/io/enmasse/systemtest/platform/KubeCMDClient.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/utils/AddressSpaceUtils.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/CommonTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/upgrade/UpgradeTest.java
- Systemtest
Includes two new test for olm upgrade process, adds the files for our custom-operator-registry used for the tests(which could be used in future to replace the olm-manifests image). Adds two new env variables, used in the process of build and deploy the custom operator registry.
This PR also includes two commits from the 0.31.0 release branch which are missing in master branch and are important in order for this new tests to run properly
=> Systemtests olm upgrade

console/console-init/ui/src/utils/utils.ts
- Bugfix
- Remove "Enter more characters" option from the dropdown if there are less than 10 records in the dropdown because of duplicates data received from the server.
=> Remove "Enter more characters option" if rows are less than 10 in typeahead dropdown

console/console-init/oauth-proxy/cfg/oauth-proxy-kubernetes.cfg, console/console-init/oauth-proxy/cfg/oauth-proxy-openshift.cfg
- Bugfix
Revert the skip_provider_button change in order that OAuthProxy is able to retain the originally requested url (including the fragment) and redirect to it after successful authentication.
=> revert skip_provider_button change

console/console-init/ui/src/modules/address-space/containers/AddressSpaceListContainer/AddressSpaceListContainer.tsx, console/console-init/ui/src/modules/address-space/utils/AddressSpaceFormatter.tsx, console/console-init/ui/src/modules/address-space/utils/TableFormatter.tsx, console/console-init/ui/src/modules/connection/components/ConnectionList/ConnectionList.tsx, console/console-init/ui/src/utils/Formatter.tsx
- Bugfix
- FIx - The column Name\Namespace is displayed as column-1 in mobile view of Address Space List.
- Replace Configuring status with Pending status when the address and address space is not picked up by controller in the server side. As configuring status misleads the user.
=> fix-column1 for name/namespace column in mobile view

console/console-init/ui/src/graphql-module/queries/Connection.ts, console/console-init/ui/src/modules/address-detail/AddressDetailPage.tsx
- Bugfix
1. ConnectionLinks:  Filter not working as expected for address category (for like operator)
2. Address Detail: After delete route didn't change
=> Fixed connectionLinks filter issue for address and delete address route isssue

CHANGELOG.md, agent/lib/internal_address_source.js, agent/test/internal_address_source.js, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/QueueTest.java
- Bugfix
Comparing addresses using their address can cause the expected
ordered input to changes function to be broken, as the addresses
retrieved from kubernetes are sorted by their name.
Fixes #4317
=> Compare addresses by their name

.gitignore, Makefile
Also: this removes the error output, when the "which" command
cannot find the controller-gen binary, which is not an error.
- Bugfix
- Refactoring
=> Only build the controller-gen when necessary

CHANGELOG.md, console/console-init/oauth-proxy/bin/init.sh, console/console-init/oauth-proxy/cfg/oauth-proxy-openshift.cfg, pkg/controller/consoleservice/consoleservice_controller.go, pkg/util/install/utils.go, pkg/util/install/utils_test.go, systemtests/src/main/java/io/enmasse/systemtest/certs/openssl/CertPair.java, systemtests/src/main/java/io/enmasse/systemtest/certs/openssl/CertSigningRequest.java, systemtests/src/main/java/io/enmasse/systemtest/certs/openssl/OpenSSLUtil.java, systemtests/src/main/java/io/enmasse/systemtest/platform/KubeCMDClient.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Minikube.java, systemtests/src/main/java/io/enmasse/systemtest/platform/OpenShift.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/web/FirefoxConsoleTest.java
- Bugfix
Inject custom CA bundle into Console pod so that Console authentication functions even when the OpenShift cluster uses a custom CA.
=> Inject OpenShift custom ca bundle into console pod

CHANGELOG.md, templates/example-plans/020-StandardInfraConfig-default-with-mqtt.yaml, templates/example-plans/020-StandardInfraConfig-default.yaml
- Bugfix
Setting minAvailable/maxUnavailable for brokers is only applicable
when using partitioned queues, and should be a concious choice.
Fixes #4332
=> Remove min broker availability in examples

CHANGELOG.md, pkg/consolegraphql/resolvers/resolver_address.go, pkg/consolegraphql/resolvers/resolver_address_test.go, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/ChromeConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/FirefoxConsoleTest.java
Fix: Address links not displayed if address resource name suffix does not match address name
- Bugfix
Fixes #4287 
Use address name, for matching links, fixes issue when resource name suffix does not match.
=> Use address name, for matching links, fixes issue when resource name suffix does not match

CHANGELOG.md, address-space-controller/src/main/java/io/enmasse/controller/TemplateInfraResourceFactory.java, address-space-controller/src/main/java/io/enmasse/controller/common/TemplateParameter.java, address-space-controller/src/main/resources/templates/brokered-space-infra.yaml, address-space-controller/src/main/resources/templates/standard-space-infra.yaml, broker-plugin/plugin/src/main/resources/brokered/broker.xml, broker-plugin/plugin/src/main/resources/brokered/login.config, broker-plugin/plugin/src/main/resources/management.xml, broker-plugin/plugin/src/main/resources/shared/broker.xml, broker-plugin/plugin/src/main/resources/standard/colocated/broker.xml, broker-plugin/plugin/src/main/resources/standard/login.config, broker-plugin/plugin/src/main/resources/standard/sharded-queue/broker.xml, broker-plugin/plugin/src/main/resources/standard/sharded-topic/broker.xml, broker-plugin/plugin/src/main/sh/init-broker.sh, broker-plugin/sasl-delegation/src/main/java/io/enmasse/artemis/sasl_delegation/SaslDelegatingLogin.java, broker-plugin/sasl-delegation/src/test/java/io/enmasse/artemis/sasl_delegation/SaslDelegatingLoginTest.java, standard-controller/src/main/resources/templates/queue-persisted.yaml, standard-controller/src/main/resources/templates/topic-persisted.yaml, systemtests/src/test/java/io/enmasse/systemtest/isolated/support/SupportToolingTest.java
For the support use case, a support user should be able to connect to the broker(s) of an address space and run standard artemis support commands ` address show` and query JMX via Jolokia.
=> Broker support access

address-space-controller/src/main/java/io/enmasse/controller/ControllerChain.java
This ensures that creation of address spaces doesnt have to wait for
the next recheck interval before infrastructure gets provisioned.
=> Rerun reconcile if requeued

documentation/modules/proc-examine-broker-state.adoc, systemtests/src/test/java/io/enmasse/systemtest/isolated/support/SupportToolingTest.java
Newer versions of jolokia require "Origin: or Referer:" added to the header, as per:
https://jolokia.org/reference/html/security.html
The change was made in jolokia-core 1.5.  Therefore the header wasn't needed in 1.3.7, but will be needed in 1.6.1
=> Fix broker support access documentation for newer version of jolokia.

documentation/modules/ref-address-space-example-connectors.adoc
Expand address space connector docs to include idleTimeout, maxFrameSize, role
=> Expand address space connector docs to include idleTimeout, maxFrameSize, role

address-space-controller/src/main/java/io/enmasse/controller/ControllerChain.java, address-space-controller/src/test/java/io/enmasse/controller/ControllerChainTest.java
- Bugfix
I think this caused a lot of random test failure in CI due to address space controller spinning in requeue.
=> Ensure that requeue is reset to false every iteration

documentation/modules/ref-address-space-example-exposing-endpoints.adoc, templates/crds/addressspaces.crd.yaml
The ability to configure endpoints at the addressspace level was removed in 0.31.  A few references to this function were left behind in the documentation.  The PR tidies those up.
=> Tidy up a few redundant refs to console endpoints in the documentation

olm-manifest/Dockerfile, systemtests/src/main/java/io/enmasse/systemtest/operator/EnmasseOperatorManager.java, systemtests/src/main/java/io/enmasse/systemtest/operator/OLMOperatorManager.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/upgrade/UpgradeTest.java
- Enhancement
This PR changes the Dockerfile for olm-manifests and modifies systemtests to build a operator registry from the olm-manifests
=> build OLM operator registry in systemtests

CHANGELOG.md, broker-plugin/plugin/src/main/sh/init-broker.sh
- Bugfix
Broker's init.sh should stop execution and return a non-zero return code to the execution environment if an initialisation command ends in error.
=> broker init.sh - stops execution of a script if a command has an error

CHANGELOG.md, agent/lib/broker_controller.js, agent/lib/qdr.js, agent/lib/router.js, agent/lib/utils.js, agent/test/utils.js
- Bugfix
Ensure that a failed broker sync retries.
* change serialize to retry the target function if it fails.
* fixed _sync_broker_addresses/_sync_broker_forwarders to rethrow on error.
* fixed an sender_error event handler that referenced an missing variable.
* reformatted _sync_broker_forwarders to correct indentation (no functional change).
=> Ensure that a failed broker sync retries.

documentation/modules/proc-get-logs-broker.adoc, documentation/modules/proc-get-logs-router.adoc
The anchors to get broker logs and get router logs are switched around.
=> Documentation - fix get log anchors

systemtests/src/main/java/io/enmasse/systemtest/logs/GlobalLogCollector.java
- Bugfix
The arguments for the collection of address spaces were wrong, meaning addresses were collected rather than address spaces.  Also removed some duplication in the collected artefacts 
and used pluralisation consistently.
=> addressspace.yml should contain address spaces rather than addresses

systemtests/src/main/java/io/enmasse/systemtest/messaginginfra/ResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/scale/ResultWriter.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/sharedinfra/MessagingAddressPerfTest.java
At present, the test needs to be run manually, but can be useful to
measure the impact of changes to the messaging address reconciling.
@kornys where would be the best place to put this kind of test that isn't too long-running but I'd like to run it nightly? Should we define a profile for messaginginfra tests? 
Also, what do I need beside creating the plot file? Does it need to have a specific name to get picked up by jenkins grapher?
=> Add performance test of create and delete

iot/iot-device-registry-base/src/main/java/io/enmasse/iot/registry/server/DeviceRegistryAmqpServer.java, iot/iot-device-registry-base/src/main/java/io/enmasse/iot/registry/server/DeviceRegistryRestServer.java, pkg/controller/iotconfig/adapter.go, pkg/controller/iotconfig/device_registry.go, pkg/controller/iotconfig/infinispan_device_registry.go, pkg/controller/iotconfig/iotconfig_controller.go, pkg/controller/iotconfig/jdbc_device_registry.go, pkg/controller/iotconfig/monitoring.go, pkg/controller/iotconfig/secret_handler.go, pkg/controller/iotconfig/utils.go, systemtests/src/main/java/io/enmasse/systemtest/iot/DefaultDeviceRegistry.java, systemtests/src/main/java/io/enmasse/systemtest/utils/IoTUtils.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/SimpleK8sDeployTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/PostgresTableSplitDeviceRegistryTest.java
- Bugfix
- Refactoring
**Note:** This is already based on @dejanb's PR, implementing the missing JDBC device registry bits.
There had been a few issues with the split deployment. The main reason for that was the fact
that we did not have a system test for it. That is added now.
Also did the services not properly select their backing pods. Fixed as well.
I reverted back from the completely split naming (iot-device-registry-adapter and iot-device-registry-management). The `iot-device-registry` service will now stay, and additionally a `iot-device-registry-management` service will be created/deleted.
The metrics service for the split mode was fixed as well.
=> Fix up the wiring when using the split registry deployment models

HACKING.md, pkg/controller/messagingaddress/messagingaddress_controller.go, pkg/controller/messagingtenant/messagingtenant_controller.go, pkg/state/broker.go, pkg/state/infra.go, pkg/state/infra_test.go, pkg/state/router.go, pkg/state/router_test.go, pkg/state/router_types.go
This allows for batching requests for multiple entities in the same
per-router invocation as well as reduces per-type code required.
=> Refator router state to work with entities

documentation/modules/proc-examine-broker-state.adoc
Command descriptions associated with the commands lines were the wrong way about.
=> [Docs] Fix CLI/Jolokia command descriptions

documentation/assemblies/assembly-ops-procedures.adoc, documentation/modules/proc-enable-protocol-trace-broker.adoc, documentation/modules/proc-enable-protocol-trace-router.adoc
Ops procedures - document the enabling/disabling of AMQP protocol trace for router/broker
=> Ops procedures - document enable protocol trace for router/broker

CHANGELOG.md, address-space-controller/src/main/java/io/enmasse/controller/RouterConfigController.java
Address space connector should offer SASL ANONYMOUS if it cannot offer PLAIN or EXTERNAL owing to the connector's configuration.
=> Address space connector should offer SASL ANONYMOUS if it cannot offer PLAIN or EXTERNAL

pkg/amqpcommand/command_client.go, pkg/controller/messagingaddress/messagingaddress_controller.go, pkg/controller/messagingendpoint/messagingendpoint_controller.go, pkg/controller/messagingtenant/messagingtenant_controller.go, pkg/state/broker.go, pkg/state/errors.go, pkg/state/infra.go, pkg/state/manager.go, pkg/state/router.go, pkg/state/test/fakeinfra.go, pkg/state/types.go
Add a syncer and deleter goroutine for each infra, which is responsible
for syncing and deleting entities in batches. This speeds up the
create/delete performance test by 2x on my laptop.
=> Batch sync and delete resources

iot/iot-infinispan-base/src/main/java/io/enmasse/iot/infinispan/config/InfinispanProperties.java, templates/iot/examples/h2/create.sql, templates/iot/examples/postgresql/create.sql
- Bugfix
There was a wrong primary key on the credentials table. It was (tenant, device) and should have been (tenant, type, auth id). This also makes the additional index unnecessary, as the lookup is always by (tenant, type, auth id).
Additionally we require a new index on (tenant, device id) for credential management operations, as they work "by device".
=> Fix the primary key on the credentials table

pkg/amqpcommand/command_client.go, pkg/amqpcommand/test/fake_client.go, pkg/consolegraphql/agent/agent.go
Fixes regression that made purgeAddress tests fail
- Bugfix
Organise for the agent command delegate to await the delegate running.
=> Organise for the agent command delegate to await the delegate running

pkg/amqpcommand/command_client.go, pkg/consolegraphql/agent/agent.go, pkg/controller/messaginginfra/messaginginfra_controller.go
The code that previously required connection to be checked has been
made resilient to handle this error instead, and this should no longer
be needed, allowing the console and infra controller to work with the
old interface.
The lastErr variable is kept to handle the closing of requests that
occur during a reconnect.
=> Remove connected and running variables

systemtests/src/main/java/io/enmasse/systemtest/logs/GlobalLogCollector.java
Capture the OpenShift openshift-authentication (OAuth) logs when the tests fail.  Hoping to identity the root cause of the 500s we see in the oauth-proxy logs.
=> investigating sporadic console login oauth authentication issue

documentation/modules/ref-address-space-example-exposing-endpoints.adoc
Typo..
Correcting typo in documentation.
=> [Docs] correct loadbalance spec indentation

console/console-init/oauth-proxy/bin/init.sh, pkg/controller/consoleservice/consoleservice_controller.go, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java
- Bugfix
FirefoxConsoleTest#testOpenShiftWithCustomCert sporadic failures showed that there race between the controller being notified of the change to the ca bundle configmap and the changes being visible in the filesystem.  In the unlucky case, the console pod was running with stale trust even though the ca bundle config map hash was fresh.
I've refactored to avoid the need for the hash and the need for the console pod to restart.  This is done by passing multiple `-openshift-ca` arguments to OpenShift OAuthProxy.  This avoid the need to aggregate the trust.  As  OpenShift OAuthProxy reloads the trust dynamically the need to bounce the console pod is removed.
The change does not affect Kubernetes.
This defect relates to #4305.  This problem never left master.
=> Fix certificate change race that would lead to permanently  failing console authentication

documentation/master-kubernetes.adoc, documentation/master-openshift.adoc, documentation/modules/con-console.adoc, documentation/modules/proc-logging-in-console.adoc
- Bugfix
The RBAC refs were OpenShift specific.
=> [Docs] correct OpenShift refs in kube docs for console

.gitignore
- Bugfix
- Refactoring
Since a recent update podman seems to create (and not remove) `.lock` files. In any case, we shouldn't add them to git.
=> Ignore .lock files generated by podman

pkg/consolegraphql/resolvers/resolver_address.go, pkg/consolegraphql/resolvers/resolver_address_test.go, pkg/consolegraphql/resolvers/resolver_connection_test.go, pkg/consolegraphql/resolvers/test_utils.go
Strengthen unit tests.
- Bugfix
I'd made this mistake:
https://www.calhoun.io/gotchas-and-common-mistakes-with-closures-in-go/#variables-declared-in-for-loops-are-passed-by-reference
=> Correct Go-lang closure problem preventing the purging of >1 address

console/console-init/ui/src/graphql-module/queries/Address.ts, console/console-init/ui/src/modules/address-detail/AddressDetailPage.tsx, console/console-init/ui/src/modules/address/AddressPage.tsx, console/console-init/ui/src/modules/address/containers/AddressListContainer/AddressListContainer.tsx
- Refactoring
Modify purge address mutation query and the usage to accept list of addresses.
=> Handle multiple addresses for purge in a single query

console/console-init/ui/src/graphql-module/queries/Address.ts, console/console-init/ui/src/modules/address-detail/AddressDetailPage.tsx, console/console-init/ui/src/schema/ResponseTypes.ts
- Bugfix
Fix - Console shows unexpected error when I click on address with error message
For address with invalid address plan the addressType in response in an empty string. Handled to pick type from address.spec.type instead of address.spec.plan.spec.addressType
=> Fix - Console shows unexpected error when I click on address with error message

systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/web/ChromeConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/web/FirefoxConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/ChromeConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/FirefoxConsoleTest.java
- Bugfix
Addresses two problems: test would fail spuriously after clicking connection tab and selenium observed the loading page rather than the connection list as it expected.  there was a similar issue after deleting/closing the addressspace/address/connection which again would lead to spurious failure.
=> Stability improvments for the addressspace/address/connection 'gone-away' page tests

pkg/custom-metrics/iot.go
=> Fix double "enmasse_" prefix on metrics

documentation/common/attributes.adoc
This enables admonition icons, based on font awesome. Everything is handled be asciidoc, and it is purely optional.
=> Enable admonition icons

documentation/contributing/master.adoc
Skip revision information to avoid pushing docs on every build (updates date).
=> Skip revision information

console/console-init/ui/src/graphql-module/queries/Address.ts, console/console-init/ui/src/graphql-module/queries/AddressSpace.ts, console/console-init/ui/src/modules/address-detail/AddressDetailPage.tsx, console/console-init/ui/src/modules/address-space/AddressSpaceDetailPage.tsx, console/console-init/ui/src/modules/address-space/AddressSpacePage.tsx, console/console-init/ui/src/modules/address-space/containers/AddressSpaceListContainer/AddressSpaceListContainer.tsx, console/console-init/ui/src/modules/address/AddressPage.tsx, console/console-init/ui/src/modules/address/containers/AddressListContainer/AddressListContainer.tsx
- Refactoring
Refactor GraphQL client query for deleteAddressSpace and deleteAddress to pass variable as an array argument in console UI
=> Refactor GraphQL query in client side for deleteAddressSpace and deleteAddress to send many target objects 

systemtests/src/main/java/io/enmasse/systemtest/Environment.java, systemtests/src/main/java/io/enmasse/systemtest/platform/cluster/KubeCluster.java
This can be helpful for local running when CRC or Minikube command is not in /usr/bin or in path
=> Add ability to override cluster type by env var

console/console-init/ui/src/components/TypeAheadSelect/TypeAheadSelect.tsx, console/console-init/ui/src/modules/device/dialogs/CreateDevice/MetaData.tsx, console/console-init/ui/src/modules/device/dialogs/CreateDevice/MetaDataRow.tsx, console/console-init/ui/src/modules/device/utils/constant.ts
Add validation on device registration fields.
This PR adds the following features to metadata form
- Adds dynamic child rows, its key, values and types in metadata json
- Enables/Disables the value field in case of Array or Object
- Enables/Disables the child row addition button
- Removes the generic typeahead component to patternfly select component
- Adds validations to metadata fields
=> Add validations to metadata and fix review comments

console/console-init/ui/mock-console-server/mock-console-server.js, console/console-init/ui/mock-console-server/schema.js, console/console-init/ui/mock-console-server/test/mock.js, console/console-server/src/main/resources/schema.graphql, pkg/consolegraphql/resolvers/generated.go
- Refactoring
Capitalisation of the v1beta2 enums needs to match the Go enum values.
=> correct capitalisation of v1beta2 enums in GraphQL schema

systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/clients/rhea/MsgPatternsInternalTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/clients/rhea/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/web/ChromeWebSocketBrowserTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/web/FirefoxWebSocketBrowserTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/clients/rhea/MsgPatternsInternalTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/clients/rhea/MsgPatternsTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/ChromeWebSocketBrowserTest.java, systemtests/src/test/java/io/enmasse/systemtest/sharedinfra/MessagingEndpointTest.java
Temporary test exclusion on the OCP4 platform, relates to  #4641
=> Temporarily exclude websocket tests from OCP4

console/console-init/ui/src/modules/iot-certificates/components/CertificateForm/CertificateForm.tsx, console/console-init/ui/src/modules/iot-project-detail/components/GeneralInfo/GeneralInfo.test.tsx, console/console-init/ui/src/modules/project/components/MessagingConfigurationStep/MessagingConfigurationStep.tsx, console/console-init/ui/src/modules/project/dailogs/index.ts
- Bugfix
This PR fixes the issue arising due to re-defining of project utils and the failing build due to the FormCertificate. The re-definition has been removed. The tests that were earlier failing due to `isMessagingProjectValid` re-definition are passing now.
=> Fix: failing UI build and unit tests

CHANGELOG.md, address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceController.java, standard-controller/src/main/java/io/enmasse/controller/standard/StandardController.java
- Bugfix
Install uncaught exception handler in address-space-controller and standard-controller so that any uncaught exception, that kills a thread, will cause the JVM to terminate.  This will allow Kubernetes to restart the pod, thus restoring service.
=> Install uncaught exception handler in address-space-controller and standard-controller

console/console-init/ui/mock-console-server/mock-console-server.js, console/console-init/ui/src/graphql-module/queries/Address.ts, console/console-init/ui/src/graphql-module/queries/AddressSpace.ts, console/console-init/ui/src/modules/address-space/AddressSpacePage.tsx, console/console-init/ui/src/modules/address-space/components/MessagingDatatoolbarToggleGroup/MessagingDataToolbarToggleGroup.tsx, console/console-init/ui/src/modules/address-space/components/MessagingToolbar/MessagingToolbar.tsx, console/console-init/ui/src/modules/address-space/containers/AddressSpaceListContainer/AddressSpaceListContainer.tsx, console/console-init/ui/src/modules/address-space/containers/MessagingToolbarContainer/MessagingToolbarContainer.tsx, console/console-init/ui/src/modules/address-space/utils/AddressSpaceFormatter.tsx, console/console-init/ui/src/modules/address/components/AddressToggleGroup/AddressToggleGroup.tsx
- Refactoring
- Add functionality to support filter address space by status
- Include terminating status in status filter dropdown for address
=> [Console-UI] Add status as filter in toolbar for address space list 

systemtests/src/main/java/io/enmasse/systemtest/Environment.java, systemtests/src/main/java/io/enmasse/systemtest/scale/ScaleTestEnvironment.java
Add ability to specify env variables for systemtests via json config.
System load json (if it is specified) via CONFIG env var or if config exists in default location (systemtests) and use all vars from json config.
So priority of env var is now: 
1. config
2. env
3. default
=> Allow load env vars from json config

CHANGELOG.md, address-space-controller/src/main/java/io/enmasse/controller/RouterConfigController.java
- Bugfix
Guard against an existing connector target secret without data causing a NPE exception and prevent address space reconciliation.
=> Guard against an existing connector target secret without data

systemtests/src/main/java/io/enmasse/systemtest/iot/IoTTestSession.java
- Refactoring
The sets the default log level to "info" and only sets enmasse and hono channels to "debug".
=> Reduce log output for systemtests

pkg/controller/iotconfig/conditions.go, templates/crds/iotconfigs.crd.yaml
This will put an emphasis on a terminal configuration error for the IoTConfig. Each configuration error will fail the IoTConfig and the message field (which will now be shown) will contain the configuration error, rather than a copy of the ready condition's message:
Before:
~~~
NAME      PHASE    MESSAGE
default   Failed   1 component out of 10 is non-ready: Configuration
~~~
After:
~~~
NAME      PHASE    MESSAGE
default   Failed   Configuration Error: Number of key owners (3) must not exceed number of replicas (2)
~~~
=> Focus on the configuration error for the message field

address-space-controller/src/main/java/io/enmasse/controller/RouterConfigController.java, address-space-controller/src/test/java/io/enmasse/controller/RouterConfigControllerTest.java, agent/lib/broker_controller.js, agent/lib/ragent.js, agent/lib/router.js, agent/lib/router_config.js, agent/test/ragent.js, broker-plugin/plugin/src/main/resources/standard/colocated/broker.xml, broker-plugin/plugin/src/main/resources/standard/sharded-queue/broker.xml, broker-plugin/plugin/src/main/resources/standard/sharded-topic/broker.xml, controller-manager/src/main/resources/templates/PrometheusRules-enmasse.yaml, documentation/design/proposals/authentication.adoc, k8s-api/src/main/java/io/enmasse/k8s/api/ResourceChecker.java, standard-controller/src/main/java/io/enmasse/controller/standard/AddressCanaryHealth.java, standard-controller/src/main/java/io/enmasse/controller/standard/AddressCanaryResult.java, standard-controller/src/main/java/io/enmasse/controller/standard/AddressProbeClient.java, standard-controller/src/main/java/io/enmasse/controller/standard/AddressProber.java, standard-controller/src/main/java/io/enmasse/controller/standard/StandardController.java, standard-controller/src/main/java/io/enmasse/controller/standard/StandardControllerOptions.java, systemtests/src/main/java/io/enmasse/systemtest/monitoring/MonitoringQueries.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/monitoring/MonitoringTest.java
Add a periodic health check for standard address space, where pre-configured canary addresses are added to the routers and brokers. The periodic check will perform a send and receive to the canary addresses, and report prometheus metrics with the result.
An example alert is provided that alerts on failed canaries for more than 5 minutes.
=> Add address canary check for routers and brokers

iot/iot-tenant-cleaner/src/main/java/io/enmasse/iot/tools/cleanup/Application.java, iot/iot-tenant-cleaner/src/main/java/io/enmasse/iot/tools/cleanup/InfinispanDeviceRegistryCleaner.java, pkg/controller/iotproject/tenant_cleanup.go
- Refactoring
The entries in the device connection cache are supposed to expire automatically. With Infinispan that would mean that we do need need to delete them explicitly.
=> Drop cleaning up device connection entries with Infinispan

go.mod, go.sum
This is battle between Golang authors and Prometheus authors (probably some others as well).
Golang requires semantic versioning, and Prometheus doesn't want submit to those rules:
* With Go 1.13 can no longer flag versions as incompatible, if the have a 'go.mod' file in their repository: https://github.com/golang/go/issues/35732
* Dropping the '+incompatible' suffix is not possible, because the module author (Prometheus) would need to add the suffix '/v2' to their module. Otherwise you run into: https://github.com/golang/go/issues/35732#issuecomment-557227639
* Prometheus doesn't care about Golang's idea of versioning and simply ignores it: https://github.com/prometheus/prometheus/issues/6048#issuecomment-534549253
You can still put a commit has into the go.mod file as version, but that …
=> Fix dependency declaration of Prometheus

systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java
Delete enmasse in case beforeall install fails, this will prevent situation where enmasse is in half installed state.
=> Delete enmasse in case installation failed

pkg/amqpcommand/command_client.go, pkg/amqpcommand/test/fake_client.go, pkg/state/broker.go, pkg/state/broker_test.go, pkg/state/broker_types.go, pkg/state/infra.go, pkg/state/infra_test.go
* Configure addresses explicitly
* Refactor broker management to easily support different entity types
@vbusch This should make it easier to wire in the per-address settings for shared infra.
=> [Shared infra] Refactor broker management

api-model/src/main/java/io/enmasse/iot/model/v1/DeviceRegistryServiceConfig.java, api-model/src/main/java/io/enmasse/iot/model/v1/ManagementConfig.java, pkg/controller/iotconfig/adapter.go, systemtests/src/main/java/io/enmasse/systemtest/bases/JUnitWorkaround.java, systemtests/src/main/java/io/enmasse/systemtest/iot/DefaultDeviceRegistry.java, systemtests/src/main/java/io/enmasse/systemtest/iot/IoTTestSession.java, systemtests/src/main/java/io/enmasse/systemtest/iot/IoTTests.java
- Bugfix
This fixes the missing secrets for the device registry, when testing on plain kubernetes.
=> Fix deployment of secrets for plain Kubernetes

pkg/controller/iotconfig/monitoring.go, pkg/util/install/delete.go, pkg/util/templatehelper.go, systemtests/src/main/java/io/enmasse/systemtest/operator/EnmasseOperatorManager.java
If monitoring is disabled, the IoT reconciler tries to "delete" the prometheus CRs. However that will fail if Prometheus CRDs are not installed.
It would be possible to add another flag or check, however I think the `ENABLE_MONTORING` env-var should already be enough. If monitoring is enabled, the prometheus CRD must be installed, otherwise it is an error. If monitoring is disabled, deleting the CR due to a missing CRD can be ignored. If the user chooses to enable monitoring without having the CRDs installed, an error is shown. It is still possible to install prometheus CRDs afterwards. The reconciler will try again and succeed the next time, as there are no stale caches. Using the `HasApi` methods would cache the outcome, which is ok for system resources, but wrong for CRDs.
In addition, …
=> Gracefully handle missing Prometheus CRDs in some cases

broker-plugin/amqp-connector/src/main/java/org/apache/activemq/artemis/integration/amqp/AMQPConnectorService.java, broker-plugin/amqp-connector/src/main/java/org/apache/activemq/artemis/integration/amqp/AMQPConnectorServiceFactory.java, broker-plugin/amqp-connector/src/main/java/org/apache/activemq/artemis/integration/amqp/ThreadPoolExecutor.java
- Bugfix
The `scheduledExecutorService` provided by Artemis does not log exceptions throws by submitted runnable.  This change ensure that any exception are logged by the plugin.
Also changed executors created by the plugin to log any exceptions thrown by submitted runnables.
=> Ensure that broker plugin logs exception if connector fails.

pkg/controller/iotconfig/device_registry.go
- Bugfix
When running on plain Kubernetes, the node ports of the external load balancer services got overwritten each time.
=> Do not overwrite the NodePort when running on plain Kubernetes

systemtests/src/test/java/io/enmasse/systemtest/isolated/support/SupportToolingTest.java
- Bugfix
We occasionally see SupportToolingTest fail in CI runs.  Logging the stdout/stderr should help identify root cause.
=> [System tests] SupportToolingTest -  Log the stdout/stderr if support tool invocation fails

systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/platform/cluster/KubeCluster.java, systemtests/src/main/java/io/enmasse/systemtest/platform/cluster/KubernetesCluster.java
ability to run tests against pure kubernetes, it autodetect if cluster is kubernetes. In additionals PR for 1.0 version we should more focus on running tests on pure kubernetes implementations.
=> Ability to run tests against pure kubernetes

api-model/src/main/resources/schema/kube-schema.json, broker-plugin/plugin/src/main/resources/shared/broker.xml, pkg/apis/enmasse/v1beta2/types_address.go, pkg/controller/messagingaddress/messagingaddress_controller.go, pkg/state/broker.go, pkg/state/broker_types.go, pkg/state/infra.go, pkg/state/router.go, pkg/state/router_types.go, systemtests/src/test/java/io/enmasse/systemtest/sharedinfra/MessagingAddressTest.java, templates/shared-infra/enmasse.io_messagingaddresses.yaml
Add support for configuring router and broker for the topic, subscription and deadLetter address types and add systemtest for all currently supported types except deadLetter, which will be added separately. This PR requires #4692 which should be merged first.
=> [Shared infra] Add support for topics

CHANGELOG.md, agent/lib/internal_address_source.js, agent/package.json, agent/test/internal_address_source.js, agent/yarn.lock
- Bugfix
addresses_ready event erroneously included addresses for other addressspaces colocated in the same namespace.
=> Ensure that addresses_ready event does not include addresses belonging to other address spaces.

systemtests/src/main/java/io/enmasse/systemtest/scale/ScaleTestManager.java, systemtests/src/main/java/io/enmasse/systemtest/scale/performance/ThroughputData.java, systemtests/src/test/java/io/enmasse/systemtest/scale/ScaleTest.java, systemtests/src/test/java/io/enmasse/systemtest/scale/ScaleTestManagerTest.java
This modifies the messaging performance test into a test that tests
anycast and queue max throughput by initially creating a fixed number of
addresses, and gradually increasing the number of
clients (1 sender+receiver pair per client) until exhausing the number
of addresses.
Results is reported for each client that is added so that one can create scaling graphs from the results.
=> Refactor messaging performance tests

CHANGELOG.md, agent/bin/agent.js, agent/lib/internal_address_source.js, agent/lib/internal_addressplan_source.js, agent/lib/internal_addressspaceplan_source.js, agent/lib/kubernetes.js, agent/test/internal_address_source.js, agent/test/internal_addressplan_source.js, agent/test/internal_addressspaceplan_source.js, agent/test/ragent.js, agent/testlib/mock_resource_server.js, systemtests/src/test/java/io/enmasse/systemtest/bases/plans/PlansTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/plans/brokered/PlansTestBrokered.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/plans/standard/PlansTestStandard.java
Enhance brokered address space's address controller (agent) to populate address plan status in the same manner that is already done for the standard address space.
This change supports the max address size / message TTL work.
=> Enhance brokered address space's address controller (agent) to populate address plan status

agent/lib/broker_controller.js, broker-plugin/plugin/src/main/resources/standard/login.config, broker-plugin/sasl-delegation/src/main/java/io/enmasse/artemis/sasl_delegation/SaslGroupBasedSecuritySettingsPlugin.java
- Bugfix
Prevent the router from racing with the agent and causing ddresses/queues to be autocreated.
Uses @lulf's idea to assign the router's user a role that denies it create/delete address and create/delete durable queue.  This means if the router attaches its link before the agent has done its work, the Broker's autocreate will fail to cause the address/queue to come into existence with the wrong properties.
=> Prevent the router from racing with the agent and causing addresses/queues to be autocreated.

systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java
- Bugfix
I saw in logs that if first attempt of image build failed the rest in retry cycle failed as well because it didn't start new build becasue old kaniko pod was still present, so I added cleaning namespace if build fail.
=> Manifest image build retry and clean

HACKING.md, Makefile, Makefile.common
Add convenient target for local development with [kubernetes in docker](https://kind.sigs.k8s.io/). (I could only get kind working using docker and not podman, but the quick turnaround you can get with this approach makes it worth switching if you're in podman-land).
```
IMAGE_PULL_POLICY=IfNotPresent make buildpushkind
```
```
IMAGE_PULL_POLICY=IfNotPresent make -C <component> buildpushkind
kubectl delete pod <component pod>
```
=> Add convenient target for working with kubernetes in docker (kind)

console/console-init/ui/src/pages/AddressSpaceDetail/AddressList/AddressListFilterPage.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/AddressList/AddressesListWithFilterAndPaginationPage.tsx
- Bugfix
Populate Plan dropdown on Create Address Wizard from Empty Address's Create Button.
=> Set global address space plan for create address buttons

controller-manager/src/main/resources/templates/PrometheusRules-enmasse.yaml
- Refactoring
Changed the severity level of the following alerts to critical:
* RouterMeshConnectivityHealth
* RouterMeshUndeliveredHealth
=> Increased severity levels on router alerts

systemtests/src/main/java/io/enmasse/systemtest/apiclients/ApiClient.java, systemtests/src/main/java/io/enmasse/systemtest/apiclients/PrometheusApiClient.java, systemtests/src/main/java/io/enmasse/systemtest/bases/iot/ITestIoTBase.java, systemtests/src/main/java/io/enmasse/systemtest/iot/CredentialsRegistryClient.java, systemtests/src/main/java/io/enmasse/systemtest/iot/DeviceManagementApi.java, systemtests/src/main/java/io/enmasse/systemtest/iot/DeviceRegistryClient.java, systemtests/src/main/java/io/enmasse/systemtest/iot/HonoApiClient.java, systemtests/src/main/java/io/enmasse/systemtest/iot/HttpAdapterClient.java, systemtests/src/main/java/io/enmasse/systemtest/iot/IoTTestSession.java, systemtests/src/main/java/io/enmasse/systemtest/iot/IoTTests.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/api/UserApiTest.java
The final missing piece was the access token. Which you don't have
initially with Minikube. So now a service account, with an appropriate
role and binding will be created and the token used instead of the
default Kubernetes client API token.
This approach should properly work on all types of Kubernetes.
- Bugfix
=> Fix testing IoT on Minikube

agent/lib/broker_controller.js, broker-plugin/plugin/src/main/resources/standard/login.config, broker-plugin/sasl-delegation/src/main/java/io/enmasse/artemis/sasl_delegation/SaslGroupBasedSecuritySettingsPlugin.java
This reverts commit 6fb365a5a2749e828610f87b43ddbec7babb1206.
- Bugfix
The change caused a regression to TopicTest#testTopicWildcardsSharded and TopicTest#testTopicWildcardsPooled.  For those use cases the router user needs to be able to create the address, which the PR didn't accommodate.
=> Revert "Prevent the router from racing with the agent and causing addresses/queues to be autocreated. (#4739)"

systemtests/src/main/java/io/enmasse/systemtest/model/addressplan/DestinationPlan.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/QueueTest.java
- Test fix
Per address-settings for global-max-size has limited the maxSizeBytes per queue.  Used a medium plan (instead of small), to send the messages without exceeding the resource-limit.
=> Fixed Queue test

console/console-init/ui/src/modules/address-space/dialogs/CreateMessagingProject/CreateMessagingProject.tsx, console/console-init/ui/src/modules/address-space/dialogs/CreateMessagingProject/MessagingProjectConfiguration.tsx, console/console-init/ui/src/modules/address/dialogs/CreateAddress/CreateAddress.tsx
- Bugfix
After endpoint changes. A bug come up that input validation for name field in configuration step of create address space is not working 
Fix- Add validation on name input
=> Console-UI Add validation for name field in create address space

systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/tls/ReloadCertificatesTest.java
For X.509 certificates we are using the manually created certificates
for the HTTP protocol adapter now. However, that will not create
the expected certificate, and also will not automatically re-create it.
So in this test, we explicitly switch back to the service CA for HTTP.
- Bugfix
=> Switch back to service CA for testing certificate re-creation

CHANGELOG.md, standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, standard-controller/src/main/java/io/enmasse/controller/standard/BrokerCluster.java, standard-controller/src/main/java/io/enmasse/controller/standard/Kubernetes.java, standard-controller/src/main/java/io/enmasse/controller/standard/KubernetesHelper.java, standard-controller/src/test/java/io/enmasse/controller/standard/BrokerClusterTest.java, systemtests/src/test/java/io/enmasse/systemtest/bases/infra/InfraTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/infra/standard/InfraTestStandard.java
- Bugfix
This works around a limitation in Kubernetes where the statefulset
volume claim template cannot be modified (i.e. when resizing a
volume). The previous workaround was to use replace instead of patch,
which has now stopped working. The new workaround will ensure that the
existing claim template will stay as is, and instead the persistent
volume claim that was generated from the template previously, is now modified.
Fixes #4753
=> Modify PVC instead of statefulset claim template

templates/pom.xml, templates/src/assembly/unix-dist.xml
Currently `mvn clean install` fails in the `template` project, because no env-var `IMAGE_VERSION` is set by default in the maven context. Adding a default value (same as as the makefile) and overriding when the env-var is set fixes this, and brings back plain maven compilation.
- Bugfix
=> Fix the maven build

pom.xml, templates/pom.xml, templates/src/assembly/unix-dist.xml
**Note:** This builds upon #4791
Changing the version of the maven assembly plugin (actually defining it, because right now it is not managed at all) to a 3.x version allows to run multi-threaded builds without warnings. Which really improves build times:
Standard build (`mvn clean install`):
~~~
[INFO] Total time:  01:39 min
~~~
Multithreaded build (`mvn clean install -T1C`):
~~~
[INFO] Total time:  35.018 s (Wall Clock)
~~~
Of course this highly depends on the number of cores you have available, but still it should improve build times on all multi-core systems.
=> Bump version of maven-assembly-plugin to 3.x

Makefile, pkg/state/broker/broker.go, pkg/state/broker/broker_test.go, pkg/state/broker/types.go, pkg/state/infra.go, pkg/state/infra_test.go, systemtests/src/main/java/io/enmasse/systemtest/amqp/AmqpClient.java, systemtests/src/main/java/io/enmasse/systemtest/amqp/DeliveryHandler.java, systemtests/src/main/java/io/enmasse/systemtest/amqp/Receiver.java, systemtests/src/main/java/io/enmasse/systemtest/platform/GenericKubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/platform/cluster/MinikubeCluster.java, systemtests/src/test/java/io/enmasse/systemtest/sharedinfra/MessagingAddressTest.java, systemtests/src/test/java/io/enmasse/systemtest/sharedinfra/MessagingEndpointTest.java, templates/shared-infra/enmasse.io_messagingaddresses.yaml, templates/shared-infra/enmasse.io_messagingendpoints.yaml, templates/shared-infra/enmasse.io_messaginginfrastructures.yaml, templates/shared-infra/enmasse.io_messagingtenants.yaml
Default settings are set to broker defaults, except broker full
policy, which is set to FAIL. More settings will be exposed at a later
point.
Add systemtests for deadletter and expiry behavior, modify the AMQP
client to be able to reject messages so that they end up in the dead
letter queue.
Make more tests run in multiple Kubernetes environments by retrieving
a node ip and using nodeport to expose service.
Issue #4469
=> [Shared infra] Add support for deadletter and expiry settings

templates/crds/addresses.crd.yaml
- Bugfix
Missed the renaming of the `ttl` field in the address status section.
=> Missed the renaming of the ttl field in the address status section

systemtests/src/test/java/io/enmasse/systemtest/isolated/api/ApiServerTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/api/CustomResourceDefinitionAddressSpacesTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/api/CustomResourceDefinitionAddressesTest.java
- Bugfix
Make testRestApiAddressResourceParams compatible for OCP4.3 responses
=> [systemtests] Investigate ApiServerTest failure on CRC

systemtests/src/main/java/io/enmasse/systemtest/broker/ArtemisUtils.java
- Bugfix
Small bug fix to  address settings / messaging ttl tests to fail early if test's observation getAddressSettingsAsJSON fails.
=> [system tests] address settings / messaging ttl tests - fail early if test observation getAddressSettingsAsJSON fails

pkg/util/install/utils.go, pkg/util/install/utils_test.go
Fix an issue with append to env-vars. Currently this creates a new env-var every time.
- Bugfix
=> Fix appending content

documentation/kubernetes/master.adoc, documentation/modules/ref-brokered-infra-config-fields.adoc, documentation/modules/ref-standard-infra-config-fields.adoc, documentation/openshift/master.adoc
Add securityContext field to the brokered/standard infra config tables
=> Fix #3560: Add securityContext field to the brokered/standard infra config tables

console/console-init/ui/src/graphql-module/queries/AddressSpace.ts, console/console-init/ui/src/modules/address-space/containers/MessagingToolbarContainer/MessagingToolbarContainer.tsx
- Bugfix
Fixed following issues
1.Fixed filter on name and status together in address space list 
2. Fixed filter on name, namespace, type and status apply all together
=> Console-UI Filter on type and status in address space list is not working when combined together

templates/crds/iotconfigs.crd.yaml
- Bugfix
These changes should fix validation issue on kubernetes 1.18 and add ability to run SimpleK8sDeployTest on minikube/other kube cluster.
=> Add services to iotconfig crd

pom.xml
- Refactoring
Add Maven Dependency override for jackson-jaxrs-json-provider.version.  We already control most Jackson dependencies, this one was absent.
=> Add Maven Dependency override for jackson-jaxrs-json-provider.version

console/console-init/ui/src/modules/address-detail/containers/AddressLinks/AddressLinksPage.tsx, console/console-init/ui/src/modules/address-space/AddressSpacePage.tsx, console/console-init/ui/src/modules/connection-detail/components/ConnectionLinksWithToolbar/ConnectionLinksWithToolbar.tsx, console/console-init/ui/src/modules/connection/ConnectionPage.tsx
- Enhancement
This PR sets the lists to the first page upon applying filters.
=> Chore: add function to reset pagination upon filtering

console/console-init/ui/package.json, console/console-init/ui/src/App.test.tsx, console/console-init/ui/src/modules/address-space/containers/AddressSpaceListContainer/AddressSpaceListContainer.test.tsx, console/console-init/ui/src/modules/address/containers/AddressListContainer/AddressListContainer.test.tsx, console/console-init/ui/src/modules/connection-detail/containers/ConnectionLinksContainer/ConnectionLinksContainer.test.tsx, console/console-init/ui/src/modules/connection/containers/ConnectionContainer/ConnectionContainer.test.tsx, console/console-init/ui/src/modules/iot-project-detail/components/GeneralInfo/GeneralInfo.tsx, console/console-init/ui/yarn.lock
- Enhancement
- Bugfix
The UI unit tests were failing because of the arphodite dependency and since react-scripts have not been updated latest versions of react-script.
The following github threads have been referred to fix it:
https://github.com/testing-library/dom-testing-library/releases/tag/v7.0.0
https://github.com/Khan/aphrodite/issues/62
Note: the jest-environment-jsdom-sixteen dependency has to be removed when react-scripts updates to the latest version of Jest.
=> Fix: failing UI unit tests upon patternfly upgrade

systemtests/src/main/java/io/enmasse/systemtest/logs/GlobalLogCollector.java
- Bugfix
[Systemtest] Catch the ingress logs too to help understand PersistentMessagesTest sporadic failure
=> [Systemtest] Catch the ingress logs too to help understand PersistentMessagesTest sporadic failure

pom.xml
- Bugfix
Bump Jackson libraries from 2.10.0 -> 2.10.4 to take the latest defect fixes on the 2.10 line.
=> Bump Jackson 2.10.0 -> 2.10.4

pkg/controller/iotconfig/auth.go, pkg/controller/iotconfig/iotconfig_controller.go, pkg/controller/messaginginfra/router/controller.go, pkg/controller/messaginginfra/router/router_config.go
This PR creates an internal listener + service for the shared infra that can be used by cluster-internal components such as iot adapters (it could also reuse the same port as the operator management, but it feels cleaner to separate that). 
The second commit that changes the iotconfig controller is just an example on how you can reconcile the client certificate and get the information that you need to inject into the adapters. I'm not sure where you think this should belong, but this is anyway how it would look. I can split out the first part in a PR if you think this approach looks good.
=> Iot cert auth shared infra

console/console-init/ui/mock-console-server/mock-console-server.js
- Bugfix
Bug - There is a duplicate address plan for topic i.e "statndard-small-topic" in mockserver
=> Console Mock server - remove duplicate address plan from mock server for topic

CHANGELOG.md, address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceController.java, standard-controller/src/main/java/io/enmasse/controller/standard/StandardController.java
- Bugfix
Ensure address space controller and standard controller record stacktrace of startup failure
=> Ensure address space controller and standard controller record stacktrace of startup failure 

systemtests/src/main/java/io/enmasse/systemtest/operator/EnmasseOperatorManager.java
- Bugfix
Workaround for removing new enmasse 1.0 crds
=> Add workaround for deleting CRDs of enmasse 1.0

CHANGELOG.md, api-model/src/main/java/io/enmasse/address/model/Address.java, api-model/src/main/java/io/enmasse/address/model/AddressSpace.java, api-model/src/main/java/io/enmasse/user/model/v1/User.java, systemtests/src/main/java/io/enmasse/systemtest/manager/ResourceManager.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/api/CustomResourceDefinitionAddressSpacesTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/api/CustomResourceDefinitionAddressesTest.java
- Bugfix
Prevent unexpected fields at the root of addresspaace, address and message from causing the controller loops to fail
We were already using `@JsonIgnoreProperties(ignoreUnknown = true)` at the root of some IoT objects.  This seemed to the least unobtrusive change.
Added supporting tests.
=> Prevent unexpected fields at the root of addresspaace etc failing the controller loop

.github/workflows/smoke.yml
Enable caching .m2 for actions runes to speed up test runs.
=> Enable caching for maven

templates/Makefile, templates/helm/Chart.yaml
Not a lot of customization other than namespace right now, but its probably a nice installation option to have given that Helm is a widely used tool. We can probably expand options later on.
=> Add initial helm chart

pkg/controller/messagingaddress/messagingaddress_controller.go, pkg/controller/messagingendpoint/messagingendpoint_controller.go, pkg/state/errors/errors.go, pkg/state/infra.go
- Bugfix
This ensures that reconciler is called again to recheck finalization of
the resource.
@kornys I've not tested if this fixes your issue, but I could see from the operator logs that it failed to remove first because address was still present, but it didn't attempt to reconcile the endpoint again, so this should ensure that it tries again after 10 seconds. Usually it tries again on errors, but maybe that is not guaranteed by framework, so explicit scheduling is probably better.
=> Requeue finalizer if resource is in use

pkg/controller/messagingaddress/messagingaddress_controller.go, pkg/controller/messagingendpoint/messagingendpoint_controller.go, pkg/controller/messaginginfra/broker/controller.go, pkg/controller/messaginginfra/cert/controller.go
- Bugfix
Improve on the fix in  #4913 so that RequeueAfter is propagated so that reconcile loop does not continue if resource is in use which leaves it in a flip-flop state.
When having multiple endpoints with TLS certs, the secret containing the certificates get rewritten for each endpoint. The fix ensures that the secret is only initialized if it was not already.
When running tests with many endpoints and queues, the broker becomes unresponsive, so the default broker memory will be set to 1GB with a TODO to make this configurable in the MessagingInfrastructure later.
=> Fix endpoint management

systemtests/src/main/java/io/enmasse/systemtest/framework/TestPlanExecutionListener.java
- Bugfix
Fix for running framework tests without kubernetes cluster connection
=> Enable framework unit tests without kube connection

systemtests/src/main/java/io/enmasse/systemtest/condition/AssumeKubernetesCondition.java, systemtests/src/main/java/io/enmasse/systemtest/condition/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/platform/cluster/ClusterType.java
- Bugfix
Allow to match all kubernetes implementation not only minikube
=> Fix Kubernetes annotation to match all kube cluster imlementation

Makefile.env.mk, controller-manager/Dockerfile, hack/verify-codegen.sh, pkg/controller/messagingaddress/messagingaddress_controller.go, pkg/controller/messagingendpoint/messagingendpoint_controller.go, pkg/controller/messaginginfra/messaginginfra_controller.go, pkg/controller/messaginginfra/router/router_config.go, pkg/state/infra.go, pkg/state/router/router.go, pkg/state/router/types.go, systemtests/pom.xml, systemtests/src/main/java/io/enmasse/systemtest/condition/AssumeKubernetesCondition.java, systemtests/src/main/java/io/enmasse/systemtest/condition/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/MessagingClientRunner.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/platform/cluster/ClusterType.java, systemtests/src/test/java/io/enmasse/systemtest/sharedinfra/MessagingEndpointTest.java, systemtests/src/test/java/io/enmasse/systemtest/sharedinfra/MessagingInfrastructureTest.java
- Bugfix
- Refactoring
This modifies the infra to access a messaging project from multiple endpoints. This also allows the IoT to start using the internal listener using the namespace as the prefix for addresses @ctron 
Until there is a new router release, I have built a custom router image from qpid dispatch master source.
=> Multiple endpoints per namespace support

pom.xml
- Bugfix
To help see why the jenkins build is failing in PR #4912, we need the yarn output in the logs.
https://github.com/eirslett/frontend-maven-plugin/issues/791 has stopped the maven build from logging the yarn output.
Downgrading to version 1.7.6 (where logging still works)
Confirmed that versions: 1.8.0, 1.9.1 and 1.10.0 do not provide output
=> downgrade version of frontend-maven-plugin to fix logging during build

console/console-init/ui/mock-console-server/README.md, console/console-init/ui/mock-console-server/mock-console-server.js, console/console-init/ui/mock-console-server/schema.js, console/console-server/src/main/resources/iot.schema.graphql
Unifying the results to create a list of resources that contains `iotptojects` and `addressSpaces` and can be filtered and paged through.
This is done with adding a `kind` field to both of the objects.
- Enhancement
See README for how to use it.
=> [Console-iot] - Unify all projects list results

.github/workflows/smoke.yml, systemtests/src/main/java/io/enmasse/systemtest/iot/HttpAdapterClient.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kind.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/platform/cluster/ClusterType.java, systemtests/src/main/java/io/enmasse/systemtest/platform/cluster/KindCluster.java, systemtests/src/main/java/io/enmasse/systemtest/platform/cluster/KubeCluster.java, systemtests/src/test/java/io/enmasse/systemtest/iot/http/StandardIoTHttpTests.java
Add ability to run IoT job on all PR builds.
IoT will run only HttpAdapterTest for now, we can add other tests in the future, but I don't want to let queue fill and let other PR runs wait.
=> Add iot job to smoke job

address-space-controller/src/test/java/io/enmasse/controller/RouterConfigControllerTest.java
- Bugfix
Fixes odd compile error appearing on some CI environments.
=> [RouterConfigControllerTest] use alternative method withValueFromSecret

console/console-server/Dockerfile
- Bugfix
The refactoring of the base-images exposed this defect.  Note that the console is not currently functional as it still needs to be wired to the new model.
=> Fix console-server docker entrypoint

CHANGELOG.md, pom.xml
Bump RESTeasy from 3.6.1.SP2 to 4.5.3.Final
=> Bump RESTeasy from 3.6.1.SP2 to 4.5.3.Final

address-space-controller/src/main/java/io/enmasse/controller/NetworkPolicyController.java, address-space-controller/src/test/java/io/enmasse/controller/NetworkPolicyControllerTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/policy/NetworkPolicyTestBrokered.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/policy/NetworkPolicyTestStandard.java
- Bugfix
The NetworkPolicyConntroller now ensures that the network policy permits traffic between the EnMasse pods (those with `app=enmasse`) on the infra-namespace.   I think the previous implementation was incorrect and meant the traffic between EnMasse's own pods was impeded.  I suspect that a defect fix included in OpenShift 4.5 allowed the issue to surface.
There was also a defect in `testNetworkPolicyWithPodSelector`.  When specifying a `podSelector`,  a `namespaceSelector` has to be included unless the target pod happens to be in the  infra namespace. See https://kubernetes.io/docs/concepts/services-networking/network-policies/
=> Ensure that application of end user network policy does not affect traffic between EnMasse components

cmd/console-server/main.go, pkg/consolegraphql/server/metrics.go, pkg/consolegraphql/server/query/handler.go, pkg/consolegraphql/server/query/handler_test.go, pkg/consolegraphql/server/query/query.go, pkg/consolegraphql/server/query/query_test.go, pkg/consolegraphql/server/request_context.go, pkg/consolegraphql/server/session.go
- Bugfix
To guard against a possible CSRF with some older browsers, apply the same-site cookie option strict to the console-server's session cookie, and deny mutation operations for requests that don't already have a session.
=> CVE-2020-14319: Deny mutation operations unless an existing session exists

documentation/design/proposals/management_tasks-for-shared.adoc
- Design sketch
I was thinking about how we'd deliver management functionality in the shared world.
I had some thoughts about a possible solution that I've captured as an embryonic proposal.
https://github.com/k-wall/enmasse/blob/man-tasks-for-shared/documentation/design/proposals/management_tasks-for-shared.adoc
All comments welcome.
=> Delivering management functionality for shared infra

console/console-init/ui/mock-console-server/README.md, console/console-init/ui/mock-console-server/mock-console-server.js, console/console-init/ui/mock-console-server/schema.js, console/console-server/src/main/resources/iot.schema.graphql
The idea is to have the JSON editor for device to have the following template : 
```
{
"id": "<optional-id>",
"registration" : 
{
"enabled": true, 
"defaults": {},
"ext": {},
},
"credentials": []
}
```
This align the graphQL schemas to match this.
=> Console Iot - proposal to align device input schema with JSON editor view

console/console-init/ui/src/modules/iot-device-detail/dialogs/CloneDevice/CloneDevicePage.tsx, console/console-init/ui/src/modules/iot-device/DeviceListPage.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceListToolbar/DeviceListToolbar.tsx, console/console-init/ui/src/modules/iot-device/components/MangeColumnModal/ManageColumnModal.tsx, console/console-init/ui/src/modules/iot-device/components/MangeColumnModal/index.ts, console/console-init/ui/src/modules/iot-device/components/index.ts, console/console-init/ui/src/modules/iot-device/containers/DeviceListContainer/DeviceListContainer.tsx, console/console-init/ui/src/modules/iot-device/utils/constant.ts, console/console-init/ui/src/stories/DeviceList.stories.tsx, console/console-init/ui/src/stories/DeviceListPage.stories.tsx
Add manage columns section in modal to manage multiple columns in device list
Design link :- https://marvelapp.com/prototype/5gbji22/screen/69081888
=> [Console-iot] Add manage columns in device list 

address-space-controller/src/main/java/io/enmasse/controller/ControllerChain.java, address-space-controller/src/main/java/io/enmasse/controller/RouterStatusCache.java, address-space-controller/src/main/java/io/enmasse/controller/keycloak/RealmController.java, k8s-api/src/main/java/io/enmasse/k8s/api/ResourceChecker.java
- Bugfix
A race condition meant that stale values from the `EventCache` could cause the AddressSpaceController to partially recreate the address space controller during deletion.
The issue occurs as follows:
1. the Controller thread blocks trying to acquire mutex in method `ResourceChecker#onUpdate` (called from `EventCache#pop`).
2. The mutex is already held by `ResourceChecker#doWork` which is the controller's main loop.
3. By the time the controller's main loop terminates, the records in `io.enmasse.k8s.api.cache.EventCache#store` are stale.  Watcher updates *have* arrived (stored in the intermediate io.enmasse.k8s.api.cache.EventCache#queue) but these can't be processed as the Controller thread is blocked awaiting the mutex.
4. In the unlucky case, after the controller's loop …
=> Prevent stale record from cache leading to incomplete address space deletion

console/console-init/ui/src/components/DropdownWithToggle/DropdownWithToggle.tsx, console/console-init/ui/src/modules/address/components/AddressConfiguration/AddressConfiguration.tsx, console/console-init/ui/src/modules/address/containers/AddressDefinitionContainer/AddressDefinitionContainer.tsx, console/console-init/ui/src/modules/address/dialogs/CreateAddress/CreateAddress.tsx
- Refactoring
In recent PF update the issue related to alignment got fixed. Remove the work around for that alignment issue
=> [Console-UI] remove blank string workaround for dropdown alignment issue

console/console-init/ui/src/modules/project/dailogs/CreateProject/CreateProject.tsx
- Bugfix
A server error was thrown whenever a new project was created.
=> Fix: error while creating a new IoT project

agent/lib/broker_controller.js
Default address settings will now be set to original Artemis defaults. I am not sure if it is better to use those, or to come up with a different set of settings.
=> Improve default redelivery settings when a deadletter address is set

agent/lib/artemis.js, agent/lib/broker_controller.js
- Bugfix
Root cause was the Broker's handling of the `expiryAdress` element in the `getAddressSettingsAsJSON` response.  It omits the value from the address settings if there is no assignment.  `compare_address_settings` assumed that all elements were present in the `orig_address_settings` map and this meant that `expiryAdresss` changes could go unnoticed. 
For the DLA field, the problem was masked by the assignment of the !GLOBAL_DLQ at the root level.  The meant that the `getAddressSettingsAsJSON` response always included the DLQ field.
=> Fix defect that prevented expiry address being assigned correctly

standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/dlq/DeadLetterTest.java
- Bugfix
Prevent the deletion of a dead letter address causing the erroneous deprovisioning of broker(s) with addresses still referencing
that dead letter address.
=> Prevent the deletion of a dead letter address causing the erroneous deprovisioning of brokers

CHANGELOG.md, agent/lib/broker_controller.js, agent/test/broker_controller.js, standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, standard-controller/src/test/java/io/enmasse/controller/standard/AddressControllerTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/dlq/DeadLetterTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/ttl/MessageTtlTest.java
- Bugfix
Fixes: #5183 The broker needs the expiry-address and the TTL to be set on the topic (not on the subscription).
=> Fix deadletter & expiry-address for durable subscriptions.

controller-manager/src/main/resources/templates/GrafanaDashboard-routers.yaml
- Bugfix
Updated router Grafana dashboard as the router metrics names have been updated causing the metrics to not show up on the dashboard.
=> Updated dashboard to use new router metric names

agent/lib/console_server.js, pkg/consolegraphql/agent/agent.go, pkg/consolegraphql/resolvers/resolver_address.go, pkg/consolegraphql/resolvers/resolver_address_test.go, pkg/consolegraphql/resolvers/test_utils.go, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java
The agent uses the .spec.address as the key in its internal map, but the
purge request uses the .metadata.name as the key when doing the lookup.
This causes purge to fail if .metadata.name and .spec.address differ.
This fix changes the console server to pass the .spec.address instead of
.metadata.name and also using this as the lookup in agent.
An alternative would be to change the mapping internally to use
.metadata.name as the key, but this would complicate other uses of the
map that assumes it is keyed by .spec.address (such as router stats
retrieval).
The systemtest is updated to test purge with one address that has .metadata.name different from .spec.address.
=> Modify address name to be different from address

agent/lib/artemis.js, agent/lib/ragent.js, agent/test/broker_controller.js, agent/test/internal_address_source.js, agent/test/internal_addressplan_source.js, agent/test/ragent.js, agent/testlib/mock_broker.js
- Bugfix
I was seeing the Agent unit test suite mostly fail both locally and on CI.  With these test only changes, the suite seems much more stable.
* The semantics of `addAddressSettings`/`removeAddressSettings` mock methods didn't match the real implementation.  The handling of those errors seemed to be cause some of the suite's instability.
* Corrected a missing Rhea `client.close()`.
* Added `close`/`done` chaining in the ragent `afterEach` to ensure that resources are definitely released before the next test starts.
* test/broker_controller.js
** `afterEach` broken in several ways
** some tests explicitly closed the controller, causing a race condition (caused 'transfer after detach')
=> Address agent unit test suite instability

agent/bin/agent.js, agent/lib/kubernetes.js
- Refactoring
Remove redundant call to the `oapi` endpoint.
=> Remove redundant call to oapi endpoint

systemtests/src/test/java/io/enmasse/systemtest/isolated/infra/standard/InfraTestStandard.java
Updated infra test to check if address if working properly when it's connected to infra config which has omitted globalMaxSize. 
Address status is changed to ready even with NaN error on Agent so we have to test if address is working properly with sender&receiver attached.
- [* ] Write tests and make sure they pass
=> Update infra test for #5130

systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java
- Bugfix
Monitoring tests are failing when run on OpenShift 3.x because the pods are never detected as being in a ready state. This is because the monitoring stack is installed on OpenShit 3.x using the Application Monitoring Operator so the pods are not labelled with `app:enmasse`. This means the test wasn't finding the pods. Removing the labels from the call to listPods fixes this issue.
=> Fixed issue where pods are not detected as ready

pkg/util/openshift.go, pkg/util/openshift_test.go
- Bugfix
It looks like in Kubernetes version 1.19 they changed
the minor version to e.g. "18+" to "19" (without the '+')
suffix.
However the reg-exp used to validate the minor version string
expected a plus in the end. This make the + optional.
=> Fix issue in detecting Kubernetes version

systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java
without this change enmasse systemtests are stuck in waiting to ready phase becasue custom catalog creates pods in enmasse-infra namespace which are in state completed
=> Fix olm test waiting for only enmasse pods

systemtests/src/main/java/io/enmasse/systemtest/logs/GlobalLogCollector.java
- Bugfix
Allow to collect routes on kubernetes 1.11 (ocp 3.11), this PR should be also picked into release 0.33 and 0.32
=> Fix collecting routes on kubernetes 1.11

agent/lib/broker_controller.js, agent/lib/log.js, agent/lib/ragent.js, agent/lib/registry.js
- Bugfix
Avoid some expensive log.debug() AP evaluations.  This avoids pointless n operations (filters, maps etc), where n is the number of connections or addresses, generating needless garbage.
=> Avoid some expensive log.debug() AP evaluations

broker-plugin/amqp-connector/pom.xml, broker-plugin/amqp-connector/src/main/java/org/apache/activemq/artemis/integration/amqp/AMQPConnectorServiceFactory.java, broker-plugin/amqp-connector/src/main/java/org/apache/activemq/artemis/integration/amqp/Util.java, broker-plugin/amqp-connector/src/test/java/org/apache/activemq/artemis/integration/amqp/UtilTest.java
- Bugfix
Treat an empty MIN_LARGE_MESSAGE_SIZE value as if it were the default (-1).
=> Fix #5228: Guard empty MIN_LARGE_MESSAGE_SIZE

broker-plugin/amqp-connector/src/main/java/org/apache/activemq/artemis/integration/amqp/AMQPConnectorService.java, broker-plugin/amqp-connector/src/main/java/org/apache/activemq/artemis/integration/amqp/ProtonClientConnectionManager.java
- Bugfix
This mimics the approach taken by Artemis itself for detecting 'idleness'.  Artemis uses FailureCheckAndFlushThread#run to periodically check all connections are ensure that they continue to see traffic.  Unfortunately, this doesn't apply to connections created by EnMasse's AMQPConnectorService as it does know about them.
I've added a period check for connections that works in the same way.  
Note: This is separate from AMQP's notion of idleness, which Artemis doesn't act upon directly.
=> Fix #5221: Periodically check outgoing broker connections for idleness

systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java
- Bugfix
Use project enmasse quay images for selenium, postgres and busybox to avoid docker pull limits.
=> Use quay.io for selenium, postgres and busybox

systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java
- Bugfix
Avoid NPE during cleanup if expected test user is not defined.
=> [System tests] Avoid NPE if test user is not defined

broker-plugin/amqp-connector/src/main/java/org/apache/activemq/artemis/integration/amqp/AMQPConnectorServiceFactory.java
- Bugfix
Actually calling the new method might actually help!
=> Fix #5228: Guard MIN_LARGE_MESSAGE_SIZE II

pkg/consolegraphql/agent/agent.go
- Bugfix
Receiving link was granting credit 1, so messages were effectively being polled.
=> Fix #5238: Console receiver grants too little credit to agent_data receiving link

Makefile.env.mk, pom.xml, systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java
Upgrade to Artemis 2.16.0 and Qpid Dispatch Router 1.14.0
=> Upgrade to Artemis 2.16.0 and Qpid Dispatch Router 1.14.0

templates/crds/addressspaceplans.crd.yaml, templates/crds/brokeredinfraconfigs.crd.yaml, templates/crds/messagingusers.crd.yaml, templates/crds/standardinfraconfigs.crd.yaml
- Bugfix
Cleanup the v1beta1 schemas in preparation for conversion to CRD v1s by removing some unstructural schema warnings.
These changes have no functional impact.
=> Clean up v1beta1 crds schemas

systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/TopicTest.java
- Bugfix
JMS allows a durable subscription to be deleted only once, regardless of the connection/session
=> [Tests] Fix TopicTest.testSharedDurableSubscription

systemtests/src/main/java/io/enmasse/systemtest/condition/OpenShiftVersion.java, systemtests/src/main/java/io/enmasse/systemtest/operator/EnmasseOperatorManager.java
- Bugfix
User workload monitoring is no longer in tech preview in OpenShift 4.6 or later so it the config to enable it has changed.
=> Enable user workload monitoring on OCP 4.6

scripts/add-crc-insecure-registry.sh
- Bugfix
Seems newer CRC versions use the newer key form.
=> Make add-crc-insecure-registry support id_ecdsa ssh identities

systemtests/src/main/java/io/enmasse/systemtest/operator/EnmasseOperatorManager.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java
- Bugfix
Check for application-monitoring pods wasn't working because only pods labelled `app:enmasse` are checked. This PR allows the labels to be passed as a parameter instead of being hardcoded
=> Wait for correctly labelled pods to be ready

.github/scripts/install_dep.sh, .github/workflows/master.yml, .github/workflows/release.yml, .github/workflows/smoke.yml
Bump minikube/kube versions used by GiHub Actions.  This is required now as it we need a version of minikube that supports V1 CRD.
=> Bump minikube/kube versions

pkg/apis/enmasse/v1beta1/types.go
- Bugfix
CRD v1 fixed a schema validation issue (bad indentation).  With proper schema validation
missing omitempty became apparent in the expose spec Go-serialisers.
=> Fix defect exposed by #5252

systemtests/src/main/java/io/enmasse/systemtest/utils/UserUtils.java
- Bugfix
Difference in the semantics of `new *Builder(original).editMetadata()` when `original` does not have metadata. Triggered by the update of fabric8 by #5265.
=> Fix test regression introduced by #5265

CHANGELOG.md, address-space-controller/src/main/java/io/enmasse/controller/RouterConfigController.java, address-space-controller/src/main/java/io/enmasse/controller/router/config/VhostPolicy.java, address-space-controller/src/test/java/io/enmasse/controller/RouterConfigControllerTest.java, api-model/src/main/java/io/enmasse/admin/model/v1/RouterPolicySpec.java, documentation/modules/ref-standard-infra-config-example.adoc, documentation/modules/ref-standard-infra-config-fields.adoc, systemtests/src/test/java/io/enmasse/systemtest/isolated/api/CustomResourceDefinitionTest.java, templates/crds/v1/standardinfraconfigs.crd.yaml, templates/crds/v1beta1/standardinfraconfigs.crd.yaml
Support router policy maxMessageSize
=> Fix #5272 - Support router configuration maxMessageSize

systemtests/src/main/java/io/enmasse/systemtest/manager/ResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/utils/UserUtils.java, systemtests/src/test/java/io/enmasse/systemtest/bases/authz/AuthorizationTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/authz/AuthorizationTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/authz/AuthorizationTest.java
- Bugfix
Fix test regression introduced by #5265 (the fabric8 kubernetes-client upgrade)
=> Fix more test regressions introduced by #5265 (fabric8 kubernetes-client)

CHANGELOG.md, address-space-controller/src/main/java/io/enmasse/controller/auth/OpenshiftCertProvider.java, api-common/src/main/java/io/enmasse/api/common/OpenShift.java, api-common/src/test/java/io/enmasse/api/common/OpenShiftTest.java, api-model/src/main/java/io/enmasse/config/AnnotationKeys.java, console/console-init/oauth-proxy/cfg/oauth-proxy-openshift.cfg, keycloak-plugin/src/main/sh/init-keycloak.sh, keycloak-user-api/src/main/java/io/enmasse/user/keycloak/KubeKeycloakFactory.java, olm-manifest/src/main/resources/enmasse.clusterserviceversion.yaml, olm-manifest/src/main/resources/latest/enmasse.clusterserviceversion.yaml, pkg/controller/add_cabundle.go, pkg/controller/address_space_controller/controller.go, pkg/controller/authenticationservice/none.go, pkg/controller/authenticationservice/standard.go, pkg/controller/ca_bundle/controller.go, pkg/controller/consoleservice/consoleservice_controller.go, pkg/controller/messaginguser/messaginguser_controller.go, pkg/controller/messaginguser/messaginguser_controller_test.go, pkg/controller/upgrader/upgrader.go, pkg/keycloak/client.go, pkg/util/install/utils.go, pkg/util/install/utils_test.go, templates/enmasse-operator/050-Deployment-enmasse-operator.yaml
Avoid reliance of deprecated service-ca.crt (OpenShift 4).  On OpenShift 3.11, the existing behaviour must be maintained.
=> Avoid reliance of deprecated service-ca.crt (OpenShift4)

documentation/common/proc-download-procedure.adoc
For this release there will be two bundles, one suitable for < Kube 1.16 (and OpenShift 3.11) and another suitable for newer Kubernetes and all OpenShift 4 versions. The documentation needs to reflect this.
=> [Docs] Alternative download bundle for older Kube/OCP 3.11

service-broker/src/main/java/io/enmasse/osb/api/OSBServiceBase.java
- Bugfix
There's a regression in the service broker associated with the upgrade of fabric8 kubernetes-client.
=> Fix regression associated with the fabric8 kc upgrade

hack/verify-codegen.sh
- Bugfix
Make build-time utility script run on Mac OS X.
=> make verify codegen macosx compatible

scripts/add-crc-insecure-registry.sh
Development utility script - add-crc-insecure-registry .
Newer CRC releases seem to run ssh on port 2222 bound to loopback.
- Bugfix
=> Make util script add-crc-insecure-registry compatible with newer CRC release

keycloak-plugin/sasl-plugin/src/main/java/io/enmasse/keycloak/spi/K8sServiceAccountCredentialProvider.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/api/UserApiTest.java
Use tokenreview v1 when authenticating against service accounts (for kube 1.22 compatibility)
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#tokenreview-v122
- Bugfix
```
2022-04-01T13:06:08.611Z WARN  [PlainSaslServerMechanism] Exception when authenticating @@serviceaccount@@: java.lang.RuntimeException: Error performing POST on /apis/authentication.k8s.io/v1beta1/tokenreviews: 404, {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404} at io.enmasse.keycloak.spi.K8sServiceAccountCredentialProvider.authenticateToken(K8sServiceAccountCredentialProvider.java:101) 
```
=> Use tokenreview v1 when authenticating against service accounts

address-space-controller/src/main/java/io/enmasse/controller/AppliedConfig.java, address-space-controller/src/main/java/io/enmasse/controller/CreateController.java, address-space-controller/src/main/java/io/enmasse/controller/TemplateInfraResourceFactory.java, address-space-controller/src/main/java/io/enmasse/controller/common/Kubernetes.java, address-space-controller/src/main/java/io/enmasse/controller/common/KubernetesHelper.java, address-space-controller/src/test/java/io/enmasse/controller/CreateControllerTest.java, api-model/src/main/java/io/enmasse/admin/model/v1/BrokeredInfraConfig.java, api-model/src/main/java/io/enmasse/admin/model/v1/StandardInfraConfig.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/api/AuthServiceTest.java
- Bugfix
Fix ##5328 : Adds digest of the authentication service CA (which may be platform trust from the container) onto applied config, so that any change to trust will trigger a reconcile and the internal `authservice-ca` to be repopulated.
=> Fix #5328 : trigger reconfiguration of address space on change of authentication service trust
