console/console-init/ui/src/Components/Common/ConnectionListFormatter.tsx
fix-display empty string only if no data is present in response
=> fix-display empty string only if no data is present in response

address-space-controller/src/main/resources/templates/brokered-space-infra.yaml, address-space-controller/src/main/resources/templates/standard-space-infra.yaml, cmd/controller-manager/main.go, controller-manager/src/main/resources/templates/ServiceMonitor-address-space-controller.yaml, controller-manager/src/main/resources/templates/ServiceMonitor-admin.yaml, controller-manager/src/main/resources/templates/ServiceMonitor-broker.yaml, controller-manager/src/main/resources/templates/ServiceMonitor-iot.yaml, controller-manager/src/main/resources/templates/ServiceMonitor-router.yaml, documentation/modules/ref-metrics-common.adoc, metrics-api/src/main/java/io/enmasse/metrics/api/PrometheusMetricsFormatter.java, metrics-api/src/test/java/io/enmasse/metrics/api/PrometheusMetricsFormatterTest.java, pkg/util/templatehelper.go, standard-controller/src/main/resources/templates/queue-persisted.yaml, standard-controller/src/main/resources/templates/topic-persisted.yaml, systemtests/src/test/java/io/enmasse/systemtest/isolated/monitoring/MonitoringTest.java
Relabel all enmasse metrics with enmasse_ prefix
=> Split service monitors into one per service

systemtests/src/main/java/io/enmasse/systemtest/operator/OperatorManager.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/CommonTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/monitoring/MonitoringTest.java
- Bugfix
Fixes for systemtests isolated tests
=> Fix isolated flaky tests

.github/scripts/setup_docker.sh
=> Docker setup fix

iot/pom.xml
=> Switch to Hono 1.0.3

CHANGELOG.md, pom.xml
=> bump netty to 4.1.45.Final

console/console-init/ui/src/Components/AddressSpace/Address/EmptyAddress.tsx, console/console-init/ui/src/Components/AddressSpaceList/AddressSpaceList.tsx, console/console-init/ui/src/Components/AddressSpaceList/EmptyAddressSpace.tsx, console/console-init/ui/src/Components/Common/About.tsx, console/console-init/ui/src/Components/Common/AddressSpaceListFormatter.tsx, console/console-init/ui/src/Components/Common/Error.tsx, console/console-init/ui/src/Components/Common/FilterDropdown.tsx, console/console-init/ui/src/Pages/AddressDetail/AddressLinksFilter.tsx, console/console-init/ui/src/Pages/AddressSpaceDetail/AddressList/AddressListPage.tsx, console/console-init/ui/src/Pages/AddressSpaceList/AddressSpaceListFilterPage.tsx, console/console-init/ui/src/Pages/AddressSpaceList/AddressSpaceListPage.tsx, console/console-init/ui/src/Pages/AddressSpaceList/AddressSpaceListWithFilterAndPaginationPage.tsx, console/console-init/ui/src/Pages/ConnectionDetail/ConnectionDetailPage.tsx, console/console-init/ui/src/Pages/ConnectionDetail/ConnectionsLinksListPage.tsx, console/console-init/ui/src/Pages/CreateAddress/CreateAddressPage.tsx, console/console-init/ui/src/Pages/CreateAddress/PreviewAddress.tsx, console/console-init/ui/src/Pages/CreateAddressSpace/CreateAddressSpaceConfiguration.tsx, console/console-init/ui/src/Pages/CreateAddressSpace/CreateAddressSpacePage.tsx, console/console-init/ui/src/Pages/CreateAddressSpace/ReviewAddressSpace.tsx, console/console-init/ui/src/Tests/AddressList.test.tsx, console/console-init/ui/src/stories/AddressDetailHeader.stories.tsx, console/console-init/ui/src/stories/AddressList.stories.tsx
Console logs have been removed. Unnecessary comment lines and unused variables have been removed.
- Bugfix
- Refactoring
=> Style: remove logging and comments

Makefile.env.mk, olm-manifest/src/main/resources/latest/enmasse.clusterserviceversion.yaml, pkg/controller/consoleservice/consoleservice_controller.go, pom.properties, templates/Makefile, templates/enmasse-operator/020-ClusterRole-enmasse-operator.yaml, templates/enmasse-operator/050-Deployment-enmasse-operator.yaml
This creates a link in the OpenShift console, to point to the EnMasse Console, if the platform is OpenShift.
=> Create a link in the console of OpenShift

k8s-api/src/main/java/io/enmasse/k8s/api/cache/Reflector.java
This could be useful information when debugging watch logic
=> Log KubernetesClientException if provided

api-model/src/main/java/io/enmasse/common/model/CustomResources.java, templates/crds/addresses.crd.yaml, templates/crds/addressplans.crd.yaml, templates/crds/addressspaceplans.crd.yaml, templates/crds/addressspaces.crd.yaml, templates/crds/addressspaceschemas.crd.yaml, templates/crds/authenticationservices.crd.yaml, templates/crds/brokeredinfraconfigs.crd.yaml, templates/crds/consoleservices.crd.yaml, templates/crds/iotconfigs.crd.yaml, templates/crds/iotprojects.crd.yaml, templates/crds/messagingusers.crd.yaml, templates/crds/standardinfraconfigs.crd.yaml
Kubernetes allows to specify categories in crd, whis allow to get resources by category.
```
oc get enmasse                                            
NAME                                                             PHASE    AGE
addressplan.admin.enmasse.io/brokered-queue                      Active   14m
addressplan.admin.enmasse.io/brokered-topic                      Active   14m
addressplan.admin.enmasse.io/standard-large-anycast              Active   14m
addressplan.admin.enmasse.io/standard-large-multicast            Active   14m
addressplan.admin.enmasse.io/standard-large-partitioned-queue    Active   14m
addressplan.admin.enmasse.io/standard-large-queue                Active   14m
addressplan.admin.enmasse.io/standard-large-subscription         Active …
```
=> Add category for enmasse CRD

iot/iot-device-registry-base/src/main/java/io/enmasse/iot/registry/util/DeviceRegistryTokenAuthHandler.java, iot/iot-device-registry-base/src/main/java/io/enmasse/iot/registry/util/DeviceRegistryTokenAuthProvider.java
=> Fix leaking promises

.github/scripts/setup_docker.sh
=> Fix githubfolder actions

pkg/controller/address_space_controller/controller.go
=> Allow setting address-space-controller annotations for legacy prometheus

pkg/controller/consoleservice/consoleservice_controller.go, pkg/controller/iotproject/utils.go, pkg/util/env.go, pkg/util/openshift.go, pkg/util/openshift_test.go
=> Implement a finer grained check for the existince of APIs

.github/scripts/build.sh, .github/scripts/collectLogs.sh, .github/scripts/olm_test.sh, .github/scripts/smoke_test.sh, HACKING.md, TESTING.md, systemtests/Makefile, systemtests/scripts/run_tests.sh
=> Remove SYSTEMTEST prefix from make env vars

cmd/controller-manager/main.go, go.mod
=> Add prefix to metrics exported by operator

pkg/controller/iotproject/finalizers.go
=> Add log messages for tenent cleaner job

systemtests/src/test/java/io/enmasse/systemtest/isolated/infra/standard/InfraTestStandard.java
=> Set property that is being tested

console/console-init/ui/src/App.tsx, console/console-init/ui/src/components/common/ErrorAlert.tsx, console/console-init/ui/src/components/common/ErrorBoundary.jsx, console/console-init/ui/src/components/common/NotFound.tsx, console/console-init/ui/src/pages/AddressDetail/AddressDetailPage.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/AddressList/AddressListPage.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/AddressList/AddressesListWithFilterAndPaginationPage.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/AddressSpaceDetailPage.tsx, console/console-init/ui/src/stories/DeleteAddress.stories.tsx
Error handling for fetch errors from server and application errors
=> Error handling on fetch of address list and application errors

CHANGELOG.md, address-space-controller/src/main/java/io/enmasse/controller/RouterConfigController.java, address-space-controller/src/main/java/io/enmasse/controller/router/config/SslProfile.java, broker-plugin/plugin/src/main/resources/brokered/broker.xml
=> Require TLSv1.2 or newer for external endpoints

systemtests/src/main/java/io/enmasse/systemtest/messagingclients/rhea/RheaClientConnector.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/web/FirefoxConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/ChromeConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/FirefoxConsoleTest.java
=> fix selectors + fix cli-rhea-connector command + metrics tests

systemtests/src/main/java/io/enmasse/systemtest/manager/ResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/ChromeConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/FirefoxConsoleTest.java
=> Test edit address using console

console/console-init/ui/package-lock.json, console/console-init/ui/src/components/AddressDetail/AddressDetailHeader.tsx, console/console-init/ui/src/components/AddressSpace/Address/AddressList.tsx, console/console-init/ui/src/components/NavToolBar/User.tsx, console/console-init/ui/src/components/common/AddressSpaceListFormatter.tsx, console/console-init/ui/src/components/common/ErrorAlert.tsx, console/console-init/ui/src/components/common/SortForMobileView.tsx, console/console-init/ui/src/pages/AddressDetail/AddressDetailPage.tsx, console/console-init/ui/src/pages/AddressDetail/AddressLinksFilter.tsx, console/console-init/ui/src/pages/AddressDetail/AddressLinksListPage.tsx, console/console-init/ui/src/pages/AddressDetail/AddressLinksWithFilterAndPaginationPage.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/AddressList/AddressListPage.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/AddressList/AddressesListWithFilterAndPaginationPage.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/ConnectionList/ConnectionsListPage.tsx, console/console-init/ui/src/pages/AddressSpaceList/AddressSpaceListFilterPage.tsx, console/console-init/ui/src/pages/AddressSpaceList/AddressSpaceListPage.tsx, console/console-init/ui/src/pages/ConnectionDetail/ConnectionDetailPage.tsx, console/console-init/ui/src/pages/ConnectionDetail/ConnectionLinksWithFilterAndPaginationPage.tsx, console/console-init/ui/src/pages/ConnectionDetail/ConnectionsLinksListPage.tsx, console/console-init/ui/src/pages/CreateAddress/PreviewAddress.tsx, console/console-init/ui/src/pages/CreateAddressSpace/ReviewAddressSpace.tsx, console/console-init/ui/src/queries/Address.ts, console/console-init/ui/src/queries/Connection.ts
- Refactoring
- Rename clients with Links for address in address detail page and links with Links for connection in connection detail page.
- Removed unused variables and warnings(i.e. replaced != with !==)
=> rename clients with links for address, removed some unused variables

pkg/controller/consoleservice/consoleservice_controller.go
- Bugfix
The console-controller no longer needs to consider the address space consoles when building the oauthclient redirect url.  Removes the redundant logic from the controller.
=> Remove the redundant address space specific oauth client redirect processing

systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/main/java/io/enmasse/systemtest/utils/AddressUtils.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/web/ChromeConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/web/FirefoxConsoleTest.java
=> Snippet tests

console/console-init/ui/src/components/ConnectionDetail/MessagesDetail.tsx, console/console-init/ui/src/pages/AddressDetail/AddressLinksListPage.tsx, console/console-init/ui/src/pages/AddressDetail/AddressLinksWithFilterAndPaginationPage.tsx, console/console-init/ui/src/pages/AddressSpaceList/AddressSpaceListPage.tsx, console/console-init/ui/src/pages/ConnectionDetail/ConnectionLinksWithFilterAndPaginationPage.tsx, console/console-init/ui/src/pages/ConnectionDetail/ConnectionsLinksListPage.tsx
=> fix loading page rendering for sort

systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/web/FirefoxConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/ChromeConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/FirefoxConsoleTest.java
- Bugfix
After #3923 , this PR changes test to expect correct valid and invalid address names
=> web tests - test valid address names

systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java
Updates valid address names according with #3940
=> update web test - valid address names

systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/resources/ClientWebItem.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/web/ChromeConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/web/FirefoxConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/ChromeConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/FirefoxConsoleTest.java
=> Address link console tests

pkg/consolegraphql/filter/filter_test.go, pkg/consolegraphql/filter/lex_test.go
Makes proper use of the testing API. No functional change.
=> [Unit tests] make proper use of Go table driven tests

console/console-init/ui/src/components/AddressDetail/ClientList.tsx, console/console-init/ui/src/components/AddressSpace/Address/AddressList.tsx, console/console-init/ui/src/components/AddressSpace/Connection/ConnectionList.tsx, console/console-init/ui/src/components/AddressSpaceList/AddressSpaceList.tsx, console/console-init/ui/src/components/ConnectionDetail/LinkList.tsx, console/console-init/ui/src/components/common/AddressSpaceListFormatter.tsx
- Bugfix
- Add scrolling in table on resize of window
=> fix - Addresses list rows resize incorrectly in small window

pkg/controller/iotproject/finalizers.go
- Bugfix
A small fix to the newly introduced logs, to avoid errors
=> Use structured logging

systemtests/src/main/java/io/enmasse/systemtest/Environment.java
- Enhancement
Fill kube domain based on api url for local development
=> Fill kubeDomain based on api url

console/console-init/ui/.gitignore
This adds the`dist` folder to the git ignore list
=> Ignore the dist folder

address-space-controller/src/main/java/io/enmasse/controller/EndpointController.java, templates/crds/addressspaces.crd.yaml
- Bugfix
Validate endpoint expose spec. Fixes #3974
=> Handle potential NPE in route tls termination handling

address-space-controller/src/main/java/io/enmasse/controller/PodDisruptionBudgetController.java
@k-wall I'm not sure if many will run into this issue, but thought I'd document it. Not sure if its worth putting into some known issue doc.
=> Add comment about PDB update failure

controller-manager/src/main/resources/templates/PrometheusRules-enmasse.yaml
Added an alert to indicate if the console is running or not
=> Added alert to indicate if console is running

console/console-init/ui/src/queries/Address.ts
- Bugfix
Fix - add "AND" keyword in query for multiple filter in address list query.
=> concat ADD keyword for multiple adresseses

controller-manager/src/main/resources/templates/PrometheusRules-enmasse.yaml
=> add a prometheus record to monitor the state of enmasse-operator

k8s-api/src/main/java/io/enmasse/k8s/api/cache/Reflector.java
Adds a pause if the resync fails with a kubernetes client exception. This will prevent a lot of logging during shutdown where CRDs are deleted before the controllers.
=> Handle kubernetes exceptions gracefully

console/console-init/ui/src/components/AddressDetail/AddressDetailHeader.tsx, console/console-init/ui/src/components/AddressSpace/AddressSpaceHeader.tsx, console/console-init/ui/src/components/AddressSpaceList/AddressSpaceList.tsx, console/console-init/ui/src/pages/AddressDetail/AddressDetailPage.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/AddressList/AddressesListWithFilterAndPaginationPage.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/AddressSpaceDetailPage.tsx, console/console-init/ui/src/pages/AddressSpaceList/AddressSpaceListPage.tsx, console/console-init/ui/src/queries/Address.ts, console/console-init/ui/src/queries/AddressSpace.ts, console/console-init/ui/src/stories/AddressDetailHeader.stories.tsx, console/console-init/ui/src/stories/AddressSpaceHeader.stories.tsx, console/console-init/ui/src/stories/AddressSpaceList.stories.tsx, console/console-init/ui/src/types/ResponseTypes.tsx
- add download option in kebab of address space list
- add edit option in kebab of address space detail header
- add purge option in kebab of address detail header
=> add edit in kebab dropdown of address space detail header and purge option in address detail header

documentation/modules/proc-upgrading-enmasse-using-ansible.adoc, documentation/modules/proc-upgrading-enmasse-using-bundle.adoc
Fix attribute name so it renders properly
=> Docs: fix attribute name

console/console-init/ui/src/Tests/AddressList.test.tsx, console/console-init/ui/src/components/AddressSpace/Address/AddressList.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/AddressList/AddressListFilterPage.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/AddressList/AddressListPage.tsx, console/console-init/ui/src/queries/Address.ts, console/console-init/ui/src/stories/AddressList.stories.tsx, console/console-init/ui/src/types/ResponseTypes.tsx
- Add creation timestamp to the address list page
=> add sortable column for time stamp in address list table

systemtests/src/main/java/io/enmasse/systemtest/selenium/resources/AddressWebItem.java
=> Modify selector regarding timestamp

cmd/console-server/main.go, console/console-server/src/main/resources/probe.sh, pkg/consolegraphql/server/handler.go, pkg/consolegraphql/server/request_context.go, pkg/consolegraphql/server/session.go, pkg/consolegraphql/server/session/listener.go, pkg/consolegraphql/server/session/memstore.go, pkg/consolegraphql/server/utils.go, pkg/consolegraphql/server/utils_test.go, pkg/consolegraphql/watchers/manager.go
If the console-server has no logged on user, it should be a quiesced state and not be pulling data from kubernetes or the agents.
=> quiesce the console-server if there are no logged on users

CHANGELOG.md, amqp-utils/src/main/java/io/enmasse/amqp/Artemis.java, standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java, standard-controller/src/main/java/io/enmasse/controller/standard/BrokerStatusCollector.java
=> Check broker address status

systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java
Include full stack trace on last retry when failing to connect to selenium for diagnostic purposes.
Also disconnects the HTTPUrlConnection.
=> improve logging from selenium remote driver test

systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/resources/ConnectionWebItem.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/ChromeConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/FirefoxConsoleTest.java
=> Blank link page test

console/console-init/ui/src/components/AddressSpace/Address/AddressList.tsx, console/console-init/ui/src/components/common/AddressFormatter.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/AddressSpaceDetailPage.tsx
- Bugfix
- Fix - console address list status message presented as very long single line
- Format the Error message in address list
=> format error message in address list

console/console-init/ui/src/components/common/NetworkStatusAlert.tsx, console/console-init/ui/src/constants/constants.ts, console/console-init/ui/src/context-state-reducer/reducer.ts, console/console-init/ui/src/graphql-module/error-helper.ts
This PR handles 403 - forbidden errors, adds a relevant error message and redirects user to sign in page
=> Handle 403 forbidden errors

systemtests/src/main/java/io/enmasse/systemtest/Environment.java
fix for running selenium on crc
=> Fix crc selenium

address-space-controller/src/main/java/io/enmasse/controller/MetricsReporterController.java, controller-manager/src/main/resources/templates/GrafanaDashboard-components.yaml, controller-manager/src/main/resources/templates/GrafanaDashboard-console.yaml, controller-manager/src/main/resources/templates/GrafanaDashboard-routers.yaml, pkg/custom-metrics/custom_metrics.go, pkg/util/templatehelper.go, standard-controller/src/main/java/io/enmasse/controller/standard/AddressController.java
- Refactoring
Updated the Grafana dashboards. 
Highlights:
* Added dashboard for console metrics
* Added authentication services metrics to components dashboards
* Updated routers dashboard to relfect metrics relabelling
* Fixed bug showing number of routers as a decimal
=> Updated the grafana dashboards

documentation/assemblies/assembly-managing-addresses.adoc, documentation/modules/proc-uninstalling-using-olm-console.adoc, documentation/modules/proc-uninstalling-using-olm.adoc, documentation/modules/ref-address-example-topic-and-sub.adoc
Minor edits to Installing instructions and fix heading level in address topic sub example
=> Docs issue 4041: minor edits to Installing instructions 

agent/lib/qdr.js
- Bugfix
Strengthen the code used to abort pending QDR requests ensuring that the outstanding promise is rejected on all paths. I have suspicion that the remaining `UnhandledPromiseRejectionWarning: null` messages in the agent log may be originating from here.
I don't believe this issue causes a functional impact.
=> Strengthen the code used to abort pending QDR requests

agent/lib/kubernetes.js
- Bugfix
Apply timeout to HTTP requests made by the agent for list, create, update, delete.
=> Apply HTTP timeout to kubernetes list, create, update, delete

systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/FirefoxConsoleTest.java
=> Add client filtering tests

systemtests/src/main/java/io/enmasse/systemtest/manager/ResourceManager.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/QueueTest.java
=> fix testScale and increase update address timeout

systemtests/src/main/java/io/enmasse/systemtest/logs/GlobalLogCollector.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java
- Test
Capture address space logs in order to understand sporadic test failure.
=> Capture address space logs from ConsoleTest#doTestCreateAddrSpaceNonClusterAdmin

systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java
fix snipped tests which failed on upstream/downstream
=> Fix sniped tests

systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java
=> Snippet tests work around fix

systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java
=> fix testHelpLink

systemtests/src/main/java/io/enmasse/systemtest/operator/OperatorManager.java
=> fix clean up of olm tests in enmasse-infra namespace

systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/web/FirefoxConsoleTest.java
=> Add test for kube client in snippets

systemtests/pom.xml, systemtests/src/main/java/io/enmasse/systemtest/TestTag.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java, systemtests/src/main/java/io/enmasse/systemtest/logs/GlobalLogCollector.java, systemtests/src/main/java/io/enmasse/systemtest/utils/AddressUtils.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/scale/ScaleTest.java
=> Scale tests init

systemtests/src/test/java/io/enmasse/systemtest/isolated/CommonTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/QueueTest.java
- Test
Test described in ENTMQMAAS-1040
=> add tests verify broker remains operable after full queue

systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/resources/AddressWebItem.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/web/FirefoxConsoleTest.java
Test for check addressPlan name in console UI
=> Add test for check custom plans in console

systemtests/src/main/java/io/enmasse/systemtest/platform/OpenShift.java, systemtests/src/main/java/io/enmasse/systemtest/utils/IoTUtils.java, systemtests/src/test/java/io/enmasse/systemtest/iot/shared/control/CommandAndControlTest.java
* If the route is not found, throw a more helpful exception.
* Combine the two setup methods, as they do rely on an order
but @BeforEach does not honor any order
* Fix a race condition when deleting an IoTProject. It relies
on an initial set of data, which might already be gone, as the
deletion is on progress.
=> Fix some issues in the system tests

.github/workflows/master.yml, .github/workflows/release.yml, .github/workflows/smoke.yml
=> Move installing dependencies to first place

console/console-init/oauth-proxy/cfg/oauth-proxy-kubernetes.cfg, console/console-init/oauth-proxy/cfg/oauth-proxy-openshift.cfg, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java
As there is only 1 provider present, there is no point in adding the
extra level of indirection.
=> Skip button to select provider to login with

systemtests/src/test/java/io/enmasse/systemtest/isolated/monitoring/MonitoringTest.java
- Test fix
Prometheus configuration wasn't getting the rules.
Toggling the enmasse-operator deployment env ENABLE_MONITORING flag, caused prometheus to pick them up.
=> Fix MonitoringTest.testAddressSpaceRules test

systemtests/src/test/java/io/enmasse/systemtest/isolated/CommonTest.java
Added test for creating and deleting address space.
=> Add test for creating and deleting address space

systemtests/src/main/java/io/enmasse/systemtest/manager/IsolatedResourcesManager.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java, systemtests/src/main/java/io/enmasse/systemtest/scale/MessagingPerformanceTestManager.java, systemtests/src/main/java/io/enmasse/systemtest/scale/ScaleTestClient.java, systemtests/src/main/java/io/enmasse/systemtest/scale/ScaleTestClientConfiguration.java, systemtests/src/main/java/io/enmasse/systemtest/scale/ScaleTestClientType.java, systemtests/src/main/java/io/enmasse/systemtest/scale/metrics/MessagingClientMetricsClient.java, systemtests/src/main/java/io/enmasse/systemtest/scale/metrics/MetricsAssertions.java, systemtests/src/main/java/io/enmasse/systemtest/scale/metrics/MetricsMonitoringResult.java, systemtests/src/main/java/io/enmasse/systemtest/scale/metrics/MetricsValidationResult.java, systemtests/src/main/java/io/enmasse/systemtest/scale/metrics/ScaleTestClientMetricsClient.java, systemtests/src/main/java/io/enmasse/systemtest/time/TimeMeasuringSystem.java, systemtests/src/test/java/io/enmasse/systemtest/scale/ScaleTest.java
=> Systemtests scale tests - messaging performance

systemtests/pom.xml
=> Dont run scale in isolated profile

systemtests/src/main/java/io/enmasse/systemtest/scale/MessagingPerformanceTestManager.java, systemtests/src/test/java/io/enmasse/systemtest/scale/ScaleTest.java
- Test
After more testing with messaging performance scale test I found this configuration gets better results. Note: there is still a lot of room for improvements that will come :)
=> tune up scale test constant values

systemtests/src/main/java/io/enmasse/systemtest/logs/GlobalLogCollector.java
=> save pods in olm namespace

systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java
=> systemtests - log olm pods

systemtests/src/main/java/io/enmasse/systemtest/manager/ResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java, systemtests/src/main/java/io/enmasse/systemtest/scale/ScalePerformanceTestManager.java, systemtests/src/main/java/io/enmasse/systemtest/scale/ScaleTestClientConfiguration.java, systemtests/src/main/java/io/enmasse/systemtest/scale/ScaleTestClientType.java, systemtests/src/main/java/io/enmasse/systemtest/scale/metrics/MessagingClientMetricsClient.java, systemtests/src/main/java/io/enmasse/systemtest/utils/AuthServiceUtils.java, systemtests/src/test/java/io/enmasse/systemtest/scale/ScaleTest.java
- Enhancement
Scale test for count of operable addresses
It is still a draft!!
=> Scale test operable addresses

systemtests/pom.xml, systemtests/src/main/java/io/enmasse/systemtest/scale/ScalePerformanceTestManager.java, systemtests/src/main/java/io/enmasse/systemtest/scale/metrics/DowntimeData.java, systemtests/src/main/java/io/enmasse/systemtest/scale/metrics/DowntimeMonitoringResult.java, systemtests/src/main/java/io/enmasse/systemtest/scale/metrics/MessagingClientMetricsClient.java, systemtests/src/main/java/io/enmasse/systemtest/scale/metrics/ScaleTestClientMetricsClient.java, systemtests/src/test/java/io/enmasse/systemtest/scale/ScaleTest.java
=> Systemtests - failure recovery test

scripts/add-crc-user.sh
Helper script to create a user in the htpasswd secret of CRC
=> Development tool - helper script to create a user in the htpasswd secret of CRC

systemtests/src/main/java/io/enmasse/systemtest/manager/IsolatedResourcesManager.java, systemtests/src/main/java/io/enmasse/systemtest/scale/MetricsMonitoringResult.java, systemtests/src/main/java/io/enmasse/systemtest/scale/ScalePerformanceTestManager.java, systemtests/src/main/java/io/enmasse/systemtest/scale/ScaleTestClient.java, systemtests/src/main/java/io/enmasse/systemtest/scale/downtime/DowntimeData.java, systemtests/src/main/java/io/enmasse/systemtest/scale/downtime/DowntimeMonitoringResult.java, systemtests/src/main/java/io/enmasse/systemtest/scale/metrics/MessagesCountRecord.java, systemtests/src/main/java/io/enmasse/systemtest/scale/metrics/MessagingClientMetricsClient.java, systemtests/src/main/java/io/enmasse/systemtest/scale/metrics/MetricsAssertions.java, systemtests/src/main/java/io/enmasse/systemtest/scale/metrics/ProbeClientMetricsClient.java, systemtests/src/main/java/io/enmasse/systemtest/scale/metrics/ScaleTestClientMetricsClient.java, systemtests/src/main/java/io/enmasse/systemtest/scale/performance/AddressTypePerformanceResults.java, systemtests/src/main/java/io/enmasse/systemtest/scale/performance/PerformanceResults.java, systemtests/src/main/java/io/enmasse/systemtest/scale/performance/ThroughputData.java, systemtests/src/test/java/io/enmasse/systemtest/scale/ScaleTest.java
Adds to scale test messaging performance the json output file with throughput information for all the clients deployed in messages per second. This PR includes minor bugfixes in scalability tests and also has a minor refactor organizing the various classes created for the scalability tests.
=> Performance test: output throughput + various improvements

systemtests/src/main/java/io/enmasse/systemtest/scale/ScalePerformanceTestManager.java, systemtests/src/main/java/io/enmasse/systemtest/scale/ScaleTestEnvironment.java, systemtests/src/main/java/io/enmasse/systemtest/scale/metrics/ScaleTestClientMetricsClient.java, systemtests/src/main/java/io/enmasse/systemtest/utils/AddressUtils.java, systemtests/src/test/java/io/enmasse/systemtest/scale/ScaleTest.java
- Enhancement 
Move all scale test related constants to environment variables
=> Scale test configuration with env vars

systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/FirefoxConsoleTest.java
=> Test error dialog

systemtests/src/main/java/io/enmasse/systemtest/time/TimeMeasuringSystem.java, systemtests/src/test/java/io/enmasse/systemtest/scale/ScaleTest.java
store results from scale tests into csv files for generating plots
=> Scale result csv

systemtests/src/main/java/io/enmasse/systemtest/scale/ScaleTestClient.java, systemtests/src/main/java/io/enmasse/systemtest/scale/ScaleTestManager.java, systemtests/src/main/java/io/enmasse/systemtest/scale/downtime/DowntimeData.java, systemtests/src/main/java/io/enmasse/systemtest/scale/downtime/DowntimeMonitoringResult.java, systemtests/src/test/java/io/enmasse/systemtest/scale/ScaleTest.java
=> scale test - add summary of brokers and routers dowtimes to csv

systemtests/src/main/java/io/enmasse/systemtest/logs/GlobalLogCollector.java, systemtests/src/main/java/io/enmasse/systemtest/manager/ResourceManager.java, systemtests/src/test/java/io/enmasse/systemtest/scale/ScaleTest.java
- Enhancement
Added scale tests ordering to warm up environment and leave test which restart pods to the end to do not affect other tests.
=> Add ordering of scale tests

documentation/assemblies/assembly-planning.adoc, documentation/modules/con-address-space.adoc
=> Docs issue-4158: add SingleBookLink

console/console-init/ui/src/Tests/ConnectionList.test.tsx
- Refactoring
Re-enable connection tests
=> Re-enable connection tests

console/console-init/ui/src/Tests/AddressSpaceList.test.tsx, console/console-init/ui/src/modules/address-space/components/AddressSpaceHeader/AddressSpaceHeader.tsx, console/console-init/ui/src/modules/address-space/index.ts
- Bugfix
fixed failure unit test and remove unused code
=> fixed failure unit test and remove unused code

systemtests/pom.xml, systemtests/src/main/java/io/enmasse/systemtest/EnmasseInstallType.java, systemtests/src/main/java/io/enmasse/systemtest/OLMInstallationType.java, systemtests/src/main/java/io/enmasse/systemtest/TestTag.java, systemtests/src/main/java/io/enmasse/systemtest/info/TestInfo.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitExecutionListener.java, systemtests/src/test/java/io/enmasse/systemtest/condition/SupportedInstallTypesConditionTest.java, systemtests/src/test/java/io/enmasse/systemtest/framework/CustomPredicatesTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/CredentialsTest.java, systemtests/src/test/java/io/enmasse/systemtest/resources/CliOutputDataTest.java
- Enhancement 
This PR adds the first needed parts to have a test profile for systemtests itself, our testsuite has grown and it's reaching a point where it's worth it to have some unit tests for some logic and utilities we have built for our tests.
This is still a WIP, there are more tests that can be added and we still have to run this new test profile in our build process, run this in our CI( gh actions,...) we can do that in this PR or leave that for once this PR is merged...
=> Systemtests framework tests

systemtests/scripts/collect_logs.sh
- Bugfix
Updates collect_logs.sh for kubernetes (kubectl) compatibility.
=> Update collect_logs.sh for kubernetes (kubectl) compatibility

console/console-init/ui/src/components/DropdownWithToggle/DropdownWithToggle.tsx, console/console-init/ui/src/modules/address-detail/components/AddressDetailHeader/AddressDetailHeader.tsx, console/console-init/ui/src/modules/address-detail/components/AddressLinksToolbarToggleGroup/AddressLinksToolbarToggleGroup.tsx, console/console-init/ui/src/modules/address-detail/containers/AddressLinksFilter/AddressLinksFilter.tsx, console/console-init/ui/src/modules/address-space/components/AddressSpaceConfiguration/AddressSpaceConfiguration.tsx, console/console-init/ui/src/modules/address-space/components/AddressSpaceList/AddressSpaceList.tsx, console/console-init/ui/src/modules/address-space/components/AddressSpaceListKebab/AddressSpaceListKebab.tsx, console/console-init/ui/src/modules/address-space/containers/AddressSpaceListContainer/AddressSpaceListContainer.tsx, console/console-init/ui/src/modules/address/components/AddressConfiguration/AddressConfiguration.tsx, console/console-init/ui/src/modules/address/components/AddressListKebab/AddressListKebab.tsx, console/console-init/ui/src/modules/address/components/AddressToolbarToggleGroup/AddressToolbarToggleGroup.tsx, console/console-init/ui/src/modules/address/containers/AddressFilter/AddressFilter.tsx, console/console-init/ui/src/modules/address/dialogs/CreateAddress/Configuration.tsx, console/console-init/ui/src/modules/connection-detail/components/ConnectionDetailFilter/ConnectionDetailFilter.tsx, console/console-init/ui/src/modules/connection/containers/ConnectionToolbar/ConnectionToolbar.tsx
- Refactoring
replaced drop down with custom  component DropdownWithToggle and DropdownWithKebabToggle
=> replaced drop down with custom  component DropdownWithToggle and DropdownWithKebabToggle

console/console-init/ui/src/modules/address-detail/components/AddressLinksToolbarToggleGroup/AddressLinksToolbarToggleGroup.tsx
- Bugfix
fixed dopdown list lisse
=> fixed dopdown list lisse

.github/scripts/build.sh, systemtests/pom.xml
=> Add unit test step for systemtests

templates/iot/examples/postgresql/drop.sql, templates/iot/examples/postgresql/drop.table.sql, templates/iot/examples/postgresql/drop.tree.sql
Improve the SQL scripts in iot postgresql deployment examples to delete all the created tables and indexes.
=> fix sql scripts in iot examples

systemtests/src/main/java/io/enmasse/systemtest/Environment.java, systemtests/src/main/java/io/enmasse/systemtest/scale/ScaleTestEnvironment.java
=> Load scale env data from jsonFile

systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitExecutionListener.java, systemtests/src/main/java/io/enmasse/systemtest/logs/GlobalLogCollector.java, systemtests/src/main/java/io/enmasse/systemtest/manager/ResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java, systemtests/src/main/java/io/enmasse/systemtest/scale/ScaleTestManager.java, systemtests/src/main/java/io/enmasse/systemtest/time/TimeMeasuringSystem.java, systemtests/src/main/java/io/enmasse/systemtest/utils/AddressSpaceUtils.java, systemtests/src/main/java/io/enmasse/systemtest/utils/AddressUtils.java, systemtests/src/test/java/io/enmasse/systemtest/scale/ScaleTest.java
- Enhancement 
This PR addresses some feedback received about scale tests.
- improve error message for errors from clients metrics monitoring
- improve error for failure recovery test for error when creating addresses and measuring time
- more reduction of log verbosity, note the current setting of the disablement is done programmatically but in future will be made using env var
- add timestamp to clients name, so clients logs can be ordered by client deployment order
=> Scale tests improvements

console/console-init/ui/src/modules/connection/containers/ConnectionContainer/ConnectionContainer.tsx
- Bugfix
fixed table header issue
=> fixed table header issue

.github/scripts/setup_docker.sh, .github/workflows/master.yml, .github/workflows/release.yml, .github/workflows/smoke.yml
=> Update ruby action

console/console-init/ui/src/components/Graphs/Graphs.tsx, console/console-init/ui/src/components/Graphs/index.ts, console/console-init/ui/src/modules/address-space/components/AddressSpaceList/AddressSpaceList.tsx, console/console-init/ui/src/modules/address-space/utils/TableFormatter.tsx
This PR adds a column for graph on address spaces table and creates a new sample graph component.
=> Add graph poc to Address space table

.github/workflows/master.yml, .github/workflows/release.yml
=> Fix master build with ruby

documentation/design/proposals/shared-infrastructure.adoc
Modifications of proposal based on meeting in Brno.
=> Shared infra proposal improvements

address-space-controller/Dockerfile, broker-plugin/Dockerfile, iot/iot-auth-service/Dockerfile, iot/iot-device-registry-file/Dockerfile, iot/iot-device-registry-infinispan/Dockerfile, iot/iot-http-adapter/Dockerfile, iot/iot-lorawan-adapter/Dockerfile, iot/iot-mqtt-adapter/Dockerfile, iot/iot-sigfox-adapter/Dockerfile, iot/iot-tenant-service/Dockerfile, keycloak-plugin/Dockerfile, mqtt-gateway/Dockerfile, mqtt-lwt/Dockerfile, none-authservice/Dockerfile, service-broker/Dockerfile, standard-controller/Dockerfile, topic-forwarder/Dockerfile
Only merge after EnMasseProject/java-docker-base#8 was merged!
=> Switch to java base image 11-5

.github/scripts/olm_test.sh, systemtests/pom.xml, systemtests/src/main/java/io/enmasse/systemtest/Environment.java, systemtests/src/test/java/io/enmasse/systemtest/olm/OLMLinksTest.java
=> systemtests - olm csv links

console/console-init/ui/src/components/Editor/Editor.tsx, console/console-init/ui/src/components/Editor/index.ts, console/console-init/ui/src/components/FinishedStep/FinishedStep.tsx, console/console-init/ui/src/components/FinishedStep/index.ts, console/console-init/ui/src/components/FormAndJson/FormAndJson.tsx, console/console-init/ui/src/components/FormAndJson/index.ts, console/console-init/ui/src/components/index.ts, console/console-init/ui/src/modules/address-space/AddressSpacePage.tsx, console/console-init/ui/src/modules/msg-and-iot/dailogs/components/MessagingProjectConfiguration/MessagingProjectConfiguration.tsx, console/console-init/ui/src/modules/msg-and-iot/dailogs/components/MessagingProjectConfiguration/index.ts, console/console-init/ui/src/modules/msg-and-iot/dailogs/components/MessagingProjectReview/MessagingProjectReview.tsx, console/console-init/ui/src/modules/msg-and-iot/dailogs/components/MessagingProjectReview/index.ts, console/console-init/ui/src/modules/msg-and-iot/dailogs/components/ProjectTypeConfiguration/ProjectTypeConfiguration.tsx, console/console-init/ui/src/modules/msg-and-iot/dailogs/components/ProjectTypeConfiguration/index.ts, console/console-init/ui/src/modules/msg-and-iot/dailogs/components/index.ts, console/console-init/ui/src/modules/msg-and-iot/dailogs/containers/CreateProjectContainer/CreateProjectContainer.tsx, console/console-init/ui/src/modules/msg-and-iot/dailogs/containers/CreateProjectContainer/index.ts, console/console-init/ui/src/modules/msg-and-iot/dailogs/containers/index.ts, console/console-init/ui/src/modules/msg-and-iot/dailogs/utils/index.ts, console/console-init/ui/src/modules/msg-and-iot/dailogs/utils/utils.ts
- Add poc component for create project wizard
=> add create project wizard

documentation/modules/con-standard-subscription.adoc
Docs:changed attribute to field
- [ x] Update documentation
=> Docs:changed attribute to field

iot/iot-jdbc-base/src/main/java/io/enmasse/iot/jdbc/store/StatementConfiguration.java, iot/iot-jdbc-base/src/test/java/io/enmasse/iot/jdbc/store/StatementTest.java
=> Fix YAML parsing

console/console-init/ui/src/components/InputText/InputText.tsx, console/console-init/ui/src/components/InputText/index.ts, console/console-init/ui/src/components/index.ts, console/console-init/ui/src/stories/AddressList.stories.tsx, console/console-init/ui/src/stories/AppHeader.stories.tsx, console/console-init/ui/src/stories/InputBox.stories.tsx
- add visual component to support input box with copy and expandable feature
=> add input box with all possiblity as a common component

pkg/controller/authenticationservice/standard.go
=> Ensure that each standard authservice uses separate admin credentials

systemtests/src/main/java/io/enmasse/systemtest/iot/CredentialsRegistryClient.java, systemtests/src/main/java/io/enmasse/systemtest/iot/DefaultDeviceRegistry.java, systemtests/src/main/java/io/enmasse/systemtest/iot/HttpAdapterClient.java, systemtests/src/main/java/io/enmasse/systemtest/iot/IoTTestSession.java, systemtests/src/main/java/io/enmasse/systemtest/iot/MessageSendTester.java, systemtests/src/main/java/io/enmasse/systemtest/iot/MqttAdapterClient.java, systemtests/src/main/java/io/enmasse/systemtest/logs/GlobalLogCollector.java, systemtests/src/main/java/io/enmasse/systemtest/mqtt/MqttClientFactory.java, systemtests/src/main/java/io/enmasse/systemtest/utils/IoTUtils.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/iot/IoTTestSessionTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/MessageSendTesterTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/AbstractMaxPayloadSizeTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/http/MaxPayloadSizeTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/mqtt/MaxPayloadSizeTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/shared/control/CommandAndControlTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/shared/http/HttpAdapterTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/shared/mqtt/MqttAdapterTest.java
Run tests for "max payload"
- Bugfix
=> Test max payload settings

pkg/amqpcommand/command_client.go, pkg/consolegraphql/agent/agent.go
- Refactoring
This allows reusing this component for AMQP management for other
components as part of shared infrastructure.
=> Pull out generic AMQP command client into separate module

address-space-controller/src/main/java/io/enmasse/controller/RouterConfigController.java, address-space-controller/src/main/java/io/enmasse/controller/router/config/Connector.java, address-space-controller/src/main/java/io/enmasse/controller/router/config/Role.java, address-space-controller/src/test/java/io/enmasse/controller/RouterConfigControllerTest.java, api-model/src/main/java/io/enmasse/address/model/AddressSpaceSpecConnector.java, pkg/apis/enmasse/v1beta1/types.go, pkg/apis/enmasse/v1beta1/zz_generated.deepcopy.go, systemtests/src/test/java/io/enmasse/systemtest/isolated/bridging/ConnectorsTest.java, templates/crds/addressspaces.crd.yaml
Expose a few useful settings to address space connectors.
=> Add idleTimeout, role and maxFrameSize settings for connectors

systemtests/src/main/java/io/enmasse/systemtest/bases/isolated/ITestIsolatedSharedInfra.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java, systemtests/src/main/java/io/enmasse/systemtest/messaginginfra/MessagingInfraResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/messaginginfra/crds/MessagingInfraCrd.java, systemtests/src/test/java/io/enmasse/systemtest/bases/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/sharedinfra/MessagingInfraTest.java
- Enhancement
new approach of shared resource manager for messaging ifra
=> Common resource manager for new messaging

console/console-init/ui/src/components/FormAndJson/FormAndJson.tsx, console/console-init/ui/src/components/ProjectHeaderCard/ProjectHeaderCard.tsx, console/console-init/ui/src/components/ProjectHeaderCard/index.ts, console/console-init/ui/src/components/index.ts, console/console-init/ui/src/stories/AppHeader.stories.tsx, console/console-init/ui/src/stories/ProjectHeaderCard.stories.tsx
- add visual component to display project counts as a header in project list.
=> add visual components for count detail header of project list

systemtests/src/main/java/io/enmasse/systemtest/iot/IoTTestSession.java, systemtests/src/test/java/io/enmasse/systemtest/iot/IoTTestSessionTest.java
=>  Don't require running kubernetes for framework test

console/console-init/pom.xml
Investigating GIT ci build issue
=> Prevents react warnings being promoted to errors failing the build on CI

.github/scripts/setup_docker.sh
I want try to change our docker installation script to official docker action.
=> Change docker installation

pkg/controller/messaginginfra/cert/controller.go, pkg/controller/messaginginfra/cert/controller_test.go
(And fix bug in test with wrong assertion on cert valid when ca is expired)
Fixes #4297
=> Add clock interface to make unit tests deterministic

console/console-init/ui/src/components/AddressSpaceList/AddressSpaceListFilter.tsx, console/console-init/ui/src/components/ConnectionDetail/ConnectionDetailHeader.tsx, console/console-init/ui/src/pages/AddressDetail/AddressLinksFilter.tsx, console/console-init/ui/src/pages/AddressDetail/AddressLinksListPage.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/AddressList/AddressListFilter.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/ConnectionList/ConnectionListFilter.tsx, console/console-init/ui/src/pages/AddressSpaceDetail/ConnectionList/ConnectionsListPage.tsx, console/console-init/ui/src/pages/AddressSpaceList/AddressSpaceListPage.tsx, console/console-init/ui/src/pages/ConnectionDetail/ConnectionDetailPage.tsx, console/console-init/ui/src/pages/ConnectionDetail/ConnectionLinksFilter.tsx, console/console-init/ui/src/pages/ConnectionDetail/ConnectionsLinksListPage.tsx, console/console-init/ui/src/pages/CreateAddress/PreviewAddress.tsx, console/console-init/ui/src/pages/CreateAddressSpace/ReviewAddressSpace.tsx, console/console-init/ui/src/pages/EditAddressSpace.tsx, console/console-init/ui/src/queries/Address.ts, console/console-init/ui/src/queries/AddressSpace.ts, console/console-init/ui/src/queries/Connection.ts, console/console-init/ui/src/types/Configs.tsx, console/console-init/ui/src/utils/utils.ts
- Bugfix
This PR adds the following functionalities:
- Escape forbidden chars in all the filters
- Remove escape characters from filter chips
- Remove Title from Edit Dialog of Address Space
- Remove warnings from Filter components
- Remove unwanted console logs
=> Escape forbidden chars in filters

systemtests/src/main/java/io/enmasse/systemtest/clients/ClientUtils.java
- Refactoring
Remove a debug statement from a test class
=> Remove test class debug

console/console-init/ui/package.json, console/console-init/ui/src/modules/address-space/containers/AddressSpaceListContainer/AddressSpaceListContainer.tsx, console/console-init/ui/src/modules/address/components/EmptyAddress/EmptyAddress.test.tsx, console/console-init/ui/src/modules/address/containers/AddressListContainer/AddressListContainer.test.tsx, console/console-init/ui/src/modules/connection-detail/containers/ConnectionLinksContainer/ConnectionLinksContainer.tsx, console/console-init/ui/src/modules/connection/components/ConnectionList/ConnectionList.tsx, console/console-init/ui/src/modules/connection/containers/ConnectionContainer/ConnectionContainer.tsx, console/console-init/ui/yarn.lock
- Bugfix
Fixed failed unit tests and upgrade react-hook package version for fixing tests
=> Fixed failed unit tests

CHANGELOG.md, pom.xml
Bump vertx from 3.8.3 to 3.9.0
=> Bump vertx from 3.8.3 to 3.9.0

systemtests/src/main/java/io/enmasse/systemtest/scale/ScaleTestManager.java, systemtests/src/test/java/io/enmasse/systemtest/scale/ScaleTest.java, systemtests/src/test/java/io/enmasse/systemtest/scale/ScaleTestManagerTest.java
=> systemtests - framework test - ScaleTestManagerTest

console/console-init/ui/src/modules/address-space/dialogs/CreateAddressSpace/Configuration.tsx, console/console-init/ui/src/modules/connection-detail/ConnectionDetailPage.tsx
- Bugfix
- Fix - no connection found state (i.e Fix - Links page goes blank if connection goes away)
- Add description in dropdown of plan in create address space (
=> add description in plan dropdown of create addressspace

console/console-init/ui/src/components/SortForMobileView/SortForMobileView.tsx
- Bugfix
- Fix - apply sort for mobile view.
=> fix - sorting for mobile view

console/console-init/ui/src/components/DropdownWithToggle/DropdownWithToggle.tsx, console/console-init/ui/src/graphql-module/queries/Connection.ts
- Bugfix
- add changes to select the option as default for dropdown if there is only one option.
- fixed typo in connection.ts query file
=> Default value for dropdown

systemtests/src/main/java/io/enmasse/systemtest/executor/Exec.java, systemtests/src/main/java/io/enmasse/systemtest/executor/ExecutionResultData.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitExecutionListener.java, systemtests/src/main/java/io/enmasse/systemtest/operator/EnmasseOperatorManager.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/platform/cluster/KubeClusterManager.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/upgrade/UpgradeTest.java, systemtests/src/test/java/io/enmasse/systemtest/olm/OLMDefaultTest.java, systemtests/src/test/java/io/enmasse/systemtest/olm/OLMLinksTest.java, systemtests/src/test/java/io/enmasse/systemtest/olm/OLMSpecificTest.java
management of kube cluster, operations like scale nodes,
=> Cluster manager

systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java
- Bugfix
As suggested, in this PR the test doTestFilterAddressesByStatus is improved to not depend on the time the addresses are in the configuring phase
=> fix racey console test doTestFilterAddressesByStatus

iot/iot-jdbc-base/src/main/java/io/enmasse/iot/jdbc/store/device/TableManagementStore.java, systemtests/src/main/java/io/enmasse/systemtest/iot/DefaultDeviceRegistry.java, systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/SimpleK8sDeployTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/DeviceRegistryTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/H2DeviceRegistryTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/PostgresTableDeviceRegistryTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/PostgresTreeDeviceRegistryTest.java, templates/iot/examples/postgresql/README.md, templates/iot/examples/postgresql/create.devcon.sql, templates/iot/examples/postgresql/create.sql, templates/iot/examples/postgresql/create.table.sql, templates/iot/examples/postgresql/drop.devcon.sql, templates/iot/examples/postgresql/drop.sql, templates/iot/examples/postgresql/drop.table.sql
- Bugfix
- Refactoring
Add test for table based device registry model with Postgres.
Also fixes: https://issues.redhat.com/browse/ENTMQMAAS-1951
=> Also test PostgreSQL with table model

CHANGELOG.md
Synching the CHANGELOG with the actual content.
=> Fixing up CHANGELOG for 0.31.1

console/console-init/ui/src/components/SelectWithToggle/SelectWithToggle.tsx, console/console-init/ui/src/components/SelectWithToggle/index.ts, console/console-init/ui/src/components/index.ts, console/console-init/ui/src/modules/address-detail/components/AddressLinksToggleGroup/AddressLinksToggleGroup.tsx, console/console-init/ui/src/modules/address-detail/components/AddressLinksToolbar/AddressLinksToolbar.tsx, console/console-init/ui/src/modules/address-detail/containers/AddressLinksToolbarContainer/AddressLinksToolbarContainer.tsx, console/console-init/ui/src/modules/address-space/components/MessagingDatatoolbarToggleGroup/MessagingDataToolbarToggleGroup.tsx, console/console-init/ui/src/modules/address-space/components/MessagingToolbar/MessagingToolbar.tsx, console/console-init/ui/src/modules/address-space/containers/MessagingToolbarContainer/MessagingToolbarContainer.tsx, console/console-init/ui/src/modules/address/components/AddressToggleGroup/AddressToggleGroup.tsx, console/console-init/ui/src/modules/address/components/AddressToolbar/AddressToolbar.tsx, console/console-init/ui/src/modules/address/containers/AddressToolbarContainer/AddressToolbarContainer.tsx, console/console-init/ui/src/modules/connection-detail/components/ConnectionLinksToggleGroup/ConnectionLinksToggleGroup.tsx, console/console-init/ui/src/modules/connection-detail/components/ConnectionLinksToolbar/ConnectionLinksToolbar.tsx, console/console-init/ui/src/modules/connection-detail/containers/ConnectionLinksToolbarContainer/ConnectionLinksToolbarContainer.tsx, console/console-init/ui/src/utils/utils.ts
- Refactoring
1. Create new  SelectWithToggle component
2. Replace all Select component with  SelectWithToggle component
=> Created SelectWithToggle component and replace existing code with SelectWithToggle component

console/console-init/ui/src/components/TypeAheadSelect/TypeAheadSelect.tsx, console/console-init/ui/src/graphql-module/queries/Address.ts, console/console-init/ui/src/graphql-module/queries/AddressSpace.ts, console/console-init/ui/src/graphql-module/queries/Connection.ts, console/console-init/ui/src/graphql-module/queries/query.ts, console/console-init/ui/src/modules/address-space/AddressSpaceDetailPage.tsx, console/console-init/ui/src/modules/address-space/containers/MessagingToolbarContainer/MessagingToolbarContainer.tsx, console/console-init/ui/src/modules/address/components/AddressToggleGroup/AddressToggleGroup.tsx, console/console-init/ui/src/modules/address/components/EmptyAddress/EmptyAddress.test.tsx, console/console-init/ui/src/modules/address/components/EmptyAddress/EmptyAddress.tsx, console/console-init/ui/src/modules/connection/containers/ConnectionToolbarContainer/ConnectionToolbarContainer.tsx
- Bugfix
1. Create generic query filter functions
2. Refactor queries 
3. Create and refactor typeahead api call in components 
4. Removed unused code
=> Refactor queries and create generic query filter functions

documentation/common/attributes.adoc, documentation/modules/proc-installing-using-ansible.adoc
=> Docs:update_example

console/console-init/ui/src/modules/iot-detail/components/IoTProjectDetailHeader/IoTProjectDetailHeader.tsx, console/console-init/ui/src/modules/iot-detail/components/IoTProjectDetailHeader/index.ts, console/console-init/ui/src/modules/iot-detail/components/index.ts, console/console-init/ui/src/stories/IoTProjectDetailHeader.stories.tsx
- add project detail header component
=> add project-detail header component

.github/scripts/build.sh, .github/scripts/clean_disk.sh, .github/scripts/setup_docker.sh, .github/scripts/smoke_test.sh, .github/workflows/master.yml, .github/workflows/release.yml, .github/workflows/smoke.yml
- Bugfix
Changed docker installation to package to docker official repositories.
=> Change docker installation package

systemtests/src/main/java/io/enmasse/systemtest/clients/ClientUtils.java, systemtests/src/main/java/io/enmasse/systemtest/condition/AssumeKubernetesCondition.java, systemtests/src/main/java/io/enmasse/systemtest/condition/AssumeOpenshiftCondition.java, systemtests/src/main/java/io/enmasse/systemtest/condition/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/condition/MultinodeCluster.java, systemtests/src/main/java/io/enmasse/systemtest/condition/OpenShift.java, systemtests/src/main/java/io/enmasse/systemtest/condition/OpenShiftVersion.java, systemtests/src/main/java/io/enmasse/systemtest/executor/Exec.java, systemtests/src/main/java/io/enmasse/systemtest/platform/KubeCMDClient.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/platform/cluster/KubeClusterManager.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/CommonTest.java, systemtests/src/test/java/io/enmasse/systemtest/soak/StabilityTest.java
=> Test operable enmasse after kube node drain

documentation/modules/proc-examine-broker-state.adoc
=> Docs:fix_command_typo

documentation/modules/proc-iot-installing-services.adoc
=> Docs:fixed_special_characters

console/console-init/ui/src/components/FinishedStep/FinishedStep.tsx, console/console-init/ui/src/modules/msg-and-iot/dailogs/components/IoTConfiguration/IoTConfiguration.tsx, console/console-init/ui/src/modules/msg-and-iot/dailogs/components/IoTConfiguration/index.ts, console/console-init/ui/src/modules/msg-and-iot/dailogs/components/IoTProjectConfiguration/IoTProjectConfiguration.tsx, console/console-init/ui/src/modules/msg-and-iot/dailogs/components/IoTProjectConfiguration/index.ts, console/console-init/ui/src/modules/msg-and-iot/dailogs/components/IoTProjectReview/IoTProjectReview.tsx, console/console-init/ui/src/modules/msg-and-iot/dailogs/components/IoTProjectReview/index.ts, console/console-init/ui/src/modules/msg-and-iot/dailogs/components/IoTReview/IoTReview.tsx, console/console-init/ui/src/modules/msg-and-iot/dailogs/components/IoTReview/index.ts, console/console-init/ui/src/modules/msg-and-iot/dailogs/components/MessagingProjectConfiguration/MessagingProjectConfiguration.tsx, console/console-init/ui/src/modules/msg-and-iot/dailogs/components/ProjectTypeConfiguration/ProjectTypeConfiguration.tsx, console/console-init/ui/src/modules/msg-and-iot/dailogs/containers/CreateProjectContainer/CreateProjectContainer.tsx, console/console-init/ui/src/modules/msg-and-iot/dailogs/utils/utils.ts
- Add wizard for create messaging and iot project
=> add wizard for create messaging project

pkg/apis/iot/v1alpha1/funcs.go, pkg/apis/iot/v1alpha1/interfaces.go, pkg/apis/iot/v1alpha1/types_config.go, pkg/apis/iot/v1alpha1/zz_generated.deepcopy.go, pkg/controller/iotconfig/adapter.go, pkg/controller/iotconfig/auth_service.go, pkg/controller/iotconfig/infinispan_device_connection.go, pkg/controller/iotconfig/infinispan_device_registry.go, pkg/controller/iotconfig/jdbc_device_connection.go, pkg/controller/iotconfig/jdbc_device_registry.go, pkg/controller/iotconfig/tenant_service.go, pkg/controller/iotconfig/utils.go, pkg/util/install/utils.go
=> Prevent empty TLS versions field

systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/MultipleProjectsTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/H2DeviceRegistryTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/InfinispanDeviceRegistryTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/PostgresFlatDeviceRegistryTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/PostgresTableDeviceRegistryTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/PostgresTreeDeviceRegistryTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/mqtt/PublishTest.java
- Refactoring
Add few iot and brokered mqtt tests to acceptance profile, which is also triggered in case enmasse is installed via OLM.
=> Add few iot and brokered mqtt to acceptance

console/console-init/ui/src/modules/address-detail/components/TypeBadge/TypeBadge.tsx, console/console-init/ui/src/modules/address-detail/utils/index.ts, console/console-init/ui/src/modules/address/components/AddressErrorMessage/AddressErrorMessage.tsx, console/console-init/ui/src/modules/address/components/AddressListKebab/AddressListKebab.tsx, console/console-init/ui/src/modules/address/utils/utils.ts, console/console-init/ui/src/modules/connection-detail/components/ConnectionLinksToggleGroup/ConnectionLinksToggleGroup.tsx, console/console-init/ui/src/modules/connection-detail/components/ConnectionLinksToolbar/ConnectionLinksToolbar.tsx, console/console-init/ui/src/types/Configs.tsx, console/console-init/ui/src/utils/utils.ts
Copyright and license have been prepended to the UI source files where they were missing.
=> Style: add copyright/license in UI source files

console/console-init/ui/src/components/Editor/Editor.tsx, console/console-init/ui/src/components/InputText/InputText.tsx, console/console-init/ui/src/components/JsonViewEditor/JsonViewEditor.tsx, console/console-init/ui/src/components/JsonViewEditor/index.ts, console/console-init/ui/src/components/ProjectHeaderCard/ProjectHeaderCard.tsx, console/console-init/ui/src/components/index.ts, console/console-init/ui/src/modules/project-detail/components/AccessCredentials/AccessCredentials.tsx, console/console-init/ui/src/modules/project-detail/components/AccessCredentials/index.ts, console/console-init/ui/src/modules/project-detail/components/DeviceRegistrationManagement/DeviceRegistrationManagement.tsx, console/console-init/ui/src/modules/project-detail/components/DeviceRegistrationManagement/index.ts, console/console-init/ui/src/modules/project-detail/components/GeneralInfo/GeneralInfo.tsx, console/console-init/ui/src/modules/project-detail/components/GeneralInfo/index.ts, console/console-init/ui/src/modules/project-detail/components/ProjectNavigation/ProjectNavigation.tsx, console/console-init/ui/src/modules/project-detail/components/ProjectNavigation/index.ts, console/console-init/ui/src/modules/project-detail/components/index.ts, console/console-init/ui/src/stories/InputBox.stories.tsx, console/console-init/ui/src/stories/ProjectDetail.stories.tsx, console/console-init/ui/src/stories/ProjectDetailPage.stories.tsx, console/console-init/ui/src/utils/utils.ts
- add visual component for project detail 
- add visual component for navigation
=> add visual component for project detail

templates/crds/iotconfigs.crd.yaml, templates/crds/iotprojects.crd.yaml
=> Add more basic openapi spec, limit IoTConfig name

systemtests/src/main/java/io/enmasse/systemtest/platform/KubeCMDClient.java
- Refactoring
Fail systemtests when installation fail.
=> Fail systemtests if installation fails

console/console-init/ui/src/components/FormAndJson/FormAndJson.tsx, console/console-init/ui/src/modules/address-space/AddressSpacePage.tsx, console/console-init/ui/src/modules/device/components/ConnectionTypeStep/ConnectionTypeStep.tsx, console/console-init/ui/src/modules/device/components/ConnectionTypeStep/index.ts, console/console-init/ui/src/modules/device/dialogs/CreateDevice/CreateDevice.tsx, console/console-init/ui/src/modules/iot-detail/components/IoTProjectDetailHeader/IoTProjectDetailHeader.tsx, console/console-init/ui/src/modules/msg-and-iot/dailogs/components/IoTConfiguration/IoTConfiguration.tsx, console/console-init/ui/src/modules/project-detail/components/AccessCredentials/AccessCredentials.tsx, console/console-init/ui/src/modules/project-detail/components/DeviceRegistrationManagement/DeviceRegistrationManagement.tsx
- Refactoring
- use Switch component 
- update create device component.
=> add wizard for create device

console/console-init/ui/src/components/DropdownWithToggle/DropdownWithToggle.tsx, console/console-init/ui/src/components/SelectWithToggle/SelectWithToggle.tsx, console/console-init/ui/src/modules/address-space/components/MessagingDatatoolbarToggleGroup/MessagingDataToolbarToggleGroup.tsx, console/console-init/ui/src/modules/address/components/AddressList/AddressList.tsx, console/console-init/ui/src/modules/address/components/AddressListKebab/AddressListKebab.tsx, console/console-init/ui/src/modules/address/components/AddressToggleGroup/AddressToggleGroup.tsx, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/resources/AddressWebItem.java
=> fix system test for edit,delete and purge address

documentation/assemblies/assembly-iot-creating-device.adoc
=> Docs:Edit {registry} variable

console/console-init/ui/src/components/DropdownWithToggle/DropdownWithToggle.tsx, console/console-init/ui/src/components/ToggleIcon/ToggleIcon.tsx, console/console-init/ui/src/components/ToggleIcon/index.ts, console/console-init/ui/src/components/index.ts, console/console-init/ui/src/modules/address/components/AddressConfiguration/AddressConfiguration.tsx, console/console-init/ui/src/modules/device/components/AddCredential/AddCredential.tsx, console/console-init/ui/src/modules/device/components/AddCredential/index.ts, console/console-init/ui/src/modules/device/components/CredentialList/CredentialList.tsx, console/console-init/ui/src/modules/device/components/CredentialList/index.ts, console/console-init/ui/src/modules/device/components/ExtensionList/ExtensionList.tsx, console/console-init/ui/src/modules/device/components/ExtensionList/index.ts, console/console-init/ui/src/modules/device/components/SecretList/SecretList.tsx, console/console-init/ui/src/modules/device/components/SecretList/index.ts, console/console-init/ui/src/modules/device/components/index.ts, console/console-init/ui/src/modules/device/index.ts, console/console-init/ui/src/stories/AddCredential.stories.tsx, console/console-init/ui/src/utils/utils.ts
- Refactoring
1. Fixed label and value issue in case different in DropdownWithToggle component
2. Create ToggleIcon component
3. Create AddCredential component 
4. Create CredentialList component
5. Create SecretList component
6. Create ExtensionList component
7. Save fields value in json object.
8. Create storybook test component
=> Create add credentials  page visual components and save value

console/console-init/ui/src/modules/address/containers/AddressDefinitionContainer/AddressDefinitionContainer.tsx
- Bugfix
Added id to fix system test - testCreateDeleteDurableSubscription
=> Add id to fix testCreateDeleteDurableSubscription

console/console-init/ui/src/modules/device/components/DeviceListAlert/DeviceListAlert.test.tsx, console/console-init/ui/src/modules/device/components/DeviceListAlert/DeviceListAlert.tsx, console/console-init/ui/src/modules/device/components/DeviceListAlert/index.ts, console/console-init/ui/src/stories/DeviceList.stories.tsx
- new feature
The alert component for` DeviceListPage` has been created along with unit tests.
=> Feature: Create Alert for DeviceList

pkg/controller/iotconfig/mesh.go
=> Only set TLS versions when we have some

iot/iot-device-registry-base/src/main/java/io/enmasse/iot/registry/debug/DebugEndpoint.java
=> Only fire up the debug port when the beans are present

documentation/modules/proc-iot-installing-cli.adoc
=> Update message host command

console/console-init/ui/src/components/ToggleIcon/ToggleIcon.tsx
Enhanced ToggleIcon component to pass Icon as props as per requirement. if not pass it will take default icon.
=> enhanced ToggleIcon component to pass icon as props

templates/iot/examples/postgresql/create.table.sql, templates/iot/examples/postgresql/create.tree.sql
=> Fix example index for PostgreSQL

documentation/modules/proc-iot-installing-services.adoc
Fix docs for setting up PostgreSQL
=> PSQL docs - add devcon service and fix syntax

console/console-init/ui/src/components/NoResultFound/NoResultFound.test.tsx, console/console-init/ui/src/components/NoResultFound/NoResultFound.tsx, console/console-init/ui/src/components/NoResultFound/index.ts, console/console-init/ui/src/components/index.ts
- New visual component
A generic component that is to be displayed when applied filters return no result.
=> Feat: no result component

systemtests/src/main/java/io/enmasse/systemtest/amqp/AmqpClient.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/web/FirefoxConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/ChromeConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/FirefoxConsoleTest.java
Test for console, try to sort addresses by messages stored for queue
=> Add test for sort by stored messages

console/console-init/ui/src/components/DropdownWithToggle/DropdownWithToggle.tsx, console/console-init/ui/src/components/SortForMobileView/SortForMobileView.tsx, console/console-init/ui/src/components/TypeAheadSelect/TypeAheadSelect.tsx, console/console-init/ui/src/graphql-module/queries/Address.ts, console/console-init/ui/src/modules/address-detail/components/AddressLinksToggleGroup/AddressLinksToggleGroup.tsx, console/console-init/ui/src/modules/address-space/components/AddressSpaceListKebab/AddressSpaceListKebab.tsx, console/console-init/ui/src/modules/address-space/components/MessagingDatatoolbarToggleGroup/MessagingDataToolbarToggleGroup.tsx, console/console-init/ui/src/modules/address/components/AddressConfiguration/AddressConfiguration.tsx, console/console-init/ui/src/modules/address/components/AddressToggleGroup/AddressToggleGroup.tsx, console/console-init/ui/src/modules/address/containers/AddressDefinitionContainer/AddressDefinitionContainer.tsx, console/console-init/ui/src/modules/connection-detail/components/ConnectionLinksToggleGroup/ConnectionLinksToggleGroup.tsx, console/console-init/ui/src/modules/connection/components/ConnectionsToggleGroup/ConnectionsToggleGroup.tsx, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java
- Bugfix
- Refactoring
Fixed system tests
=> Fixed systemtests

console/console-init/ui/public/index.html, console/console-init/ui/public/manifest.json
- Bugfix
Fix default app title issue, in case title will not set, default title will display "Messaging Console"
=> Fixed default app title issue

systemtests/src/main/java/io/enmasse/systemtest/Environment.java, systemtests/src/main/java/io/enmasse/systemtest/annotations/SkipResourceLogging.java, systemtests/src/main/java/io/enmasse/systemtest/annotations/SkipResourceLoggingExtension.java, systemtests/src/main/java/io/enmasse/systemtest/messaginginfra/ResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/sharedinfra/MessagingAddressPerfTest.java
- Refactoring
Clean env class and add ability to disable resource logging
=> Clean env and annotation for verbose resoruce logging

console/console-init/ui/src/modules/device/components/DeviceList/DeviceList.test.tsx, console/console-init/ui/src/modules/device/components/DeviceList/DeviceList.tsx, console/console-init/ui/src/modules/device/components/DeviceList/index.tsx, console/console-init/ui/src/modules/device/utils/TableFormatter.tsx, console/console-init/ui/src/modules/device/utils/index.ts, console/console-init/ui/src/stories/DeviceList.stories.tsx
- New Visual Component
Implemented the visual component for the DeviceList table along with its storybook and a few test cases.
=> Feat: table component for DeviceList page

olm-manifest/src/main/resources/latest/enmasse.clusterserviceversion.yaml
=> Fix OLM permissions

systemtests/src/main/java/io/enmasse/systemtest/operator/EnmasseOperatorManager.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Minikube.java, systemtests/src/main/java/io/enmasse/systemtest/platform/OpenShift.java, systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java
- Refactoring
* Small clean of kubernetes class
* Small clean of systemtests kubernetes app class
* Remove okhttp client workaround in systemtests
=> Refactor kubernetes class and deployments

api-model/src/main/java/io/enmasse/address/model/AddressSpaceStatusRouter.java, api-model/src/main/java/io/enmasse/address/model/Schema.java, iot/iot-device-registry-base/src/main/java/io/enmasse/iot/registry/devcon/AbstractDeviceConnectionService.java, iot/iot-device-registry-base/src/test/java/io/enmasse/iot/registry/device/AbstractCredentialsManagementServiceTest.java, iot/iot-device-registry-infinispan/src/main/java/io/enmasse/iot/registry/infinispan/device/impl/CredentialsManagementServiceImpl.java, iot/iot-jdbc-base/src/main/java/io/enmasse/iot/jdbc/store/AbstractStore.java, iot/iot-service-base/src/main/java/io/enmasse/iot/service/base/AbstractKubernetesBasedService.java, iot/iot-utils/src/main/java/io/enmasse/iot/utils/MoreFutures.java, iot/iot-utils/src/test/java/io/enmasse/iot/utils/MoreFuturesTest.java
=> Drop dead code, update a few deprecated calls, and organize some imports

systemtests/pom.xml, systemtests/src/main/java/io/enmasse/systemtest/operator/EnmasseOperatorManager.java, systemtests/src/main/java/io/enmasse/systemtest/platform/KubeCMDClient.java
- Bugfix
This change fixes behavios in scale test when first scale test is sharedinfra and second is standard scale test, check for bundle installed checked only operator which is installed by sharedinfra and rest of scale test failed because no other crds etc are installed.
=> Fix install enmasse bundle after shared infra tests

documentation/assemblies/assembly-configuring-olm.adoc, documentation/modules/con-standard-queue.adoc, documentation/modules/proc-create-address-plan-custom-resource-olm-ui.adoc, documentation/modules/ref-iot-project-managed-example.adoc
=> Docs:Fix broken links 1

documentation/modules/proc-enable-protocol-trace-broker.adoc, documentation/modules/proc-enable-protocol-trace-router.adoc
=> Docs: Edit protocol trace ops procedures

systemtests/src/main/java/io/enmasse/systemtest/logs/GlobalLogCollector.java, systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java
- Enhancement
Collect logs and info from all namespaces which are used for systemtests (postgress, selenium etc...)
=> Collect logs from st namespaces

iot/iot-infinispan-base/src/main/java/io/enmasse/iot/infinispan/config/InfinispanProperties.java
=> Fix default name of device connection cache

go.mod
We made the switch to using go 1.13 language features, we need to reflect this in our metadata too.
=> Bump Go version in go.mod

systemtests/src/main/java/io/enmasse/systemtest/utils/IoTUtils.java
=> Fix NPE in case address space is requested, but missing

documentation/modules/proc-enable-protocol-trace-broker.adoc, documentation/modules/proc-enable-protocol-trace-router.adoc, documentation/modules/proc-examine-broker-state.adoc
=> Docs:Fix variable text

console/console-init/ui/src/modules/device/components/CreateDeviceButton/CreateDeviceButton.test.tsx, console/console-init/ui/src/modules/device/components/CreateDeviceButton/CreateDeviceButton.tsx, console/console-init/ui/src/modules/device/components/CreateDeviceButton/index.ts, console/console-init/ui/src/modules/device/components/EmptyDeviceList/EmptyDeviceList.test.tsx, console/console-init/ui/src/modules/device/components/EmptyDeviceList/EmptyDeviceList.tsx, console/console-init/ui/src/modules/device/components/EmptyDeviceList/index.ts, console/console-init/ui/src/modules/device/components/index.ts, console/console-init/ui/src/stories/DeviceList.stories.tsx
- Visual component
`EmptyDeviceList` component along with its storybook and unit tests.
=> Feat: visual component for empty device list

systemtests/src/main/java/io/enmasse/systemtest/iot/CredentialsRegistryClient.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/MultipleProjectsTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/project/ManagedTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/DeviceRegistryTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/registry/InfinispanDeviceRegistryTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/shared/control/CommandAndControlTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/shared/http/HttpAdapterTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/shared/mqtt/MqttAdapterTest.java
=> Add tests for conflicting tenant, type, auth combinations

console/console-init/ui/src/utils/utils.ts
- Bugfix
- Refactoring
Add changes to put key as "" for array element
=> add function getJsonForMetadata in utils

console/console-init/ui/src/modules/address-space/utils/AddressSpaceFormatter.tsx, console/console-init/ui/src/modules/address/components/AddressToggleGroup/AddressToggleGroup.tsx
- Bugfix
Include failed status in dropdown for address list.
=> add failed status in filter dropdown of adress list

console/console-init/ui/src/modules/address-space/components/AddressSpaceReview/AddressSpaceReview.tsx, console/console-init/ui/src/modules/address/dialogs/CreateAddress/Preview.tsx, console/console-init/ui/src/modules/msg-and-iot/components/IoTReview/IoTReview.tsx
- Bugfix
Add link to show/hide the configuration in IOT review screen
=> add method to show or hide the configuration code in iot review

documentation/design/user-stories/shared-infra.adoc
Convenient readable link: https://github.com/lulf/enmasse/blob/user-stories-1.0/documentation/design/user-stories/shared-infra.adoc
=> User stories 1.0

console/console-init/ui/src/components/BulkSelect/BulkSelect.test.tsx, console/console-init/ui/src/components/BulkSelect/BulkSelect.tsx, console/console-init/ui/src/components/BulkSelect/index.ts
- Visual component
Bulk select component for tables along with its unit tests.
=> Feat: bulk select component

address-space-controller/src/main/java/io/enmasse/controller/AddressSpaceController.java, address-space-controller/src/main/java/io/enmasse/controller/MetricsReporterController.java, address-space-controller/src/test/java/io/enmasse/controller/MetricsReporterTest.java, controller-manager/src/main/resources/templates/PrometheusRules-enmasse.yaml, controller-manager/src/main/resources/templates/ServiceMonitor-broker.yaml
Added alert for high broker address memory usage
=> Added alert for high broker address memory usage

console/console-init/ui/src/components/DropdownWithBulkSelect/DropdownWithBulkSelect.test.tsx, console/console-init/ui/src/components/DropdownWithBulkSelect/DropdownWithBulkSelect.tsx, console/console-init/ui/src/components/DropdownWithBulkSelect/index.ts, console/console-init/ui/src/components/index.ts, console/console-init/ui/src/modules/device/components/DeviceListToolbar/DeviceListToolbar.tsx, console/console-init/ui/src/modules/device/components/DeviceListToolbar/index.ts, console/console-init/ui/src/modules/device/components/index.ts, console/console-init/ui/src/stories/DeviceList.stories.tsx
- Visual component
The visual component for Device List Toolbar along with its storybook.
=> Feat: visual component for Device List Toolbar

systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java
- Bugfix
TestOpenShiftWithCustomCert robustness improvements
=> TestOpenShiftWithCustomCert robustness improvements

documentation/modules/con-address-space.adoc
Docs:Add text to note that users cannot modify endpoints for an existing address space.
=> Docs:Add text to note endpoints are not mutable

console/console-init/ui/src/modules/device/components/DeviceListToolbar/DeviceListToolbar.test.tsx
- Unit test
Unit tests for the `DeviceListToolbar` component.
=> Test: unit tests for DeviceListToolbar component

CHANGELOG.md, broker-plugin/amqp-connector/src/main/java/org/apache/activemq/artemis/integration/amqp/AMQPClientConnectionFactory.java, broker-plugin/amqp-connector/src/main/java/org/apache/activemq/artemis/integration/amqp/LinkInitiator.java, broker-plugin/amqp-connector/src/main/java/org/apache/activemq/artemis/integration/amqp/ProtonClientConnectionManager.java, broker-plugin/amqp-connector/src/main/java/org/apache/qpid/proton/engine/impl/LinkMutator.java
=> Disregard incoming remote target on receiving links initiated by the plugin

pom.xml, systemtests/pom.xml, systemtests/src/main/java/io/enmasse/systemtest/selenium/SeleniumProvider.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/Openshift4WebPage.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/OpenshiftLoginWebPage.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/OpenshiftWebPage.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/RheaWebPage.java
=> systemtests - remove ngwebdriver

console/console-init/ui/src/components/SwitchWithToggle/SwitchWithToggle.tsx, console/console-init/ui/src/components/SwitchWithToggle/index.ts, console/console-init/ui/src/components/index.ts, console/console-init/ui/src/modules/device-detail/components/DeviceDetailHeader/DeviceDetailHeader.test.tsx, console/console-init/ui/src/modules/device-detail/components/DeviceDetailHeader/DeviceDetailHeader.tsx, console/console-init/ui/src/modules/device-detail/components/DeviceDetailHeader/index.ts, console/console-init/ui/src/stories/DeviceDetail.stories.tsx, console/console-init/ui/src/stories/DeviceList.stories.tsx
add visual component for device detail header
=> add device detail header visual component

console/console-init/ui/yarn.lock
=> upgrade yarn

systemtests/src/test/java/io/enmasse/systemtest/isolated/web/FirefoxConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/web/FirefoxConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/FirefoxConsoleTest.java
- Refactoring
Adding more tests to acceptance profile to verify more features in case LP testing
=> Add more web tests to acceptance profile

systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java
=> olm image builder - wait until pod is created

console/console-init/ui/src/modules/device/components/DeviceList/DeviceList.tsx, console/console-init/ui/src/modules/device/components/DeviceListFooterToolbar/DeviceListFooterToolbar.tsx, console/console-init/ui/src/modules/device/components/DeviceListFooterToolbar/index.ts, console/console-init/ui/src/modules/device/components/index.ts, console/console-init/ui/src/stories/DeviceListPage.stories.tsx
- Storybook
* A storybook has been created using all visual components made for device list page
* Fixed a typo in DeviceList
=> Feat: story book for device list page

documentation/assemblies/assembly-connecting-applications.adoc
Document procedure for extracting the CA created by the selfsigned provider type.
=> [Docs] procedure for extracting a self signed cert

console/console-init/ui/src/components/JsonViewEditor/JsonViewEditor.tsx, console/console-init/ui/src/stories/JsonEditor.stories.tsx
-  Enhancement / new feature
- Create a generic component to handle the Editor and copy functionality.
=> Json editor -visual component

console/console-init/ui/src/components/DialogPrompt/DialogPrompt.tsx
Modify dialog prompt component to handle confirm label button and color and add icon in the header
=> Modify dialog prompt component

console/console-init/ui/yarn.lock
=> Update yarn dependencies

documentation/master-kubernetes.adoc, documentation/master-openshift.adoc, documentation/modules/proc-logging-in-console.adoc
Docs: Add KubePlatformCredentials variable
=> Docs:Add KubePlatformCredentials variable

console/console-init/ui/src/modules/device/components/DeviceFilter/DateFilterSection.tsx, console/console-init/ui/src/modules/device/components/DeviceFilter/DeviceFilter.tsx, console/console-init/ui/src/modules/device/utils/constant.ts, console/console-init/ui/src/modules/device/utils/index.ts, console/console-init/ui/src/stories/DeviceFilter.stories.tsx, console/console-init/ui/src/utils/utils.ts
Modify implementation of last redo filter. Redo last filter will update the filter to the previous state.
=> Device List Filter - redo last filter

documentation/modules/proc-standard-auth-service-ha.adoc
Docs: Fix code block formatting HA auth service
=> Docs: Fix code block formatting HA auth service

.github/scripts/install_dep.sh, .github/workflows/master.yml, .github/workflows/release.yml, .github/workflows/smoke.yml
- Bugfix
Install golang from official supported golang action to possibly avoid more issues with ubuntu packages.
=> Change golang installation

console/console-init/ui/src/stories/AddressSpaceHeader.stories.tsx, console/console-init/ui/src/stories/AddressSpaceList.stories.tsx
- Bugfix
- Storybook
The stories for AddressSpaceList and AddressSpaceHeader were not functional.
=> Fix: storybook for AddressSpaceList and AddressSpaceHeader

console/console-init/ui/src/modules/device/components/DeviceListAlert/DeviceListAlert.tsx, console/console-init/ui/src/modules/device/dialogs/CreateDevice/AddGateway.tsx, console/console-init/ui/src/modules/device/dialogs/CreateDevice/CreateDevice.tsx, console/console-init/ui/src/stories/DeviceList.stories.tsx, console/console-init/ui/src/stories/DeviceListPage.stories.tsx, console/console-init/ui/src/types/Configs.tsx
- Visual component
The add gateway step for `CreateDevice` wizard.
=> Feat: add device gateway in CreateDevice

.jenkins/Jenkinsfile-pr, systemtests/scripts/build_pr_response.sh
- Bugfix
Report correct PR message in case job failed or was aborted
=> Report proper Jenkins status into PR

CHANGELOG.md, console/console-init/ui/mock-console-server/README.md, console/console-init/ui/mock-console-server/mock-console-server.js, console/console-init/ui/mock-console-server/schema.js, console/console-server/src/main/resources/schema.graphql, pkg/consolegraphql/resolvers/generated.go, pkg/consolegraphql/resolvers/resolver_address.go, pkg/consolegraphql/resolvers/resolver_address_test.go, pkg/consolegraphql/resolvers/test_utils.go
- Refactoring
Implement new purgeAddresses API
=> Implement new purgeAddresses API

CHANGELOG.md, agent/bin/agent.js, agent/lib/artemis.js, agent/lib/broker_controller.js, agent/lib/console_server.js, agent/lib/qdr.js, agent/lib/registry.js, agent/lib/router_stats.js, cmd/console-server/main.go, console/console-init/ui/mock-console-server/README.md, console/console-init/ui/mock-console-server/mock-console-server.js, console/console-init/ui/mock-console-server/schema.js, console/console-server/src/main/resources/schema.graphql, pkg/consolegraphql/agent/agent.go, pkg/consolegraphql/agent/agenttypes.go, pkg/consolegraphql/resolvers/generated.go, pkg/consolegraphql/resolvers/resolver_address_test.go, pkg/consolegraphql/resolvers/resolver_connection.go, pkg/consolegraphql/resolvers/resolver_connection_test.go, pkg/consolegraphql/resolvers/test_utils.go, pkg/util/install/utils_test.go
Implement management connection close
=> Implement management connection close

templates/iot/examples/k8s-tls/common
=> Add missing IoT mesh certificates in example for plain k8s

systemtests/src/main/java/io/enmasse/systemtest/logs/GlobalLogCollector.java, systemtests/src/main/java/io/enmasse/systemtest/monitoring/MonitoringClient.java, systemtests/src/main/java/io/enmasse/systemtest/monitoring/MonitoringQueries.java, systemtests/src/main/java/io/enmasse/systemtest/operator/EnmasseOperatorManager.java, systemtests/src/main/java/io/enmasse/systemtest/platform/KubeCMDClient.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/monitoring/MonitoringTest.java
1. Refactor monitoring tests
2. Move install part into EnmasseOperatorManager
3. Few new tests for check if we export right data in prometheus
=> Monitoring tests

systemtests/src/main/java/io/enmasse/systemtest/Environment.java
- Bugfix
Allow to specify install type and olm install type with lower case word
=> Fix olm install type and install type

console/console-init/ui/src/components/DividerWithHeading/DividerWithHeading.tsx, console/console-init/ui/src/components/DividerWithTitle/DividerWithTitle.tsx, console/console-init/ui/src/components/DividerWithTitle/index.ts, console/console-init/ui/src/components/index.ts, console/console-init/ui/src/modules/device/components/AddCredential/AddCredential.tsx, console/console-init/ui/src/modules/device/components/CredentialList/CredentialList.tsx, console/console-init/ui/src/modules/device/components/ExtensionList/ExtensionList.tsx, console/console-init/ui/src/modules/device/components/SecretList/SecretList.tsx, console/console-init/ui/src/utils/utils.ts
Implemented changes according to new design  for Add Credentials Page
=> Implemented changes according to new design  for Add Credentials Page 

console/console-init/ui/src/modules/address/components/AddressList/AddressList.tsx, console/console-init/ui/src/modules/connection/components/ConnectionList/ConnectionList.tsx, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/ExternalMessagingClient.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/resources/AddressWebItem.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/resources/ConnectionWebItem.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/resources/SortType.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/web/FirefoxConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/shared/standard/web/FirefoxConsoleTest.java
System test for close connection feature
=> System test for close connection feature

console/console-init/ui/src/modules/address-detail/components/AddressLinks/AddressLinks.tsx, console/console-init/ui/src/modules/address-space/components/AddressSpaceList/AddressSpaceList.tsx, console/console-init/ui/src/modules/address/components/AddressList/AddressList.tsx, console/console-init/ui/src/modules/connection-detail/components/ConnectionLinksList/ConnectionLinksList.tsx, console/console-init/ui/src/modules/connection/components/ConnectionList/ConnectionList.tsx, console/console-init/ui/src/modules/msg-and-iot/components/ProjectList/ProjectList.test.tsx, console/console-init/ui/src/modules/msg-and-iot/components/ProjectList/ProjectList.tsx, console/console-init/ui/src/modules/msg-and-iot/components/ProjectList/index.ts, console/console-init/ui/src/modules/msg-and-iot/components/index.ts, console/console-init/ui/src/modules/msg-and-iot/utils/ProjectFormatter.tsx, console/console-init/ui/src/modules/msg-and-iot/utils/constant.ts, console/console-init/ui/src/stories/ProjectList.stories.tsx
Add visual component and unit test for project list 
Design - https://marvelapp.com/5gbji22/screen/66859702
=> add project list visual component

systemtests/src/main/java/io/enmasse/systemtest/monitoring/MonitoringClient.java, systemtests/src/main/java/io/enmasse/systemtest/monitoring/PrometheusMetricResource.java, systemtests/src/main/java/io/enmasse/systemtest/operator/EnmasseOperatorManager.java
- Enhancement
Created new class for storing prometheus metric results and parsing from json
=> Add better parsing for prometheus query result

systemtests/src/main/java/io/enmasse/systemtest/operator/EnmasseOperatorManager.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java
- Enhancement
Check if Deployments, StatefulSets, ReplicaSets, Pods and Conatiners are ready instead of waiting only for pods ready.
=> Add better check for resource deployed

documentation/Makefile, documentation/common/device-management-reference.adoc, documentation/kubernetes/master.adoc, documentation/openshift/master.adoc, documentation/src/main/resources/eclipse-hono.yaml
=> Add IoT device registry management API documentation

iot/iot-tenant-service/pom.xml
=> Add testing scope

documentation/assemblies/assembly-using-console.adoc, documentation/modules/proc-closing-connections.adoc
Docs: Add procedure for closing connections using Console
=> Docs: Add procedure for closing connections using Console

api-model/src/main/java/io/enmasse/iot/model/v1/IoTConfigStatus.java, api-model/src/main/java/io/enmasse/iot/model/v1/IoTProjectStatus.java, pkg/apis/iot/v1alpha1/types_config.go, pkg/apis/iot/v1alpha1/types_project.go, pkg/controller/iotconfig/conditions.go, pkg/controller/iotconfig/iotconfig_controller.go, pkg/controller/iotproject/external.go, pkg/controller/iotproject/iotproject_controller.go, pkg/controller/iotproject/managed.go, templates/crds/iotconfigs.crd.yaml, templates/crds/iotprojects.crd.yaml
**Note:** This PR is based on some other changes, please only take a look at the latest commit.
- Refactoring
=> Rename the field "phaseReason" to "message"

templates/iot/examples/iot-config-k8s.yaml
=> Add missing secrets in example k8s IoTConfig

console/console-init/ui/src/components/ServerMessageAlert/ServerMessageAlert.tsx
- Refactoring
Modify server error component to display multiple errors in the server response.
=> Console-UI Modify client side error handling for multiple errors

systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/IWebPage.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java
=> Unify console page waits

systemtests/src/main/java/io/enmasse/systemtest/iot/IoTTestSession.java, systemtests/src/main/java/io/enmasse/systemtest/manager/ResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/monitoring/MonitoringClient.java, systemtests/src/main/java/io/enmasse/systemtest/monitoring/MonitoringQueries.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/monitoring/MonitoringTest.java
Added tests for basic enmasse queries
Added tests for iot queries
=> Monitoring tests vol2

pkg/controller/iotconfig/device_registry.go
=> Fix the selector of the device registry external service

systemtests/src/main/java/io/enmasse/systemtest/mqtt/MqttClientFactory.java, systemtests/src/test/java/io/enmasse/systemtest/bases/mqtt/MqttPublishTestBase.java
=> Fix brokered MQTT systemtests

systemtests/src/test/java/io/enmasse/systemtest/isolated/monitoring/MonitoringTest.java
workaround for maven surefire in monitoring test
=> Workaround for catching beforeall exceptions

console/console-init/ui/src/modules/iot-certificates/components/CertificateCard/CertificateCard.tsx, console/console-init/ui/src/modules/iot-certificates/components/CertificateCard/index.ts, console/console-init/ui/src/modules/iot-certificates/components/CertificateForm/CertificateForm.tsx, console/console-init/ui/src/modules/iot-certificates/components/CertificateForm/index.ts, console/console-init/ui/src/modules/iot-certificates/components/IoTCertificate/IoTCertificate.tsx, console/console-init/ui/src/modules/iot-certificates/components/IoTCertificate/index.ts, console/console-init/ui/src/modules/iot-certificates/components/IoTCertificateList/IoTCertificateList.tsx, console/console-init/ui/src/modules/iot-certificates/components/IoTCertificateList/index.ts, console/console-init/ui/src/modules/iot-certificates/components/IoTCertificateToolbar/IoTCertificateToolbar.tsx, console/console-init/ui/src/modules/iot-certificates/components/IoTCertificateToolbar/index.ts, console/console-init/ui/src/modules/iot-certificates/components/index.ts, console/console-init/ui/src/modules/iot-certificates/utils/constant.ts, console/console-init/ui/src/modules/iot-certificates/utils/index.ts, console/console-init/ui/src/stories/ProjectCertificates.stories.tsx, console/console-init/ui/src/utils/utils.ts
- Bugfix
The visual components required for Project Certificate Lists have been created. It addresses the following: 
* Certificates can be displayed in cards.
* A form to create/edit certificates.
* Auto-population of form fields upon edit.
* Toggling between view and edit mode.
=> Feat: visual component for Project certificates

pkg/apis/iot/v1alpha1/funcs.go
=> Prevent global logging to overide local configuration

documentation/modules/proc-iot-api.adoc, documentation/modules/proc-iot-installing-cli.adoc
Docs: Fix namespace for IoT devices
=> Docs:Fix namespace for IoT devices

iot/iot-tenant-service/src/test/java/io/enmasse/iot/tenant/impl/TenantServiceImplTest.java
=> Cleanup test, be more explicit in what is being tested

documentation/assemblies/assembly-iot-service-admin-guide.adoc, documentation/modules/con-iot-logging.adoc, documentation/modules/proc-iot-logging.adoc
=> Add documentation for IoT logging

pkg/controller/iotconfig/adapter.go, pkg/controller/iotconfig/device_registry.go, templates/iot/examples/iot-config-k8s.yaml
- Bugfix
Fixes currently broken K8s IoT getting started guide
=> Fix K8s IoT deployment

documentation/modules/proc-iot-receiving-commands-mqtt.adoc
Docs: Fix IoT device namespace for receiving commands using mqtt
=> Docs:Fix IoT device namespace for receiving commands using mqtt

systemtests/src/main/java/io/enmasse/systemtest/operator/OLMOperatorManager.java, systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java
- Bugfix
Retry build of OLM image in case of fail due to openshift network or test env.
=> Retry build of manifest image if fail

documentation/assemblies/assembly-iot-service-admin-guide.adoc, documentation/modules/con-iot-logging.adoc, documentation/modules/proc-iot-logging.adoc
Docs:Update IoT logging procedures
=> Docs:Update IoT logging procedures

documentation/assemblies/assembly-iot-configuring-sigfox.adoc, documentation/assemblies/assembly-iot-creating-device.adoc, documentation/modules/proc-iot-creating-new-sigfox-callback.adoc, documentation/modules/proc-iot-installing-cli.adoc, documentation/modules/proc-iot-register-sigfox-backend-gateway-device.adoc, documentation/modules/proc-iot-register-sigfox-device.adoc
Docs: Fix multiple broken links in IoT modules.
=> Docs: Fix iot broken links

pkg/util/install/utils.go
- Bugfix
It is an unused method, but still it should be correct.
=> Fix infinite call recursion

systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/web/ChromeConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/web/FirefoxConsoleTest.java
- Test
Test for addressspace console status
=> Test for console addressspace status

documentation/modules/proc-iot-logging.adoc
Docs: Fix callout format in code blocks
=> Docs:Fix callout format in code blocks

api-model/src/main/java/io/enmasse/iot/model/v1/ServiceConfig.java, pkg/apis/iot/v1alpha1/types_config.go, pkg/apis/iot/v1alpha1/zz_generated.deepcopy.go, pkg/controller/iotconfig/utils.go
=> Allow configuring Pod affinities for IoT

CHANGELOG.md
Tracking IoT related changes, to prevent constant merge conflicts due to changes in `CHANGELOG.md`.
=> Changes of IoT components

standard-controller/src/test/java/io/enmasse/controller/standard/AddressControllerTest.java
=> Stop leaking file descriptors during test

systemtests/src/main/java/io/enmasse/systemtest/utils/AddressSpaceUtils.java
=> Add a bit more information to the log

agent/lib/artemis.js
- Bugfix
There was the possibility that the (unneeded) response from the temporary queue's creation
could be erronously processed as if it were the response to list queues/list addresses.
Also use .once() idiom to avoid the need for the separate flag.
=> Avoid race when processing Artemis response when connecting to broker

systemtests/src/main/java/io/enmasse/systemtest/info/TestInfo.java, systemtests/src/main/java/io/enmasse/systemtest/iot/IoTTests.java, systemtests/src/main/java/io/enmasse/systemtest/iot/MqttAdapterClient.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java, systemtests/src/main/java/io/enmasse/systemtest/logs/GlobalLogCollector.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/http/HttpAdapterTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/mqtt/MqttAdapterTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/mqtt/StandardIoTMqttTests.java
=> Try fixing IoT tests

address-space-controller/src/main/java/io/enmasse/controller/TemplateInfraResourceFactory.java
=> Ensure that memory settings are applied if minReplicas is not specified

pom.xml
=> Align version of opentracing

console/console-init/ui/src/Routes.tsx
- Discussion
- New feature
- Refactoring
Add routes path for iot screens
=> add-routes

systemtests/src/main/java/io/enmasse/systemtest/info/TestInfo.java, systemtests/src/main/java/io/enmasse/systemtest/iot/IoTTests.java, systemtests/src/main/java/io/enmasse/systemtest/iot/MqttAdapterClient.java, systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java, systemtests/src/main/java/io/enmasse/systemtest/logs/GlobalLogCollector.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/http/HttpAdapterTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/mqtt/MqttAdapterTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/mqtt/StandardIoTMqttTests.java
- Bugfix
Try to work around the issue of detecting Postgres to be ready.
=> Try fixing flaky test, detecting proper postgresql startup

systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/x509/StandardX509Cases.java
=> Add missing case of future validity

CHANGELOG.md
=> Add some missing changelog entries

documentation/assemblies/assembly-iot-service-admin-guide.adoc, documentation/modules/con-iot-tracing.adoc, documentation/modules/proc-iot-tracing.adoc
=> Add documentation for enabling tracing

documentation/modules/ref-metrics-standard-controller-agent.adoc, standard-controller/src/main/java/io/enmasse/controller/standard/AddressCanaryHealth.java, standard-controller/src/main/java/io/enmasse/controller/standard/StandardController.java
=> Document address canary metrics

systemtests/src/main/java/io/enmasse/systemtest/iot/IoTTestSession.java, systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java
- Bugfix
The logic to detect Minikube was wrong. Also it is more important that it is "not openshift".
=> Fix deploying Infinispan on plain Kubernetes

systemtests/src/main/java/io/enmasse/systemtest/operator/OLMOperatorManager.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java
- Bugfix
Catch also AssertionError
=> Fix runUntilPass catch also assertion exception

ansible/playbooks/openshift/precheck.yml, ansible/roles/cluster_admin/tasks/main.yml, ansible/roles/upgrade_precheck/tasks/main.yml, systemtests/src/test/java/io/enmasse/systemtest/isolated/upgrade/UpgradeTest.java
=> Add upgrade pre-check when installing via ansible

documentation/modules/proc-iot-tracing.adoc
Docs: Fix typo in procedure for configuring IoT tracing
=> Docs:Fix typo in procedure for configuring IoT tracing

console/console-init/ui/src/components/ServerMessageAlert/ServerMessageAlert.tsx, console/console-init/ui/src/modules/address-space/dialogs/CreateAddressSpace/Configuration.tsx, console/console-init/ui/src/modules/iot-certificates/IoTCertificatesPage.tsx, console/console-init/ui/src/modules/iot-device-detail/DeviceDetailPage.tsx, console/console-init/ui/src/modules/iot-project-detail/IoTProjectDetailPage.tsx, console/console-init/ui/src/modules/iot-project-detail/components/IoTProjectDetailHeader/IoTProjectDetailHeader.tsx
- Refactoring
- resolve warnings for console-iot branch
=> Console-IoT Resolve warning

systemtests/src/main/java/io/enmasse/systemtest/selenium/SeleniumProvider.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/page/ConsoleWebPage.java, systemtests/src/main/java/io/enmasse/systemtest/selenium/resources/EndpointItem.java, systemtests/src/main/java/io/enmasse/systemtest/utils/AddressSpaceUtils.java, systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/certs/CertProviderTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/web/FirefoxConsoleTest.java
Added tests for new console endpoint functionality
=> Console endpoints test

systemtests/src/main/java/io/enmasse/systemtest/infra/InfraConfiguration.java, systemtests/src/main/java/io/enmasse/systemtest/utils/PlanUtils.java, systemtests/src/test/java/io/enmasse/systemtest/bases/infra/InfraTestBase.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/infra/brokered/InfraTestBrokered.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/infra/standard/InfraTestStandard.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/plans/standard/PlansTestStandard.java
- Enhancement
Adds to InfraTests the new usecase to set cpu requests and limits
=> systemtests - infra tests update cpu limits

console/console-init/ui/src/Routes.tsx, console/console-init/ui/src/graphql-module/queries/iot_device.ts, console/console-init/ui/src/modules/iot-device/DeviceListPage.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceFilter/DeviceFilter.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceList/DeviceList.test.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceList/DeviceList.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceListToolbar/DeviceListToolbar.test.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceListToolbar/DeviceListToolbar.tsx, console/console-init/ui/src/modules/iot-device/containers/DeviceListContainer/DeviceListContainer.tsx, console/console-init/ui/src/modules/iot-device/containers/DeviceListContainer/index.ts, console/console-init/ui/src/modules/iot-device/containers/index.ts, console/console-init/ui/src/modules/iot-device/utils/TableFormatter.tsx, console/console-init/ui/src/modules/iot-project-detail/Routes.tsx, console/console-init/ui/src/schema/iot_device.ts, console/console-init/ui/src/stories/DeviceFilter.stories.tsx, console/console-init/ui/src/stories/DeviceList.stories.tsx, console/console-init/ui/src/stories/DeviceListPage.stories.tsx
- Integration
* modify schema according to server response types.
* Implement device list page with sort and actions.
* Handle multiple selections.
=> Feat: integration for device list components

documentation/assemblies/assembly-configuration-sizing-guide.adoc, documentation/modules/ref-address-sizing.adoc
Docs: Add address sizing module
=> Docs: Add address sizing module

systemtests/src/test/java/io/enmasse/systemtest/isolated/infra/standard/InfraTestStandard.java
This is a test to verify InfraConfig updates fail on latest kubernetes version
=> add InfraTestStandard.testDecrementInfra to acceptance profile

standard-controller/src/main/java/io/enmasse/controller/standard/AddressProbeClient.java
=> Use expected string type for LVQ property

systemtests/src/main/java/io/enmasse/systemtest/manager/IsolatedResourcesManager.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/AbstractClient.java, systemtests/src/main/java/io/enmasse/systemtest/messagingclients/ExternalMessagingClient.java, systemtests/src/main/java/io/enmasse/systemtest/utils/AddressSpaceUtils.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/brokered/SmokeTest.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/standard/SmokeTest.java
- Enhancement
Run smoke tests only with messaging on cluster without routes/ingress
based on PR #4727
=> Smoke tests messaging on cluster

pkg/controller/messagingaddress/messagingaddress_controller.go, pkg/controller/messagingendpoint/messagingendpoint_controller.go, pkg/controller/messaginginfra/broker/controller.go, pkg/controller/messaginginfra/messaginginfra_controller.go, pkg/controller/messaginginfra/router/controller.go, pkg/controller/messaginginfra/router/controller_test.go, pkg/state/broker/broker.go, pkg/state/broker/broker_test.go, pkg/state/broker/types.go, pkg/state/common/types.go, pkg/state/errors/errors.go, pkg/state/infra.go, pkg/state/infra_test.go, pkg/state/manager.go, pkg/state/router/router.go, pkg/state/router/router_test.go, pkg/state/router/types.go, pkg/state/scheduler.go, pkg/state/test/fakeinfra.go, pkg/state/types.go
- Refactoring
Split state/infra code into separate modules for broker and router to make the code more manageable.
=> Refactor state code

iot/pom.xml
=> Upgrade to Hono version 1.2.3

systemtests/src/main/java/io/enmasse/systemtest/iot/IoTTestSession.java, systemtests/src/main/java/io/enmasse/systemtest/utils/IoTUtils.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/x509/TrustAnchorTests.java
=> Delete second IoTProject during cleanup

systemtests/src/main/java/io/enmasse/systemtest/iot/IoTTestSession.java
- Bugfix
Deploy iot certs into right namespace
=> Deploy iot certs to right namespace

systemtests/src/main/java/io/enmasse/systemtest/executor/Exec.java, systemtests/src/main/java/io/enmasse/systemtest/iot/IoTTestSession.java
- Bugfix
Currently if create/deploy script fail system ignores that and continue, so this should prevent it.
=> Fail in case iot cannot deploy certs

iot/iot-tenant-service/src/main/java/io/enmasse/iot/tenant/impl/AbstractTenantService.java, iot/iot-tenant-service/src/main/java/io/enmasse/iot/tenant/impl/TenantServiceImpl.java, iot/iot-tenant-service/src/test/java/io/enmasse/iot/tenant/impl/TenantServiceImplTest.java, pkg/controller/iotproject/configuration.go, pkg/controller/iotproject/configuration_test.go, pkg/util/x500.go, pkg/util/x500_test.go, systemtests/src/main/java/io/enmasse/systemtest/iot/DeviceCertificateManager.java, systemtests/src/main/java/io/enmasse/systemtest/iot/HttpAdapterClient.java, systemtests/src/main/java/io/enmasse/systemtest/iot/IoTTestSession.java, systemtests/src/main/java/io/enmasse/systemtest/iot/KeyStoreCreator.java, systemtests/src/test/java/io/enmasse/systemtest/iot/DeviceCertificateManagerTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/KeyStoreCreatorTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/http/StandardIoTHttpTests.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/x509/StandardX509Cases.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/x509/TrustAnchorTests.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/x509/X509EcAuthenticationTests.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/x509/X509RsaAuthenticationTests.java, systemtests/src/test/java/io/enmasse/systemtest/iot/mqtt/StandardIoTMqttTests.java
=> Fix IoT tests and Go subject DN handling

systemtests/src/main/java/io/enmasse/systemtest/manager/IsolatedResourcesManager.java
=> [systemtests] Check if resources are removed

console/console-init/ui/src/graphql-module/queries/iot_device.ts, console/console-init/ui/src/modules/iot-device/DeviceListPage.tsx, console/console-init/ui/src/modules/iot-device/containers/DeviceListContainer/DeviceListContainer.tsx, console/console-init/ui/src/modules/iot-device/containers/EmptyDeviceContainer/EmptyDeviceContainer.tsx, console/console-init/ui/src/modules/iot-device/containers/EmptyDeviceContainer/index.ts, console/console-init/ui/src/modules/iot-device/containers/index.ts, console/console-init/ui/src/modules/iot-device/utils/constant.ts, console/console-init/ui/src/schema/iot_device.ts
- Bugfix
The empty state and alert are now being adjusted according to the number of devices available and filter applied.
=> Feat: EmptyDeviceContainer and alert messages

systemtests/src/main/java/io/enmasse/systemtest/iot/HttpAdapterClient.java, systemtests/src/test/java/io/enmasse/systemtest/iot/http/StandardIoTHttpTests.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/http/MaxPayloadSizeTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/mqtt/StandardIoTMqttTests.java
=> Reduce number of expected exceptions in the log

console/console-init/ui/src/graphql-module/queries/iot_device.ts, console/console-init/ui/src/modules/iot-device/DeviceListPage.tsx, console/console-init/ui/src/modules/iot-device/containers/EmptyDeviceContainer/EmptyDeviceContainer.tsx, console/console-init/ui/src/modules/iot-device/utils/constant.ts, console/console-init/ui/src/schema/iot_device.ts
- Refactoring
Changes according to reviews for #4764 .
=>  Refactor: device alert and empty device according to reviews

agent/lib/broker_controller.js, standard-controller/src/main/java/io/enmasse/controller/standard/RouterStatus.java
=> Handle the case where one or more of the fields of router entities are null

console/console-init/ui/src/modules/address/dialogs/CreateAddress/CreateAddress.tsx
- Bugfix
Fix input validation issue for address name
=> [console] fix address name validation

pkg/util/images/mapping.go
=> Fix missing images

documentation/assemblies/assembly-managing-addresses.adoc, documentation/common/address-example-ttl.yaml, documentation/modules/con-address-plans.adoc, documentation/modules/ref-address-example-ttl.adoc, documentation/modules/ref-ttl.adoc
Documentation for the TTL feature #3158.
=> Message TTL

console/console-init/ui/src/modules/iot-device/components/CreateMetadata/CreateMetadata.tsx, console/console-init/ui/src/modules/iot-device/components/CreateMetadata/MetaDataRow.tsx, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/DeviceInformation.tsx, console/console-init/ui/src/modules/iot-device/utils/constant.ts, console/console-init/ui/src/stories/CreateDevice.stories.tsx
Added following changes in the metadata form:
- Change TypeAhead to TextInput
- Fix onSelect of Type Dropdown
- Show/Hide Child Addition Button based on selected type
- Clear value field based on selected type
- Disable/Enable Type and Value fields based on Type
- Set Default value of Type
=> Add validation in Create device

systemtests/src/main/java/io/enmasse/systemtest/operator/EnmasseOperatorManager.java, systemtests/src/test/java/io/enmasse/systemtest/isolated/monitoring/MonitoringTest.java
- Bugfix
Changed systemtests to use existing monitoring stack on OpenShift4
=> Fixed failing monitoring installation on OCP4

CHANGELOG.md, templates/crds/addressspaces.crd.yaml
- Bugfix
Resolve the structural warnings from the addressspace CRD.  There should be no functional change associated with this change.
=> [CRD] Resolve the structural warnings from the addressspace CRD

pkg/controller/iotproject/configuration.go
=> Fix condition value: OK is "true"

documentation/modules/proc-iot-installing-services.adoc
=> Add a note about choosing a namespace when deploying test certificates

console/console-init/ui/src/modules/address-space/utils/TableFormatter.tsx
Fix Alignment of columns and cells in Address Space Table.
=> Fix alignment of Address Space table

systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java
System test modify for [4814](https://github.com/EnMasseProject/enmasse/pull/4814)
=> Multiple filter test

documentation/assemblies/assembly-iot-creating-device.adoc, documentation/assemblies/assembly-iot-device-manager-guide.adoc, documentation/modules/proc-iot-management-token.adoc
=> Add help about getting an authentication token

pom.xml
- Refactoring
* Remove redundant override of commons-collections (commons-collections is no longer a transitive dependency of project).
* Bump micro versions of snakeyaml and hibernate.validator
=> Update  snakeyaml/hibernate dependencies

console/console-init/ui/package.json, console/console-init/ui/src/components/NetworkStatusAlert/NetworkStatusAlert.tsx, console/console-init/ui/src/components/NotFound/NotFound.tsx, console/console-init/ui/src/components/PasswordInputFieldWithToggle/PasswordInputFieldWithToggle.tsx, console/console-init/ui/src/components/ServerMessageAlert/ServerMessageAlert.tsx, console/console-init/ui/src/components/UpdatePassword/UpdatePassword.tsx, console/console-init/ui/src/constant/constants.ts, console/console-init/ui/src/hooks/index.ts, console/console-init/ui/src/hooks/useSearchParams.tsx, console/console-init/ui/src/modules/address-space/components/AddressSpaceReview/AddressSpaceReview.tsx, console/console-init/ui/src/modules/address-space/components/EndpointConfiguraion/EndpointConfiguraion.tsx, console/console-init/ui/src/modules/address-space/dialogs/CreateMessagingProject/ConfiguringRoutes.tsx, console/console-init/ui/src/modules/address-space/dialogs/CreateMessagingProject/CreateMessagingProject.tsx, console/console-init/ui/src/modules/address/AddressPage.tsx, console/console-init/ui/src/modules/address/dialogs/CreateAddress/CreateAddress.tsx, console/console-init/ui/src/modules/iot-device-detail/components/DeviceInfo/ErrorStateAlert.tsx, console/console-init/ui/src/use-patternfly/NotFound.tsx
- Bugfix
Fixed following issues
1. Alret component alignment and background color issue
2. Address space review alignment issue
3. Address space review  hide button issue
=> Fixed patternfly issues

iot/iot-device-registry-base/pom.xml, iot/iot-device-registry-infinispan/pom.xml, iot/iot-device-registry-jdbc/pom.xml, iot/iot-infinispan-base/pom.xml, iot/iot-jdbc-base/pom.xml
- Bugfix
Mark hamcrest as scope `test`.
=> [IoT] hamcrest erroneously a production dependency

iot/iot-jdbc-base/pom.xml, iot/iot-jdbc-base/src/main/java/io/enmasse/iot/jdbc/config/JdbcProperties.java, iot/pom.xml
=> Fix issue with wrong connection pool, enforce using C3P0.

documentation/modules/proc-iot-management-token.adoc
Docs: Fix typo in procedure for obtaining auth token
=> Docs: Fix typo in procedure for obtaining auth token

documentation/modules/con-standard-queue.adoc
=> Docs: Remove note about DLQs

console/console-init/ui/mock-console-server/mock-console-server.js, console/console-init/ui/mock-console-server/schema.js, console/console-init/ui/src/components/DropdownWithToggle/DropdownWithToggle.tsx, console/console-init/ui/src/constant/constants.ts, console/console-init/ui/src/graphql-module/queries/iot_device.ts, console/console-init/ui/src/modules/iot-device-detail/DeviceDetailPage.tsx, console/console-init/ui/src/modules/iot-device-detail/components/ActionManager/ActionManager.tsx, console/console-init/ui/src/modules/iot-device-detail/components/ConfigurationInfo/ConfigurationInfo.tsx, console/console-init/ui/src/modules/iot-device-detail/components/DeviceDetailHeader/DeviceDetailHeader.tsx, console/console-init/ui/src/modules/iot-device-detail/containers/ConfigurationInfoContainer/ConfigurationInfoContainer.tsx, console/console-init/ui/src/modules/iot-device-detail/pf-overrides.css, console/console-init/ui/src/modules/iot-device-detail/utils/constants.ts, console/console-init/ui/src/modules/iot-device-detail/utils/index.ts, console/console-init/ui/src/modules/iot-device-detail/utils/utils.ts
- Refactoring
Implemented credentials filter functionality:
- Create credentials type and value dropdown
- Implement credentials filter functionality in mock-server
- Write query and schema
=> Implemented credentials filter functionality

documentation/design/iot/README.adoc
=> Adopt the new messaging infrastructure

systemtests/pom.xml, systemtests/src/test/java/io/enmasse/systemtest/sharedinfra/MessagingAddressPerfTest.java, systemtests/src/test/java/io/enmasse/systemtest/sharedinfra/MessagingTenantTest.java
1. Use default messaging infra in the last test with defaults
2 Create scale profile in shared infra end enable them
=> Use defaults in tests

agent/lib/qdr.js
(prevents accumulation of Router and related objects)
- Bugfix
There were actually two leaks:
1. Leak on the unexpected router disconnect path that would leave the timer running
1. The 'facade' Router objects (i.e. those that share a connection to a management node) were (needlessly) installing their own listeners on the shared connection.  These listeners accumulated every time routers were added and removed (or even transitively restarted)
=> [Agent] ensure that router disconnect cancels the timer / doesn't accumulate listeners from facades

pkg/util/cchange/change.go
=> Fix issue converting map to sorted map

documentation/modules/proc-enable-tenant-metrics.adoc, documentation/modules/proc-installing-using-ansible.adoc
=> Docs:Fix config examples

console/console-init/ui/mock-console-server/mock-console-server.js, console/console-init/ui/mock-console-server/schema.js, console/console-init/ui/src/components/AdapterList/AdapterList.tsx, console/console-init/ui/src/components/PasswordInputFieldWithToggle/PasswordInputFieldWithToggle.tsx, console/console-init/ui/src/containers/AdapterListContainer/AdapterListContainer.tsx, console/console-init/ui/src/containers/AdapterListContainer/index.ts, console/console-init/ui/src/containers/index.ts, console/console-init/ui/src/graphql-module/queries/index.ts, console/console-init/ui/src/graphql-module/queries/iot_project.ts, console/console-init/ui/src/mock-data/iot_device.ts, console/console-init/ui/src/modules/address-space/utils/TableFormatter.tsx, console/console-init/ui/src/modules/iot-device-detail/components/ConfigurationInfo/ConfigurationInfo.tsx, console/console-init/ui/src/modules/iot-device-detail/components/CredentialsView/CredentialsView.tsx, console/console-init/ui/src/modules/iot-device-detail/components/CredentialsView/ExtensionsView/ExtensionsView.tsx, console/console-init/ui/src/modules/iot-device-detail/components/CredentialsView/SecretsView/SecretsView.tsx, console/console-init/ui/src/modules/iot-device-detail/containers/ConfigurationInfoContainer/ConfigurationInfoContainer.tsx, console/console-init/ui/src/modules/iot-project-detail/IoTProjectDetailInfoPage.tsx, console/console-init/ui/src/modules/iot-project-detail/components/AccessCredentials/AccessCredentials.tsx, console/console-init/ui/src/modules/iot-project-detail/components/DeviceRegistrationManagement/DeviceRegistrationManagement.tsx, console/console-init/ui/src/modules/iot-project-detail/containers/IoTProjectDetailHeaderContainer/IoTProjectDetailHeaderContainer.tsx, console/console-init/ui/src/modules/project/ProjectPage.tsx, console/console-init/ui/src/modules/project/components/EmptyProject/EmptyProject.tsx, console/console-init/ui/src/modules/project/components/ProjectList/ProjectList.tsx, console/console-init/ui/src/modules/project/containers/ProjectListContainer/ProjectListContainer.tsx, console/console-init/ui/src/schema/iot_project.ts, console/console-init/ui/src/stories/AdapterList.stories.tsx, console/console-init/ui/src/stories/ConfigurationInfo.stories.tsx, console/console-init/ui/src/stories/ProjectDetail.stories.tsx, console/console-init/ui/src/stories/ProjectDetailPage.stories.tsx, console/console-server/src/main/resources/iot.schema.graphql
- Bugfix
- Refactoring
Integrate mock-server with UI and Fix issues 
1. Integrate fetch iot-projects query on project list page
2. Integarte delete project query
3. Fix delete credentials query in mock-server
4. Added tls property in mock-server for Adapters
5. Create AdapterListContainer and integrate query
6. Fix CredentialsView alignment issues
7. Fix change password dialog icon issue
=> Integrate mock-server with UI and Fix issues 

documentation/assemblies/assembly-monitoring.adoc, documentation/modules/proc-enable-ocp4-monitoring.adoc
Added instructions for monitoring on OpenShift 4
=> Added docs for monitoring on OpenShift 4

console/console-init/ui/mock-console-server/mock-console-server.js
- Bugfix
Fix delete project query issue
=> Fix delete project query issue

console/console-init/ui/src/graphql-module/queries/iot_device.ts, console/console-init/ui/src/modules/iot-device-detail/DeviceDetailPage.tsx
- Bugfix
Fixed delete iot device query error
=> Fixed delete iot device query error

console/console-init/ui/mock-console-server/mock-console-server.js, console/console-init/ui/mock-console-server/schema.js, console/console-init/ui/src/graphql-module/queries/iot_project.ts, console/console-init/ui/src/modules/iot-project-detail/IoTProjectDetailInfoPage.tsx, console/console-init/ui/src/modules/iot-project-detail/components/AccessCredentials/AccessCredentials.tsx, console/console-init/ui/src/modules/iot-project-detail/components/DeviceRegistrationManagement/DeviceRegistrationManagement.tsx, console/console-init/ui/src/modules/iot-project-detail/components/GeneralInfo/GeneralInfo.tsx, console/console-init/ui/src/modules/iot-project-detail/containers/IoTProjectDetailHeaderContainer/IoTProjectDetailHeaderContainer.tsx, console/console-init/ui/src/schema/iot_project.ts, console/console-init/ui/src/stories/ProjectDetail.stories.tsx, console/console-init/ui/src/stories/ProjectDetailPage.stories.tsx
- Enhancement
- Bugfix
* Project detail info page integrated with mock.
* JSON view of Device Registration management fixed.
* Enable status implemented.
* Delete project added to ProjectDetailHeader.
=> Feat: Integrate Project Detail Info page with mock-server

pom.xml
Bump Netty (4.1.48.Final => 4.1.50.Final), Qpid Proton (0.33.0 => 0.33.4), Qpid JMS (0.40.0 => 0.52.0 *test dependency*)
=> Bump Netty/Qpid Proton/QpidJMS

console/console-init/ui/src/modules/iot-device/DeviceListPage.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceFilter/DeviceFilter.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceList/DeviceList.test.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceList/DeviceList.tsx, console/console-init/ui/src/modules/iot-device/containers/DeviceListContainer/DeviceListContainer.tsx, console/console-init/ui/src/modules/iot-device/utils/TableFormatter.tsx, console/console-init/ui/src/modules/iot-project-detail/components/GeneralInfo/GeneralInfo.tsx, console/console-init/ui/src/stories/DeviceList.stories.tsx, console/console-init/ui/src/stories/DeviceListPage.stories.tsx
- Fix breaking of filter options.
- Handle reset filter.
- Change no result component position.
- Show updated and created in device list.
- Bugfix
- Enhancement
- Refactoring
- Fix breaking of filter options.
- Handle reset filter.
- Change no result component position.
- Show updated and created in device list.
=> Fix: changes in device list page

console/console-init/ui/src/components/FinishedStep/FinishedStep.tsx, console/console-init/ui/src/modules/project/components/EndpointConfiguraion/EndpointConfiguraion.tsx, console/console-init/ui/src/modules/project/components/MessagingReview/MessagingReview.tsx, console/console-init/ui/src/modules/project/dailogs/CreateProject/CreateProject.tsx, console/console-init/ui/src/modules/project/utils/utils.ts
- Refactoring
- Include Changes of PF update in endpoint configuration steps
=> Console-Iot - Update create project component

console/console-init/ui/mock-console-server/README.md, console/console-init/ui/mock-console-server/mock-console-server.js, console/console-init/ui/mock-console-server/schema.js, console/console-init/ui/src/components/NotFound/NotFound.tsx, console/console-init/ui/src/graphql-module/queries/iot_project.ts, console/console-init/ui/src/modules/iot-device/DeviceListPage.tsx, console/console-init/ui/src/modules/iot-device/containers/DeviceListContainer/DeviceListContainer.tsx, console/console-init/ui/src/modules/iot-project-detail/components/IoTProjectDetailHeader/IoTProjectDetailHeader.test.tsx, console/console-init/ui/src/modules/iot-project-detail/components/IoTProjectDetailHeader/IoTProjectDetailHeader.tsx, console/console-init/ui/src/modules/iot-project-detail/containers/IoTProjectDetailHeaderContainer/IoTProjectDetailHeaderContainer.tsx, console/console-init/ui/src/stories/IoTProjectDetailHeader.stories.tsx
- Enhancement
The PR implements bulk delete feature for DeviceList and refactors the queries for changing IoT Project status.
=> Feat: implement bulk delete of Devices

.github/workflows/master.yml, .github/workflows/smoke.yml
Enable actions to cache go modules and yarn dependencies.
=> Add go and yarn caching

systemtests/src/main/java/io/enmasse/systemtest/framework/ITestSeparator.java
=> Fix typo in logging testcases

console/console-init/ui/src/components/DialogPrompt/DialogPrompt.tsx, console/console-init/ui/src/modules/project/containers/ProjectListContainer/ProjectListContainer.tsx
- Add options to enable or disable iot projects in project list page
=> add enable/disable for iot projects

console/console-init/ui/src/Routes.tsx
- Bugfix
- Refactoring
Add routes for viewing messaging projects (temporary fix)
=> [conosle-iot] Add routes for messaging project

console/console-init/ui/src/graphql-module/queries/iot_project.ts, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/CreateDevice.tsx, console/console-init/ui/src/modules/iot-project-detail/IoTProjectDetailInfoPage.tsx, console/console-init/ui/src/modules/iot-project-detail/IoTProjectDetailPage.tsx, console/console-init/ui/src/modules/iot-project-detail/components/AccessCredentials/AccessCredentials.tsx, console/console-init/ui/src/modules/iot-project-detail/components/GeneralInfo/GeneralInfo.test.tsx, console/console-init/ui/src/modules/iot-project-detail/components/GeneralInfo/GeneralInfo.tsx, console/console-init/ui/src/modules/iot-project-detail/components/IoTProjectDetailHeader/IoTProjectDetailHeader.test.tsx, console/console-init/ui/src/modules/iot-project-detail/components/IoTProjectDetailHeader/IoTProjectDetailHeader.tsx, console/console-init/ui/src/modules/iot-project-detail/containers/IoTProjectDetailHeaderContainer/IoTProjectDetailHeaderContainer.tsx, console/console-init/ui/src/schema/iot_project.ts, console/console-init/ui/src/stories/IoTProjectDetailHeader.stories.tsx
- Bugfix
- Refactoring
- Modify query to fetch iot Project
- remove address space and type from the UI as it is not supported in shared infra
- some modification in list of adapters
=> modify query and some refactoring in iot project detail page

systemtests/src/main/java/io/enmasse/systemtest/framework/TestLifecycleManager.java, systemtests/src/main/java/io/enmasse/systemtest/framework/TestPlanExecutionListener.java, systemtests/src/main/java/io/enmasse/systemtest/messaginginfra/ResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java
- Bugfix
Collect logs of pods etc... if exception or assert error appears in junit lifecycle callbacks
=> Collect logs if exception appears in lifecycle callbacks

systemtests/src/main/java/io/enmasse/systemtest/messagingclients/MessagingClientRunner.java, systemtests/src/main/java/io/enmasse/systemtest/utils/AssertionUtils.java, systemtests/src/test/java/io/enmasse/systemtest/TestBase.java, systemtests/src/test/java/io/enmasse/systemtest/sharedinfra/MessagingAddressTest.java, systemtests/src/test/java/io/enmasse/systemtest/sharedinfra/MessagingEndpointTest.java, systemtests/src/test/java/io/enmasse/systemtest/sharedinfra/MessagingInfrastructureTest.java
- Refactoring
Refactoring continue on doTest methods with client uses. Migrated rest of doTest methods from current tests to clientRunner.
=> Migrate do test clients

console/console-init/ui/package.json, console/console-init/ui/yarn.lock
- version upgrade
Upgrade patternfly react-core version to match Donald's patch
=> Upgrade PF react-core

pkg/apis/enmasse/v1/types_endpoint.go, templates/crds/enmasse.io_messagingendpoints.yaml
=> Fix misspelt word certificate messaging endpoint crd

CHANGELOG.md
Change log update
Changelog update for issue #4915 and issue #4914
4914 is merged into 0.33.x
4915 is merged into master
both are targeted for 0.32.1
=> Updated changelog for issue #4914 and #4915

Makefile
=> time the go vet call

console/console-init/ui/package.json, console/console-init/ui/yarn.lock
Remove the dependency from use-patternfly, after PF upgrade.
=> Remove use-patternfly's dependency

console/console-init/ui/mock-console-server/mock-console-server.js
- Bugfix
Fix mock server issue for uidv1
=> fix uidv1 error in mock server

console/console-init/ui/src/graphql-module/queries/iot_device.ts, console/console-init/ui/src/modules/iot-device-detail/DeviceDetailPage.tsx, console/console-init/ui/src/modules/iot-device-detail/components/DeviceDetailHeader/DeviceDetailHeader.tsx, console/console-init/ui/src/modules/iot-device/DeviceListPage.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceFilter/DeviceFilter.tsx, console/console-init/ui/src/modules/iot-device/containers/DeviceListContainer/DeviceListContainer.tsx
- Enhancement
IoT Device status toggle implemented in DeviceList and DeviceDetailPage. Filter of device list updated to support boolean values.
=> Feat: implement iot device status toggle

systemtests/pom.xml
- Bugfix
Do not trigger scale tests in pr profile
=> Do not run scale and perf in pr profile

systemtests/pom.xml
Added acceptance profile into systemtests pom
=> Add acceptance profile into pom

systemtests/src/main/java/io/enmasse/systemtest/framework/TestLifecycleManager.java, systemtests/src/main/java/io/enmasse/systemtest/framework/TestPlanExecutionManager.java
=> Fix systemtests SKIP_CLEANUP and SKIP_UNINSTALL

console/console-init/ui/src/modules/iot-device/DeviceListPage.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceListToolbar/DeviceListToolbar.tsx, console/console-init/ui/src/modules/iot-device/components/MangeColumnModal/ManageColumnModal.tsx, console/console-init/ui/src/modules/iot-device/components/MangeColumnModal/index.ts, console/console-init/ui/src/modules/iot-device/components/index.ts, console/console-init/ui/src/modules/iot-device/containers/DeviceListContainer/DeviceListContainer.tsx, console/console-init/ui/src/modules/iot-device/utils/constant.ts, console/console-init/ui/src/stories/DeviceList.stories.tsx, console/console-init/ui/src/stories/DeviceListPage.stories.tsx
Add manage columns section in modal to manage multiple columns in device list
Design link :- https://marvelapp.com/prototype/5gbji22/screen/69081888
=> [Console-iot] Add manage colmuns in device list 

systemtests/src/main/java/io/enmasse/systemtest/iot/IoTTestSession.java
=> simply re-create certificates

.github/workflows/smoke.yml
Parallelization actions PR flow
- Separate unit and systemtests
- Run them in parallel
- Unit tests kill systemtests run if failed
- We will have to change job requiements for merging after this PR
Next plan is to add IoT jobs run for jobs with IoT tag and also play with caching api-model from unit tests and somehow store images :) across jobs.
=> Parallelization actions proposal

go.mod, go.sum, vendor/modules.txt, vendor/pack.ag/amqp/go.mod
Revert to interconnectedcloud-go-amqp now https://github.com/interconnectedcloud/go-amqp/pull/1 is merged.
- Refactoring
=> Switch back to interconnectedcloud-go-amqp now PR #1 is merged.

console/console-init/ui/mock-console-server/README.md, console/console-init/ui/mock-console-server/mock-console-server.js, console/console-init/ui/src/graphql-module/queries/iot_device.ts, console/console-init/ui/src/modules/iot-device-detail/DeviceDetailPage.tsx, console/console-init/ui/src/modules/iot-device-detail/components/DeviceInfo/DeviceInfo.tsx, console/console-init/ui/src/modules/iot-device/DeviceListPage.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceList/DeviceList.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceListToolbar/DeviceListToolbar.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceListToolbar/pf-overrides.css, console/console-init/ui/src/modules/iot-device/containers/DeviceListContainer/DeviceListContainer.tsx, console/console-init/ui/src/modules/iot-device/containers/EmptyDeviceContainer/EmptyDeviceContainer.tsx, console/console-init/ui/src/modules/iot-device/utils/TableFormatter.tsx, console/console-init/ui/src/modules/iot-project-detail/IoTProjectDetailPage.tsx, console/console-init/ui/src/modules/project/components/ProjectList/ProjectList.test.tsx, console/console-init/ui/src/schema/iot_device.ts, console/console-init/ui/src/stories/DeviceList.stories.tsx, console/console-init/ui/src/stories/DeviceListPage.stories.tsx
- Enhancement
- Bugfix
- Handle pagination on applying filters.
- Re-style the toolbar
- Change device query according to mock
- Handle options for multiple select
- Get credentials in device list query to get device type
- Modify CSS of IoTProjectDetailHeader and IoTDeviceDetailHeader
- Fix some typos
- Update README.md of mock-server
=> Chore: make changes to DeviceList

console/console-init/ui/mock-console-server/mock-console-server.js, console/console-init/ui/mock-console-server/schema.js, console/console-init/ui/package.json, console/console-init/ui/src/App.css, console/console-init/ui/src/components/DividerWithTitle/DividerWithTitle.tsx, console/console-init/ui/src/components/NotFound/NotFound.tsx, console/console-init/ui/src/graphql-module/queries/iot_device.ts, console/console-init/ui/src/modules/iot-device-detail/components/ConfigurationInfo/ConfigurationInfo.tsx, console/console-init/ui/src/modules/iot-device-detail/components/CredentialsView/ExtensionsView/ExtensionsView.tsx, console/console-init/ui/src/modules/iot-device-detail/components/CredentialsView/SecretsView/SecretsView.tsx, console/console-init/ui/src/modules/iot-device-detail/components/DeviceInfo/DeviceInfo.tsx, console/console-init/ui/src/modules/iot-device-detail/components/DeviceInfo/ErrorStateAlert.tsx, console/console-init/ui/src/modules/iot-device-detail/containers/ConfigurationInfoContainer/ConfigurationInfoContainer.tsx, console/console-init/ui/src/modules/iot-device-detail/containers/DeviceInfoContainer/DeviceInfoContainer.tsx, console/console-init/ui/src/modules/iot-device-detail/utils/utils.ts, console/console-init/ui/src/modules/iot-device/components/AddCredential/AddCredential.tsx, console/console-init/ui/src/modules/iot-device/components/CredentialList/CredentialList.tsx, console/console-init/ui/src/modules/iot-device/components/ExtensionList/ExtensionList.tsx, console/console-init/ui/src/modules/iot-device/components/SecretList/SecretList.tsx, console/console-init/ui/src/modules/iot-device/containers/AddCredentialsContainer/AddCredentialsContainer.tsx, console/console-init/ui/src/modules/iot-device/containers/EditCredentialsContainer/EditCredentialsContainer.tsx, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/CreateDevice.tsx, console/console-init/ui/src/modules/iot-device/utils/utils.ts, console/console-init/ui/src/stories/ConfigurationInfo.stories.tsx, console/console-init/ui/yarn.lock
- Bugfix
- Refactoring
Implement add credential functionality and fix mock-server query issues
=> Implement add credential functionality and fix mock-server query issues

iot/pom.xml
- Bugfix
Update Postgres from 42.2.9 to 42.2.13
=> Update Postgres to 42.2.13 [CVE-2020-13692]

.github/workflows/master.yml, .github/workflows/release.yml, .github/workflows/smoke.yml
=> Move to new go

TESTING.md
=> Update testing.md file for new enmasse 1.0

console/console-init/ui/mock-console-server/mock-console-server.js, console/console-init/ui/src/graphql-module/queries/iot_device.ts, console/console-init/ui/src/modules/iot-device-detail/DeviceDetailPage.tsx, console/console-init/ui/src/modules/iot-device-detail/components/DeviceDetailHeader/DeviceDetailHeader.tsx, console/console-init/ui/src/modules/iot-device-detail/containers/ConfigurationInfoContainer/ConfigurationInfoContainer.tsx, console/console-init/ui/src/modules/iot-device-detail/containers/DeviceInfoContainer/DeviceInfoContainer.tsx, console/console-init/ui/src/modules/iot-device/DeviceListPage.tsx, console/console-init/ui/src/modules/iot-device/containers/DeviceListContainer/DeviceListContainer.tsx, console/console-init/ui/src/modules/iot-device/containers/EditDeviceInJsonContainer/EditDeviceInJsonContainer.tsx, console/console-init/ui/src/modules/iot-device/containers/EditGatewaysContainer/EditGatewaysContainer.tsx
=> Chore: modify device queries

systemtests/src/main/resources/logback.xml
Store ourput of systemtests into file without color escape chars.
=> Store systemtests output also to a file

console/console-init/ui/src/App.css, console/console-init/ui/src/AppLayout.tsx, console/console-init/ui/src/AppNavHeader.tsx, console/console-init/ui/src/index.css
- Refactoring
Refactored the header, to allow a new one to easily be swapped in.
=> Refactored header to make it easier to swap the nav

templates/enmasse-operator/enmasse-operator.clusterrole.yaml
=> fix broken yaml

.github/scripts/install_dep.sh
=> Remove nodejs installation on actions

console/console-init/ui/mock-console-server/README.md, console/console-init/ui/mock-console-server/mock-console-server.js, console/console-init/ui/mock-console-server/schema.js, console/console-server/src/main/resources/iot.schema.graphql
That should make things easier !
=> Console iot - graphQL API Device refactoring

.tekton/test/systemtest-task.yaml
- Enhancement
1. Use google builder images for tekton
2. Split test task into more steps
=> Tekton split task to steps and use builder images

console/console-init/ui/src/modules/iot-certificates/components/CertificateCard/CertificateCard.tsx, console/console-init/ui/src/modules/iot-certificates/components/CertificateForm/CertificateForm.tsx, console/console-init/ui/src/modules/iot-certificates/components/IoTCertificate/IoTCertificate.tsx, console/console-init/ui/src/modules/iot-certificates/components/IoTCertificateList/IoTCertificateList.tsx, console/console-init/ui/src/modules/iot-certificates/components/IoTCertificateToolbar/IoTCertificateToolbar.tsx
- Refactoring
Add meaningful ID for IoT certificates
=> [Console-IoT]- Add ID for IoT certificates

console/console-init/ui/src/modules/endpoints/EndpointPage.tsx, console/console-init/ui/src/modules/endpoints/components/EmptyEndpoints/EmptyEndpoints.tsx, console/console-init/ui/src/modules/endpoints/components/EndPointList/EndPointList.tsx
- Refactoring
Add meaningful ID for endpoint components
=> [Console-IoT]-Add ID for endpoint components

console/console-init/ui/src/modules/connection/components/ConnectionList/ConnectionList.tsx, console/console-init/ui/src/modules/connection/components/ConnectionsToggleGroup/ConnectionsToggleGroup.tsx, console/console-init/ui/src/modules/connection/components/ConnectionsToolbar/ConnectionsToolbar.tsx, console/console-init/ui/src/modules/connection/components/EmptyConnection/EmptyConnection.tsx
- Refactoring
Add meaningful ID to connections component
=> [Console-IoT] Add id to connection module

console/console-init/ui/src/modules/address-detail/AddressDetailPage.tsx, console/console-init/ui/src/modules/address-detail/components/AddressDetailHeader/AddressDetailHeader.tsx, console/console-init/ui/src/modules/address-detail/components/AddressLinks/AddressLinks.tsx, console/console-init/ui/src/modules/address-detail/components/AddressLinksToggleGroup/AddressLinksToggleGroup.tsx, console/console-init/ui/src/modules/address-detail/components/AddressLinksToolbar/AddressLinksToolbar.tsx, console/console-init/ui/src/modules/address-detail/components/EmptyAddressLinks/EmptyAddressLinks.tsx, console/console-init/ui/src/modules/address-detail/containers/AddressLinks/AddressLinksPage.tsx, console/console-init/ui/src/modules/address-detail/containers/AddressLinksToolbarContainer/AddressLinksToolbarContainer.tsx
- Refactoring
Adding meaningful id to components for address detail module
=> [Console-IoT] Add meaningful id to address detail module components

console/console-init/ui/src/modules/address/AddressPage.tsx, console/console-init/ui/src/modules/address/components/AddressConfiguration/AddressConfiguration.tsx, console/console-init/ui/src/modules/address/components/AddressList/AddressList.tsx, console/console-init/ui/src/modules/address/components/AddressListKebab/AddressListKebab.tsx, console/console-init/ui/src/modules/address/components/AddressToggleGroup/AddressToggleGroup.tsx, console/console-init/ui/src/modules/address/components/AddressToolbar/AddressToolbar.tsx, console/console-init/ui/src/modules/address/components/EmptyAddress/EmptyAddress.tsx, console/console-init/ui/src/modules/address/components/TypeAndPlan/TypePlan.tsx, console/console-init/ui/src/modules/address/dialogs/CreateAddress/CreateAddress.tsx, console/console-init/ui/src/modules/address/dialogs/CreateAddress/Preview.tsx, console/console-init/ui/src/modules/address/dialogs/EditAddress/EditAddress.tsx
- Refactoring
Adding meaningful id to components for address module
=> [Console-IoT] Add meaningful ID to components

console/console-init/ui/src/AppNavHeader.tsx
- Bugfix
Modify AppNavHeader component to fix the issue related to PF updates.
- avatar and toolbar is removed from the PageHeaderProps in the PF update.
=> [Console-iot] fix applayout breaking changes due to PF upgrade

console/console-init/ui/src/containers/AdapterListContainer/AdapterListContainer.tsx, console/console-init/ui/src/graphql-module/queries/iot_project.ts, console/console-init/ui/src/modules/iot-project-detail/IoTProjectDetailInfoPage.tsx, console/console-init/ui/src/modules/iot-project-detail/containers/IoTProjectDetailHeaderContainer/IoTProjectDetailHeaderContainer.tsx, console/console-init/ui/src/modules/project/containers/ProjectListContainer/ProjectListContainer.tsx, console/console-init/ui/src/schema/index.ts, console/console-init/ui/src/schema/iot_project.ts
- Bugfix
- Fix - project list query in UI.
- Currently displaying only iot-projects in UI.
=> [Console-iot UI] Include project list query changes in UI

console/console-init/ui/mock-console-server/mock-console-server.js, console/console-init/ui/mock-console-server/schema.js, console/console-init/ui/src/graphql-module/queries/iot_device.ts, console/console-init/ui/src/modules/iot-device-detail/DeviceDetailPage.tsx, console/console-init/ui/src/modules/iot-device-detail/containers/DeviceInfoContainer/DeviceInfoContainer.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceList/DeviceList.tsx, console/console-init/ui/src/modules/iot-device/containers/DeviceListContainer/DeviceListContainer.tsx, console/console-init/ui/src/modules/iot-device/containers/EditDeviceInJsonContainer/EditDeviceInJsonContainer.tsx, console/console-init/ui/src/modules/iot-device/containers/EditGatewaysContainer/EditGatewaysContainer.tsx, console/console-init/ui/src/modules/iot-device/utils/TableFormatter.tsx, console/console-init/ui/src/schema/iot_device.ts, console/console-init/ui/src/stories/DeviceList.stories.tsx
- Enhancement
Modify device list and device detail queries according to the mock server
=> Chore: modify device list and device detail queries according to the mock server

.tekton/test/systemtest-pipeline.yaml, .tekton/test/systemtest-task.yaml, systemtests/Makefile
- Enhancement
1. Allow to specify branch and repo (fork) for download testing code
=> Tekton allow to pass also branch name

systemtests/src/test/java/io/enmasse/systemtest/TestBase.java
=> Clean test base unused methods

HACKING.md, pkg/accesscontrolserver/amqp/types.go
- Refactoring
Remove Go-shim func now we are on Go 1.14.
=> [Access Control] Remove Go-shim func now we are on Go 1.14

.tekton/test/examples/pipeline-run-iot.yaml, .tekton/test/examples/pipeline-run-systemtests.yaml, .tekton/test/resources/systemtest-pipeline.yaml, .tekton/test/resources/systemtest-task.yaml, .tekton/test/systemtest-pipeline.yaml, .tekton/test/systemtest-task.yaml, systemtests/Makefile, systemtests/src/main/java/io/enmasse/systemtest/platform/cluster/MinikubeCluster.java
1. Allow to pass image source
2. use image with openssl (we use that in iot tests)
3. add examples to pipeline runs without tkn command
=> Tekton allow specify image source and use image with openssl

pom.xml, systemtests/pom.xml, systemtests/src/main/java/io/enmasse/systemtest/time/TimeMeasuringSystem.java
- Refactoring
Eliminate explicit GSON dependency.
=> Eliminate explicit GSON dependency

pom.xml, systemtests/pom.xml, systemtests/src/main/java/io/enmasse/systemtest/platform/GenericKubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kind.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Minikube.java, systemtests/src/main/java/io/enmasse/systemtest/platform/OpenShift.java
- Refactoring
Remove keycloak dependency and associated test support methods.
=> Remove keycloak dependency

olm-manifest/src/main/resources/latest/enmasse.clusterserviceversion.yaml
- Bugfix
Works around https://bugzilla.redhat.com/show_bug.cgi?id=1856413
=> Ensure that IoT roles iot-tenant-service/iot-device-connection have distinct permission sets

systemtests/scripts/build_pr_response.sh
- Bugfix
Fix printing error in GH PR reponse for class issue
=> Fix GH response for class failure

iot/pom.xml
Bump postgresql-jdbc from 42.2.13 -> 42.2.14.
=> Bump postgresql-jdbc from 42.2.13 -> 42.2.14

console/console-init/ui/src/Routes.tsx, console/console-init/ui/src/modules/iot-device/DeviceListPage.tsx, console/console-init/ui/src/modules/iot-device/components/AddDeviceWithJson/AddDeviceWithJson.tsx, console/console-init/ui/src/modules/iot-device/components/AddDeviceWithJson/AddJsonUsingTemplate.tsx, console/console-init/ui/src/modules/iot-device/components/index.ts, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/CreateDevicePage.tsx, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/CreateDeviceUsingJsonPage.tsx, console/console-init/ui/src/stories/AddDeviceWithJson.stories.tsx
Integrate visual component to add a device using json format
=> [console-iot] integrate create device using json component in page

console/console-init/ui/src/AppLayout.tsx
- Bugfix
- Fix UI code to add id "main-container" in Page component as mainContainerId in AppLayout.tsx file
=> [fix-id-issue] fix tests failing due to not finding element by id ("main-container")

systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java
- Bugfix
Clean iot namespaces after deletion of device registry
=> [Bugfix] Clean iot namespaces

console/console-init/ui/src/containers/AdapterListContainer/AdapterListContainer.tsx, console/console-init/ui/src/graphql-module/queries/iot_project.ts
- Bugfix
Fix projects query to get list of adapters in device configuration detail.
=> [console-iot] - fix project query in device configuration page

console/console-init/ui/src/graphql-module/queries/iot_device.ts, console/console-init/ui/src/modules/iot-device/components/DeviceFilter/AddCriteria.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceList/DeviceList.tsx
- Enhancement
Enable device list to be ordered by dates.
=> Chore: handle order by dates for DeviceList

systemtests/src/main/java/io/enmasse/systemtest/messaginginfra/resources/MessagingAddressResourceType.java, systemtests/src/main/java/io/enmasse/systemtest/messaginginfra/resources/MessagingEndpointResourceType.java, systemtests/src/main/java/io/enmasse/systemtest/messaginginfra/resources/MessagingInfrastructureResourceType.java, systemtests/src/main/java/io/enmasse/systemtest/messaginginfra/resources/MessagingProjectResourceType.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java
- Refactoring
Stop using deprecated fabric8 methods
=> Remove fabric8 deprecated methods

console/console-init/ui/src/constant/constants.ts, console/console-init/ui/src/graphql-module/queries/iot_device.ts, console/console-init/ui/src/modules/iot-device-detail/DeviceDetailPage.tsx, console/console-init/ui/src/modules/iot-device-detail/components/DeviceDetailHeader/DeviceDetailHeader.tsx, console/console-init/ui/src/modules/iot-device/components/AddCredential/AddCredential.tsx, console/console-init/ui/src/modules/iot-device/components/CredentialList/CredentialList.tsx, console/console-init/ui/src/modules/iot-device/components/ExtensionList/ExtensionList.tsx, console/console-init/ui/src/modules/iot-device/containers/AddCredentialsContainer/AddCredentialsContainer.tsx, console/console-init/ui/src/modules/iot-device/containers/EditCredentialsContainer/EditCredentialsContainer.tsx, console/console-init/ui/src/modules/iot-device/containers/EditCredentialsContainer/edit-credentials.module.css, console/console-init/ui/src/modules/iot-device/utils/utils.ts, console/console-init/ui/src/utils/utils.ts
- Refactoring
1. Create serialize  function for credentials
2. Create deserialize  function for credentials
3. Integrate mock-server to get exising credentials and polputae fields in edit cerdentials form
4. Save credentials
=> Implemented edit credentials functionality

systemtests/src/main/java/io/enmasse/systemtest/certs/ssl/CertPair.java, systemtests/src/main/java/io/enmasse/systemtest/certs/ssl/CertSigningRequest.java, systemtests/src/main/java/io/enmasse/systemtest/certs/ssl/SSLUtils.java, systemtests/src/main/java/io/enmasse/systemtest/utils/TestUtils.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/x509/TrustAnchorTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/x509/X509EcAuthenticationTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/isolated/x509/X509RsaAuthenticationTest.java, systemtests/src/test/java/io/enmasse/systemtest/sharedinfra/MessagingEndpointTest.java
=> Move toPem into OpenSSL class

pkg/util/finalizer/finalizer.go, pkg/util/finalizer/finalizer_test.go
This change allows to run finalizers in parallel if they need more time.
Before this change, if a finalizer required more time to process, it was blocking the other finalizers in the list.
With this change, if a finalizer reports that it needs more time, the following finalizers are triggered as well, until the first one
reports that it completed, which requires persisting the resource.
=> allow running finalizers in parallel

console/console-init/ui/src/modules/iot-device/DeviceListPage.tsx, console/console-init/ui/src/modules/iot-device/components/AddDeviceWithJson/AddDeviceWithJson.tsx, console/console-init/ui/src/modules/iot-device/components/AddDeviceWithJson/AddJsonUsingTemplate.tsx, console/console-init/ui/src/modules/iot-device/components/AddGateways/AddGateway.tsx, console/console-init/ui/src/modules/iot-device/components/ConnectionTypeStep/ConnectionTypeStep.tsx, console/console-init/ui/src/modules/iot-device/components/CreateDeviceButton/CreateDeviceButton.tsx, console/console-init/ui/src/modules/iot-device/components/CreateMetadata/CreateMetadata.tsx, console/console-init/ui/src/modules/iot-device/components/CreateMetadata/MetaDataRow.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceFilter/AddCriteria.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceFilter/DateFilterSection.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceFilter/DeviceFilter.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceFilter/LastSeenFilterSection.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceFilterCriteria/DeviceFilterCriteria.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceList/DeviceList.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceListToolbar/DeviceListToolbar.tsx, console/console-init/ui/src/modules/iot-device/components/ExtensionList/ExtensionList.tsx, console/console-init/ui/src/modules/iot-device/components/SecretList/SecretList.tsx, console/console-init/ui/src/modules/iot-device/containers/AddCredentialsContainer/AddCredentialsContainer.tsx, console/console-init/ui/src/modules/iot-device/containers/AddGatewaysContainer/AddGatewaysContainer.tsx, console/console-init/ui/src/modules/iot-device/containers/EditDeviceInJsonContainer/EditDeviceInJsonContainer.tsx, console/console-init/ui/src/modules/iot-device/containers/EditGatewaysContainer/EditGatewaysContainer.tsx, console/console-init/ui/src/modules/iot-device/containers/EditMetadataContainer/EditMetadataContainer.tsx, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/CreateDevicePage.tsx, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/DeviceInformation.tsx
- Refactoring
Add ID to IoT device module
=> [Console-IoT] Add ID to IoT device module

console/console-init/ui/src/modules/iot-project-detail/components/AccessCredentials/AccessCredentials.tsx, console/console-init/ui/src/modules/iot-project-detail/components/DeviceRegistrationManagement/DeviceRegistrationManagement.tsx, console/console-init/ui/src/modules/iot-project-detail/components/GeneralInfo/GeneralInfo.tsx, console/console-init/ui/src/modules/iot-project-detail/components/IoTProjectDetailHeader/IoTProjectDetailHeader.tsx, console/console-init/ui/src/modules/iot-project-detail/components/ProjectNavigation/ProjectNavigation.tsx
- Refactoring
Add ID to IoT project detail module
=> [Console-IoT]-Add ID to IoT project detail

console/console-init/ui/src/modules/connection-detail/ConnectionDetailPage.tsx, console/console-init/ui/src/modules/connection-detail/components/ConnectionDetailHeader/ConnectionDetailHeader.tsx, console/console-init/ui/src/modules/connection-detail/components/ConnectionDetailHeaderAttributes/ConnectionDetailHeaderAttributes.tsx, console/console-init/ui/src/modules/connection-detail/components/ConnectionLinksList/ConnectionLinksList.tsx, console/console-init/ui/src/modules/connection-detail/components/ConnectionLinksToggleGroup/ConnectionLinksToggleGroup.tsx, console/console-init/ui/src/modules/connection-detail/components/ConnectionLinksToolbar/ConnectionLinksToolbar.tsx, console/console-init/ui/src/modules/connection-detail/components/EmptyConnectionLinks/EmptyConnectionLinks.tsx, console/console-init/ui/src/modules/connection-detail/components/MessagesDetailHeaderAttributes/MessagesDetailHeaderAttributes.tsx
- Refactoring
Add meaningul ID to Connection Detail module
=> [Console-IoT] Add meaningul ID to Connection Detail module

console/console-init/ui/src/components/About/About.tsx, console/console-init/ui/src/components/FinishedStep/FinishedStep.tsx, console/console-init/ui/src/components/FormAndJson/FormAndJson.tsx, console/console-init/ui/src/components/JsonEditor/JsonEditor.tsx, console/console-init/ui/src/components/MetadataListTable/MetadataListTable.tsx, console/console-init/ui/src/components/MetadataListTable/NoMetadataFound.tsx, console/console-init/ui/src/components/NavToolbar/NavToolbar.tsx, console/console-init/ui/src/components/NetworkStatusAlert/NetworkStatusAlert.tsx, console/console-init/ui/src/components/NoDataFound/NoDataFound.tsx, console/console-init/ui/src/components/NoResultFound/NoResultFound.tsx, console/console-init/ui/src/components/NotFound/NotFound.tsx, console/console-init/ui/src/components/PasswordInputFieldWithToggle/PasswordInputFieldWithToggle.tsx, console/console-init/ui/src/components/RootModal/RootModal.tsx, console/console-init/ui/src/components/ServerMessageAlert/ServerMessageAlert.tsx, console/console-init/ui/src/components/SortForMobileView/SortForMobileView.tsx, console/console-init/ui/src/components/TablePagination/TablePagination.tsx, console/console-init/ui/src/components/UpdatePassword/UpdatePassword.tsx
- Refactoring
Add ID to generic components
=> [Console-IoT] Add ID to generic components

systemtests/pom.xml
=> Fix surefire logging

systemtests/scripts/build_pr_response.sh
* Use JQ to encode body
* Collapse different if branches
* Indicate cancelled test
- Refactoring
=> improve GH test summary

systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java
Adding extra logging and an additional screenshot to understand a test failure on OpenShift 4.5.
=> FirefoxConsoleTest.testOpenShiftWithCustomCert on OpenShift 4.5 - add extra Custom cert test logging

console/console-init/ui/src/modules/iot-device-detail/DeviceDetailPage.tsx, console/console-init/ui/src/modules/iot-device-detail/components/ActionManager/ActionManager.tsx, console/console-init/ui/src/modules/iot-device-detail/components/ConfigurationInfo/ConfigurationInfo.tsx, console/console-init/ui/src/modules/iot-device-detail/components/CredentialsView/CredentialsView.tsx, console/console-init/ui/src/modules/iot-device-detail/components/CredentialsView/ExtensionsView/ExtensionsView.tsx, console/console-init/ui/src/modules/iot-device-detail/components/CredentialsView/SecretsView/SecretsView.tsx, console/console-init/ui/src/modules/iot-device-detail/components/DeviceDetailHeader/DeviceDetailHeader.tsx, console/console-init/ui/src/modules/iot-device-detail/components/DeviceDetailNavigation/DeviceDetailNavigation.tsx, console/console-init/ui/src/modules/iot-device-detail/components/DeviceInfo/DeviceInfo.tsx, console/console-init/ui/src/modules/iot-device-detail/components/DeviceInfo/ErrorStateAlert.tsx
- Refactoring
Add ID to IoT Device Detail components
=> [Console-IoT] Add ID to IoT Device Detail components

console/console-init/ui/src/modules/project/ProjectPage.tsx, console/console-init/ui/src/modules/project/components/EmptyProject/EmptyProject.tsx, console/console-init/ui/src/modules/project/components/EndpointCertificateConfiguration/EndpointCertificateConfiguration.tsx, console/console-init/ui/src/modules/project/components/EndpointConfiguraion/EndpointConfiguraion.tsx, console/console-init/ui/src/modules/project/components/IoTConfiguration/IoTConfiguration.tsx, console/console-init/ui/src/modules/project/components/IoTReview/IoTReview.tsx, console/console-init/ui/src/modules/project/components/MessagingConfiguration/MessagingConfiguration.tsx, console/console-init/ui/src/modules/project/components/MessagingReview/MessagingReview.tsx, console/console-init/ui/src/modules/project/components/ProjectDatatoolbarToggleGroup/ProjectDataToolbarToggleGroup.tsx, console/console-init/ui/src/modules/project/components/ProjectListKebab/ProjectListKebab.tsx, console/console-init/ui/src/modules/project/components/ProjectToolbar/ProjectToolbar.tsx, console/console-init/ui/src/modules/project/components/ProjectTypeConfigurationStep/ProjectTypeConfigurationStep.tsx, console/console-init/ui/src/modules/project/dailogs/CreateProject/ConfiguringRoutes.tsx, console/console-init/ui/src/modules/project/dailogs/CreateProject/CreateProject.tsx
- Refactoring
Add meaningful  ID to  project modules folder
=> [Console-IoT] Add meaningful  ID to  project modules folder

console/console-init/ui/src/graphql-module/queries/project.ts, console/console-init/ui/src/modules/address/dialogs/EditAddress/EditAddress.tsx, console/console-init/ui/src/modules/iot-certificates/IoTCertificatesPage.tsx, console/console-init/ui/src/modules/project/ProjectPage.tsx, console/console-init/ui/src/modules/project/components/ProjectDatatoolbarToggleGroup/ProjectDataToolbarToggleGroup.tsx, console/console-init/ui/src/modules/project/containers/ProjectListContainer/ProjectListContainer.tsx, console/console-init/ui/src/modules/project/containers/ProjectToolbarContainer/ProjectToolbarContainer.tsx, console/console-init/ui/src/modules/project/utils/utils.ts, console/console-init/ui/src/schema/iot_project.ts
- Refactoring
- Intgegrate filter functionality for project list
=> [Console-IoT] implement filter for project list

systemtests/src/test/java/io/enmasse/systemtest/bases/web/ConsoleTest.java
- Bugfix
On newer OpenShift versions it seems that the oauth proxy endpoint gets the replacement
cert a significant time before the EnMasse console endpoint.  This causes the test to fail.
Test now awaits both endpoints to present the new cert.  Also guards against a stale selenium session.
=> Fix FirefoxConsoleTest#testOpenShiftWithCustomCert to work on newer OpenShift

console/console-init/ui/src/graphql-module/queries/project.ts, console/console-init/ui/src/modules/project/ProjectPage.tsx, console/console-init/ui/src/modules/project/containers/ProjectListContainer/ProjectListContainer.tsx
Implement sorting and pagination in project list and integrate this with mockserver
=> [Console-Iot] add sorting and pagination for project list

.github/workflows/smoke.yml, systemtests/src/test/java/io/enmasse/systemtest/iot/http/StandardIoTHttpTests.java
=> Fix iot logging in actions

console/console-init/ui/package.json, console/console-init/ui/yarn.lock
- Bugfix
Downgrade react-popper version for fixing build warning issue
=> Downgrade react-popper version for fixing build warning issue

systemtests/src/main/java/io/enmasse/systemtest/amqp/AmqpClient.java, systemtests/src/main/java/io/enmasse/systemtest/amqp/ClientHandlerBase.java, systemtests/src/main/java/io/enmasse/systemtest/amqp/Receiver.java, systemtests/src/main/java/io/enmasse/systemtest/iot/CommandTester.java, systemtests/src/main/java/io/enmasse/systemtest/iot/HttpAdapterClient.java, systemtests/src/main/java/io/enmasse/systemtest/iot/IoTUtils.java, systemtests/src/main/java/io/enmasse/systemtest/iot/MessageSendTester.java, systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java, systemtests/src/test/java/io/enmasse/systemtest/iot/CommandTesterTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/http/HttpSubordinate.java
=> fix some testing issues

systemtests/src/main/java/io/enmasse/systemtest/framework/annotations/DefaultMessagingInfrastructureExtension.java, systemtests/src/main/java/io/enmasse/systemtest/framework/annotations/DefaultMessagingProjectExtension.java, systemtests/src/main/java/io/enmasse/systemtest/messaginginfra/ResourceManager.java, systemtests/src/main/java/io/enmasse/systemtest/messaginginfra/resources/MessagingAddressResourceType.java, systemtests/src/main/java/io/enmasse/systemtest/messaginginfra/resources/MessagingEndpointResourceType.java, systemtests/src/main/java/io/enmasse/systemtest/messaginginfra/resources/MessagingInfrastructureResourceType.java, systemtests/src/main/java/io/enmasse/systemtest/messaginginfra/resources/MessagingProjectResourceType.java, systemtests/src/main/java/io/enmasse/systemtest/messaginginfra/resources/NamespaceResourceType.java, systemtests/src/main/java/io/enmasse/systemtest/messaginginfra/resources/ResourceKind.java, systemtests/src/test/java/io/enmasse/systemtest/sharedinfra/DefaultsTest.java, systemtests/src/test/java/io/enmasse/systemtest/sharedinfra/MessagingAddressPerfTest.java, systemtests/src/test/java/io/enmasse/systemtest/sharedinfra/MessagingAddressTest.java, systemtests/src/test/java/io/enmasse/systemtest/sharedinfra/MessagingEndpointTest.java, systemtests/src/test/java/io/enmasse/systemtest/sharedinfra/MessagingInfrastructureTest.java, systemtests/src/test/java/io/enmasse/systemtest/sharedinfra/MessagingProjectTest.java
Allow resource manager to share default resources created by annotations between parallel tests
=> Update resource manager to share resources between parallel tests

console/console-init/ui/src/components/DropdownWithToggle/DropdownWithToggle.tsx, console/console-init/ui/src/components/NavToolbar/NavToolbar.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceListToolbar/DeviceListToolbar.test.tsx
- Refactor
The warnings arising from yarn tests have been resolved. They were mostly caused due to absence of unique keys.
Addresses #5012
=> Fix: resolve yarn test warnings

console/console-init/ui/src/modules/iot-device/components/CreateMetadata/MetaDataRow.tsx, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/DeviceInformation.tsx, console/console-init/ui/src/modules/iot-device/utils/constant.ts
Validate the value of metadata value based on Type during device Registration.
=> Validate metadata value based on type

console/console-init/ui/src/graphql-module/queries/project.ts, console/console-init/ui/src/modules/project/components/ProjectList/ProjectList.test.tsx, console/console-init/ui/src/modules/project/components/ProjectList/ProjectList.tsx, console/console-init/ui/src/modules/project/containers/ProjectListContainer/ProjectListContainer.tsx, console/console-init/ui/src/schema/iot_project.ts
- Refactoring
- Remove Error column from project list
- Update query to fetch count for address and connections for messaging project and display them in entities column of project list
=> [Console-IoT] remove error column in project list

documentation/modules/proc-create-address-plan-custom-resource-olm-ui.adoc, documentation/modules/proc-create-address-space-plan-custom-resource-olm-ui.adoc, documentation/modules/proc-create-auth-service-custom-resource-olm-ui.adoc, documentation/modules/proc-create-infraconfig-custom-resource-olm-ui.adoc, documentation/modules/proc-olm-installing-from-operatorhub-using-console.adoc
Docs: Update procedures for creating custom resource
=> Docs:Update procedures for creating custom resource

console/console-init/ui/src/modules/iot-certificates/components/IoTCertificateList/IoTCertificateList.tsx, console/console-init/ui/src/modules/iot-certificates/components/IoTCertificateToolbar/IoTCertificateToolbar.tsx
Add Json view for IoT certificates
=> [Console-IoT] Add Json view for IoT certificates

console/console-init/ui/src/modules/address-detail/AddressDetailPage.tsx, console/console-init/ui/src/modules/address-detail/components/AddressDetailHeader/AddressDetailHeader.tsx, console/console-init/ui/src/modules/address-detail/components/AddressLinksToggleGroup/AddressLinksToggleGroup.tsx, console/console-init/ui/src/modules/address/components/AddressConfiguration/AddressConfiguration.tsx, console/console-init/ui/src/modules/address/components/AddressListKebab/AddressListKebab.tsx, console/console-init/ui/src/modules/address/components/AddressToggleGroup/AddressToggleGroup.tsx, console/console-init/ui/src/modules/connection-detail/ConnectionDetailPage.tsx, console/console-init/ui/src/modules/connection-detail/components/ConnectionLinksToggleGroup/ConnectionLinksToggleGroup.tsx, console/console-init/ui/src/modules/connection/components/ConnectionsToggleGroup/ConnectionsToggleGroup.tsx, console/console-init/ui/src/modules/iot-device-detail/DeviceDetailPage.tsx, console/console-init/ui/src/modules/iot-device-detail/components/DeviceDetailHeader/DeviceDetailHeader.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceFilter/DeviceFilter.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceFilter/LastSeenFilterSection.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceFilterCriteria/DeviceFilterCriteria.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceListToolbar/DeviceListToolbar.tsx, console/console-init/ui/src/modules/iot-device/components/ExtensionList/ExtensionList.tsx, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/CreateDevicePage.tsx, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/CreateDeviceUsingJsonPage.tsx, console/console-init/ui/src/modules/iot-project-detail/IoTProjectDetailPage.tsx, console/console-init/ui/src/modules/iot-project-detail/components/DeviceRegistrationManagement/DeviceRegistrationManagement.tsx, console/console-init/ui/src/modules/iot-project-detail/components/IoTProjectDetailHeader/IoTProjectDetailHeader.tsx, console/console-init/ui/src/modules/project/components/IoTConfiguration/IoTConfiguration.tsx, console/console-init/ui/src/modules/project/components/ProjectDatatoolbarToggleGroup/ProjectDataToolbarToggleGroup.tsx
- Refactoring
Remove error messages data from project list
Rename use of dropdowntoggle in ID to dropdown
=> [Console-IoT] Rename use of 'dropdowntoggle' in ID to 'dropdown'

console/console-init/ui/src/components/UpdatePassword/UpdatePassword.tsx, console/console-init/ui/src/modules/iot-device-detail/components/CredentialsView/CredentialsView.tsx, console/console-init/ui/src/modules/iot-device-detail/components/CredentialsView/SecretsView/SecretsView.tsx, console/console-init/ui/src/modules/iot-device-detail/components/DeviceInfo/DeviceInfo.tsx, console/console-init/ui/src/modules/iot-device-detail/containers/SecretViewContainer/SecretViewContainer.tsx, console/console-init/ui/src/modules/iot-device-detail/containers/SecretViewContainer/index.ts, console/console-init/ui/src/modules/iot-device-detail/containers/index.ts
- Refactoring
Implemented update secret password functionality
=> Implemented update secret password functionality

systemtests/src/main/java/io/enmasse/systemtest/iot/IoTTestSession.java
- Refactoring
**Note** This is based on some other changes, only the top commit is relevant.
=> use routes on OCP4

systemtests/src/main/java/io/enmasse/systemtest/executor/Exec.java, systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java
- Enhancement
Logging of running commands cause really mess in our logs, so I changed that behavior to log that command only if logging is enabled.
=> Log executor only if logging is enabled

pkg/controller/iotinfra/adapter.go, systemtests/src/main/java/io/enmasse/systemtest/iot/DefaultDeviceRegistry.java, systemtests/src/main/java/io/enmasse/systemtest/iot/IoTTestSession.java, systemtests/src/test/java/io/enmasse/systemtest/iot/IoTTestSessionTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/tls/ReloadCertificatesTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/tls/TlsVersionTest.java
=> disable test for now

iot/pom.xml, pkg/controller/iotinfra/adapter.go, systemtests/src/main/java/io/enmasse/systemtest/iot/DefaultDeviceRegistry.java, systemtests/src/main/java/io/enmasse/systemtest/iot/IoTTestSession.java, systemtests/src/test/java/io/enmasse/systemtest/iot/IoTTestSessionTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/tls/ReloadCertificatesTest.java, systemtests/src/test/java/io/enmasse/systemtest/iot/tls/TlsVersionTest.java
- Bugfix
**Note:** Only the most recent commit is part of this PR. The others will be gone after this is rebased.
=> update dependency version

console/console-init/ui/src/graphql-module/queries/iot_project.ts, console/console-init/ui/src/graphql-module/queries/project.ts, console/console-init/ui/src/modules/iot-device-detail/containers/DeviceInfoContainer/DeviceInfoContainer.tsx, console/console-init/ui/src/modules/iot-device/components/CreateMetadata/CreateMetadata.tsx, console/console-init/ui/src/modules/iot-device/components/CreateMetadata/MetaDataProperty.tsx, console/console-init/ui/src/modules/iot-device/components/CreateMetadata/MetaDataRow.tsx, console/console-init/ui/src/modules/iot-device/components/CreateMetadata/MetaDataType.tsx, console/console-init/ui/src/modules/iot-device/components/CreateMetadata/MetaDataValue.tsx, console/console-init/ui/src/modules/iot-device/components/ReviewDevice/ReviewDevice.tsx, console/console-init/ui/src/modules/iot-device/utils/constant.ts, console/console-init/ui/src/modules/project/containers/ProjectListContainer/ProjectListContainer.tsx, console/console-init/ui/src/modules/project/utils/ProjectFormatter.tsx, console/console-init/ui/src/utils/utils.ts
- Refactoring
Restructure the metadata json, refactored json updates and removed unwanted variables and queries.
=> Restructure metadata json to form parent and child hierarcies

console/console-init/ui/src/Routes.tsx, console/console-init/ui/src/modules/iot-device-detail/components/CredentialsView/CredentialsView.tsx, console/console-init/ui/src/modules/iot-device/components/AddDeviceWithJson/AddDeviceWithJson.tsx, console/console-init/ui/src/modules/iot-device/components/AddDeviceWithJson/AddJsonUsingTemplate.tsx, console/console-init/ui/src/modules/iot-device/components/ReviewDevice/ReviewDevice.tsx, console/console-init/ui/src/modules/iot-device/containers/ReviewDeviceContainer/ReviewDeviceContainer.tsx, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/AddDeviceUsingJsonPage.tsx, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/CreateDevicePage.tsx, console/console-init/ui/src/modules/iot-device/utils/constant.ts, console/console-init/ui/src/stories/AddDeviceWithJson.stories.tsx, console/console-init/ui/src/stories/ReviewDevice.stories.tsx
- Integrate Preview section in Add Device Using Json Page.
- Update File Upload component to manage drag feature and handle error at page level
=> [Console-Iot] Integrate preview section in add device using json.

console/console-init/ui/src/components/TablePagination/TablePagination.tsx, console/console-init/ui/src/modules/iot-device/DeviceListPage.tsx, console/console-init/ui/src/modules/iot-device/containers/DeviceListContainer/DeviceListContainer.tsx, console/console-init/ui/src/modules/project/ProjectPage.tsx, console/console-init/ui/src/modules/project/containers/ProjectListContainer/ProjectListContainer.tsx
- Bugfix
* Fix the bug in device list for unselecting an item if all the items are selected.
* ID was not getting rendered for TablePagination component.
=> Fix: multiple select of device list and render id for TablePagination

documentation/modules/proc-create-address-plan-custom-resource-olm-ui.adoc, documentation/modules/proc-create-address-space-plan-custom-resource-olm-ui.adoc, documentation/modules/proc-create-auth-service-custom-resource-olm-ui.adoc, documentation/modules/proc-create-infraconfig-custom-resource-olm-ui.adoc, documentation/modules/proc-olm-installing-from-operatorhub-using-console.adoc
Docs:Update procedures for creating custom resource
=> Docs:Update procedures for creating custome resource

console/console-init/ui/src/modules/messaging-project/MessagingProjectDetailPage.tsx, console/console-init/ui/src/modules/messaging-project/components/EditMessagingProject/EditMessagingProject.tsx, console/console-init/ui/src/modules/messaging-project/components/EditMsgProject/EditMsgProject.tsx, console/console-init/ui/src/modules/messaging-project/components/EmptyMessagingProject/EmptyMessagingProject.tsx, console/console-init/ui/src/modules/messaging-project/components/EndpointCertificateConfiguration/EndpointCertificateConfiguration.tsx, console/console-init/ui/src/modules/messaging-project/components/EndpointConfiguraion/EndpointConfiguraion.tsx, console/console-init/ui/src/modules/messaging-project/components/MessagingDatatoolbarToggleGroup/MessagingDataToolbarToggleGroup.tsx, console/console-init/ui/src/modules/messaging-project/components/MessagingProjectConfiguration/MessagingProjectConfiguration.tsx, console/console-init/ui/src/modules/messaging-project/components/MessagingProjectHeader/MessagingProjectHeader.tsx, console/console-init/ui/src/modules/messaging-project/components/MessagingProjectList/MessagingProjectList.tsx, console/console-init/ui/src/modules/messaging-project/components/MessagingProjectListKebab/MessagingProjectListKebab.tsx, console/console-init/ui/src/modules/messaging-project/components/MessagingProjectNavigation/MessagingProjectNavigation.tsx, console/console-init/ui/src/modules/messaging-project/components/MessagingProjectReview/MessagingProjectReview.tsx, console/console-init/ui/src/modules/messaging-project/components/MessagingToolbar/MessagingToolbar.tsx, console/console-init/ui/src/modules/messaging-project/dialogs/CreateMessagingProject/ConfiguringRoutes.tsx, console/console-init/ui/src/modules/messaging-project/dialogs/CreateMessagingProject/CreateMessagingProject.tsx
- Refactoring
Add ID to messaging project module
=> [Console-IoT] Add ID to messaging project module

console/console-init/ui/src/components/TypeAheadSelect/TypeAheadSelect.tsx, console/console-init/ui/src/graphql-module/queries/iot_device.ts, console/console-init/ui/src/mock-data/iot_device.ts, console/console-init/ui/src/modules/iot-device/components/AddGateways/AddGateway.tsx, console/console-init/ui/src/modules/iot-device/components/AddGateways/pf-overrides.css, console/console-init/ui/src/modules/iot-device/containers/AddGatewaysContainer/AddGatewaysContainer.tsx, console/console-init/ui/src/modules/iot-device/containers/EditGatewaysContainer/EditGatewaysContainer.tsx, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/CreateDevicePage.tsx, console/console-init/ui/src/modules/iot-device/utils/constant.ts
- Enhancement
* Modify TypeAheadSelect to support multiple selections.
* Write queries for setting gateways of iot devices.
* Check if gateway id exists.
=> Chore: modify AddGateway visual component

RELEASING.md
Update documentation release instructions
=> Add new doc release instructions

console/console-init/ui/src/graphql-module/queries/iot_device.ts, console/console-init/ui/src/modules/iot-device/components/DeviceList/DeviceList.tsx, console/console-init/ui/src/modules/iot-device/containers/DeviceListContainer/DeviceListContainer.tsx, console/console-init/ui/src/modules/iot-device/utils/TableFormatter.tsx, console/console-init/ui/src/schema/iot_device.ts, console/console-init/ui/src/stories/DeviceList.stories.tsx, console/console-init/ui/src/stories/DeviceListPage.stories.tsx
- Bugfix
In IDevice interface, credential field has been removed and viaGroups have been added.
=> Fix: change IDevice interface according to mock-server

console/console-init/ui/src/modules/iot-device/components/CreateMetadata/MetaDataRow.tsx, console/console-init/ui/src/modules/iot-device/components/CreateMetadata/MetaDataType.tsx, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/DeviceInformation.tsx
- Refactoring
Fix alignment issue in add a device page
[ https://marvelapp.com/prototype/5gbji22/screen/68586288](url)
=> [Console-IoT] Fix alignment issue in add a device page

console/console-init/ui/src/graphql-module/queries/iot_device.ts, console/console-init/ui/src/modules/iot-device/DeviceListPage.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceList/DeviceList.test.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceList/DeviceList.tsx, console/console-init/ui/src/modules/iot-device/components/MangeColumnModal/ManageColumnModal.tsx, console/console-init/ui/src/modules/iot-device/containers/DeviceListContainer/DeviceListContainer.tsx, console/console-init/ui/src/modules/iot-device/utils/TableFormatter.tsx, console/console-init/ui/src/stories/DeviceList.stories.tsx, console/console-init/ui/src/stories/DeviceListPage.stories.tsx
integrate manage column toolbar in device list component and query
=> [Console-Iot] integrate manage column toolbar in device list component and query

documentation/modules/con-standard-queue.adoc
Docs: Update wording for queue concept
=> Docs: Update wording for queue concept

console/console-init/ui/src/modules/project/components/ProjectDatatoolbarToggleGroup/ProjectDataToolbarToggleGroup.tsx
- Refactoring
Fix alignment issue for Project List Toolbar
=> [Console-IoT] Fix alignment issue for Project List Toolbar

console/console-init/ui/mock-console-server/schema.js, console/console-init/ui/src/graphql-module/queries/iot_device.ts, console/console-init/ui/src/modules/iot-device/components/AddDeviceWithJson/AddJsonUsingTemplate.tsx, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/AddDeviceUsingJsonPage.tsx, console/console-init/ui/src/modules/iot-device/utils/utils.ts, console/console-init/ui/src/schema/iot_device.ts
- Enhancement 
Integrate create device flow with JSON with server
=> [console-Iot] Integrate add device using json with mock server

console/console-init/ui/mock-console-server/mock-console-server.js, console/console-init/ui/mock-console-server/schema.js, console/console-init/ui/mock-console-server/test/mock.js
Console mock for DLQ/Expiry feature
=> Add console mock for DLQ/Expiry feature

console/console-init/ui/src/graphql-module/queries/iot_device.ts, console/console-init/ui/src/modules/iot-device/containers/DeviceListContainer/DeviceListContainer.tsx, console/console-init/ui/src/modules/iot-device/utils/TableFormatter.tsx, console/console-init/ui/src/stories/DeviceList.stories.tsx, console/console-init/ui/src/stories/DeviceListPage.stories.tsx
- Bugfix
Fix device list connection type issue
=> fix device list connection type

console/console-init/ui/src/components/Editor/Editor.tsx, console/console-init/ui/src/components/JsonEditor/JsonEditor.tsx, console/console-init/ui/src/modules/iot-device-detail/components/DeviceDetailHeader/DeviceDetailHeader.tsx, console/console-init/ui/src/modules/iot-device-detail/dialogs/CloneDevice/CloneDeviceUsingJsonPage.tsx, console/console-init/ui/src/modules/iot-device/components/AddDeviceWithJson/AddDeviceWithJson.tsx, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/AddDeviceUsingJsonPage.tsx, console/console-init/ui/src/schema/iot_device.ts, console/console-init/ui/src/stories/AddDeviceWithJson.stories.tsx
- Bugfix
- Integrate clone device using json
- fix issue related to json editor
=> [Console-Iot] Integrate clone device using json with mock server

console/console-init/ui/src/modules/project/ProjectPage.tsx, console/console-init/ui/src/modules/project/components/ProjectListKebab/ProjectListKebab.tsx, console/console-init/ui/src/modules/project/components/ProjectToolbar/ProjectToolbar.tsx, console/console-init/ui/src/modules/project/containers/ProjectToolbarContainer/ProjectToolbarContainer.tsx, console/console-init/ui/src/modules/project/utils/utils.ts
In project list toolbar add option to enable/disable multiple iot projects
=> [console-iot] add option to enable/disable multiple iot projects

.jenkins/Jenkinsfile-pr
=> PR jenkins index build

console/console-init/ui/src/modules/iot-project-detail/containers/IoTProjectDetailHeaderContainer/IoTProjectDetailHeaderContainer.tsx
- Bugfix
- Refactoring
Add fetch policy and poll interval in query to fetch iot project
=> add network policy in project detial query

console/console-init/ui/src/components/ChipGroupsWithTitle/ChipGroupsWithTitle.tsx, console/console-init/ui/src/components/ChipGroupsWithTitle/index.ts, console/console-init/ui/src/components/index.ts, console/console-init/ui/src/modules/iot-device-detail/components/ActionManager/ActionManager.tsx, console/console-init/ui/src/modules/iot-device/DeviceListPage.tsx, console/console-init/ui/src/modules/iot-device/components/AddGatewayGroupMembership/AddGatewayGroupMembership.tsx, console/console-init/ui/src/modules/iot-device/components/AddGateways/AddGateway.tsx, console/console-init/ui/src/modules/iot-device/containers/EditGatewaysContainer/EditGatewaysContainer.tsx, console/console-init/ui/src/modules/iot-project-detail/Routes.tsx
- Refactoring
- Enhancement AddGateway component
- Enhancement EditGatewayContainer component 
- Create generic chip groups component
- Fix reset device action type
- Remove duplicate routes from Routes.ts file
=> Edit gateway connection 

console/console-init/ui/mock-console-server/mock-console-server.js, console/console-init/ui/src/modules/iot-device-detail/components/ConnectionGateway/ConnectionGateway.tsx, console/console-init/ui/src/modules/iot-device-detail/components/ConnectionGateway/GatewayItems.tsx, console/console-init/ui/src/modules/iot-device-detail/components/ConnectionGateway/index.ts, console/console-init/ui/src/modules/iot-device-detail/components/DeviceInfo/DeviceInfo.tsx, console/console-init/ui/src/modules/iot-device-detail/components/GatewayMembership/GatewayMembership.tsx, console/console-init/ui/src/modules/iot-device-detail/components/GatewayMembership/index.ts, console/console-init/ui/src/modules/iot-device-detail/containers/DeviceInfoContainer/DeviceInfoContainer.tsx, console/console-init/ui/src/modules/iot-device/components/AddGatewayGroupMembership/AddGatewayGroupMembership.tsx, console/console-init/ui/src/stories/DeviceInfo.stories.tsx
- Enhancement
Display gateway groups and group membership in device info page.
Upgrades to #5120
=> Feat: fetch gateway groups for device info

console/console-init/ui/src/modules/address-detail/containers/AddressLinksToolbarContainer/AddressLinksToolbarContainer.tsx, console/console-init/ui/src/modules/address/containers/AddressToolbarContainer/AddressToolbarContainer.tsx, console/console-init/ui/src/modules/connection-detail/containers/ConnectionLinksToolbarContainer/ConnectionLinksToolbarContainer.tsx, console/console-init/ui/src/modules/connection/containers/ConnectionToolbarContainer/ConnectionToolbarContainer.tsx, console/console-init/ui/src/modules/iot-device-detail/components/DeviceInfo/DeviceInfo.tsx, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/CreateDevicePage.tsx, console/console-init/ui/src/modules/project/containers/ProjectToolbarContainer/ProjectToolbarContainer.tsx
- Enhancement
- Typo
* The AddGatewayGroupMembership component has been reused in CreateDevicePage for the memberOf step.
* A typo has been fixed.
=> Feat: add gateway membership step for create device flow

console/console-init/ui/src/modules/iot-device/components/AddDeviceWithJson/AddDeviceWithJson.tsx, console/console-init/ui/src/modules/iot-device/components/CreateDeviceButton/CreateDeviceButton.test.tsx, console/console-init/ui/src/modules/iot-device/components/CreateDeviceButton/CreateDeviceButton.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceListToolbar/DeviceListToolbar.test.tsx, console/console-init/ui/src/modules/iot-project-detail/components/AccessCredentials/AccessCredentials.tsx, console/console-init/ui/src/modules/iot-project-detail/components/ProjectNavigation/ProjectNavigation.tsx, console/console-init/ui/src/modules/project/containers/ProjectListContainer/ProjectListContainer.tsx
- Refactoring
Include latest changes as per new UX updates
- Delete/Disable a IoT Project  notification modal
- Tab name:  Device certificates  
- Label name: Tenant certificate
- Change label in Create Device dropdown
- Add with wizard
- Add in JSON
=> add changes as per updated UX desgins in iot project

console/console-init/ui/src/modules/iot-device/components/CreateMetadata/CreateMetadata.tsx, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/CreateDevicePage.tsx, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/DeviceInformation.tsx, console/console-init/ui/src/modules/iot-device/utils/utils.ts
- Enhancement
- Refactoring
The wizard steps have been integrated at an upper level and data is being sent to server to create the device
=> Feat: integrate create device wizard

console/console-init/ui/src/modules/project/dailogs/CreateProject/CreateProject.tsx
- Refactoring
As per latest wireframes, finish step from wizard of create project removed.
- remove the logic to display final step
=> [console-iot] remove finish step from create project wizard

console/console-init/ui/package.json, console/console-init/ui/src/modules/project/utils/constant.ts, console/console-init/ui/src/modules/project/utils/utils.ts, console/console-init/ui/yarn.lock
- Bugfix
- Add count of pending projects in card if the status fetched from server is empty string
- update PF version to fix typeahead issue related to onEnter event for invalid input
=> add empty status as pending

console/console-init/ui/src/modules/iot-device/components/AddGateways/AddGateway.tsx, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/CreateDevicePage.tsx, console/console-init/ui/src/modules/iot-device/utils/utils.ts, console/console-init/ui/src/utils/utils.ts
- Enhancement
- Refactoring
- Review step of create device flow
- Inability to use generic functions.
- ReviewDevice prop should be object.
=> Feat: device review page in create device review

console/console-init/ui/src/components/DialogPrompt/DialogPrompt.tsx, console/console-init/ui/src/components/ServerMessageAlert/ServerMessageAlert.tsx, console/console-init/ui/src/constant/constants.ts, console/console-init/ui/src/context-state-reducer/reducer.ts, console/console-init/ui/src/graphql-module/error-helper.ts, console/console-init/ui/src/hooks/useMutationQuery.ts, console/console-init/ui/src/modules/iot-device/components/AddGatewayGroupMembership/AddGatewayGroupMembership.tsx, console/console-init/ui/src/modules/iot-device/containers/EditGatewayGroupMembershipContainer/EditGatewayGroupMembershipContainer.tsx, console/console-init/ui/src/utils/utils.ts
- Refactoring
Implemented toast alert  for success and failed queries
=> Implemented toast alert  for success and failed queries 

console/console-init/ui/src/modules/iot-device/DeviceListPage.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceList/DeviceList.tsx, console/console-init/ui/src/modules/iot-device/components/DeviceListToolbar/DeviceListToolbar.tsx, console/console-init/ui/src/modules/iot-device/containers/DeviceListContainer/DeviceListContainer.tsx, console/console-init/ui/src/stories/DeviceList.stories.tsx, console/console-init/ui/src/stories/DeviceListPage.stories.tsx
- Bugfix
Fix following issues in device list:-
- Change label of memberOf and via gateways as per new standards
- Remove Multiselect component from device toolbar
- Add multiselect component in device list
- After bulk deletion render previous page in device list
=> [console-iot] Fix device list

console/console-init/ui/src/App.css, console/console-init/ui/src/modules/iot-device-detail/dialogs/CloneDevice/CloneDevicePage.tsx, console/console-init/ui/src/modules/iot-device/components/AddDeviceWithJson/AddDeviceWithJson.tsx, console/console-init/ui/src/modules/iot-device/components/ReviewDevice/ReviewDevice.tsx, console/console-init/ui/src/modules/iot-device/components/ViewMetaData/ViewMetaData.tsx, console/console-init/ui/src/modules/iot-device/containers/ReviewDeviceContainer/ReviewDeviceContainer.tsx, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/CreateDevicePage.tsx, console/console-init/ui/src/modules/iot-device/utils/utils.ts, console/console-init/ui/src/stories/ReviewDevice.stories.tsx, console/console-init/ui/src/utils/utils.ts
- Bugfix
- Refactoring
- Fix issues in review device section in createDevicePage
- Add JsonEditor component to view the device in JSON format
=> [console-iot] add Json Editor in create device using form 

console/console-init/ui/src/modules/iot-device/components/DeviceList/DeviceList.tsx, console/console-init/ui/src/modules/iot-device/utils/constant.ts, console/console-init/ui/src/modules/project/ProjectPage.tsx, console/console-init/ui/src/modules/project/components/ProjectList/ProjectList.test.tsx, console/console-init/ui/src/modules/project/components/ProjectList/ProjectList.tsx, console/console-init/ui/src/modules/project/dailogs/CreateProject/CreateProject.tsx
- Bugfix
Fix following issues in project list :-
- rename header label of project list table
- Update the page in URL params after bulk deletion
=> [console-iot] fix issues related to project list

console/console-init/ui/src/App.css, console/console-init/ui/src/modules/iot-device-detail/dialogs/CloneDevice/CloneDevicePage.tsx, console/console-init/ui/src/modules/iot-device/components/AddDeviceWithJson/AddDeviceWithJson.tsx, console/console-init/ui/src/modules/iot-device/components/ReviewDevice/ReviewDevice.tsx, console/console-init/ui/src/modules/iot-device/components/ViewMetaData/ViewMetaData.tsx, console/console-init/ui/src/modules/iot-device/containers/ReviewDeviceContainer/ReviewDeviceContainer.tsx, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/CreateDevicePage.tsx, console/console-init/ui/src/modules/iot-device/utils/utils.ts, console/console-init/ui/src/stories/ReviewDevice.stories.tsx, console/console-init/ui/src/utils/utils.ts
Reverts EnMasseProject/enmasse#5169
=> Revert "[console-iot] add Json Editor in create device using form "

console/console-init/ui/src/modules/iot-device-detail/dialogs/CloneDevice/CloneDevicePage.tsx, console/console-init/ui/src/modules/iot-device/components/AddDeviceWithJson/AddDeviceWithJson.tsx, console/console-init/ui/src/modules/iot-device/components/ReviewDevice/ReviewDevice.tsx, console/console-init/ui/src/modules/iot-device/components/ViewMetaData/ViewMetaData.tsx, console/console-init/ui/src/modules/iot-device/containers/ReviewDeviceContainer/ReviewDeviceContainer.tsx, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/CreateDevicePage.tsx, console/console-init/ui/src/modules/iot-device/utils/utils.ts, console/console-init/ui/src/stories/ReviewDevice.stories.tsx, console/console-init/ui/src/utils/utils.ts
- Bugfix
- Fix issues in review device section in createDevicePage
- Add JsonEditor component to view the device in JSON format
=> [console-iot] add Json Editor in create device using form

documentation/modules/ref-supported-table.adoc
Docs: Update supported features table
=> Docs: Update supported features table

console/console-init/ui/src/modules/iot-device-detail/components/ActionManager/ActionManager.tsx, console/console-init/ui/src/modules/iot-device-detail/components/DeviceDetailHeader/DeviceDetailHeader.tsx, console/console-init/ui/src/modules/iot-device-detail/components/GatewayMembership/GatewayMembership.tsx, console/console-init/ui/src/modules/iot-device/components/AddGateways/AddGateway.tsx, console/console-init/ui/src/modules/iot-device/containers/AddCredentialsContainer/AddCredentialsContainer.tsx, console/console-init/ui/src/modules/iot-device/containers/AddGatewaysContainer/AddGatewaysContainer.tsx, console/console-init/ui/src/modules/iot-device/containers/EditDeviceInJsonContainer/EditDeviceInJsonContainer.tsx, console/console-init/ui/src/modules/iot-device/containers/EditGatewayGroupMembershipContainer/EditGatewayGroupMembershipContainer.tsx, console/console-init/ui/src/modules/iot-device/containers/EditGatewaysContainer/EditGatewaysContainer.tsx, console/console-init/ui/src/modules/iot-device/containers/EditMetadataContainer/EditMetadataContainer.tsx, console/console-init/ui/src/utils/index.ts, console/console-init/ui/src/utils/messages.ts, console/console-init/ui/src/utils/utils.ts
- Bugfix
- Refactoring
Fixed issues  for device detail page
=> Fixed issues  for device detail page

documentation/common/snip-prerequisites-openshift.adoc
Docs: Update OCP Prerequisites
=> Docs: Update OCP Prerequisites

console/console-init/ui/src/graphql-module/queries/project.ts, console/console-init/ui/src/modules/project/ProjectPage.tsx, console/console-init/ui/src/modules/project/containers/ProjectListContainer/ProjectListContainer.tsx, console/console-init/ui/src/modules/project/utils/utils.ts
- Bugfix
Fix count card in project list
=> [Console-IoT] Fix count card in project list

console/console-init/ui/src/modules/project/utils/utils.ts
- Bugfix
Fix app crashing on uploading a .pem file for a TLS certificate
=> [Console IoT]- Fix app crashing on uploading a .pem file for a TLS certificate

documentation/modules/ref-address-example-forwarders.adoc
Re-created from https://github.com/EnMasseProject/enmasse/pull/5112
=> [Docs] Forwarder priority documentation

documentation/modules/ref-address-example-message-redelivery.adoc, documentation/modules/ref-address-example-message-ttl.adoc
Docs: fix module id for TTL and deadletter examples
=> Docs: fix module id for ttl and deadletter examples

documentation/assemblies/assembly-ops-procedures.adoc, documentation/modules/proc-change-logging-level-broker.adoc
From https://github.com/EnMasseProject/enmasse/pull/5124
=> [Documentation] Document changing broker logging level at runtime

documentation/modules/proc-change-logging-level-broker.adoc
Docs: Minor changes to the module for changing the broker logging level.
=> Docs:Update broker logging level module

documentation/modules/proc-change-address-space-auth-service-console.adoc, documentation/modules/proc-change-address-space-plan-console.adoc, documentation/modules/proc-create-address-console.adoc, documentation/modules/proc-enable-ocp4-monitoring.adoc, documentation/modules/proc-managing-user-permissions-cli.adoc, documentation/modules/proc-olm-installing-from-operatorhub-using-console.adoc, documentation/modules/ref-address-example.adoc, documentation/modules/ref-address-space-example-exporting-endpoints.adoc, documentation/modules/ref-brokered-infra-config-override-probe-timeout.adoc, documentation/modules/ref-standard-infra-config-override-probe-timeout.adoc
Docs: Updated some links to OpenShift docs and fixed a few minor punctuation issues
=> Docs:update links and punctuation

documentation/assemblies/assembly-managing-addresses.adoc, documentation/modules/proc-create-address-console.adoc, documentation/modules/proc-delete-address-console.adoc
Docs: Added Module for deleting addresses and updated steps in module for creating addresses.
=> Docs: Add Module for deleting addresses

console/console-init/ui/mock-console-server/mock-console-server.js, console/console-init/ui/src/graphql-module/queries/Address.ts, console/console-init/ui/src/modules/address/components/AddressConfiguration/AddressConfiguration.tsx, console/console-init/ui/src/modules/address/containers/AddressDefinitionContainer/AddressDefinitionContainer.tsx, console/console-init/ui/src/modules/address/dialogs/CreateAddress/CreateAddress.tsx, console/console-init/ui/src/modules/address/dialogs/EditAddress/EditAddress.tsx
- Bugfix
Fixes: #5183 . Fix UI to add set the expiry-address and dlq on the topic (not on the subscription).
=> UI - Set expiry address on the topic (not on the subscription)

documentation/modules/con-standard-topic.adoc, documentation/modules/proc-deploy-monitoring-operator.adoc, documentation/modules/proc-enable-tenant-metrics.adoc, documentation/modules/proc-run-calculation-script.adoc, documentation/modules/ref-operator-component-sizing.adoc, documentation/modules/ref-standard-auth-service-example.adoc
Minor fixes to the documentation.
Not applicable
=> Minor documentation fixes

documentation/modules/con-standard-address-space.adoc, documentation/modules/ref-address-space-example-exposing-endpoints.adoc
Docs: Remove references to MQTT
=> Docs: Remove references to MQTT

console/console-init/ui/src/App.tsx, console/console-init/ui/src/components/FormAndJson/FormAndJson.tsx, console/console-init/ui/src/modules/address/components/AddressList/AddressList.tsx
- Refactoring
Remove inline css and replace it with aphrodite functions
=> [UI] Remove inline css and replace it with aphrodite functions

console/console-init/ui/src/modules/iot-device-detail/dialogs/CloneDevice/CloneDevicePage.tsx, console/console-init/ui/src/modules/iot-device/components/index.ts, console/console-init/ui/src/modules/iot-device/dialogs/CreateDevice/CreateDevicePage.tsx, console/console-init/ui/src/utils/utils.ts
Create flow for clone a device using wizard
=> [Console-IoT] Create flow for clone a deice using wizard

documentation/modules/ref-standard-infra-config-fields.adoc
=> Add documentation for new broker configuration fields

systemtests/src/test/java/io/enmasse/systemtest/isolated/infra/standard/InfraTestStandard.java
=> Fix broken reject test

.github/workflows/smoke.yml
- Bugfix
- Refactoring
Workaround for jobs to be running, till I fix minikube issues on actions again...
=> Workaround for actions

.github/workflows/master.yml
=> Workaround for master run

.github/workflows/smoke.yml
=> EXPRMT: debug registry

documentation/modules/proc-olm-installing-from-operatorhub-using-console.adoc
Update the OLM installation instructions.
=> Docs:Update OLM installation instructions

documentation/modules/proc-olm-installing-from-operatorhub-using-console.adoc
Docs: Small edit to OLM install
=> Docs:small edit to OLM install

.jenkins/Jenkinsfile-pr, systemtests/olm/subscription.yaml, systemtests/src/main/java/io/enmasse/systemtest/Environment.java, systemtests/src/main/java/io/enmasse/systemtest/operator/OLMOperatorManager.java
Now the install depends on upstream/downstream run.
=> Modified OLM install

documentation/modules/ref-broker-component-sizing.adoc
Small update to the broker component config example.
=> Docs:update broker component config example

systemtests/olm/subscription.yaml, systemtests/src/main/java/io/enmasse/systemtest/Environment.java, systemtests/src/main/java/io/enmasse/systemtest/operator/OLMOperatorManager.java
Signed-off-by: Jan Kalinic <jkalinic@redhat.com>
added env variable  and modified  subscription source
=> added subscription source var

systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java
- Bugfix
- Refactoring
Removes IoT related test code.
=> Remove some IoT related test methods

documentation/common/snip-prerequisites-openshift.adoc, documentation/modules/proc-enable-ocp4-monitoring.adoc, documentation/modules/proc-olm-installing-from-operatorhub-using-console.adoc, documentation/modules/ref-brokered-infra-config-override-probe-timeout.adoc, documentation/modules/ref-standard-infra-config-override-probe-timeout.adoc
Docs: Updated some links in documentation
=> Docs:update links

documentation/common/snip-prerequisites-openshift.adoc
=> Docs: fix typo

.github/scripts/clean_disk.sh
=> Github action: Update clean_disk.sh to remove monodoc-http

documentation/modules/ref-ability-restrict-address-space-connections.adoc, documentation/openshift/master.adoc
=> Update links 03-05-21

.github/workflows/release.yml
- Bugfix
Applies #5220 to the release profile too.
=> Apply #5220 to github release profile too

documentation/modules/con-address-plans.adoc, documentation/modules/con-external-auth-service.adoc, documentation/modules/con-standard-auth-service.adoc, documentation/modules/proc-applying-infra-config.adoc
Fixed some minor typos in the docs.
=> Docs: fix typos

systemtests/src/main/java/io/enmasse/systemtest/utils/AddressSpaceUtils.java
- Bugfix
- Refactoring
Test fix only, no functional change.
=> Avoid systemtest NPE during failed test cleanup

.github/workflows/release.yml
Release the pre kube 1.16 bundle as an artefact.
=> [GitHub Actions] Release prekube-bundle-too

CHANGELOG.md, service-broker/src/main/java/io/vertx/core/http/impl/headers/VertxHttpHeaders.java
- Bugfix
Workaround #5292 by patching VertxHttpHeaders class.
=> Workaround for issue 5292

systemtests/src/test/java/io/enmasse/systemtest/shared/standard/api/UserApiTest.java
=> Test compile err

systemtests/src/main/java/io/enmasse/systemtest/platform/Kubernetes.java, systemtests/src/main/java/io/enmasse/systemtest/platform/apps/SystemtestsKubernetesApps.java
Refactor tests to use ingress v1
=> Tests to use ingress v1
